SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "¿Has ido a la ZONA del SAFARI\n"
	.string "en CIUDAD FUCSIA?\p"
	.string "¡Había muchos tipos raros\n"
	.string "de POKéMON!$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "¡Mi padre y yo pensamos que\n"
	.string "la ZONA del SAFARI es genial!$"

