SafariZone_North_Frlg_MapScripts::
	.byte 0

SafariZone_North_EventScript_RestHouseSign::
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips1::
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
	end

SafariZone_North_EventScript_AreaSign::
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips2::
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips3::
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
	end

SafariZone_North_Text_RestHouse::
	.string "CASA DE REPOSO$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "PISTAS ENTRENADOR\p"
	.string "¡La CASA SECRETA sigue estando\n"
	.string "justo delante!$"

SafariZone_North_Text_Area2::
	.string "ZONA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Los POKéMON se ocultan entre la\n"
	.string "alta hierba!\p"
	.string "Zigzaguea por zonas de hierba para\n"
	.string "que salgan.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Encuentra la CASA SECRETA\n"
	.string "y ganarás una MO!$"

