SaffronCity_Mart_hns_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "En PUEBLO LAVANDA hay una gran TORRE\n"
	.string "RADIO.$"

SaffronMart_Text_CooltrainerF:
	.string "Quiero ser más fuerte, pero aún debo\n"
	.string "aprender…\p"
	.string "¿Podrías ayudarme a mejorar?$"
