SafariZoneGate_PokemonCenter_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, SafariZoneGate_PokemonCenter_OnTransition
	.byte 0

SafariZoneGate_PokemonCenter_OnTransition::
	setrespawn HEAL_LOCATION_SAFARI_ZONE_GATE_HNS
	end

SafariZoneGate_PokemonCenter_EventScript_NPC1::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_NPC1, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_EventScript_NPC2::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_NPC2, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_Text_Boy::
	lock
	faceplayer
	msgbox SafariZoneGate_PokemonCenter_Text_SafariSong, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_PokemonCenter_Text_NPC1:
	.string "Quienes vienen a un CENTRO POKéMON\n"
	.string "suelen cuidar bien de sus POKéMON.\p"
	.string "¿No crees?$"

SafariZoneGate_PokemonCenter_Text_NPC2:
	.string "Después de una larga caminata por las\n"
	.string "montañas buscando un CENTRO\l"
	.string "POKéMON, cuando estás a punto de caer\l"
	.string "rendido…\p"
	.string "¡Es como estar en el paraíso!$"

SafariZoneGate_PokemonCenter_Text_SafariSong:
	.string "¡La ZONA SAFARI es algo genial!\p"
	.string "¡La ZONA SAFARI es sensacional!\p"
	.string "Con tantísimos POKéMON… un lugar sin\n"
	.string "igual…\p"
	.string "Es una canción que me he inventado.\p"
	.string "La canto mientras paseo por la ZONA\n"
	.string "SAFARI.$"
