SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
	.string "¿Sabes algo de esta cámara\n"
	.string "de piedra?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
	.string "Eso no hacía falta.\n"
	.string "No tenías que ser tan brusco.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
	.string "Las RUINAS SETE tienen unos\n"
	.string "1.500 años.\p"
	.string "Pero nadie ha conseguido averiguar\n"
	.string "cuál es su razón de ser.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
	.string "Dicen que aquí dentro duerme\n"
	.string "un mítico POKéMON.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
	.string "A mí lo de los combates no se me\n"
	.string "da bien.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
	.string "Yo he oído que hay otras ruinas\n"
	.string "como éstas.\p"
	.string "¿Serán lugares de descanso de\n"
	.string "otros míticos POKéMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
	.string "CLEN me está enseñando a\n"
	.string "pintar.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
	.string "Igual nos llaman la atención\n"
	.string "por haber hecho tanto ruido.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
	.string "Yo quería pintar un edificio\n"
	.string "antiguo.\p"
	.string "Por eso me trajo CLEN hasta aquí.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
	.string "Hoy, como complemento a la clase,\n"
	.string "hemos venido a visitar la cámara.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
	.string "Qué barbaridad...$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
	.string "Ah, así que estudias a los POKéMON\n"
	.string "por tu cuenta…\p"
	.string "Sí, desde luego eres una persona\n"
	.string "extraordinaria, sin duda.$"
