OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Cuando hace buen día, salgo\n"
	.string "a contemplar el volcán.\p"
	.string "Es lo que hago siempre.$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Mmm, no consigo acordarme...\n"
	.string "¿Cuándo fue la última vez que\l"
	.string "entró en erupción el MT. ASCUAS?$"

