PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "¡Hola! ¡Mira mi GYARADOS!\p"
	.string "Procede de un MAGIKARP. No me puedo\n"
	.string "creer lo fuerte que es.$"

PewterCity_Mart_Text_SuperNerd:
	.string "Había una vez un anciano muy raro que\n"
	.string "vendía MAGIKARP.\p"
	.string "Decía que los MAGIKARP del LAGO\p"
	.string "DE LA FURIA eran excelentes.$"

