Route21_South_Frlg_MapScripts::
	.byte 0

Route21_South_Text_JackIntro::
	.string "Capturé mis POKéMON en el mar.$"

Route21_South_Text_JackDefeat::
	.string "¡¡Buceador!!\n"
	.string "¡¡Abajo!!$"

Route21_South_Text_JackPostBattle::
	.string "¿Dónde atrapaste tus POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "¡Ahora estoy en un encuentro\n"
	.string "de triatlón!$"

Route21_South_Text_JeromeDefeat::
	.string "Ufff...\n"
	.string "Ufff... Ufff...$"

Route21_South_Text_JeromePostBattle::
	.string "¡Me has ganado! ¡Pero aún falta\n"
	.string "el ciclismo y la maratón!$"

Route21_South_Text_RolandIntro::
	.string "¡Ah!\n"
	.string "¡Siente el sol y el viento!$"

Route21_South_Text_RolandDefeat::
	.string "¡Auuu!\n"
	.string "¡He perdido!$"

Route21_South_Text_RolandPostBattle::
	.string "¡Estoy quemado como un chicharrón!$"

Route21_South_Text_ClaudeIntro::
	.string "¡Eh!\n"
	.string "¡No asustes a los peces!$"

Route21_South_Text_ClaudeDefeat::
	.string "¡Perdona!\n"
	.string "¡No lo hice adrede!$"

Route21_South_Text_ClaudePostBattle::
	.string "Vaya, no he pescado nada.\n"
	.string "¿Podría ser este sitio una piscina\l"
	.string "gigante o algo así?$"

Route21_South_Text_NolanIntro::
	.string "Hazme compañía hasta que pique algo.$"

Route21_South_Text_NolanDefeat::
	.string "Qué forma de matar el tiempo...$"

Route21_South_Text_NolanPostBattle::
	.string "¡Eh!\n"
	.string "¡Algo ha picado! ¡Sí!$"

Route21_North_Text_LilIntro::
	.string "ÍA: ¿Cómo, que quieres luchar?\n"
	.string "IGOR, ¿cómo lo ves?$"

Route21_North_Text_LilDefeat::
	.string "ÍA: ¿Eso es lo que querías,\n"
	.string "que perdiéramos?$"

Route21_North_Text_LilPostBattle::
	.string "ÍA: Estoy cansada, ¿nos vamos ya\n"
	.string "a casa?$"

Route21_North_Text_LilNotEnoughMons::
	.string "ÍA: ¿Luchar? Con sólo un POKéMON\n"
	.string "no nos vamos a tomar la molestia.$"

Route21_North_Text_IanIntro::
	.string "IGOR: Mi hermana no se cansa\n"
	.string "de hacer ejercicio, por eso viene.$"

Route21_North_Text_IanDefeat::
	.string "IGOR: ¡Hermanita, no pasa nada!$"

Route21_North_Text_IanPostBattle::
	.string "IGOR: ¡Hermanita, así no hay forma\n"
	.string "de perder peso!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IGOR: Queremos un combate dos\n"
	.string "contra dos.\n"
	.string "¿Puedes traer dos POKéMON?$"
