SafariZone_West_Frlg_MapScripts::
	.byte 0

SafariZone_West_EventScript_RestHouseSign::
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_LostTeethNotice::
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
	end

SafariZone_West_EventScript_TrainerTips::
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_AreaSign::
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_West_Text_RestHouse::
	.string "CASA DE REPOSO$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "AVISO\p"
	.string "Encuentra los DIENTES de ORO\n"
	.string "perdidos del GUARDA del SAFARI.\l"
	.string "Están por aquí.\p"
	.string "¡Se ofrece recompensa!\n"
	.string "Contactar con el GUARDA.$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Operación Exploración de la zona!\n"
	.string "¡La búsqueda de la CASA SECRETA!$"

SafariZone_West_Text_AreaSign::
	.string "ZONA 3\n"
	.string "ESTE: ZONA CENTRAL$"

