Route11_EastEntrance_1F_Frlg_MapScripts::
	.byte 0

Route11_EastEntrance_1F_EventScript_TopGuard::
	msgbox Route11_EastEntrance_1F_Text_ManInLavenderRatesNames, MSGBOX_NPC
	end

Route11_EastEntrance_1F_EventScript_BottomGuard::
	msgbox Route11_EastEntrance_1F_Text_RockTunnelToReachLavender, MSGBOX_NPC
	end

@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
	.string "Parece que la MOCHILA de\n"
	.string "{PLAYER}{KUN} está llena.$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
	.string "¿No crees que es difícil pensar\n"
	.string "buenos motes para los POKéMON?\p"
	.string "¿Sobre todo si has capturado\n"
	.string "un montón?\p"
	.string "En PUEBLO LAVANDA hay un hombre\n"
	.string "que valora los motes de POKéMON.\p"
	.string "También puede ayudarte a cambiar\n"
	.string "el mote de tus POKéMON.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
	.string "Si quieres llegar a PUEBLO LAVANDA,\n"
	.string "toma el TÚNEL ROCA.\p"
	.string "Puedes llegar al TÚNEL ROCA desde\n"
	.string "CIUDAD CELESTE.$"

