Route10_PowerPlantBackRoom_hns_MapScripts::
	.byte 0


Route10_PowerPlantBackRoom_EventScript_Manager::
	lock
	faceplayer
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 0, Route10_PowerPlantBackRoom_EventScript_ManagerInitial
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 1, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 2, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 3, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 4, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 5, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 6, Route10_PowerPlantBackRoom_EventScript_ManagerCheckPart
	goto_if_ge VAR_KANTO_ROCKET_STORY_STATE, 7, Route10_PowerPlantBackRoom_EventScript_ManagerDone
	msgbox Route10_PowerPlantBackRoom_Text_ManagerMyBelovedGenerator, MSGBOX_DEFAULT
	closemessage
	release
	end

Route10_PowerPlantBackRoom_EventScript_ManagerInitial::
	msgbox Route10_PowerPlantBackRoom_Text_ManagerWhoWouldRuinMyGenerator, MSGBOX_DEFAULT
	closemessage
	setvar VAR_KANTO_ROCKET_STORY_STATE, 1
	release
	end

Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket::
	msgbox Route10_PowerPlantBackRoom_Text_ManagerIWontForgiveCulprit, MSGBOX_DEFAULT
	closemessage
	release
	end

Route10_PowerPlantBackRoom_EventScript_ManagerCheckPart::
	checkitem ITEM_MACHINE_PART
	goto_if_eq VAR_RESULT, FALSE, Route10_PowerPlantBackRoom_EventScript_ManagerDuringRocket
	removeitem ITEM_MACHINE_PART
	msgbox Route10_PowerPlantBackRoom_Text_ManagerThatsThePart, MSGBOX_DEFAULT
	msgbox Route10_PowerPlantBackRoom_Text_ManagerTakeThisTM, MSGBOX_DEFAULT
	giveitem ITEM_TM_THUNDER
	msgbox Route10_PowerPlantBackRoom_Text_ManagerTM07IsZapCannon, MSGBOX_DEFAULT
	closemessage
	setvar VAR_KANTO_ROCKET_STORY_STATE, 7
	clearflag FLAG_HIDE_ROUTE25_MISTY
	setvar VAR_CERULEAN_CITY_STATE, 2
	setflag FLAG_HIDE_POWER_PLANT_ENGINEER
	setflag FLAG_RETURNED_MACHINE_PART
	setvar VAR_VERMILION_CITY_SAMSON, 1
	release
	end

Route10_PowerPlantBackRoom_EventScript_ManagerDone::
	msgbox Route10_PowerPlantBackRoom_Text_ManagerMyBelovedGenerator, MSGBOX_DEFAULT
	closemessage
	release
	end

Route10_PowerPlantBackRoom_EventScript_Engineer::
	msgbox Route10_PowerPlantBackRoom_Text_Engineer, MSGBOX_NPC
	end

Route10_PowerPlantBackRoom_Text_ManagerWhoWouldRuinMyGenerator:
	.string "ENCARGADO: ¡Es-es-estoy listo para\n"
	.string "fulminar a alguien!\p"
	.string "¿Quién se habrá atrevido a estropear\n"
	.string "mi generador?\p"
	.string "¡Con todo el tiempo que le he\n"
	.string "dedicado!\p"
	.string "Si lo pillo, ¡va a probar mi\n"
	.string "ELECTROCAÑÓN!$"

Route10_PowerPlantBackRoom_Text_ManagerIWontForgiveCulprit:
	.string "DIRECTOR: ¡Nunca le perdonaré!\p"
	.string "Aunque el culpable llore y suplique\n"
	.string "perdón, ¡le machacaré!\p"
	.string "¡Ja, ja, ja!$"

Route10_PowerPlantBackRoom_Text_ManagerThatsThePart:
	.string "ENCARGADO: ¡Ah! ¡Sí!\p"
	.string "¡Es la PIEZA que le faltaba a mi\n"
	.string "querido generador! ¿La has\l"
	.string "encontrado tú?$"

Route10_PowerPlantBackRoom_Text_ManagerTakeThisTM:
	.string "¡Yuju! ¡Gracias!\p"
	.string "¡Toma esta MT como recompensa!$"

Route10_PowerPlantBackRoom_Text_ManagerTM07IsZapCannon:
	.string "ENCARGADO: Esa MT es TRUENO.\p"
	.string "¡Es una técnica muy poderosa!\p"
	.string "No es que sea muy precisa, ¡pero pega\n"
	.string "fuerte!$"

Route10_PowerPlantBackRoom_Text_ManagerMyBelovedGenerator:
	.string "ENCARGADO: ¡Mi querido generador!\p"
	.string "¡Sigue produciendo electricidad!$"

Route10_PowerPlantBackRoom_Text_Engineer:
	.string "Esta puerta no es segura sin\n"
	.string "electricidad.$"

