SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "La ZONA del SAFARI es gigante,\n"
	.string "¿no te parece?\p"
	.string "El LÍDER del GIMNASIO de FUCSIA,\n"
	.string "KOGA, viene con mucha frecuencia\l"
	.string "por esta zona.\p"
	.string "Gracias a él, podemos jugar aquí\n"
	.string "sin miedo.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Tirar PIEDRAS a los POKéMON\n"
	.string "podría hacerles huir, pero hará\l"
	.string "que sean más fáciles de atrapar.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Usar CEBO hará que los POKéMON\n"
	.string "se queden más tiempo si se ponen\l"
	.string "a comer.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Caminé mucho, pero no he visto\n"
	.string "a los POKéMON que quería.$"

