SevenIsland_SevaultCanyon_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Text_CyndyIntro::
	.string "¡Estoy en plena forma!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
	.string "¿Mmm?\n"
	.string "Aquí hay algo que falla...$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
	.string "Así no puedo presentarme a la\n"
	.string "TORRE DESAFÍO...$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
	.string "No importa que tengas los POKéMON\n"
	.string "más fuertes…\p"
	.string "¡No sirve de nada si no sabes\n"
	.string "usarlos como es debido!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
	.string "Sabes bien lo que haces...$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
	.string "Hay mucho ENTRENADOR por ahí\n"
	.string "suelto con POKéMON increíbles y sin\l"
	.string "idea de cómo hay que tratarlos.\p"
	.string "Antes de entrenar POKéMON,\n"
	.string "son los propios ENTRENADORES los\l"
	.string "que deben crecer como personas.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
	.string "Trabajo para proteger el medio\n"
	.string "ambiente. ¡A cambio, la naturaleza\l"
	.string "me protege!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
	.string "¡Buah, eres fuerte!\n"
	.string "¿Y a mí quién me protege ahora?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
	.string "Visto desde las estrellas, nuestro\n"
	.string "planeta es un granito de arena.\p"
	.string "Y debemos proteger ese granito\n"
	.string "de arena por el bien de todos.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
	.string "Esos zapatos que llevas son\n"
	.string "muy llamativos.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
	.string "Eres un hacha a pesar de tu\n"
	.string "aspecto mono.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
	.string "¿Te ha comprado tu mamá esas\n"
	.string "DEPORTIVAS tan chulas?\p"
	.string "¡Debe de adorarte!$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
	.string "¡Pareces fuerte!\n"
	.string "¡Vamos a luchar, anda!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
	.string "¡Lo sabía!\n"
	.string "¡Sabía que eras increíble!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
	.string "La forma de luchar que tienes\n"
	.string "dice mucho de ti.\p"
	.string "¡Gracias!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
	.string "He recibido la mejor educación\n"
	.string "para tener la fuerza que tengo.\p"
	.string "¡No pienso perder ante nadie!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
	.string "Gracias, ya no tengo la presión\n"
	.string "de antes.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
	.string "Por alguna razón, me enfurezco\n"
	.string "por lo más mínimo.\p"
	.string "Me calmaré respirando hondo.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
	.string "LINO: Mi adorada ABA, ¡no hay\n"
	.string "nadie que pueda con nosotros!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
	.string "LINO: Me parece que he bajado\n"
	.string "la guardia...$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
	.string "LINO: Creo que ha sido una buena\n"
	.string "experiencia para ABA. Gracias.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
	.string "LINO: ¿Podrías luchar con los dos\n"
	.string "a la vez?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
	.string "ABA: Me esforzaré mucho para no\n"
	.string "defraudar a mi maestro LINO.$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
	.string "ABA: Oooh... Lo siento...$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
	.string "ABA: Creo que voy a necesitar que\n"
	.string "LINO me tutele y me oriente más...\p"
	.string "LINO, ¿te parece bien?...$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
	.string "ABA: Lo siento, pero queremos\n"
	.string "luchar dos contra dos.$"

SevenIsland_SevaultCanyon_Text_RouteSign::
	.string "CAÑÓN SÉTANO\n"
	.string "HACIA LAS RUINAS SETE$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
	.string "Entrenarse uno mismo no está mal.\p"
	.string "Pero tampoco está mal buscar\n"
	.string "una buena pareja de combate.\p"
	.string "Fíjate en BRUNO...\n"
	.string "Él se entrenó con un tal MARCIAL.$"
