Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
	.string "¡Gane, pierda o empate!$"

Route11_Text_HugoDefeat::
	.string "¡Vaya!\n"
	.string "¡No ha salido como quería!$"

Route11_Text_HugoPostBattle::
	.string "¡Los POKéMON son vida!\n"
	.string "¡Y vivir es jugar!$"

Route11_Text_JasperIntro::
	.string "¡Competición!\n"
	.string "¡No me canso de competir!$"

Route11_Text_JasperDefeat::
	.string "¡He perdido la oportunidad!$"

Route11_Text_JasperPostBattle::
	.string "¡No se puede ser cobarde\n"
	.string "en el mundo de los POKéMON!$"

Route11_Text_EddieIntro::
	.string "¡Vamos allá, pero no hagas\n"
	.string "trampas!$"

Route11_Text_EddieDefeat::
	.string "¿Qué?\n"
	.string "¡No puede ser!$"

Route11_Text_EddiePostBattle::
	.string "¡He hecho lo que he podido!\n"
	.string "¡Y no me arrepiento!$"

Route11_Text_BraxtonIntro::
	.string "¡Cuidado!\n"
	.string "¡Estoy colocando unos cables!$"

Route11_Text_BraxtonDefeat::
	.string "¡Electrizante!$"

Route11_Text_BraxtonPostBattle::
	.string "¡Di a todos que ahorren energía!$"

Route11_Text_DillonIntro::
	.string "¡Me acabo de hacer ENTRENADOR!\n"
	.string "¡Pero creo que puedo ganar!$"

Route11_Text_DillonDefeat::
	.string "Mis POKéMON no pudieron ganar…\n"
	.string "¿No habrán crecido lo suficiente?$"

Route11_Text_DillonPostBattle::
	.string "¿Qué quieres?\n"
	.string "¡Déjame en paz!$"

Route11_Text_DirkIntro::
	.string "¡Ja, ja, ja!\n"
	.string "¡No he perdido nunca!$"

Route11_Text_DirkDefeat::
	.string "¡La primera vez que pierdo!$"

Route11_Text_DirkPostBattle::
	.string "¡Has tenido mucha suerte!$"

Route11_Text_DarianIntro::
	.string "Nunca he ganado...$"

Route11_Text_DarianDefeat::
	.string "Lo veía venir...$"

Route11_Text_DarianPostBattle::
	.string "Tuve mala suerte, como siempre.$"

Route11_Text_YasuIntro::
	.string "¡Soy el mejor de mi clase!$"

Route11_Text_YasuDefeat::
	.string "¡Vaya! ¡Mis POKéMON deberían\n"
	.string "ser más fuertes!$"

Route11_Text_YasuPostBattle::
	.string "Hay un POKéMON muy gordo\n"
	.string "que baja de las montañas.\p"
	.string "Seguro que es muy fuerte.$"

Route11_Text_BernieIntro::
	.string "¡Cuidado con esos cables!$"

Route11_Text_BernieDefeat::
	.string "¡Uau!\n"
	.string "¡Eres una chispa!$"

Route11_Text_BerniePostBattle::
	.string "¡Más vale que vuelva al trabajo!$"

Route11_Text_DaveIntro::
	.string "¡Mis POKéMON ya deberían\n"
	.string "estar listos!$"

Route11_Text_DaveDefeat::
	.string "¡Adiós!\n"
	.string "¡Gracias, y hasta luego!$"

Route11_Text_DavePostBattle::
	.string "¡Voy a buscarme unos más fuertes!$"

Route11_Text_DiglettsCave::
	.string "CUEVA DIGLETT$"

