gText_ApprenticeChallenge0::
	.string "Eh… Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}. Snif… Estos nervios me\l"
	.string "pueden…$"

gText_ApprenticeChallenge1::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}! ¡Allá vamos!$"

gText_ApprenticeChallenge2::
	.string "¡Eh! ¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Saca músculo!$"

gText_ApprenticeChallenge3::
	.string "¡Soy el aprendiz n.º 1.000 de {STR_VAR_1}!\n"
	.string "¡Bueno, el n.º {STR_VAR_2}! ¿Qué importa eso?$"

gText_ApprenticeChallenge4::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}! ¡Te dejaré desafiarme!$"

gText_ApprenticeChallenge5::
	.string "Estoy ocupadísimo, pero además\n"
	.string "resulta que soy el aprendiz n.º\l"
	.string "{STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}. ¡Encantado de conocerte!$"

gText_ApprenticeChallenge7::
	.string "Sirvo como aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}. ¿Puedo empezar?$"

gText_ApprenticeChallenge8::
	.string "¡Iiih! ¡Soy el aprendiz n.º {STR_VAR_2}\n"
	.string "de {STR_VAR_1}! ¡Daré lo mejor de mí!$"

gText_ApprenticeChallenge9::
	.string "¡Yija! ¡Soy el aprendiz n.º {STR_VAR_2}\n"
	.string "de {STR_VAR_1}! ¡En guardia!$"

gText_ApprenticeChallenge10::
	.string "¡Soy el aprendiz n.º 1000 de\n"
	.string "{STR_VAR_1}! En realidad, ¡soy el n.º\l"
	.string "{STR_VAR_2}! ¡Allá voy!$"

gText_ApprenticeChallenge11::
	.string "¡Sí, soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}! ¡Vamos a darle caña al\l"
	.string "rock and roll!$"

gText_ApprenticeChallenge12::
	.string "¡Yupi, yahú! ¡Soy lo que se dice el\n"
	.string "aprendiz n.º {STR_VAR_2} de\l"
	.string "{STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "¡Cof! Soy el aprendiz n.º {STR_VAR_2}\n"
	.string "de {STR_VAR_1}. ¡Encantado de\l"
	.string "conocerte! ¡Cof!$"

gText_ApprenticeChallenge14::
	.string "¡Sí, soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Al abordaje!$"

gText_ApprenticeChallenge15::
	.string "Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}, y no es mentira.$"

gText_ApprenticePleaseTeach0::
	.string "¿Eres… {PLAYER}?\n"
	.string "¡Oh! Snif… Snif…\p"
	.string "¡Ay! Lo-lo siento…\n"
	.string "Los nervios… No puedo dejar\l"
	.string "de llorar…\p"
	.string "So-soy {STR_VAR_1}, y tú, {PLAYER},\n"
	.string "siempre has sido mi ídolo.\p"
	.string "Yo-yo… soñaba con que algún día me\n"
	.string "pudieses enseñar cosas de los POKéMON.\p"
	.string "¡Anda, por favor, {PLAYER}!\n"
	.string "¡Enséñame algo sobre los POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… Pe-pero…\n"
	.string "Snif… ¡Buaaaaaaaa!\p"
	.string "¡Po-po-por fa-fa-vor!\n"
	.string "¡Te lo pido po-po-por fa-fa-vor!$"

gText_ApprenticeWhichLevelMode0::
	.string "¿En serio? ¿Lo harás?\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "Oh… Perdona otra vez…\n"
	.string "Ahora lloro de alegría…\p"
	.string "Mm… Entonces, dime algo…\n"
	.string "sobre la TORRE BATALLA…\p"
	.string "¿Qué nivel crees que me iría mejor?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento otra vez!\n"
	.string "Eso de que elijas por mí me hace\l"
	.string "tan feliz que no puedo contenerme…\p"
	.string "Snif…\n"
	.string "¡Muchas gracias!\l"
	.string "¡No te olvides de mí!$"

gText_ApprenticePleaseTeach1::
	.string "¡Guau! Tú eres {PLAYER}, ¿a que sí?\n"
	.string "Guau, todo el mundo te conoce.\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de convertirme en ENTRENADOR!\p"
	.string "¡Porfa, {PLAYER}!\n"
	.string "¿Querrías tomarme como aprendiz para\l"
	.string "enseñarme a ser un buen ENTRENADOR?$"

gText_ApprenticeRejectTeaching1::
	.string "Ooohh, pero ¿por qué?\n"
	.string "¡Anda, porfa! ¡No seas así!\l"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode1::
	.string "¡Yupi! ¡Genial!\p"
	.string "¡Lo primero que quiero preguntarte\n"
	.string "es sobre la TORRE BATALLA!\p"
	.string "Entre el nivel 50 y el nivel libre…\n"
	.string "¿En cuál crees que debería inscribirme?$"

gText_ApprenticeLevelModeThanks1::
	.string "¿{STR_VAR_1}? ¡Claro, es verdad!\n"
	.string "¡Haré lo que pueda para no defraudarte!\p"
	.string "¡Ojalá nos volvamos a ver\n"
	.string "para que me enseñes algo más!$"

gText_ApprenticePleaseTeach2::
	.string "Mm… ¿Eres {PLAYER}?\n"
	.string "Yo me llamo {STR_VAR_1}.\p"
	.string "Quiero ser un gran ENTRENADOR POKéMON,\n"
	.string "aunque no sé por dónde empezar…\p"
	.string "Ya que estás aquí, a lo mejor podrías\n"
	.string "ayudarme, con toda esa fama que tienes.\p"
	.string "¿Qué me dices, {PLAYER}? ¿Me ayudarías?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, pero…\p"
	.string "¡Pero es que de verdad que quiero\n"
	.string "ser un buen ENTRENADOR POKéMON!\p"
	.string "¡Por favor, dime que sí!$"

gText_ApprenticeWhichLevelMode2::
	.string "¡Gracias!\n"
	.string "¡Ahí va entonces mi primera pregunta!\p"
	.string "La TORRE BATALLA tiene dos niveles:\n"
	.string "el nivel 50 y el nivel libre, ¿sí?\p"
	.string "¿En cuál de los dos niveles crees\n"
	.string "que me vendría mejor participar?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, ¿en el {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "Si tengo más dudas, ¡vendré\n"
	.string "otra vez a preguntarte!$"

gText_ApprenticePleaseTeach3::
	.string "¿Eh? ¿Qué? Tú eres… No, no puede ser.\p"
	.string "Es imposible que alguien como yo\n"
	.string "conozca a {PLAYER}.\p"
	.string "… ¿De verdad eres {PLAYER}? ¡No me\n"
	.string "creo que esté hablando contigo!\p"
	.string "Cuando pasa algo tan bueno, ahora\n"
	.string "solo me pasarán cosas terribles, lo\l"
	.string "sé…\p"
	.string "… Lo siento… Soy… {STR_VAR_1}…\p"
	.string "No tengo nada especial de lo que\n"
	.string "pueda estar orgulloso…\p"
	.string "Ni siquiera debería hablar de mí,\n"
	.string "porque se te va a olvidar…\p"
	.string "Soñaba con que, si algún día te\n"
	.string "conocía, {PLAYER}, quizá podría\l"
	.string "pedirte consejo como ENTRENADOR.\p"
	.string "Pero no creo que aceptes.\p"
	.string "… ¿O serías tan amable de darme algún\n"
	.string "consejo?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sabía…\p"
	.string "Era lo normal porque yo soy\n"
	.string "una don nadie…\p"
	.string "Pero, por un momento pensé…\n"
	.string "No cambiarías de opinión, ¿verdad?\p"
	.string "¡Perdona que insista, pero una ocasión\n"
	.string "así no se presenta todos los días!\p"
	.string "Por favor, ¿serías tan amable de darme\n"
	.string "unos consejillos sobre los POKéMON?$"

gText_ApprenticeWhichLevelMode3::
	.string "¿De verdad? ¡No me lo puedo creer!\n"
	.string "¡No me creo que quieras darme consejos!\l"
	.string "¡Estoy…! ¡Estoy tan contenta!…\p"
	.string "Lo primero que querría preguntarte es\n"
	.string "una tontería, pero yo no me decido…\p"
	.string "En la TORRE BATALLA, te dejan elegir\n"
	.string "entre el nivel 50 y el nivel libre.\p"
	.string "¿En cuál crees que tendría más\n"
	.string "posibilidades de ganar algo?$"

gText_ApprenticeLevelModeThanks3::
	.string "¿{STR_VAR_1}? ¡Vale!\n"
	.string "Pero ¿de verdad crees que alguien\l"
	.string "como yo tiene la menor posibilidad?\p"
	.string "Bueno, haré lo que pueda,\n"
	.string "aunque sé que no puedo mucho.\p"
	.string "¡Y perdona que te haya robado\n"
	.string "tanto tiempo!$"

gText_ApprenticePleaseTeach4::
	.string "¡Oh! Tú eres {PLAYER}{KUN}, ¿verdad?\p"
	.string "¡Dicen que hay pocos ENTRENADORES\n"
	.string "que entrenen POKéMON como tú!\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Voy a ser tu amiga!\p"
	.string "¿Sabes?\p"
	.string "No se puede ganar nada en el FRENTE de\n"
	.string "BATALLA sabiendo únicamente lo que te\l"
	.string "enseñan en la ESCUELA de ENTRENADORES.\p"
	.string "Por eso me gustaría oír tus consejos.\n"
	.string "Si quieres dármelos, claro…$"

gText_ApprenticeRejectTeaching4::
	.string "¿Eh? ¿Por qué te niegas?\n"
	.string "¡Soy yo quien te lo está pidiendo!\l"
	.string "¡Anda, piénsatelo otra vez!$"

gText_ApprenticeWhichLevelMode4::
	.string "¡Vale, entonces, cuando tenga alguna\n"
	.string "duda, te dejo decidir por mí!\p"
	.string "Sabes que en la TORRE BATALLA está\n"
	.string "el nivel 50 y el nivel libre, ¿verdad?\p"
	.string "¿Cuál crees que es el más adecuado\n"
	.string "para mí, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "¿Piensas que el {STR_VAR_1}?\n"
	.string "¡Gracias!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticePleaseTeach5::
	.string "¡Oh, hola! ¡{PLAYER}{KUN}! ¡Te conozco\n"
	.string "porque eres famoso! ¡Llámame\l"
	.string "{STR_VAR_1}! ¡Encantado!\p"
	.string "Soy TRIATLETA, así que me mantengo\n"
	.string "en forma mientras crío POKéMON.\p"
	.string "También me dedico a otras cosas, como\n"
	.string "el trabajo, la siesta, el baile de\l"
	.string "salón…\p"
	.string "Con tanto lío, no me resulta fácil\n"
	.string "convertirme en un ENTRENADOR\l"
	.string "decente.\p"
	.string "¡Así que tengo una propuesta!\p"
	.string "Por algo nos hemos conocido. Así que,\n"
	.string "{PLAYER}{KUN}, ¿qué tal si de vez en cuando\l"
	.string "compartes tu sabiduría conmigo?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, pero, ¡por favor!\n"
	.string "¡Un tipo como yo necesita alguien como\l"
	.string "tú a su lado, {PLAYER}{KUN}!\p"
	.string "¡En serio, necesito tus consejos!$"

gText_ApprenticeWhichLevelMode5::
	.string "¡Gracias! ¡Eso es genial!\n"
	.string "¡Vamos a empezar por uno fácil!\p"
	.string "Ya sabes que en la TORRE BATALLA\n"
	.string "hay dos niveles de combates, ¿verdad?\l"
	.string "Ya sabes, el nivel 50 y el nivel libre.\p"
	.string "¿Cuál es el que más le conviene\n"
	.string "a un tipo tan ocupado como yo?$"

gText_ApprenticeLevelModeThanks5::
	.string "¿{STR_VAR_1}? Vale, comprendido.\n"
	.string "¡A ver cuándo tengo tiempo y pruebo!\p"
	.string "¡Huy, me tengo que largar!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticePleaseTeach6::
	.string "¡No puedo creerlo! ¡Eh!\n"
	.string "¿Eres tú de verdad, {PLAYER}?\p"
	.string "¡Guau! ¡Alucinante! ¡Soy {STR_VAR_1},\n"
	.string "encantada de conocerte!\p"
	.string "{PLAYER}, eres muy fuerte,\n"
	.string "¿a que sí?\p"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¡Oh! ¡Tengo una idea!\n"
	.string "¡Te pediré que me aconsejes, {PLAYER}!\l"
	.string "¡Así yo también me haré más fuerte!\p"
	.string "¿A que es buena idea?\n"
	.string "¡Por favor, necesito que me aconsejes!$"

gText_ApprenticeRejectTeaching6::
	.string "Ja, ja, ja, ja. ¡A mí no me engañas!\n"
	.string "¡No puedes ser tan egoísta!\l"
	.string "En realidad, me vas a ayudar, ¿verdad?$"

gText_ApprenticeWhichLevelMode6::
	.string "¡Yupi! ¡Sabía que tenías buen corazón,\n"
	.string "{PLAYER}!\p"
	.string "¿Qué puedo preguntarte primero?…\n"
	.string "¡Ah, sí, ya sé!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Para participar en un desafío de la\n"
	.string "TORRE BATALLA, ¿qué nivel elijo?\p"
	.string "¿El nivel 50 o el nivel libre?\n"
	.string "¿Qué sería mejor para mí?$"

gText_ApprenticeLevelModeThanks6::
	.string "¡Oh-oh-oh!\n"
	.string "¡Has dicho {STR_VAR_1}!\l"
	.string "¡Muchas gracias por tu respuesta!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticePleaseTeach7::
	.string "Disculpa, pero… ¿Eres {PLAYER}?\p"
	.string "Soy {STR_VAR_1} y estoy encantado de\n"
	.string "conocerte.\p"
	.string "Hace mucho tiempo que te admiro…\p"
	.string "… … … … … …\p"
	.string "Eh… Espero que esta petición no te\n"
	.string "resulte demasiado pesada, pero…\p"
	.string "¿Puedo ser tu aprendiz, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "¡Oh…!\p"
	.string "… … … … … … … … … … … …\p"
	.string "… Me habré desmayado del susto. Lo\n"
	.string "siento, debo de haberte oído mal.\p"
	.string "¡Por favor! ¡Por favor, di que me\n"
	.string "aceptas como aprendiz!$"

gText_ApprenticeWhichLevelMode7::
	.string "¡Oh!… ¡Estoy feliz!\p"
	.string "No quiero hacerte perder más tiempo,\n"
	.string "así que contéstame a esto, porfa.\p"
	.string "Tengo la intención de participar pronto\n"
	.string "en la TORRE BATALLA.\p"
	.string "Pero hay dos niveles…\p"
	.string "¿Cuál crees que se adapta mejor a mí?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks7::
	.string "¿Me has dicho el {STR_VAR_1}?\n"
	.string "¡Vale! ¡A ver qué tal se me da!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticePleaseTeach8::
	.string "¡Iiih! ¡Iiih! ¡{PLAYER}! ¡Me has hablado!\n"
	.string "¡Es… es lo más!\p"
	.string "¡Yo! ¡Me llamo {STR_VAR_1}! ¡Acabo de\n"
	.string "hacerme ENTRENADOR!\p"
	.string "¡Estoy encantado de conocerte,\n"
	.string "{PLAYER}, el gran nombre del mundo\l"
	.string "POKéMON!\p"
	.string "¡Ay, ay, ay, ya sé! ¿Puedo pedirte un\n"
	.string "favor enorme, {PLAYER}?\p"
	.string "¡Acéptame como aprendiz! ¡Quiero\n"
	.string "aprender de ti!$"

gText_ApprenticeRejectTeaching8::
	.string "¡Buaaa! {PLAYER} me ha rechazado… ¡Es…\n"
	.string "es una experiencia que no tiene\l"
	.string "precio!\p"
	.string "¡{PLAYER}, por favor! ¡Esta vez quiero\n"
	.string "oír un sí!\p"
	.string "¡Te suplico que me guíes!$"

gText_ApprenticeWhichLevelMode8::
	.string "¡Yupi! ¡{PLAYER} ha dicho que sí!\n"
	.string "¡{PLAYER} ha dicho que sí!\p"
	.string "Ya no voy a dormir esta noche…\n"
	.string "¡Muchisísimas gracias!\p"
	.string "¡Oye, tengo una primera pregunta!\p"
	.string "En la TORRE BATALLA, qué crees que me\n"
	.string "conviene, ¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks8::
	.string "¡{STR_VAR_1}! ¡Vale, entiendo!\n"
	.string "¡Lo entiendo perfectamente!\l"
	.string "¡Qué genial! ¡Qué suerte!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticePleaseTeach9::
	.string "¡Guau! ¿No serás tú…?\n"
	.string "¡¿Es posible que seas… {PLAYER}{KUN}?!\l"
	.string "¡Ésta sí que es buena!\p"
	.string "¡Hola, me llamo {STR_VAR_1}!\p"
	.string "Llevo tiempo buscando un buen\n"
	.string "profesor que sepa de POKéMON.\p"
	.string "¡Y ahora llegas tú {PLAYER}{KUN},\n"
	.string "como agua de mayo!\p"
	.string "Bueno, ya lo sabes, {PLAYER}{KUN}.\n"
	.string "¿Me aceptas como tu aprendiz?$"

gText_ApprenticeRejectTeaching9::
	.string "¡Buaaaa!\n"
	.string "¡No hay nadie como tú!…\p"
	.string "No seas así, te lo pido por favor.\n"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode9::
	.string "¡Genial! ¡Eso es una respuesta!\n"
	.string "¡Una excelente, si puedo decirlo!\p"
	.string "¿Por qué no me das tu primer consejo\n"
	.string "sobre la TORRE BATALLA?\p"
	.string "Si fuese a participar en un desafío,\n"
	.string "¿qué elijo, el nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks9::
	.string "¡{STR_VAR_1}!\n"
	.string "¡G-e-n-i-a-l!\l"
	.string "¡Haré exactamente lo que dices!\p"
	.string "¡Ahora que soy tu aprendiz, nos veremos\n"
	.string "más a menudo! ¡Adiós!$"

gText_ApprenticePleaseTeach10::
	.string "Eh, tú eres {PLAYER}{KUN}, ¿verdad?\n"
	.string "¡Te está buscando la policía!\p"
	.string "…\n"
	.string "¡Es broma!\p"
	.string "Yo me llamo {STR_VAR_1}. Aunque no lo\n"
	.string "parezca, soy un CAMPEÓN POKéMON…\l"
	.string "¡Eso también es broma!\p"
	.string "Bueno, ahora fuera de bromas:\n"
	.string "no soy demasiado bueno combatiendo.\p"
	.string "¿Por qué no me dejas ser tu aprendiz\n"
	.string "y me enseñas algo sobre los POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Si vas a ir por ahí pasando de todo,\n"
	.string "¡vas a ver lo que hago yo!\p"
	.string "¡Buaaaa! ¡Buaaaa! ¡Buaaaa!\n"
	.string "¡Snif! ¡Buaaaa! ¡Buaaaa!\p"
	.string "¡Ja, ja, ja, ja! ¡Ése es mi LLANTO FALSO!\p"
	.string "Vamos, venga, que no se diga.\n"
	.string "¿Me dejas ser tu aprendiz?$"

gText_ApprenticeWhichLevelMode10::
	.string "¡Yupi!\n"
	.string "¡Te voy a regalar un yate!\p"
	.string "¡Bueno, otro día, claro!\n"
	.string "Pero… ¡gracias, mi capitán!\p"
	.string "Ya sabes que hay un nivel 50 y un nivel\n"
	.string "libre en la TORRE BATALLA, ¿verdad?\p"
	.string "Es que tengo problemas para decidirme\n"
	.string "en cuál de los dos debería participar…\p"
	.string "¿Cuál elegirías en mi lugar?$"

gText_ApprenticeLevelModeThanks10::
	.string "Vale, conque el {STR_VAR_1}.\n"
	.string "Entonces me apunto al otro, ¿no?\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticePleaseTeach11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "¡Me llamo {STR_VAR_1}, soy soltero,\n"
	.string "mal poeta y buen MARINERO!\p"
	.string "¡Dime algo de ti, hombre,\n"
	.string "aunque sólo sea tu nombre!\p"
	.string "¡Mmm! ¡{PLAYER}{KUN} dices llamarte,\n"
	.string "y que te gusta de POKéMON rodearte!\p"
	.string "¡Ah, qué edad la tuya más tierna,\n"
	.string "en la que la vida parece eterna!\p"
	.string "Bueno, de suerte creo que estoy,\n"
	.string "pues contigo ya son 10\l"
	.string "los ENTRENADORES que he visto hoy.\p"
	.string "Y, ya puestos, vamos a rematarlo.\n"
	.string "¡Hazme tu aprendiz para celebrarlo!$"

gText_ApprenticeRejectTeaching11::
	.string "Será broma, espero…\n"
	.string "¿O acaso rehúsas a un caballero?\p"
	.string "¡No me dejes con mal sabor!\n"
	.string "¡Hazme tu aprendiz, por favor!$"

gText_ApprenticeWhichLevelMode11::
	.string "¡Eso es! ¡{PLAYER}, así me gusta!\p"
	.string "Así que aquí va mi primera pregunta,\n"
	.string "¡que tu consejo no se desentienda!\p"
	.string "Es sobre la TORRE BATALLA, y depende\n"
	.string "de mi poder, ¡ya ves!\p"
	.string "Hay nivel 50 y nivel libre, ¿cuál de los\n"
	.string "dos me conviene a mí, dime cuál es?$"

gText_ApprenticeLevelModeThanks11::
	.string "Vale, el {STR_VAR_1} me aconsejas.\n"
	.string "¡Una duda que me despejas!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticePleaseTeach12::
	.string "¡Ey! ¿{PLAYER}? ¿Eres tú?\n"
	.string "¡Pues claro! “¡Only you!”\p"
	.string "Tranqui, {PLAYER}, no estoy loco.\n"
	.string "¡Es la música, que me absorbe el coco!\p"
	.string "Llámame {STR_VAR_1} si quieres,\n"
	.string "o rey de la guitarra, si lo prefieres.\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "{PLAYER}, voy a echarle valor,\n"
	.string "y te voy a pedir un favor.\p"
	.string "¡“Please”, déjame ser tu aprendiz!\n"
	.string "¡No habría nadie en el mundo tan feliz!$"

gText_ApprenticeRejectTeaching12::
	.string "¿Así que me rechazas? ¡Pues tendré\n"
	.string "que volver a pedírtelo!\p"
	.string "¡{PLAYER}, te suplico ser tu discípulo!\n"
	.string "¡Necesito que me enseñes todo de\l"
	.string "corrido!$"

gText_ApprenticeWhichLevelMode12::
	.string "“¡Ou, yea!” ¡Y ya que soy tu aprendiz!\n"
	.string "¿Por qué no me ayudas a decidir?\p"
	.string "En la TORRE BATALLA, siempre tengo\n"
	.string "una duda que nunca falla.\p"
	.string "De los niveles que vas a ver,\n"
	.string "¿cuál crees que debo escoger?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si {STR_VAR_1} es lo que sugieres,\n"
	.string "¡seguro que es lo mejor que eliges!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticePleaseTeach13::
	.string "¡Oh, hola! ¡Qué tal!\n"
	.string "¿Me das un masaje en el hombro?…\p"
	.string "¡Sí, ahí! ¡Justo ahí!\n"
	.string "¡Ay! ¡Ah! ¡Oh! ¡Oooh! ¡Mucho mejor!\p"
	.string "Me llamo {STR_VAR_1}.\n"
	.string "Voy a clases de karate, pero creo que\l"
	.string "mi cuerpo no está hecho para sufrir…\p"
	.string "He decidido combatir con POKéMON,\n"
	.string "así al menos yo no me haré daño.\p"
	.string "Tú eres {PLAYER}{KUN}, ¿a que sí?\n"
	.string "¿Verdad que has conseguido un\l"
	.string "CAMPEONATO de la LIGA POKéMON?\p"
	.string "Oye, ¿por qué no te animas a darme\n"
	.string "consejos en plan maestro y aprendiz?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, ¿y por qué no?\p"
	.string "¡No te daré la lata, de verdad!\n"
	.string "¿Anda, por favor?$"

gText_ApprenticeWhichLevelMode13::
	.string "Muchas gracias. ¡Es un detallazo!…\n"
	.string "¡Achís! ¡Achís!\p"
	.string "Ay, tengo que curarme esto…\p"
	.string "Voy a participar ahora mismo en la\n"
	.string "TORRE BATALLA, pero ¿qué crees que me\l"
	.string "convendría más? ¿El nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks13::
	.string "Ah, vale, el {STR_VAR_1}.\n"
	.string "Me largo ahora mismo.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticePleaseTeach14::
	.string "Esto… Mm…\n"
	.string "¿{PLAYER}{KUN}?…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me vas a sacar los colores.\p"
	.string "Yo… soy {STR_VAR_1}.\p"
	.string "Suena un poco pretencioso y así, pero\n"
	.string "yo me dedico a explorar ruinas, ¿sabes?\p"
	.string "Aunque puede que hasta suene\n"
	.string "más pretencioso querer participar\l"
	.string "en el FRENTE de BATALLA…\p"
	.string "{PLAYER}{KUN}, tú tienes fama de saber\n"
	.string "entrenar duro…\p"
	.string "No quería soltártelo así de repente,\n"
	.string "pero no me queda otro remedio.\p"
	.string "¿Querrías tomarme como aprendiz\n"
	.string "tuyo y darme consejos?$"

gText_ApprenticeRejectTeaching14::
	.string "¡Por favor, no me rechaces!\n"
	.string "Llevo fatal lo de las humillaciones.\p"
	.string "¡Anda, déjame ser tu aprendiz!\n"
	.string "¡Necesito tus consejos!$"

gText_ApprenticeWhichLevelMode14::
	.string "Gra-gracias…\p"
	.string "Pero no me mires más con esa cara\n"
	.string "o sólo tendrás un aprendiz frustrado.\p"
	.string "Anda, respóndeme a esta pregunta,\n"
	.string "pero sin mirarme a los ojos.\p"
	.string "En la TORRE BATALLA…\n"
	.string "¿en qué nivel debería inscribirme?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Probaré en ése, a ver qué tal.\p"
	.string "Espero combatir de manera digna para\n"
	.string "que no tengas que avergonzarte de mí…\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticePleaseTeach15::
	.string "¿Mmm? Pareces {PLAYER}{KUN}… Pero ¿eres\n"
	.string "real de verdad?\p"
	.string "Puedes llamarme {STR_VAR_1}.\p"
	.string "Llevo tiempo dándole vueltas a la idea\n"
	.string "de ser aprendiz de un ENTRENADOR\l"
	.string "fuerte.\p"
	.string "¡Así que debo decir que he tenido\n"
	.string "suerte de que aparecieras! … De\l"
	.string "verdad eres {PLAYER}{KUN}, ¿no?\p"
	.string "No, no, si eres real, no pasa nada. Solo\n"
	.string "quiero que me reconozcas como tu\l"
	.string "aprendiz.$"

gText_ApprenticeRejectTeaching15::
	.string "¡Oh!\n"
	.string "¿Qué te habrá empujado a rechazarme?\p"
	.string "Siento haberme mostrado tan escéptico\n"
	.string "sobre tu verdadera identidad.\p"
	.string "Te ruego aceptes mis disculpas\n"
	.string "y me tomes como tu aprendiz.$"

gText_ApprenticeWhichLevelMode15::
	.string "¿Realmente me aceptas de aprendiz?\n"
	.string "No querría lanzar las campanas al vuelo.\p"
	.string "Si es verdad, perdona las dudas que\n"
	.string "expresé antes sobre tu identidad.\l"
	.string "Pero ahora, necesito de tu consejo.\p"
	.string "Si fuese a entrar en la TORRE BATALLA,\n"
	.string "¿qué nivel sería digno de mí?,\l"
	.string "¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks15::
	.string "¿{STR_VAR_1}? ¿Estás seguro?\p"
	.string "Ya veo. Si es así, me parece bien. Te\n"
	.string "agradezco tu tiempo.\p"
	.string "Sé que puedo resultar molesto, pero me\n"
	.string "alegra que me hayas aceptado.\p"
	.string "¡Volvamos a vernos!$"

gText_ApprenticeWhatHeldItem0::
	.string "Ay… Snif…\p"
	.string "¡Oh, {PLAYER}!\p"
	.string "Estoy hecho un lío con un dilema que\n"
	.string "no consigo resolver.\p"
	.string "No sé qué objeto debería llevar mi\n"
	.string "{STR_VAR_1}.\p"
	.string "Dímelo, por favor, {PLAYER}. ¿Qué\n"
	.string "objeto debería llevar?$"

gText_ApprenticeHoldNothing0::
	.string "¿Ah, sí? ¿Crees que es mejor que mi\n"
	.string "{STR_VAR_1} no sostenga ningún objeto?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "¡Ah, vale! ¡Pues entonces ya está!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem0::
	.string "Ah, muy bien…\n"
	.string "Sí, tengo eso que llamas {STR_VAR_1}.\p"
	.string "¡Una preocupación menos!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "¡Buaaaa! ¡Anda, no seas así!\p"
	.string "Eso que llamas {STR_VAR_1} ya me\n"
	.string "suena de haberlo oído antes…\p"
	.string "¿O me quieres decir que {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem1::
	.string "¡Yupi! ¡Pero si eres {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "¿Tus POKéMON sostienen objetos?\n"
	.string "Quiero que el mío sostenga uno, pero…\p"
	.string "¿Cuál crees que le convendría más\n"
	.string "sostener a {STR_VAR_1}?\p"
	.string "¿Tú qué piensas?$"

gText_ApprenticeHoldNothing1::
	.string "¿Cómo? ¿Quieres decir que es mejor\n"
	.string "que mi {STR_VAR_1} no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "¡Vale, lo he pillado!\n"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeThanksHeldItem1::
	.string "Conque {STR_VAR_1}, ¿eh?\n"
	.string "¡Vale, lo he pillado!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ah, no, eso no es lo que quería.\n"
	.string "Quería que me dijeses un objeto\l"
	.string "distinto de los que ya conozco.\p"
	.string "¿O me estás queriendo decir que no\n"
	.string "debería sujetar nada mi POKéMON?$"

gText_ApprenticeWhatHeldItem2::
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}…\p"
	.string "Quiero que sostenga algún objeto.\n"
	.string "¿Cuál le vendría mejor?$"

gText_ApprenticeHoldNothing2::
	.string "Ah, ¿entonces crees que no tiene\n"
	.string "que sostener nada mi {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "¡Vale, lo he entendido!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, ¿{STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Haré lo que pueda por encontrar eso!\n"
	.string "¡Hasta otra!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Lo de {STR_VAR_1} ya me suena\n"
	.string "que me lo han dicho antes.\p"
	.string "Pero yo quiero que mi POKéMON\n"
	.string "sostenga algo distinto.\p"
	.string "¿O piensas que mi {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}… Siento molestarte,\n"
	.string "pero quería preguntarte otra cosa.\p"
	.string "No creo que sea lo bastante bueno\n"
	.string "como para ganar combates yo solo, así\l"
	.string "que estoy pensando en darle un objeto\l"
	.string "a mi {STR_VAR_1}.\p"
	.string "Pero no sé qué le iría bien.\p"
	.string "{PLAYER}, por favor, ¿podrías decidirlo\n"
	.string "tú por mí?$"

gText_ApprenticeHoldNothing3::
	.string "¿Crees que, teniendo en cuenta a quién\n"
	.string "pertenece, sería mejor que mi POKéMON\l"
	.string "no sostuviese ningún objeto?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Entiendo… Quieres decir que no\n"
	.string "debería depender de los objetos.\l"
	.string "¡Haré lo posible por no hacerlo!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem3::
	.string "Uf, {STR_VAR_1}, vale.\n"
	.string "No va a ser fácil conseguir algo así…\l"
	.string "Pero haré lo que pueda.\p"
	.string "¡Gracias mil!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, pero…\n"
	.string "Eso ya me lo han recomendado…\p"
	.string "¿A lo mejor es que no sé manejar\n"
	.string "bien ninguna clase de {STR_VAR_1}?\p"
	.string "¿O me quieres decir realmente que\n"
	.string "{STR_VAR_2} no debería sostener nada?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Tenía ganas de preguntarte una cosa.\p"
	.string "¿Te acuerdas de que una vez me dijiste\n"
	.string "qué clase de POKéMON debería entrenar?\p"
	.string "Pues es que se te olvidó decirme\n"
	.string "qué clase de objeto debería sostener.\p"
	.string "Ya que te decidiste a darme un consejo,\n"
	.string "no quiero que lo dejes a medias, claro.\p"
	.string "Anda, dime, ¿qué objeto debería\n"
	.string "sostener mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing4::
	.string "¡Ah! ¿Conque a mi {STR_VAR_1}\n"
	.string "le irá mejor si no lleva nada?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si crees que es lo mejor, lo haré.\p"
	.string "Sabiendo que lo has decidido tú,\n"
	.string "{PLAYER}{KUN}, no me disgustaré tanto si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem4::
	.string "Así que {STR_VAR_1}, ¿eh?\n"
	.string "¡No está mal! ¡Tomo nota!\p"
	.string "Sabiendo que me lo has dicho tú,\n"
	.string "{PLAYER}{KUN}, no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "¿Cómo? Pero ¿de qué hablas?\n"
	.string "No me vengas otra vez con lo de\l"
	.string "{STR_VAR_1}.\p"
	.string "¿O quieres decir que a {STR_VAR_2}\n"
	.string "le iría mejor si no llevase nada?$"

gText_ApprenticeWhatHeldItem5::
	.string "¡Eh, {PLAYER}{KUN}!\p"
	.string "¡Los dos estamos muy ocupados, pero\n"
	.string "parece que nos encontramos a menudo!\p"
	.string "Hoy tengo que pasear, limpiar y\n"
	.string "cepillar.\p"
	.string "Ni siquiera he tenido tiempo de\n"
	.string "comprarle nada a mi querido\l"
	.string "{STR_VAR_1}.\p"
	.string "No tengo tiempo, así que ¿qué tal si\n"
	.string "me aconsejas qué debería llevar mi\l"
	.string "{STR_VAR_1}?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, así que, como tengo tanto lío, ¿no\n"
	.string "tengo que buscarle nada a {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Vale, ya sé por dónde vas.\n"
	.string "¡Así no perderé el tiempo de compras!\p"
	.string "¡Gracias!\n"
	.string "¡Ya nos veremos!$"

gText_ApprenticeThanksHeldItem5::
	.string "{STR_VAR_1}, vale, entiendo.\n"
	.string "A ver si puedo sacar un rato libre\l"
	.string "y me voy a comprar eso que dices.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "¿Eh? Lo de {STR_VAR_1} ya me suena\n"
	.string "de haberlo oído antes.\p"
	.string "¡Ah, ya! ¡Ahora pillo la indirecta!\n"
	.string "Que no pierda el tiempo en comprarle\l"
	.string "nada a {STR_VAR_2}, ¿no?$"

gText_ApprenticeWhatHeldItem6::
	.string "¡{PLAYER}! ¡Soy yo!\n"
	.string "Necesito tu coco otra vez.\l"
	.string "¡Tienes que darme un consejo!\p"
	.string "¡Iré al grano!\n"
	.string "Mi pregunta es…\p"
	.string "Si quiero que mi {STR_VAR_1} sostenga\n"
	.string "un objeto, ¿cuál me recomendarías?$"

gText_ApprenticeHoldNothing6::
	.string "¿Seguro? Que mejor que mi {STR_VAR_1}\n"
	.string "no sostenga nada, dices, ¿eh?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "¡Vale, eso haré!\p"
	.string "Creo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Volvamos a vernos aquí, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeThanksHeldItem6::
	.string "¡Ajá! Un {STR_VAR_1}. ¡Qué buena\n"
	.string "elección! ¡Lo probaré seguro!\p"
	.string "Creo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Volvamos a vernos aquí, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "¡Ja, ja, ja! ¡Qué tontería!\n"
	.string "¡Eso de {STR_VAR_1} ya me lo habías\l"
	.string "dicho antes!\p"
	.string "¿Seguro que estás bien, {PLAYER}?\p"
	.string "¡Espera! ¡Era una indirecta para decirme\n"
	.string "que {STR_VAR_2} no debería llevar nada!$"

gText_ApprenticeWhatHeldItem7::
	.string "Hola, {PLAYER}. Espero que te vaya\n"
	.string "bien.\p"
	.string "¿Puedo pedirte consejo?\p"
	.string "En un combate reciente, parecía que\n"
	.string "mi rival le había dado un objeto a su\l"
	.string "POKéMON.\p"
	.string "Y por eso me derrotó…\p"
	.string "No quiero quedarme atrás. A mí también\n"
	.string "me gustaría darle un objeto a mi\l"
	.string "{STR_VAR_1}.\p"
	.string "Me alegraría mucho que decidieras qué\n"
	.string "le iría bien a mi POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "En otras palabras…, que mi POKéMON\n"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeThanksNoHeldItem7::
	.string "¡Pues claro! ¡Ahora lo entiendo!\n"
	.string "Seguiré combatiendo como hasta ahora.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeThanksHeldItem7::
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Ahora mismo voy a pedir lo que me dices!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "¡Eso ya me lo dijiste\n"
	.string "y además ya lo tengo!\p"
	.string "¿O me estás diciendo que mi POKéMON\n"
	.string "no necesita llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem8::
	.string "¡Hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh! ¡Ya sé! ¡Voy a preguntarte\n"
	.string "algo ahorita mismo, {PLAYER}!\p"
	.string "¡Dime qué objeto crees que\n"
	.string "debería sostener mi {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8::
	.string "¡Oh, vaya! ¡Eso no me lo esperaba!\n"
	.string "¿Así que no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "¡Lo he entendido a la primera!\n"
	.string "¡Seguiré luchando sin objetos!\p"
	.string "Espero que no te olvides\n"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeThanksHeldItem8::
	.string "¡{STR_VAR_1}! ¡Por supuestísimo!\p"
	.string "Mmm… ¿No será, {PLAYER}, que tu POKéMON\n"
	.string "también sostiene ese objeto?\p"
	.string "¡Da igual! ¡Te haré caso!\n"
	.string "Espero que no te olvides\l"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "¿Cómo? ¿{STR_VAR_1}? ¿Otra vez?\n"
	.string "¡Pero eso ya me lo recomendaste antes!\p"
	.string "Una de dos, o te gusta mucho,\n"
	.string "o me estás diciendo que mi {STR_VAR_2}\l"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeWhatHeldItem9::
	.string "¡Hola! ¡{PLAYER}{KUN}!\n"
	.string "¡Qué ganas tenía de verte!\p"
	.string "Necesito que me aconsejes\n"
	.string "sobre los objetos POKéMON.\p"
	.string "¿Cuál crees que sería mejor\n"
	.string "que sostuviese mi {STR_VAR_1}?\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeHoldNothing9::
	.string "¿Eh? ¿Así que mi {STR_VAR_1}\n"
	.string "no debería llevar nada?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "¡Vale, vale!\n"
	.string "¡Lo intentaré como dices, a ver qué tal!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem9::
	.string "¿{STR_VAR_1}? ¡Vale, vale!\n"
	.string "¡A ver si pillo algo de eso!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "¡No, no! ¡Eso ya lo has dicho antes!\n"
	.string "¡Sí, me acuerdo! ¡{STR_VAR_1}!\p"
	.string "Alto ahí… ¿No me estarás diciendo que\n"
	.string "{STR_VAR_2} puede ganar sin objetos?$"

gText_ApprenticeWhatHeldItem10::
	.string "¡{PLAYER}{KUN}, ha pasado algo increíble!\p"
	.string "¡Esta mañana me he despertado y mi\n"
	.string "POKéMON tenía 10 PEPITAS!\p"
	.string "¡Pues claro que es mentira!\n"
	.string "¡Juajajajá!\p"
	.string "Pero esto no es mentira: no se me da\n"
	.string "muy bien pensar qué objetos deberían\l"
	.string "llevar los POKéMON.\p"
	.string "Así que ¿qué tal si decides tú qué\n"
	.string "debería llevar mi {STR_VAR_1},\l"
	.string "maestro?$"

gText_ApprenticeHoldNothing10::
	.string "¿Qué significa eso?\n"
	.string "¿Que no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Vale, entonces no sostendrá nada.\n"
	.string "Pero yo sí puedo, ¿no?\p"
	.string "¡Es broma!\n"
	.string "¡Te voy a hacer caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeThanksHeldItem10::
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Le compraré todo menos eso!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Eh, eso ya me lo dijiste antes, ¿no?\p"
	.string "¿No hay otra cosa?\p"
	.string "¿O quieres decir que mi {STR_VAR_2} no\n"
	.string "lleve nada?$"

gText_ApprenticeWhatHeldItem11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy un poeta MARINERO,\n"
	.string "y necesito otro de tus consejos\l"
	.string "para llegar a donde quiero.\p"
	.string "¡Aconséjame bien sobre un objeto\n"
	.string "y te ganarás todo mi respeto!\p"
	.string "Dime, ¿de entre todos los objetos,\n"
	.string "cuál debe mi {STR_VAR_1} llevar sujeto?$"

gText_ApprenticeHoldNothing11::
	.string "La cosa no parece muy clara. Acaso…,\n"
	.string "¿no debe mi {STR_VAR_1} sujetar nada?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "¡Ah, claro! ¡Ya entiendo tu teoría!\n"
	.string "¡Mi POKéMON irá con las manos vacías!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeThanksHeldItem11::
	.string "¿{STR_VAR_1}? ¿Has dicho eso?\n"
	.string "¡Si no picara mi barba, te daría un beso!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{STR_VAR_1} me dijiste ya el otro día…\n"
	.string "¿Te repites o es sólo antipatía?\p"
	.string "Espera, ahora veo la cosa más clara…,\n"
	.string "¿no debe mi POKéMON sujetar nada?$"

gText_ApprenticeWhatHeldItem12::
	.string "Oh, “yea”, {PLAYER}, ¿qué tal?\n"
	.string "¡A mí me va la cosa fatal!\p"
	.string "¿Qué hago? ¿Te pido consejo?\n"
	.string "¿Por qué no? ¡Si tú eres mi espejo!\p"
	.string "{PLAYER}, ¿te estoy dando la lata?\n"
	.string "Naa, qué va, ¡yo nunca meto la pata!\p"
	.string "¿Me escucharías un segundo?\n"
	.string "Estoy buscando un consejo\l"
	.string "para ganar combates por todo el mundo.\p"
	.string "Anda, dime, ¿qué objeto crees\n"
	.string "que mi {STR_VAR_1} debería sujetar?\l"
	.string "Es una decisión que no puedo demorar.$"

gText_ApprenticeHoldNothing12::
	.string "¿Que mi {STR_VAR_1} no necesita nada?\n"
	.string "¡Eso sí que no me lo esperaba!$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si no llevar nada es lo mejor, ¡haré lo\n"
	.string "que dices, por favor!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticeThanksHeldItem12::
	.string "Si llevar ese {STR_VAR_1} es lo mejor,\n"
	.string "¡haré lo que dices, por favor!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "¿{STR_VAR_1}? Esa cosa ya me suena.\n"
	.string "¿No tienes una idea más nueva?\p"
	.string "Pero, espera, quieres decir acaso…,\n"
	.string "¿que mi {STR_VAR_2} no necesita nada?\l"
	.string "¡Eso sí que no me lo esperaba!$"

gText_ApprenticeWhatHeldItem13::
	.string "¡Uaa! ¡Ay! ¡{PLAYER}{KUN}, me he roto el brazo!\n"
	.string "¡No me lo toques, por favor!\p"
	.string "He debido de rompérmelo antes cuando\n"
	.string "estaba intentando sujetar distintos\l"
	.string "objetos con mi pose de POKéMON.\p"
	.string "Bueno, visto lo visto, ahora voy\n"
	.string "a necesitar tu ayuda para decidirme.\p"
	.string "{PLAYER}{KUN}, ¿qué objeto crees\n"
	.string "que debería sujetar mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "¡Ay!…\p"
	.string "¿Tanto probar y ahora me dices que\n"
	.string "mi {STR_VAR_1} no debería llevar nada?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Mmm, de acuerdo. Tal y como están\n"
	.string "las cosas ahora, me vendrá bien.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeThanksHeldItem13::
	.string "¿{STR_VAR_1}? Mmm, de acuerdo.\n"
	.string "El brazo de mi POKéMON está bien,\l"
	.string "así que le haré sujetar eso ahora mismo.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, ese {STR_VAR_1} ya me lo dijiste\n"
	.string "antes, ¿te acuerdas?\p"
	.string "¿Qué tal si me dices algo aún mejor?\p"
	.string "Ah, espera un momento. ¿Entonces\n"
	.string "sugieres que mi {STR_VAR_2} no tiene\l"
	.string "por qué llevar nada?$"

gText_ApprenticeWhatHeldItem14::
	.string "Eh… Mmm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Mi POKéMON no tiene nada.\p"
	.string "Me… avergüenza un poco decirlo,\n"
	.string "pero necesito otro consejo tuyo.\p"
	.string "No me decido sobre qué objeto haría más\n"
	.string "fuerte a mi {STR_VAR_1} si lo sujetara.\p"
	.string "{PLAYER}{KUN}, ¿tú cuál crees\n"
	.string "que lo haría más fuerte?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Conque piensas que a mi {STR_VAR_1}\n"
	.string "le iría mejor si no sujetase nada…$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Eh… ¡Como tú digas!\n"
	.string "Sin ningún objeto, entonces.\p"
	.string "Aunque me agobia un poco la idea.\n"
	.string "¿No crees que es ir de muy guay?\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… ¡Como tú digas!\n"
	.string "¿{STR_VAR_1}? Vale, vale.\p"
	.string "Aunque me agobia un poco la idea.\n"
	.string "¿No crees que es ir de muy guay?\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "Pe-pero eso ya me suena de otra vez.\p"
	.string "¡Anda, no te burles así de mí!\n"
	.string "¡Bastante agobio tengo ya!\p"
	.string "Oh, espera… ¿Era una indirecta?…\n"
	.string "¿En realidad estás diciéndome que\l"
	.string "mi {STR_VAR_2} no debería sujetar nada?$"

gText_ApprenticeWhatHeldItem15::
	.string "¿Mmm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\l"
	.string "¿O es que te pareces mucho?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor,\l"
	.string "perdona el despiste.\p"
	.string "La verdad es que me gustaría\n"
	.string "solicitar uno de tus sabios consejos.\p"
	.string "Desearía conocer el objeto que más le\n"
	.string "convendría sostener a mi {STR_VAR_1}.\p"
	.string "¿Cuál crees que sería más digno de él?$"

gText_ApprenticeHoldNothing15::
	.string "¿Nada, dices que sostenga?\n"
	.string "¿Es ésa tu conclusión?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ya veo. Si es así, me parece bien. Te\n"
	.string "agradezco tu tiempo.\p"
	.string "¡Volvamos a vernos!$"

gText_ApprenticeThanksHeldItem15::
	.string "¿Un {STR_VAR_1}? ¿Estás seguro?\p"
	.string "Ya veo. Si es así, me parece bien. Te\n"
	.string "agradezco tu tiempo.\p"
	.string "Espero que mi POKéMON pueda sacarle\n"
	.string "partido.\p"
	.string "¡Volvamos a vernos!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Vaya, qué contradicción.\n"
	.string "Creo haber oído eso ya otra vez de ti.\p"
	.string "Me hubiese gustado oír\n"
	.string "algo diferente esta vez.\p"
	.string "Salvo que… estés sugiriéndome que mi\n"
	.string "{STR_VAR_2} no sujete nada…\l"
	.string "¿Estoy en lo cierto? ¿Es lo que dices?$"

gText_ApprenticeWhichMonFirst0::
	.string "¡Ay, {PLAYER}!\n"
	.string "Qué dilema tengo, snif…\p"
	.string "Quiero empezar a combatir,\n"
	.string "pero no sé muy bien qué hacer.\p"
	.string "¿Cómo debo alinear mis POKéMON\n"
	.string "para que sean más fuertes?\p"
	.string "Porfa, dímelo, {PLAYER}.\n"
	.string "Si fueses yo, ¿a cuál de estos POKéMON\l"
	.string "sacarías a combatir en primer lugar?$"

gText_ApprenticeMonFirstThanks0::
	.string "¿Primero mi {STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "De tanta alegría por elegir a mi primer\l"
	.string "POKéMON me he puesto a llorar…\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMonFirst1::
	.string "¡Yupi, {PLAYER}! ¡Qué suerte!\n"
	.string "¡Así podré hacerte una pregunta!\p"
	.string "Eh, de todos mis POKéMON, ¿a cuál crees\n"
	.string "que debería sacar primero a combatir?$"

gText_ApprenticeMonFirstThanks1::
	.string "¿Mi {STR_VAR_1}? ¡Claro, es verdad!\n"
	.string "¡Perfecto, será lo que haga!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMonFirst2::
	.string "¡{PLAYER}, hola!\p"
	.string "Creo que es muy importante elegir qué\n"
	.string "POKéMON saldrá primero a combatir.\p"
	.string "De todos los POKéMON que tengo,\n"
	.string "¿a cuál debería sacar primero?$"

gText_ApprenticeMonFirstThanks2::
	.string "¿{STR_VAR_1}, el primero?\n"
	.string "¡Vale, entendido!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte otra vez\l"
	.string "con una de mis preguntas.\p"
	.string "Confío tan poco en mí…\n"
	.string "No sé lo que haría sin ti, {PLAYER}.\p"
	.string "A lo mejor es sólo una tontería,\n"
	.string "pero te lo pregunto de todos modos\l"
	.string "porque no me decido…\p"
	.string "¿A qué POKéMON debería sacar\n"
	.string "primero en los combates?$"

gText_ApprenticeMonFirstThanks3::
	.string "¿Mi {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Qué suerte! ¡Creí que no ibas a querer\n"
	.string "responder a todas mis preguntillas!\p"
	.string "Te daría las gracias aunque sólo fuera\n"
	.string "por hablar conmigo… ¡Gracias!$"

gText_ApprenticeWhichMonFirst4::
	.string "¡Eh, hola, {PLAYER}{KUN}! ¡Soy yo!\n"
	.string "Qué suerte que estés aquí,\l"
	.string "porque tengo una duda.\p"
	.string "No me decido sobre cuál sería la mejor\n"
	.string "alineación de mis POKéMON. ¿Me ayudas?\p"
	.string "No hace falta que decidas toda\n"
	.string "la alineación ahora.\p"
	.string "Basta que me digas a qué POKéMON\n"
	.string "sacarías primero. ¿Cuál sería mejor?$"

gText_ApprenticeMonFirstThanks4::
	.string "¿Mi querido {STR_VAR_1}? ¡Fenomenal!\p"
	.string "Sabiendo que lo has decidido tú,\n"
	.string "{PLAYER}{KUN}, ya no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMonFirst5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Sigo sin parar de hacer cosas!\p"
	.string "Que si correr en bici, que si comprar,\n"
	.string "que si hacer esto y aquello…\p"
	.string "La verdad es que no he tenido tiempo de\n"
	.string "pensar en la alineación de mis POKéMON.\p"
	.string "Anda, ¿por qué no me ayudas tú un poco?\n"
	.string "¿A cuál debería sacar siempre primero?$"

gText_ApprenticeMonFirstThanks5::
	.string "Hecho.\n"
	.string "¡Espero al menos tener tiempo para\l"
	.string "poner a mi {STR_VAR_1} el primero!\p"
	.string "¡Huy, me está esperando mi novia!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMonFirst6::
	.string "¡Eh, mírate, {PLAYER}!\n"
	.string "¡Siempre vas por ahí de perdonavidas!\p"
	.string "Escucha, necesito otro favorcillo.\n"
	.string "Una cosilla de nada, ya sabes.\p"
	.string "Y la pregunta es…\n"
	.string "¡Tachán, tachán!…\p"
	.string "¿A cuál de mis POKéMON\n"
	.string "debo sacar primero en los combates?$"

gText_ApprenticeMonFirstThanks6::
	.string "¡Mmm!\n"
	.string "Mi {STR_VAR_1}, ¿dices?\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo\n"
	.string "lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMonFirst7::
	.string "Huy, qué fenomenal que vengas\n"
	.string "a hablar conmigo, {PLAYER}.\p"
	.string "No quiero parecer una desvergonzada,\n"
	.string "pero ¿podría pedirte otro favor?\p"
	.string "Querría que eligieses por mí el orden\n"
	.string "de los POKéMON de mi equipo.\p"
	.string "Te estaría agradecidísima si me dijeras\n"
	.string "a cuál de mis POKéMON sacarías primero.$"

gText_ApprenticeMonFirstThanks7::
	.string "¿{STR_VAR_1}? ¡Justo lo que pensaba!\n"
	.string "¡Voy a ponerlo primero ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMonFirst8::
	.string "¡Hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte otra vez!\p"
	.string "¡Gracias a ti, mis POKéMON son ahora\n"
	.string "pero que muchísimo más fuertes!\p"
	.string "Aunque no siempre gano. Creo que\n"
	.string "depende de qué POKéMON salga primero.\p"
	.string "¡{PLAYER}, por favor, ayúdame con esto!\p"
	.string "¡Elige al POKéMON que crees que\n"
	.string "tengo que sacar primero a combatir!$"

gText_ApprenticeMonFirstThanks8::
	.string "Ay… Me desborda la felicidad…\p"
	.string "Es como un sueño que lo decidas tú por\n"
	.string "mí, {PLAYER}.\p"
	.string "¡Pero entendido perfectamente!\n"
	.string "¡Empezaré con mi {STR_VAR_1}!\p"
	.string "Espero que quieras enseñarme algo más\n"
	.string "en otra ocasión.$"

gText_ApprenticeWhichMonFirst9::
	.string "¡Pero si eres tú, {PLAYER}{KUN}!\n"
	.string "¡Sorpréndeme con otro sabio\l"
	.string "consejo de los tuyos!\p"
	.string "He conseguido formar un equipo de tres\n"
	.string "POKéMON. Así dicho, la cosa suena bien.\p"
	.string "Pero no tengo muy claro el orden\n"
	.string "en que deben combatir.\p"
	.string "¡Y para eso estás tú aquí, {PLAYER}{KUN}! ¡Tú\n"
	.string "decidirás a qué POKéMON saco primero!\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeMonFirstThanks9::
	.string "¡Eso es, mi {STR_VAR_1} será el primero!\n"
	.string "¡G-e-n-i-a-l!\l"
	.string "¡Voy a cambiar ya mismo la alineación!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst10::
	.string "¡{PLAYER}{KUN}, escucha!\n"
	.string "¡Estoy en medio de una crisis!\p"
	.string "¡Los tres POKéMON de mi equipo\n"
	.string "salen a la vez a combatir!\p"
	.string "¡Bueno, bueno, “casi” a la vez!\n"
	.string "Je, je, je, je.\p"
	.string "Pero hay algo que es verdad.\n"
	.string "Mis tres POKéMON son tan buenos que\l"
	.string "no me decido a elegir cuál sale primero.\p"
	.string "¿Por qué no me ayudas? ¿Tú qué crees,\n"
	.string "a qué POKéMON sacarías primero?$"

gText_ApprenticeMonFirstThanks10::
	.string "Entendido, mi {STR_VAR_1}, vale.\n"
	.string "¡Lo pondré el último!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMonFirst11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy un poeta MARINERO,\n"
	.string "y necesito otro de tus consejos\l"
	.string "para llegar a donde quiero.\p"
	.string "¡Aconséjame sobre la alineación\n"
	.string "y te lo agradeceré con devoción!\p"
	.string "De todos los POKéMON de este MARINERO\n"
	.string "¿con cuál combatirías primero?$"

gText_ApprenticeMonFirstThanks11::
	.string "¡Hacerte caso es lo que quiero!\n"
	.string "¡Pondré al que dices primero!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMonFirst12::
	.string "¡Yahú, {PLAYER}! ¿Qué tal estás?\p"
	.string "¿Qué hago? ¿Te pregunto sin más?\n"
	.string "¡Ajá, tengo algo que preguntar, ya\l"
	.string "verás! ¿Me recibes? ¡Me recibes!\p"
	.string "Tienes que decidir cuál de mis POKéMON\n"
	.string "sale el primero a lucir… ¡Al combate,\l"
	.string "quiero decir!$"

gText_ApprenticeMonFirstThanks12::
	.string "¿Mi {STR_VAR_1}? ¡Sí! ¡Con eso no hay\n"
	.string "agobio!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticeWhichMonFirst13::
	.string "Uuf… Auu… {PLAYER}{KUN}…\n"
	.string "Me duele mucho la tripa…\p"
	.string "Pero se me está pasando…\p"
	.string "Deben de ser los nervios por no saber\n"
	.string "a qué POKéMON debería sacar primero.\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, ¿a qué POKéMON debería\n"
	.string "sacar primero? Para ganar, se entiende.$"

gText_ApprenticeMonFirstThanks13::
	.string "Mm, muy bien.\n"
	.string "Pondré primero a mi {STR_VAR_1}.\p"
	.string "Voy a comer algo y luego arreglo\n"
	.string "lo de la alineación.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMonFirst14::
	.string "Esto… Mm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me vas a sacar los colores.\p"
	.string "Mm…\n"
	.string "Necesito tu consejo, de verdad.\p"
	.string "Ahora que por fin había elegido los\n"
	.string "tres POKéMON de mi equipo, no me\l"
	.string "decido por cuál debería salir primero.\p"
	.string "¿Cuál crees que debería salir primero\n"
	.string "para por lo menos no hacer el ridículo?$"

gText_ApprenticeMonFirstThanks14::
	.string "Ah… ¡Vale!\n"
	.string "Pondré a mi {STR_VAR_1} primero.\p"
	.string "Espero hacerlo bien y no aturullarme\n"
	.string "en el momento del combate.\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMonFirst15::
	.string "¿Mmm? Pareces {PLAYER}{KUN}… Pero ¿lo eres\n"
	.string "de verdad? ¿No serás un doble muy\l"
	.string "logrado?\p"
	.string "Ay, no, no, no, ¡no te preocupes! Si de\n"
	.string "verdad eres {PLAYER}, olvida mi\l"
	.string "grosería, por favor.\p"
	.string "Lo que me gustaría es un buen consejo\n"
	.string "tuyo.\p"
	.string "Aquí tengo a mi equipo POKéMON. Me\n"
	.string "gustaría que me dijeras cuál debería\l"
	.string "salir el primero en un combate.$"

gText_ApprenticeMonFirstThanks15::
	.string "Mi {STR_VAR_1}…\n"
	.string "¿Te burlas de mí?\p"
	.string "En fin, confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Confío en hacerlo lo mejor que pueda.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeWhichMon0::
	.string "Snif… ¡Oh, {PLAYER}!\p"
	.string "¡Qué oportuno! Hay algo que no\n"
	.string "consigo decidir…\p"
	.string "No sé qué POKéMON debería usar.\p"
	.string "No me decido entre {STR_VAR_1} y\n"
	.string "{STR_VAR_2}…\p"
	.string "{PLAYER}, ¿cuál crees que me daría\n"
	.string "alguna posibilidad de ganar, incluso a\l"
	.string "mí?$"

gText_ApprenticeMonThanks0::
	.string "Snif… Ya… Comprendo.\n"
	.string "¡Oh! ¡Cuánto lo siento!\l"
	.string "Son lágrimas de felicidad otra vez…\p"
	.string "¡Haré lo que pueda por atrapar uno\n"
	.string "de esos {STR_VAR_1}!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMon1::
	.string "¡Yupi! ¡Eres {PLAYER}!\n"
	.string "¡Y llegas en el momento adecuado!\l"
	.string "¡Necesito otra vez tu ayuda!\p"
	.string "Estoy hecho un lío. Que si el\n"
	.string "{STR_VAR_1} o que si el {STR_VAR_2}…\p"
	.string "¿Cuál crees que debería entrenar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, mejor mi {STR_VAR_1}, ¿eh?\n"
	.string "¡Genial, haré justo eso!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMon2::
	.string "¡{PLAYER}, hola!\n"
	.string "Quería preguntarte algo.\p"
	.string "Tengo el dilema de si debería entrenar\n"
	.string "un {STR_VAR_1} o un {STR_VAR_2}.\p"
	.string "¿Con qué POKéMON crees que llegaré\n"
	.string "a hacerme más fuerte?$"

gText_ApprenticeMonThanks2::
	.string "Un {STR_VAR_1}. Perfecto.\n"
	.string "¡Vale, lo he entendido!\p"
	.string "¡Voy a atrapar ahora mismo\n"
	.string "un {STR_VAR_1} fuerte de verdad!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMon3::
	.string "Hola, {PLAYER}…\p"
	.string "Mm, probablemente ya ni te acuerdes\n"
	.string "de mí…\p"
	.string "Pero no importa, con tal de que quieras\n"
	.string "volver a darme un consejo…\p"
	.string "No me decido por qué clase de\n"
	.string "POKéMON debería entrenar…\p"
	.string "Ahora la duda está entre un {STR_VAR_1}\n"
	.string "o un {STR_VAR_2}, pero no salgo de ahí…\p"
	.string "{PLAYER}, ¿sería mucho pedirte\n"
	.string "que decidieses por mí?$"

gText_ApprenticeMonThanks3::
	.string "Espero que los {STR_VAR_1} salvajes\n"
	.string "no pasen también de mí.\p"
	.string "¡Intentaré encontrar uno!\p"
	.string "No sé si seré capaz de encontrar uno…\n"
	.string "¡No! ¡Basta ya! ¡Tengo que ser positiva!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Qué alegría verte! ¡Iba\n"
	.string "a ir a buscarte!\p"
	.string "¿Puedes decidir qué POKéMON debería\n"
	.string "usar?\p"
	.string "Por ejemplo… ¿Qué tal {STR_VAR_1} y\n"
	.string "{STR_VAR_2}?\p"
	.string "¿Cuál crees que sería mejor?$"

gText_ApprenticeMonThanks4::
	.string "¿{STR_VAR_1}? ¡Maravilloso!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMon5::
	.string "¡Pero si es {PLAYER}{KUN}! ¿Cómo te va?\n"
	.string "¡Yo, ocupado, como siempre!\p"
	.string "Ya sabes que yo también quiero llegar a\n"
	.string "ser alguien muy bueno con mis POKéMON,\l"
	.string "pero no sé en cuál debo centrarme.\p"
	.string "Sí, los {STR_VAR_1} son fuertes,\n"
	.string "pero los {STR_VAR_2} no lo son menos.\p"
	.string "¡{PLAYER}{KUN}, dame un consejillo!\n"
	.string "¿Cuál me vendría mejor a mí?$"

gText_ApprenticeMonThanks5::
	.string "Perfecto, entendido.\n"
	.string "A ver si pillo un rato libre y atrapo uno\l"
	.string "de esos {STR_VAR_1} que recomiendas.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeWhichMon6::
	.string "¡Oh!\n"
	.string "¡Eh, hola, es {PLAYER}!\p"
	.string "¡No he perdido el tiempo presumiendo de\n"
	.string "haberte conocido delante de mis amigos!\p"
	.string "Necesito tu coco otra vez.\n"
	.string "¡Ahí va una fácil para ti!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Si tuviera que entrenar un POKéMON,\n"
	.string "y las opciones fueran un {STR_VAR_1}\l"
	.string "o un {STR_VAR_2}, ¿cuál debería elegir?$"

gText_ApprenticeMonThanks6::
	.string "¡Aaah!\n"
	.string "¡{STR_VAR_1}, claro!\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon7::
	.string "¡Oh, oh, oh! ¡{PLAYER}!\n"
	.string "¡Encantadísima de volver a verte!\p"
	.string "Desde que soy tu aprendiz,\n"
	.string "tengo mucha más confianza en mí misma.\p"
	.string "¡Creo que ya estoy preparada para\n"
	.string "entrenar un POKéMON yo solita!\p"
	.string "¡Sólo necesito que ahora tú\n"
	.string "me aconsejes cuál, {PLAYER}!\p"
	.string "Las opciones son un POKéMON\n"
	.string "{STR_VAR_1} o un {STR_VAR_2}…\l"
	.string "¿Cuál es mejor para mí?$"

gText_ApprenticeMonThanks7::
	.string "¡Un {STR_VAR_1}! ¡Perfecto!\n"
	.string "¡Voy a buscar uno ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMon8::
	.string "¡Hooola, {PLAYER}! ¡Qué suerte!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¡No quiero que te me vayas así!\p"
	.string "¿Puedo pedirte un gran favor, {PLAYER}?\n"
	.string "¡Elige un POKéMON por mí!\p"
	.string "Decide por mí a cuál debería entrenar,\n"
	.string "¿a {STR_VAR_1} o a {STR_VAR_2}?$"

gText_ApprenticeMonThanks8::
	.string "¡Guay! ¡Gracias por decidir!\n"
	.string "¡Voy a entrenar a ese {STR_VAR_1}\l"
	.string "lo mejor que pueda, ya verás!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeWhichMon9::
	.string "¡Eh, eh! ¡{PLAYER}{KUN}!\n"
	.string "¡Soy tu aprendiz favorito! Espero…\p"
	.string "¡He andado por ahí buscándote porque\n"
	.string "necesito otro de tus sabios consejos!\p"
	.string "¿Cuál de estos dos POKéMON piensas\n"
	.string "tú que me convendría entrenar más,\l"
	.string "un {STR_VAR_1} o un {STR_VAR_2}?\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeMonThanks9::
	.string "¡Ah, ajá, un {STR_VAR_1}!\n"
	.string "¡Genial!\l"
	.string "¡Voy a meterlo en mi BOLA pero que ya!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon10::
	.string "¡{PLAYER}{KUN}, escucha! ¡Buenas noticias!\n"
	.string "¡He pillado un POKéMON espejismo!\p"
	.string "¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Pero lo que voy a decirte ahora no lo es.\n"
	.string "Soy un poco malillo pillando POKéMON.\p"
	.string "He pensado que lo mejor es que me\n"
	.string "centre en atrapar sólo uno, y por eso\l"
	.string "quería que eligieses por mí cuál.\p"
	.string "¿Cuál me convendría más?\n"
	.string "¿Un {STR_VAR_1} o un {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Vale, dices que un {STR_VAR_1}, ¿no?\n"
	.string "¡Entonces trataré de pillar el otro!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMon11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "¡Soy el poeta MARINERO!\n"
	.string "¡De tus aprendices, el primero!\p"
	.string "Sobre un POKéMON te quiero preguntar,\n"
	.string "¡espero que tú me sepas contestar!\p"
	.string "Quiero uno de estos POKéMON entrenar:\n"
	.string "un {STR_VAR_1} o un {STR_VAR_2}.\l"
	.string "Dime, ¿cuál de los dos POKéMON será?$"

gText_ApprenticeMonThanks11::
	.string "¡{STR_VAR_1}! ¡Bien visto!\n"
	.string "¡Voy a por él ahora mismo!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMon12::
	.string "¡Anda, si es {PLAYER}!\p"
	.string "¿Qué hago? ¿Pedirte consejo? ¿Por\n"
	.string "qué no? ¡Si ya estoy hablando contigo!\p"
	.string "Hace mucho que no nos vemos. Para\n"
	.string "romper el hielo, ¡también busco\l"
	.string "consejo! ¿Me recibes? ¡Me recibes!\p"
	.string "Mis POKéMON… ¿cuál debería usar? Es\n"
	.string "{STR_VAR_1} o {STR_VAR_2}. ¿Cuál\l"
	.string "eliges?$"

gText_ApprenticeMonThanks12::
	.string "Si ese {STR_VAR_1} es lo mejor, ¡haré lo\n"
	.string "que dices, por favor!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticeWhichMon13::
	.string "Ay, hola, {PLAYER}{KUN}…\n"
	.string "Qué dolor de cabeza llevo…\p"
	.string "Seguro que es por pensar tanto en qué\n"
	.string "POKéMON debería elegir para entrenar.\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, si tuvieras que elegir entre\n"
	.string "el POKéMON {STR_VAR_1} y el {STR_VAR_2}\l"
	.string "para mí, ¿cuál elegirías?$"

gText_ApprenticeMonThanks13::
	.string "Mm, un {STR_VAR_1}, de acuerdo.\n"
	.string "Buscaré uno cuando se me pase esto.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMon14::
	.string "Eh… Mm…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me frustra mucho eso…\l"
	.string "Es que… necesito otro consejo.\p"
	.string "Es que… me avergüenza reconocerlo,\n"
	.string "pero no sé qué POKéMON entrenar.\p"
	.string "Entre un {STR_VAR_1} o un {STR_VAR_2},\n"
	.string "¿cuál es mejor para mí?$"

gText_ApprenticeMonThanks14::
	.string "Oh… ¡Vale!\n"
	.string "A ver dónde llego con ese {STR_VAR_1}…\p"
	.string "Espero hacerlo bien y no aturullarme\n"
	.string "en el momento del combate.\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMon15::
	.string "¿Mm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\p"
	.string "No, no, si lo eres, está bien.\n"
	.string "A propósito, necesitaría un consejo.\p"
	.string "Es sobre el POKéMON que debo entrenar.\p"
	.string "Si las posibilidades fueran un POKéMON\n"
	.string "{STR_VAR_1} y un {STR_VAR_2}, ¿cuál\l"
	.string "crees tú que sería más digno de mí?$"

gText_ApprenticeMonThanks15::
	.string "¿{STR_VAR_1}? ¿Estás seguro?\p"
	.string "Ya veo. Si es así, me parece bien. Te\n"
	.string "agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso yo\n"
	.string "pueda manejar con soltura.\p"
	.string "¡Volvamos a vernos!$"

gText_ApprenticeWhichMove0::
	.string "¡Buaaa! ¡Oh, {PLAYER}!\n"
	.string "Snif… Snif…\p"
	.string "¡Tengo un terrible dilema!\n"
	.string "No sé qué movimiento usar\l"
	.string "con mi {STR_VAR_1}…\p"
	.string "Porfa, porfa, {PLAYER}.\n"
	.string "¡Decide tú por mí!\p"
	.string "Para mi {STR_VAR_1}, qué movimiento\n"
	.string "sería mejor: ¿{STR_VAR_2}\l"
	.string "o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento, {PLAYER}!\n"
	.string "Me alegra tanto que hayas elegido tú el\l"
	.string "movimiento, que me he puesto a llorar…\p"
	.string "Snif…\n"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMove1::
	.string "¡Yupi! ¡Hola, {PLAYER}!\n"
	.string "¡Necesito otro consejo!\p"
	.string "Quiero enseñar a mi {STR_VAR_1}\n"
	.string "un movimiento alucinante.\p"
	.string "Me gustan {STR_VAR_2} y\n"
	.string "{STR_VAR_3}. ¿Cuál me recomiendas?$"

gText_ApprenticeMoveThanks1::
	.string "¿Mejor {STR_VAR_1}? ¡Supongo que sí!\n"
	.string "¡Vale, haré lo que dices!\p"
	.string "¡Ojalá nos volvamos a ver para que me\n"
	.string "enseñes algo más!$"

gText_ApprenticeWhichMove2::
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}, me preocupa\l"
	.string "qué movimiento debo enseñarle.\p"
	.string "Estoy dudando entre {STR_VAR_2}\n"
	.string "y {STR_VAR_3}.\p"
	.string "¿Cuál de ellos crees que haría más\n"
	.string "fuerte a mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "¿De verdad crees que {STR_VAR_1}?\n"
	.string "¡Muy bien, te haré caso!\p"
	.string "Voy a tratar de enseñarle {STR_VAR_1}\n"
	.string "a mi POKéMON ahora mismo.\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMove3::
	.string "Ooooh, {PLAYER}…\n"
	.string "¡Soy un caso, en serio!\p"
	.string "Ahora que me decido a entrenar un\n"
	.string "POKéMON, no puedo decidirme sobre\l"
	.string "qué movimiento debo enseñarle…\p"
	.string "Ya sé que esto no tiene ninguna\n"
	.string "importancia para ti, {PLAYER}.\p"
	.string "Pero sí la tiene para mí…\p"
	.string "{PLAYER}, ayúdame a elegir un movimiento\n"
	.string "para mi {STR_VAR_1}, ¿vale?\p"
	.string "Te doy a elegir entre {STR_VAR_2} y\n"
	.string "{STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "¡Comprendido!\p"
	.string "¿Pero tú crees que {STR_VAR_1}\n"
	.string "querrá aprenderlo…?\l"
	.string "¡Esperemos que sí!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Yo también tenía ganas\n"
	.string "de verte!\p"
	.string "Me preguntaba qué movimiento le iría\n"
	.string "bien a mi {STR_VAR_1}.\p"
	.string "No me decido, así que ¿puedes\n"
	.string "decidirlo tú por mí?\p"
	.string "Por ejemplo… ¿Qué tal los movimientos\n"
	.string "{STR_VAR_2} y {STR_VAR_3}? ¿Cuál\l"
	.string "sería mejor?$"

gText_ApprenticeMoveThanks4::
	.string "¿{STR_VAR_1}? ¡Maravilloso!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMove5::
	.string "¿Cómo puede haber tanto lío? ¡Eh, si\n"
	.string "es {PLAYER}{KUN}! ¿Qué tal?\p"
	.string "Desde que me he levantado esta\n"
	.string "mañana, ¡he ido a correr, he nadado y\l"
	.string "he cocinado!\p"
	.string "¡No te creerías lo ocupado que estoy!\p"
	.string "¡Ni siquiera puedo decidir qué\n"
	.string "movimiento debería aprender mi\l"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2} tiene buena pinta, ¿eh?\n"
	.string "Pero {STR_VAR_3} tampoco está mal.\p"
	.string "{PLAYER}{KUN}, ¡dame uno de tus buenos\n"
	.string "consejos! ¿Qué movimiento me iría\l"
	.string "bien?$"

gText_ApprenticeMoveThanks5::
	.string "¡Vale, comprendido!\n"
	.string "Tendré que hacer un hueco en mi\l"
	.string "agenda para enseñárselo.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeWhichMove6::
	.string "¡Oh! ¡Qué suerte!\n"
	.string "¡Nos volvemos a ver, {PLAYER}!\l"
	.string "Necesito tu coco otra vez.\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Para mi {STR_VAR_1}, ¿qué movimiento\n"
	.string "le vendría mejor aprender, \l"
	.string "{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "¡Aaah!\n"
	.string "¡{STR_VAR_1}, claro!\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hola, {PLAYER}.\n"
	.string "¿Te va todo superfantástico?\p"
	.string "Siento tener que pedirte ayuda\n"
	.string "una vez más, pero es sobre mi\l"
	.string "queridísimo {STR_VAR_1}.\p"
	.string "¿Qué movimiento haría a mi adorado\n"
	.string "{STR_VAR_1} más superalucinante?\l"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "¡{STR_VAR_1}!\n"
	.string "¡Voy a enseñárselo ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMove8::
	.string "¡Hooola, {PLAYER}! ¡Otra vez!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Siempre que estoy desesperada,\n"
	.string "aquí llega mi {PLAYER}!\p"
	.string "¡Hoy necesito que me recomiendes\n"
	.string "un movimiento!\p"
	.string "¡Anda, elige el que crees que le iría\n"
	.string "mejor a mi {STR_VAR_1}!\p"
	.string "¿Con cuál te quedas de estos dos?\n"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "¡Oh-oh-oh! ¡Gracias mil!\n"
	.string "¡{STR_VAR_1}!\l"
	.string "¡Recibido! ¡Cambio y corto!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeWhichMove9::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Espero poder contar hoy con otro\l"
	.string "de esos impagables consejos tuyos!\p"
	.string "¿Cuál sería el mejor movimiento\n"
	.string "para mi {STR_VAR_1}?\p"
	.string "¡Tendría que ser algo que me\n"
	.string "ayudase a ganar así, sin más!\p"
	.string "¿Qué tal {STR_VAR_2}?\n"
	.string "¿O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "¡Ajá, {STR_VAR_1}!\n"
	.string "¡Vale!\l"
	.string "¡Me voy corriendo a enseñárselo!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove10::
	.string "¡{PLAYER}{KUN}, esto es una locura!\p"
	.string "¡Mi POKéMON!\n"
	.string "¡Ya ha aprendido seis movimientos!\p"
	.string "¡Na! ¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Pero te diré algo en serio.\n"
	.string "Soy pésimo eligiendo movimientos para\l"
	.string "mis POKéMON.\p"
	.string "Estaba pensando que por qué no\n"
	.string "eliges tú por mí, ¿de acuerdo?\p"
	.string "{STR_VAR_2} o quizá {STR_VAR_3}.\n"
	.string "¿Cuál le iría mejor a mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Muy bien, has dicho {STR_VAR_1}.\n"
	.string "¡Entonces le enseñaré otro!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMove11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy poeta y además MARINERO,\n"
	.string "pero ENTRENAR es lo que quiero.\p"
	.string "¡Aconséjame sobre un movimiento\n"
	.string "y te expresaré mi agradecimiento!\p"
	.string "{STR_VAR_2}, {STR_VAR_3}… Dime,\n"
	.string "¿cuál hará a mi {STR_VAR_1} más sublime?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, ¿ése me aconsejas?\n"
	.string "¡Gracias! ¡Otra duda que me despejas!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMove12::
	.string "¡Oh, sí, si es {PLAYER}!\p"
	.string "¿Qué hago? ¿Pedirte consejo? ¿Por\n"
	.string "qué no? ¡Si ya estoy hablando contigo!\p"
	.string "{PLAYER}, ¿te sorprendo? ¡Quiero tu\n"
	.string "consejo, ya lo ves!\p"
	.string "¿Me recibes? ¡Me recibes!\p"
	.string "Mi {STR_VAR_1}… ¿qué debería usar? Es\n"
	.string "{STR_VAR_2} o {STR_VAR_3}, ¿cuál vas a\l"
	.string "elegir, dime ya?$"

gText_ApprenticeMoveThanks12::
	.string "Si ese {STR_VAR_1} es lo mejor, ¡haré lo\n"
	.string "que dices, por favor!\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, pero de mí no te debes olvidar.\p"
	.string "¡Hasta pronto, mi listo amigo!$"

gText_ApprenticeWhichMove13::
	.string "¡Achís! ¡Aaaaaachís! Oh, {PLAYER}{KUN}…\n"
	.string "He pillado este espantoso resfriado…\p"
	.string "Querría elegir un movimiento para mi\n"
	.string "POKéMON, pero ya ves cómo estoy…\p"
	.string "En fin, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, si yo tuviera que elegir entre\n"
	.string "{STR_VAR_2} y {STR_VAR_3} para mi\l"
	.string "{STR_VAR_1}, ¿cuál debería escoger?$"

gText_ApprenticeMoveThanks13::
	.string "Mm, {STR_VAR_1}, vale. ¡Aaaachís!\n"
	.string "¡Se lo enseñaré en cuanto me recupere!\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMove14::
	.string "Esto… Mm…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me frustra mucho eso…\l"
	.string "Es que… necesito otro consejo.\p"
	.string "Es que… me avergüenza reconocerlo,\n"
	.string "pero no sé qué movimiento debo enseñar\l"
	.string "a mi POKéMON.\p"
	.string "Es para mi {STR_VAR_1}.\n"
	.string "Entre {STR_VAR_2} y {STR_VAR_3},\l"
	.string "¿cuál piensas que debería elegir?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Lo intentaré con {STR_VAR_1}.\p"
	.string "Espero poder enseñárselo…\n"
	.string "No sé si podré con los nervios…\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMove15::
	.string "¿Mmm? Pareces {PLAYER}{KUN}… Pero ¿eres\n"
	.string "real de verdad?\p"
	.string "¿No serás uno de esos imitadores tan\n"
	.string "populares?\p"
	.string "No, no, si eres real, no pasa nada. ¡No\n"
	.string "hace falta que te enfades, te lo\l"
	.string "aseguro!\p"
	.string "Por cierto, me gustaría pedirte\n"
	.string "consejo.\p"
	.string "Es sobre mi {STR_VAR_1}.\p"
	.string "¿Qué movimiento le iría mejor,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "¿{STR_VAR_1}? ¿No hay duda?\p"
	.string "Ya veo. Si es así, me parece bien. Te\n"
	.string "agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso mi\n"
	.string "POKéMON pueda aprender.\p"
	.string "¡Volvamos a vernos!$"

gText_ApprenticePickWinSpeech0::
	.string "Ah… ¿{PLAYER}?\n"
	.string "¿Eres tú, {PLAYER}?\l"
	.string "¡Oh! Snif… Snif… Escúchame, por favor…\p"
	.string "Me… pongo tan nervioso en los combates\n"
	.string "que no puedo evitar llorar, aunque gane.\p"
	.string "En lugar de eso, me gustaría poder decir\n"
	.string "algo que quedara guay…\p"
	.string "¡Anda, por favor, {PLAYER}!\n"
	.string "¡Enséñame a decir algo guay\l"
	.string "para no llorar cuando gane!$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\n"
	.string "¡Suena totalmente guay!\p"
	.string "Oh… lo siento otra vez…\n"
	.string "Lloro de alegría…\p"
	.string "Snif… ¡{PLAYER}!\n"
	.string "¡Muchas gracias por todo!\p"
	.string "¡Combatiré lo mejor que pueda\n"
	.string "en tu honor, {PLAYER}!\p"
	.string "{PLAYER}…, la próxima vez…,\n"
	.string "¡debemos combatir tú y yo!$"

gText_ApprenticePickWinSpeech1::
	.string "¡Bien! ¡Es {PLAYER}! ¡Hola! ¡Quería\n"
	.string "preguntarte algo!\p"
	.string "Quiero decir algo guay cuando gane un\n"
	.string "combate.\p"
	.string "¿Tienes alguna frase guay que puedas\n"
	.string "recomendarme?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "¡Eh! ¡Eso suena guay!\n"
	.string "¡Genial! ¡Voy a decir eso!\p"
	.string "¡Gracias por todas tus enseñanzas!\n"
	.string "A partir de ahora voy a combatir\l"
	.string "lo mejor que pueda, ¡ya verás!\p"
	.string "¡La próxima vez que nos veamos,\n"
	.string "será para enfrentarnos el uno al otro!$"

gText_ApprenticePickWinSpeech2::
	.string "¡Hola, {PLAYER}!\p"
	.string "Mis POKéMON y yo estamos listos para\n"
	.string "todo, menos para una cosa.\p"
	.string "Creo que estaría bien tener algo que\n"
	.string "gritar cuando gane.\p"
	.string "¿Se te ocurre algo bueno que decir?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "¡Estupendo!\n"
	.string "¡Voy a gritar eso cada vez que ganemos!\p"
	.string "Ahora voy a ponerme a combatir por\n"
	.string "todos los sitios.\p"
	.string "Quién sabe, quizás llegue a enfrentarme\n"
	.string "a ti algún día, {PLAYER}.\p"
	.string "¡Ojalá la próxima vez nos veamos\n"
	.string "en un escenario de combate!$"

gText_ApprenticePickWinSpeech3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte otra vez, de verdad,\l"
	.string "pero es que no debo de valer para nada…\p"
	.string "Ni siquiera cuando gano se me ocurre\n"
	.string "nada especial que decir…\p"
	.string "Sí, ya sé que eso te tiene sin cuidado,\n"
	.string "{PLAYER}.\p"
	.string "Pero para mí es muy importante…\p"
	.string "Porfa, {PLAYER}, dime algo especial que\n"
	.string "pueda decir yo cuando gane un combate.$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Es inspirador…\p"
	.string "Eh… ¿Está bien que alguien como yo\n"
	.string "diga algo así?\p"
	.string "¡No! ¡Daré lo mejor de mí!\p"
	.string "{PLAYER}, muchísimas gracias por\n"
	.string "aguantarme tanto tiempo…\p"
	.string "Te prometo que a partir de ahora daré\n"
	.string "lo mejor de mí.\p"
	.string "Seguro que te olvidarás enseguida de\n"
	.string "alguien como yo, pero ¡volvamos a\l"
	.string "vernos en algún sitio!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que me gustaría decirte.\p"
	.string "Ya sé que no siempre sueno muy\n"
	.string "agradable y educada…\p"
	.string "Pero cuando gano un combate, creo\n"
	.string "que todos piensan que soy arrogante.\p"
	.string "No quiero que la gente me odie,\n"
	.string "así que querría decirles algo bonito\l"
	.string "a los que pierden contra mí.\p"
	.string "¡Lo peor es que no se me ocurre nada!\n"
	.string "Anda, ayúdame, ¿qué les digo?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "¡No está mal!\n"
	.string "¡Perfecto, con eso bastará!\p"
	.string "Voy a echarme a la aventura a ver\n"
	.string "qué tal se me da con todo lo que\l"
	.string "me has enseñado.\p"
	.string "¡Y siento mucho todas las veces\n"
	.string "que he sido tan borde!\p"
	.string "La próxima vez, luchamos, ¿vale?\n"
	.string "¡Nos vemos!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, justo estaba buscándote, {PLAYER}{KUN}.\n"
	.string "¡No te imaginas lo liado que estoy!\p"
	.string "Tú supongo que como siempre, ¿no?\n"
	.string "Es que yo no paro, oye.\p"
	.string "Que si correr, combatir, dibujar planos,\n"
	.string "hacer planes. ¿Por qué seré siempre yo?\p"
	.string "Pero ni siquiera lo ocupado que estoy\n"
	.string "es excusa para largarme sin decir nada\l"
	.string "después de ganar un combate.\p"
	.string "Dime, {PLAYER}{KUN}, ¿qué crees que debería\n"
	.string "decir nada más ganar para que quedase\l"
	.string "guay y resaltase el carisma que tengo?$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Vale, lo he entendido.\n"
	.string "¡Creo que tendré tiempo de decir eso!\p"
	.string "Eh, he tenido mucha suerte contigo.\n"
	.string "Ningún aprendiz tuvo mejor ejemplo.\p"
	.string "Debo sacar tiempo de debajo de las\n"
	.string "piedras y ponerme a combatir en serio.\p"
	.string "¡Gracias por todo, {PLAYER}{KUN}!\n"
	.string "¡Tenemos que luchar, tú y yo, un día!$"

gText_ApprenticePickWinSpeech6::
	.string "¡Qué suertuda que soy!\n"
	.string "¡{PLAYER}! ¡Cómo me alegro de verte!\l"
	.string "¡Como siempre, necesito tu ayuda!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Si gano un combate y quiero ponerle\n"
	.string "la guinda diciendo algo que quede guay,\l"
	.string "¿qué debo decir?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "¡Es… es fabuloso! ¡Es digno y guay! ¡Me\n"
	.string "lo quedo!\p"
	.string "… Oye, creo que se me está dando\n"
	.string "bastante bien esto, ¿eh?\p"
	.string "Así que estoy pensando en desafiar a\n"
	.string "otros ENTRENADORES a partir de ahora.\p"
	.string "{PLAYER}, tus consejos me han ayudado\n"
	.string "muchísimo.\p"
	.string "¡Quizá algún día nos toque luchar!\p"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}. ¡Encantadísima que estoy\n"
	.string "de volver a verte!\p"
	.string "¿Sabes? Ya no me preocupan\n"
	.string "en absoluto mis POKéMON.\p"
	.string "Ahora lo que me preocupa soy yo…\p"
	.string "Sabes que los ENTRENADORES dicen\n"
	.string "unas palabras cuando ganan, ¿verdad?\p"
	.string "Pues eso es lo que yo quiero: saber\n"
	.string "qué podría decir para quedar chuli.\p"
	.string "¿Qué piensas tú? ¿Qué debería\n"
	.string "decir cuando gane un combate?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "¡Ah! ¡Esa frase! ¡Me refresca y me hace\n"
	.string "sentir como nuevo!\p"
	.string "¡Tengo que usarla ahora mismo!\p"
	.string "Y ahora debo despedirme, {PLAYER}…\p"
	.string "Saldré a luchar contra muchos otros,\n"
	.string "pero nunca olvidaré tus enseñanzas.\p"
	.string "Quizás algún día… ¡Adiós!$"

gText_ApprenticePickWinSpeech8::
	.string "¡Eh, hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh! ¡Ya sé! ¡Ya sé!\n"
	.string "¡Déjame preguntarte algo!\p"
	.string "Hace poco, gané un combate.\n"
	.string "¡No te puedes ni imaginar la alegría…!\p"
	.string "¡Pero estaba tan alucinada\n"
	.string "que no pude decir ni pío!\p"
	.string "No quiero que me vuelva a pasar.\n"
	.string "¡Anda, {PLAYER}, dime qué crees que\l"
	.string "debería decir la próxima vez que gane!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "¡Buaaaaa!\n"
	.string "¡¿Quieres que diga eso?!\l"
	.string "Qué… ¡Qué alucinante!\p"
	.string "¡Gra-gra-gracias!\n"
	.string "¡Qué suerte he tenido contigo!\p"
	.string "Ahora voy a viajar por ahí para\n"
	.string "combatir con todo tipo de gente.\p"
	.string "Todo te lo debo a ti, {PLAYER}.\n"
	.string "¡En serio, de verdad, gracias!\p"
	.string "Ahora tengo que irme, pero ojalá\n"
	.string "nos veamos otra vez, ¡combatiendo!$"

gText_ApprenticePickWinSpeech9::
	.string "¡Hola, bueno! ¡{PLAYER}{KUN}!\p"
	.string "¿Sabes? Me están entrando ganas de ir\n"
	.string "por ahí a luchar donde pueda.\p"
	.string "Pero antes, ¡quiero tu consejo una vez\n"
	.string "más, por favor!\p"
	.string "Si ganara un combate, ¿qué\n"
	.string "fanfarronada podría decirle al\l"
	.string "ENTRENADOR derrotado?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "¡Ah, vale, perfecto!\n"
	.string "¡Entonces será eso lo que diga!\p"
	.string "¡Y llegó el momento de despedirse!\n"
	.string "¡Gracias por toda tu ayuda!\p"
	.string "Enfrentémonos algún día, ¿vale?\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech10::
	.string "¡{PLAYER}{KUN}, tengo un problema!\p"
	.string "¡Cada vez que gano un combate, me paso\n"
	.string "la hora siguiente presumiendo de ello!\p"
	.string "¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Y ahora, en serio.\n"
	.string "Lo mío no es el idioma.\p"
	.string "Así que, ¿por qué no decides tú por mí\n"
	.string "lo que debo decir al ganar un combate?\l"
	.string "Venga, ¿qué crees que quedaría bien?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Eso es lo que debería decir, ¿eh?\n"
	.string "¡Pues entonces no lo diré!\p"
	.string "¡Es broma! ¡Obedeceré tus enseñanzas,\n"
	.string "maestro!\p"
	.string "¡Gracias por enseñarme todo este\n"
	.string "tiempo, maestro!\p"
	.string "Por fin empiezo a entender lo que\n"
	.string "significa ser ENTRENADOR.\p"
	.string "Voy a salir a ganar combates contra\n"
	.string "cualquier ENTRENADOR.\p"
	.string "¡Quizá algún día seas tú, maestro!\p"
	.string "¡Eso es todo! ¡Adiós, maestro!$"

gText_ApprenticePickWinSpeech11::
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy el poeta MARINERO.\n"
	.string "¡Una última pregunta,\l"
	.string "antes de decirte “hasta luego”!\p"
	.string "Aconséjame sobre qué decir,\n"
	.string "que no me acabo de decidir.\p"
	.string "Cuando gane un combate a un rival,\n"
	.string "¿qué puedo decir que suene cabal?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "¡Perfecto! ¡Suena bien! ¡Te haré caso!\n"
	.string "¡Será lo que diga cuando llegue el caso!\p"
	.string "Y ahora, como siempre ocurre en la vida,\n"
	.string "¡llegó la hora de la amarga despedida!\p"
	.string "Gracias otra vez por tus consejos,\n"
	.string "¡siento que con ellos llegaré muy lejos!\p"
	.string "¡Adiós! “¡Goodbye!” “¡Au revoir!”\n"
	.string "¡Ojalá nos volvamos a encontrar!$"

gText_ApprenticePickWinSpeech12::
	.string "¡Oh, sí, {PLAYER}! ¡Hoy te he vuelto a\n"
	.string "encontrar!\p"
	.string "¿Qué hago? ¿Preguntarte otra vez?\n"
	.string "¿Por qué no? ¡Si ya te estoy\l"
	.string "preguntando!\p"
	.string "En fin, {PLAYER}… ¿Me recibes? ¡Me\n"
	.string "recibes! ¡Necesito más consejos para\l"
	.string "mí!\p"
	.string "Es sobre qué debería gritar. Algo guay\n"
	.string "que soltar cuando un combate acabe\l"
	.string "bien, ya verás.\p"
	.string "¡Venga, quiero oírtelo decir!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "¡Muy bien, muy bien! ¡Usaré eso porque\n"
	.string "está genial!\p"
	.string "Ya no me quedan preguntas que hacer.\n"
	.string "Solo me queda decir adiós con la mano,\l"
	.string "ya lo ves.\p"
	.string "Pero quizá algún día nos veamos, y uno\n"
	.string "de los dos caerá, ya verás.\p"
	.string "Pero de verdad que es hora de decir\n"
	.string "adiós.\p"
	.string "Bueno, {PLAYER}, tengo que irme a\n"
	.string "vagar, ¡pero de mí no te debes olvidar!\p"
	.string "¡Cuídate, {PLAYER}! ¡Te quiero!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, estoy hecho polvo…\n"
	.string "No dejo de moquear…\p"
	.string "Resulta que estaba pensando en algo\n"
	.string "guay que decir tras ganar un combate.\p"
	.string "Me gustaban tanto las ideas, que me\n"
	.string "puse a llorar de la emoción y mira,\l"
	.string "empecé a moquear y ahora no paro…\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú, {PLAYER}{KUN}.\p"
	.string "Cuando gane un combate,\n"
	.string "¿qué debería decir?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … … Está bien. ¡No, es impresionante!\n"
	.string "¡Me hace saltar las lágrimas otra vez!\p"
	.string "¡Pero, a pesar de las lágrimas y los\n"
	.string "mocos, usaré esa frase!\p"
	.string "Ya no me quedan preguntas que\n"
	.string "hacerte, {PLAYER}{KUN}.\p"
	.string "¡A partir de ahora, somos rivales!\n"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech14::
	.string "Esto… Mm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me estás poniendo nervioso.\p"
	.string "Esto… quería pedirte un consejo.\n"
	.string "Pero te prometo que será el último…\p"
	.string "Me da no sé qué preguntarlo, pero,\n"
	.string "si alguna vez ganase un combate,\l"
	.string "¿qué crees que debería decir al final?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… ¡Perfecto!\n"
	.string "¡Trataré de decirlo!\l"
	.string "Aunque, con los nervios, no sé si podré…\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Ahora tengo que decirte adiós.\p"
	.string "Tendré presentes todos tus consejos,\n"
	.string "{PLAYER}{KUN}, y lo haré lo mejor que pueda.$"

gText_ApprenticePickWinSpeech15::
	.string "¿Mmm? Pareces {PLAYER}{KUN}… Pero ¿lo eres\n"
	.string "de verdad? ¿No serás un MUÑECO de\l"
	.string "{PLAYER} muy logrado?\p"
	.string "Ay, no, no, no, ¡no te preocupes! Si de\n"
	.string "verdad eres real, olvida mi grosería,\l"
	.string "por favor.\p"
	.string "No hace falta que te enfades tanto.\n"
	.string "Solo deseo más de tus buenos\l"
	.string "consejos.\p"
	.string "Es sobre una frase.\p"
	.string "Más concretamente, ¿qué debería\n"
	.string "decir si gano un combate?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… \n"
	.string "Así que cuando gane debo decir…\p"
	.string "{STR_VAR_1}\p"
	.string "¿Estás hablando en serio?\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Espero saber decirlo con la misma\n"
	.string "sabiduría que tú.\p"
	.string "Bueno, parece ser que no me queda\n"
	.string "nada más que inquirirte.\p"
	.string "Creo que ha llegado la hora de decirnos\n"
	.string "adiós y desearnos suerte. \p"
	.string "¡Gracias, pues, y suerte!\n"
	.string "¡Y disculpa una vez más mi escepticismo!$"
