
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Te damos la bienvenida a la TIENDA\n"
	.string "de BATALLA de PUEBLO PARDAL!\p"
	.string "¡Yo soy el guía del TORNEO con JUEZ!$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Te damos la bienvenida a la TIENDA\n"
	.string "de BATALLA de PUEBLO PARDAL!\p"
	.string "¡Yo soy el guía del TORNEO con JUEZ!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "¿Te atreves a participar\n"
	.string "en un TORNEO con JUEZ?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Esperamos que vuelvas\n"
	.string "pronto por aquí.$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "En la TIENDA de BATALLA ARENA,\n"
	.string "se disputan TORNEOS con JUEZ.\p"
	.string "Cada ENTRENADOR participa\n"
	.string "con un equipo de tres POKéMON.\p"
	.string "Primero, debes elegir los tres POKéMON\n"
	.string "en el orden en que deseas que combatan.\p"
	.string "Durante el combate, los POKéMON\n"
	.string "aparecerán uno a uno en ese orden.\p"
	.string "Una vez entre un POKéMON en combate,\n"
	.string "deberá seguir hasta que concluya.\p"
	.string "Pero si no hay ganador al cabo\n"
	.string "de tres turnos, decidirá el JUEZ.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, no podrás\n"
	.string "continuar con tu desafío.\p"
	.string "Si logras derrotar a tres\n"
	.string "ENTRENADORES seguidos,\l"
	.string "te daremos un buen premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Te mostraré la TIENDA de BATALLA,\n"
	.string "pero antes guardaré la partida, ¿eh?…$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Ofrecemos dos niveles de desafío:\n"
	.string "nivel 50 y nivel libre. ¿Cuál eliges?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Selecciona los tres POKéMON\n"
	.string "con los que quieres combatir.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Qué lástima…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Cuando los consigas, deben sostener\n"
	.string "distintos tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Qué lástima…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres POKéMON diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ahora te guiaré hasta\n"
	.string "la TIENDA de BATALLA.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Lástima…\p"
	.string "No guardaste la partida antes\n"
	.string "de abandonar el desafío, ¿verdad?…\p"
	.string "Eso implica la descalificación…\p"
	.string "No obstante, puedes volver\n"
	.string "a participar cuando quieras.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "¡Espléndido! ¡Has vencido a tres\n"
	.string "ENTRENADORES consecutivos!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Espera un segundo mientras\n"
	.string "guardo la partida.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Toma este premio para conmemorar\n"
	.string "tu racha de 3 victorias consecutivas.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "¡Pero bueno!\n"
	.string "Tienes la MOCHILA repleta.\p"
	.string "Será mejor que la vacíes un poco\n"
	.string "si quieres llevarte el premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "¡Muchas gracias por participar!\p"
	.string "Espera un segundo mientras\n"
	.string "guardo la partida.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Esperamos que vuelvas\n"
	.string "pronto por aquí.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Ya tenía ganas de volver a verte.\p"
	.string "Antes de conducirte a la TIENDA\n"
	.string "de BATALLA, debo guardar la partida.\l"
	.string "Espera un momento…$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Ésta es la TIENDA de BATALLA\n"
	.string "de VERDEGAL!\p"
	.string "Aquí ponemos a prueba la confianza\n"
	.string "de los ENTRENADORES en sus POKéMON.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Ésta es la TIENDA de BATALLA\n"
	.string "de VERDEGAL!\p"
	.string "Aquí ponemos a prueba la confianza\n"
	.string "de los ENTRENADORES en sus POKéMON.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "¿Deseas afrontar el desafío de\n"
	.string "la TIENDA de BATALLA PALACIO?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "En la TIENDA de BATALLA PALACIO,\n"
	.string "hay una regla fundamental que\l"
	.string "debe respetarse.\p"
	.string "Los ENTRENADORES solo pueden cambiar\n"
	.string "a sus POKéMON.\p"
	.string "Por lo demás, tienen prohibido\n"
	.string "dar órdenes a sus POKéMON.\p"
	.string "Los POKéMON se comportarán según\n"
	.string "su naturaleza y combatirán por su cuenta.\p"
	.string "Debes confiar en tus POKéMON\n"
	.string "y vigilarlos.\p"
	.string "Si logras el honor de derrotar a\n"
	.string "tres ENTRENADORES seguidos,\l"
	.string "te daremos un premio.\p"
	.string "Si quieres interrumpir el\n"
	.string "desafío, guarda la partida.\p"
	.string "Si no guardas antes de interrumpir,\n"
	.string "quedarás descalificado.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Vuelve cuando tu corazón y el de tus\n"
	.string "POKéMON latan como uno solo.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hay dos niveles de dificultad: nivel 50\n"
	.string "y nivel libre. ¿Qué desafío eliges?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Qué desgracia…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres POKéMON diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Qué desgracia…\p"
	.string "No tienes tres POKéMON que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres POKéMON diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los HUEVOS{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Selecciona los tres POKéMON\n"
	.string "con los que quieres combatir.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de conducirte a la TIENDA\n"
	.string "de BATALLA, debes guardar la partida.\l"
	.string "¿Estás de acuerdo?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Ahora, sígueme.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Me siento privilegiado por poder haber\n"
	.string "visto combatir a tus POKéMON.\p"
	.string "Voy a guardar tu resultado.\n"
	.string "Sólo será un segundo, por favor.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "A juzgar por tus tres victorias\n"
	.string "consecutivas…\p"
	.string "El vínculo que une tu corazón al de tus \n"
	.string "POKéMON debe de ser firme y fuerte.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Voy a guardar tu récord.\n"
	.string "Espera unos instantes.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Tus tres victorias consecutivas se\n"
	.string "merecen qué menos que este premio.$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Ésta es la TIENDA de BATALLA\n"
	.string "de CIUDAD PORTUAL!\p"
	.string "Aquí se celebran los famosos \n"
	.string "TORNEOS de COMBATES con TRUEQUE.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Ésta es la TIENDA de BATALLA\n"
	.string "de CIUDAD PORTUAL!\p"
	.string "Aquí se celebran los famosos \n"
	.string "TORNEOS de COMBATES con TRUEQUE.$"
#endif


SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "¿Deseas afrontar el desafío de un\n"
	.string "TORNEO de COMBATES con TRUEQUE?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Aquí, en la TIENDA de BATALLA FÁBRICA,\n"
	.string "celebramos eventos de Combate Intercambio\l"
	.string "con POKéMON de alquiler.\p"
	.string "Primero, se te prestarán tres\n"
	.string "POKéMON específicamente para este evento.\p"
	.string "Con los POKéMON de alquiler,\n"
	.string "debes disputar un COMBATE INDIVIDUAL.\p"
	.string "Si ganas, puedes intercambiar\n"
	.string "uno de tus POKéMON de alquiler.\p"
	.string "Repite este ciclo de combate e\n"
	.string "intercambio: si ganas tres veces\l"
	.string "seguidas, obtendrás un buen premio.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "guarda la partida.\p"
	.string "Si no guardas antes de interrumpir,\n"
	.string "quedarás descalificado.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperamos que vuelvas a visitarnos.\p"
	.string "$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "¿Qué nivel quieres desafiar? ¿Nivel 50\n"
	.string "o nivel 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de afrontar tu desafío,\n"
	.string "debo guardar la partida, ¿de acuerdo?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Muy bien. Guardaré tus POKéMON\n"
	.string "mientras participas.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Por aquí, por favor.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "¡Gracias por participar!\p"
	.string "Voy a devolverte tus POKéMON\n"
	.string "a cambio de los que te prestamos.\p"
	.string "Y voy a guardar también tus resultados.\n"
	.string "Un momento, por favor.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Te devolveré tus POKéMON a cambio de\n"
	.string "nuestros POKéMON de alquiler.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "¡Enhorabuena!\n"
	.string "¡Tres victorias seguidas!\p"
	.string "Voy a devolverte tus POKéMON\n"
	.string "a cambio de los que te prestamos.\p"
	.string "Y voy a guardar también tus resultados.\n"
	.string "Un momento, por favor.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Como premio por las tres victorias\n"
	.string "seguidas, toma esto. Para ti.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "¿Eh?\n"
	.string "Se diría que no tienes sitio para esto.\p"
	.string "Haz un hueco en la MOCHILA\n"
	.string "y vuelve por aquí.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "¡Te estábamos esperando!\p"
	.string "Antes de continuar el desafío,\n"
	.string "debo guardar la partida.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Siento decírtelo, pero no guardaste\n"
	.string "la partida la última vez que jugaste.\p"
	.string "Así que se te ha descalificado.\n"
	.string "Lo siento.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Te devolvemos tus POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha recibido como premio\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Aquí están las reglas del Intercambio\n"
	.string "de Combate.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué apartado quieres leer?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En los enfrentamientos de COMBATE\n"
	.string "con TRUEQUE, sólo se usan tres POKéMON.\p"
	.string "Al tomar prestados o trocar POKéMON,\n"
	.string "hay que tener en cuenta que el equipo\l"
	.string "no debe tener dos POKéMON iguales.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Sólo puedes cambiarle un POKéMON\n"
	.string "al ENTRENADOR al que acabas de vencer.\p"
	.string "Y sólo puedes elegir entre los POKéMON\n"
	.string "que haya usado ese ENTRENADOR.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Después de cada victoria, podrás\n"
	.string "cambiar uno de tus POKéMON por\l"
	.string "uno de los del ENTRENADOR derrotado.\p"
	.string "Con el tercer ENTRENADOR\n"
	.string "no podrás hacer trueque de POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "A la hora de trocar POKéMON, debes\n"
	.string "tener en cuenta dos cosas.\p"
	.string "Primera: en el momento del trueque,\n"
	.string "no podrás ver las características\l"
	.string "del POKéMON que vas a recibir.\p"
	.string "Segunda: los POKéMON de tu equipo\n"
	.string "se mostrarán siguiendo el orden\l"
	.string "en el que los elegiste.\p"
	.string "Ese orden no se altera aunque\n"
	.string "luego realices trueques.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Todos los POKéMON de la TIENDA de\n"
	.string "BATALLA de CIUDAD PORTUAL se alquilan.\p"
	.string "Todos los POKéMON que se alquilan\n"
	.string "se encuentran en el nivel 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Aquí están las reglas de la TIENDA\n"
	.string "BATALLA de PUEBLO VERDEGAL.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué apartado quieres leer?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Aquí, en la TIENDA BATALLA de PUEBLO\n"
	.string "VERDEGAL, los POKéMON deben pensar y\l"
	.string "luchar por sí mismos.\p"
	.string "A diferencia de los salvajes, los\n"
	.string "POKéMON que viven con personas se\l"
	.string "comportan de forma distinta según su\l"
	.string "naturaleza.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Según su naturaleza, un POKéMON\n"
	.string "puede preferir atacar pase lo que\l"
	.string "pase.\p"
	.string "Otro POKéMON puede preferir\n"
	.string "protegerse de cualquier daño.\p"
	.string "Y otro puede disfrutar molestando o\n"
	.string "confundiendo a sus rivales.\p"
	.string "Según su naturaleza, un POKéMON\n"
	.string "tendrá movimientos favoritos que se\l"
	.string "le dan bien.\p"
	.string "También puede que no le gusten\n"
	.string "ciertos movimientos que le cuesta\l"
	.string "usar.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hay movimientos ofensivos que causan\n"
	.string "daño directo al rival.\p"
	.string "Hay movimientos defensivos que\n"
	.string "sirven para prepararse ante los\l"
	.string "ataques enemigos o para recuperar PS,\l"
	.string "etc.\p"
	.string "Y también hay otros movimientos algo\n"
	.string "raros que pueden debilitar a los\l"
	.string "rivales con problemas de estado, como\l"
	.string "el envenenamiento y la parálisis.\p"
	.string "Los POKéMON se plantearán usar\n"
	.string "movimientos de estas tres\l"
	.string "categorías.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Si su ENTRENADOR no le da órdenes, un\n"
	.string "POKéMON puede no ser capaz de usar\l"
	.string "bien ciertos movimientos.\p"
	.string "A un POKéMON no se le da bien usar los\n"
	.string "movimientos que no le gustan.\p"
	.string "Si un POKéMON solo sabe movimientos\n"
	.string "que no encajan con su naturaleza, a\l"
	.string "menudo no podrá rendir al máximo.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Según su naturaleza, un POKéMON\n"
	.string "puede empezar a usar movimientos que\l"
	.string "no encajan con ella cuando está en\l"
	.string "apuros.\p"
	.string "Si un POKéMON empieza a comportarse\n"
	.string "de forma rara en un aprieto, obsérvalo\l"
	.string "con atención.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En esta TIENDA de BATALLA, los niveles\n"
	.string "de tus rivales se ajustarán para\l"
	.string "igualarse a los de tus POKéMON.\p"
	.string "Con todo, ningún ENTRENADOR\n"
	.string "al que te enfrentes tendrá POKéMON\l"
	.string "por debajo del nivel 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Son las reglas de la TIENDA de BATALLA\n"
	.string "de VERDEGAL.$"

BattleTentLobby_Text_EarnedBattlePoints:
	.string "¡Has ganado {STR_VAR_1} Puntos de\n"
	.string "Batalla!$"

