gText_Birch_Welcome::
	.string "¡Hola! ¡Perdona por hacerte esperar!\p"
	.string "¡Bienvenido al mundo de los POKéMON!\p"
	.string "Me llamo ABEDUL.\p"
	.string "Pero todos me llaman el PROFESOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Esto es lo que llamamos un “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "El mundo está habitado por\n"
	.string "criaturas llamadas POKéMON.\p"
	.string "Los humanos y los POKéMON vivimos\n"
	.string "juntos. A veces nos lo pasamos bien\l"
	.string "y nos ayudamos unos a otros.\p"
	.string "A veces nos unimos y combatimos\n"
	.string "contra equipos como el nuestro.\p"
	.string "Pero, a pesar de estos vínculos,\n"
	.string "ignoramos mucho sobre los POKéMON.\p"
	.string "De hecho, hay multitud de secretos\n"
	.string "que rodean a los POKéMON.\p"
	.string "En mi afán por descubrirlos, he\n"
	.string "dedicado mi vida a la investigación.\l"
	.string "Eso es lo que hago.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿Tú quién eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gText_Birch_WhatsYourName::
	.string "Muy bien.\n"
	.string "¿Y cómo te llamas?$"

gText_Birch_SoItsPlayer::
	.string "Así que eres {PLAYER}{KUN}…$"

gText_Birch_YourePlayer::
	.string "¡Ah, vale!\p"
	.string "Eres {PLAYER}{KUN}, que se muda a mi\n"
	.string "pueblo, VILLA RAÍZ.\l"
	.string "¡Ya lo entiendo!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Muy bien, ¿preparado?\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "¡Ármate de valor y salta al mundo de\n"
	.string "los POKéMON, donde te esperan\l"
	.string "sueños, aventuras y amistades!\p"
	.string "Bueno, te espero más tarde.\n"
	.string "Pásate por mi LABORATORIO POKéMON.\p"
	.string "$"
