BerryBlender_Text_BlendWithTheBlendMaster:
	.string "LICUÓLOGO: ¡Que sí, que sí!\n"
	.string "¡Que yo soy el LICUÓLOGO! ¿Quién si no?\p"
	.string "¡Quédate conmigo y aprenderás\n"
	.string "a sacarle el jugo a las cosas!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MASTER: Hmmm! So, you wish to\n"
	.string "see my mastery in action?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "So, you are too busy now, I see!\p"
	.string "But fear not!\n"
	.string "I shall be here all day!\l"
	.string "Hurry back from your errand!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "You haven't got a single BERRY!\p"
	.string "I shall be here all day!\n"
	.string "Hurry back with some BERRIES!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Of course!\n"
	.string "Of course!\p"
	.string "Incidentally…\n"
	.string "You do know how to blend {POKEBLOCK}S\l"
	.string "from BERRIES?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, but it is a simple process!\p"
	.string "When the BLENDER's arrow comes to\n"
	.string "your marker, just press the A Button.\p"
	.string "That's all you have to do.\p"
	.string "When you see how precisely I press\n"
	.string "the A Button, you will understand.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Fine!\p"
	.string "Let's get started, then!\p"
	.string "All together with the BLEND MASTER,\n"
	.string "let's BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "You don't appear to have gotten\n"
	.string "the {POKEBLOCK} CASE!\p"
	.string "I shall be here all day!\n"
	.string "Obtain the {POKEBLOCK} CASE and hurry back!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Your {POKEBLOCK} CASE appears to be full!\p"
	.string "I shall be here all day!\n"
	.string "Use some {POKEBLOCK}S and hurry back!$"

BerryBlender_Text_WhoaAwesome:
	.string "¡Eh!\n"
	.string "¡Fenomenal!$"

BerryBlender_Text_WickedlyFast:
	.string "¡Espectacular!$"

BerryBlender_Text_WhatAnExpert:
	.string "¡Estoy francamente impresionado!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Me encanta licuar con el LICUÓLOGO,\n"
	.string "¡hacemos {POKEBLOCK}S alucinantes!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Esa concentración…\n"
	.string "Esos ojos fijos en la flecha…\p"
	.string "Esa rapidez para pulsar el Botón A…\n"
	.string "Esa increíble precisión…\p"
	.string "Ese LICUÓLOGO es realmente único.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Dicen que el LICUÓLOGO se pasa la vida\n"
	.string "practicando su técnica en la montaña.\p"
	.string "Pero a veces se acerca a CALAGUA y\n"
	.string "se queda el día entero licuando BAYAS.$"
