CableClub_Text_WelcomeWhichCableClubService:
	.string "Hola.\n"
	.string "Éste es el CLUB del CABLE POKéMON.\p"
	.string "¿Qué te apetece hacer?$"

CableClub_Text_WhichService:
	.string "¿Qué servicio quieres usar?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercambiar PKMN con otro jugador\n"
	.string "usando el cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Usando el cable Game Link de GBA,\n"
	.string "podrás luchar contra alguien.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Usa un cable Game Link de GBA para\n"
	.string "jugar en el CENTRO de RÉCORDS.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Cerrar este menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Para un combate doble debes tener al\n"
	.string "menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Para realizar el intercambio debes\n"
	.string "llevar al menos dos POKéMON contigo.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "No puedes intercambiar el POKéMON\n"
	.string "que tiene la BAYA {STR_VAR_1}.$"

gText_PleaseWaitForLink::
	.string "Por favor, espera. Botón B: cancelar$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Cuando todos estén listos…\n"
	.string "Botón A: confirmar   Botón B: cancelar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Comenzar conexión con {STR_VAR_1} jugadores…\n"
	.string "Botón A: confirmar   Botón B: cancelar$"

gText_AwaitingLinkup::
	.string "Esperando conexión…\n"
	.string "(…) Botón B: cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Hay que guardar la partida antes de\n"
	.string "conectarse. ¿Quieres guardar?$"

CableClub_Text_PleaseEnter:
	.string "Adelante.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Te voy a llevar a tu sala.$"

Text_SomeoneIsNotReadyToLink:
	.string "Uno de los jugadores no está listo\n"
	.string "para realizar la conexión.\p"
	.string "Vuelve cuando todos estéis listos.$"

Text_LinkErrorPleaseReset:
	.string "Error de conexión…\n"
	.string "Comprueba el cable Game Link, reinicia\l"
	.string "la consola e inténtalo de nuevo.$"

Text_PlayersMadeDifferentSelections:
	.string "Los demás jugadores parecen haber\n"
	.string "seleccionado opciones diferentes.$"

CableClub_Text_PleaseVisitAgain:
	.string "Por favor, vuelve pronto.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El número de jugadores no es correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "No se puede jugar al modo de combate\n"
	.string "INDIVIDUAL con {STR_VAR_1} jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "No se puede jugar al modo de combate\n"
	.string "DOBLE con {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers:
	.string "Se necesitan cuatro jugadores\n"
	.string "para jugar a este modo de combate.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Confirma el número de jugadores\n"
	.string "y vuelve a empezar.$"

Text_TerminateLinkConfirmation:
	.string "Si sales de la sala, se pondrá fin\n"
	.string "a la conexión. ¿Estás de acuerdo?$"

Text_TerminateLinkPleaseWait:
	.string "Finalizando conexión… Te acompañamos\n"
	.string "fuera de la sala. Espera un momento.$"

CableClub_Text_TooBusyToNotice:
	.string "Este ENTRENADOR no te hace ni caso…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "¡Bingo! ¡Puedes mirar la FICHA\n"
	.string "de ENTRENADOR de {STR_VAR_1}!\l"
	.string "¡Es de color {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Ocupa tu sitio y empieza el combate.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Puedes comenzar el intercambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Se van a sobrescribir los datos\n"
	.string "de la FICHA de ENTRENADOR.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "¡Vuelve cuando quieras!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Lo siento mucho.\p"
	.string "Aún no podemos realizar intercambios\n"
	.string "con ENTRENADORES de otra región…$"

CableClub_Text_OtherTrainerNotReady:
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tienes al menos un POKéMON que no se\n"
	.string "puede seleccionar.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Siéntate y espera, por favor.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "¡{STR_VAR_1} envió {STR_VAR_2}!$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Hay un error de conexión.\p"
	.string "No puedes mezclar récords con las\n"
	.string "versiones japonesas de POKéMON\l"
	.string "Rubí y Zafiro.\p"
	.string "Tampoco puedes mezclar a la vez\n"
	.string "récords con la versión japonesa\l"
	.string "de POKéMON Esmeralda y cualquier\l"
	.string "versión de Rubí y Zafiro.$"

CableClub_Text_AdapterNotConnected:
	.string "El Conector inalámbrico de GBA\n"
	.string "no está bien conectado.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Los participantes deben pasar\n"
	.string "por el mostrador de recepción.$"

@ Unused
CableClub_Text_Hello:
	.string "¡Hola!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Espera un momento, por favor.$"

CableClub_Text_YouMayTradeHere::
	.string "Aquí puedes intercambiar POKéMON\n"
	.string "con un amigo.$"

CableClub_Text_YouMayBattleHere::
	.string "Aquí puedes luchar con tus amigos.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Para hacer POLVO de BAYA, hacen\n"
	.string "falta de dos a cinco ENTRENADORES.$"

CableClub_Text_CanMixRecords::
	.string "Se pueden mezclar los récords\n"
	.string "de dos a cuatro jugadores.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Guía de los servicios del CLUB\n"
	.string "INALÁMBRICO.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancelar la selección.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "¿Qué modo de combate quieres?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Vuelve al paso anterior.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Para usar el MACHACABAYAS,\n"
	.string "necesitas al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Para entrar en la SALA UNIÓN,\n"
	.string "debes tener al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Los POKéMON que tienen BAYAS\n"
	.string "{STR_VAR_1} no pueden entrar en la\l"
	.string "SALA UNIÓN.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Ésta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Vaya, tu Conector inalámbrico\n"
	.string "de GBA no está bien conectado…\p"
	.string "Vuelve más tarde.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh… ¡Disculpa!$"

CableClub_Text_PlayerIsWaiting:
	.string "¡Parece que {STR_VAR_1} está jugando\n"
	.string "ahora mismo! ¡Conéctate!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Si quieres, puedo explicarte las\n"
	.string "reglas de los juegos.\p"
	.string "¿Qué juego quieres que te explique?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“SALTO POKéMON”\p"
	.string "Haz que tu POKéMON salte la cuerda de\n"
	.string "LÁTIGO CEPA con el Botón A.\p"
	.string "Solo pueden participar POKéMON\n"
	.string "pequeños, de unos 70 cm o menos.\p"
	.string "A los POKéMON que solo nadan, excavan\n"
	.string "o vuelan no se les da bien saltar.\p"
	.string "Por eso, esos POKéMON no pueden\n"
	.string "participar.\p"
	.string "Si todos saltan a la vez, pasan cosas\n"
	.string "buenas.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO A POR BAYAS”\p"
	.string "Haz que las tres cabezas de DODRIO\n"
	.string "atrapen las BAYAS que caen.\p"
	.string "Pulsa derecha, arriba o izquierda en la\n"
	.string "Cruz de Control {PLUS} para\l"
	.string "mover las cabezas.\p"
	.string "Para jugar a este juego, necesitas un\n"
	.string "DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si quieres jugar a un juego, díselo al\n"
	.string "anciano que está a mi lado.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "¡Hola, bienvenido! ¿Vienes a jugar con\n"
	.string "la Comunicación Inalámbrica?\p"
	.string "¿Puedes esperar un poquito?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "¡Muy bien, vuelve cuando quieras!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "conectado. ¡Vuelve cuando esté\l"
	.string "conectado!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Muy bien, ¿a qué juego querías jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "¿Qué POKéMON quieres inscribir?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Vale, todo listo. ¡Que no te ganen los\n"
	.string "demás!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "¿Ya te vas? ¡Vuelve cuando quieras!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Parece que no tienes ningún POKéMON\n"
	.string "que pueda participar…\p"
	.string "¿Quieres que te explique qué clase de\n"
	.string "POKéMON pueden participar?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "En el “SALTO POKéMON” pueden\n"
	.string "participar POKéMON de unos 70 cm o\l"
	.string "menos.\p"
	.string "No pueden participar los POKéMON que\n"
	.string "no saben saltar.\p"
	.string "Ya sabes, como los POKéMON que solo\n"
	.string "nadan, excavan o vuelan.\p"
	.string "Eso es todo lo que necesitas saber.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO A POR BAYAS es un juego en el\n"
	.string "que solo puede participar DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "¿Podrías volver a intentarlo desde el\n"
	.string "principio, por favor?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Ésta es la ZONA DIRECTA del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con tus amigos.\p"
	.string "¿En qué sala quieres entrar?$"

CableClub_Text_TradePokemon:
	.string "¿Quieres cambiar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "¿Qué modo de combate quieres?$"

CableClub_Text_AccessRecordCorner:
	.string "¿Quieres entrar en el\n"
	.string "CENTRO de RÉCORDS?$"

CableClub_Text_UseBerryCrush:
	.string "¿Quieres usar el MACHACABAYAS?$"

CableClub_Text_ExplainBattleModes:
	.string "Hay tres modos de combate.\p"
	.string "El COMBATE INDIVIDUAL es para dos\n"
	.string "ENTRENADORES con uno o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR puede usar\n"
	.string "un POKéMON cada vez.\p"
	.string "El COMBATE DOBLE es para dos\n"
	.string "ENTRENADORES con dos o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR usará dos\n"
	.string "POKéMON cada vez.\p"
	.string "El COMBATE MULTIJUGADOR es para\n"
	.string "cuatro ENTRENADORES con uno o más\l"
	.string "POKéMON cada uno.\p"
	.string "Cada ENTRENADOR puede usar\n"
	.string "un POKéMON cada vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Un jugador debe ser LÍDER.\p"
	.string "Y el otro, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Un jugador debe ser LÍDER\n"
	.string "del GRUPO.\p"
	.string "Y los otros, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_ChooseGroupLeader:
	.string "Un jugador debe ser LÍDER\n"
	.string "del GRUPO.\p"
	.string "Y los otros, “UNIRSE\n"
	.string "al GRUPO”.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Ésta es la SALA UNIÓN del CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con ENTRENADORES\l"
	.string "a los que puede que no conozcas.\p"
	.string "¿Quieres entrar en la SALA?$"

CableClub_Text_UnionRoomInfo:
	.string "Los ENTRENADORES de la SALA UNIÓN\n"
	.string "serán los jugadores que tengas\l"
	.string "cerca y hayan entrado en la SALA.\p"
	.string "¡Aquí se pueden hacer muchas\n"
	.string "cosas, empezando por saludarse\l"
	.string "y celebrar el encuentro!\p"
	.string "Puedes registrar dos POKéMON\n"
	.string "de nivel no superior a 30 para\l"
	.string "entablar combates de 1 contra 1.\p"
	.string "También puedes participar en chats;\n"
	.string "podéis ser de 2 a 5 jugadores.\p"
	.string "Y, por supuesto, puedes registrar\n"
	.string "POKéMON para realizar intercambios.\p"
	.string "¿Quieres entrar en la SALA?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Espero que disfrutes de esta visita a\n"
	.string "la Sala Unión.\p"
	.string "$"

CableClub_Text_FirstTimeRightThisWay:
	.string "¡Hola!\n"
	.string "Me llamo TEALA.\p"
	.string "Es la primera vez que vienes, ¿no?\p"
	.string "Te voy a explicar cómo funciona\n"
	.string "el sistema de comunicación\l"
	.string "inalámbrica.\p"
	.string "Primero, te enseñaré esta planta\n"
	.string "de nuestro CENTRO POKéMON.\p"
	.string "Por aquí, por favor.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "En el primer piso de los CENTROS\n"
	.string "POKéMON hay dos salas.\p"
	.string "Primero te hablaré de la sala\n"
	.string "de la izquierda: la SALA UNIÓN.\p"
	.string "En ella puedes conectarte con los\n"
	.string "ENTRENADORES que también\p"
	.string "hayan entrado en la SALA UNIÓN\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear,\n"
	.string "luchar y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la ZONA DIRECTA.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates POKéMON.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la ZONA\n"
	.string "DIRECTA.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_AskAboutLinking:
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy yo, TEALA, la encargada de la 2.ª\n"
	.string "planta del CENTRO POKéMON.\p"
	.string "¿Querías preguntarme algo sobre las\n"
	.string "conexiones?$"

CableClub_Text_ExplainWirelessClub:
	.string "Te voy a explicar cómo funciona\n"
	.string "el CLUB INALÁMBRICO POKéMON.\p"
	.string "Éste es el piso de arriba y tiene\n"
	.string "dos salas.\p"
	.string "Primero te hablaré de la sala\n"
	.string "de la izquierda: la SALA UNIÓN.\p"
	.string "En ella puedes conectarte con los\n"
	.string "ENTRENADORES que también\p"
	.string "hayan entrado en la SALA UNIÓN\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear,\n"
	.string "luchar y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la ZONA DIRECTA.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates POKéMON.\p"
	.string "Si no encontraras a tus amigos\n"
	.string "en la SALA UNIÓN ni en la ZONA\l"
	.string "DIRECTA, acercad las consolas.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la ZONA\n"
	.string "DIRECTA.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"
