@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Soy el ENCARGADO de la GUARDERÍA.\p"
	.string "Ayudo a los ENTRENADORES a cuidar\n"
	.string "de sus preciosos POKéMON.\p"
	.string "Si quieres que me encargue del tuyo,\n"
	.string "ve a hablar con mi mujer.$"

DayCare_Text_DoYouWantEgg::
	.string "¡Ah, eres tú!\p"
	.string "¡Hemos cuidado de tu POKéMON y vaya\n"
	.string "sorpresa que nos hemos llevado!\p"
	.string "¡Tu POKéMON ha tenido un HUEVO!\p"
	.string "No sabemos cómo ha sucedido,\n"
	.string "pero es de tu POKéMON, seguro.\p"
	.string "¿Lo quieres?$"

DayCare_Text_YourMonIsDoingFine::
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Tu {STR_VAR_1} está estupendamente.$"

DayCare_Text_IllKeepIt::
	.string "Muy bien, entonces me seguiré\n"
	.string "ocupando de él. ¡Gracias!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "No tienes sitio para él…\n"
	.string "Vuelve cuando lo tengas.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} recibió el HUEVO del\n"
	.string "ENCARGADO de la GUARDERÍA.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Cuídalo bien.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "Si quieres recoger tus POKéMON,\n"
	.string "habla con mi mujer.$"

DayCare_Text_YourMonsAreDoingFine::
	.string "¡Ah, eres tú! Tu {STR_VAR_1} y el\n"
	.string "{STR_VAR_2} están muy bien.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Yo me lo quedaría.\n"
	.string "Pero imagino que lo quieres.$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Soy la ENCARGADA de la GUARDERÍA.\p"
	.string "Podemos ocuparnos de tus POKéMON.\p"
	.string "¿Quieres que cuidemos de alguno?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "¿Qué POKéMON quieres que cuidemos?$"

DayCare_Text_WellRaiseYourMon::
	.string "Estupendo, nos ocuparemos de tu\n"
	.string "{STR_VAR_1} cuanto sea necesario.\p"
	.string "Vuelve cuando quieras.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Podemos criar dos de tus POKéMON.\p"
	.string "¿Quieres que criemos un\n"
	.string "POKéMON más para ti?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Mi marido te estaba buscando.$"

DayCare_Text_FineThenComeAgain::
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

DayCare_Text_NotEnoughMoney::
	.string "No tienes bastante dinero.$"

DayCare_Text_TakeOtherOneBackToo::
	.string "¿Quieres llevarte el otro también?$"

DayCare_Text_ComeAgain::
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"

DayCare_Text_GoodToSeeYou::
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Y tú te alegrarás de saber esto…$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Tu {STR_VAR_1} ha crecido\n"
	.string "estos niveles: ¡{STR_VAR_2}!$"

DayCare_Text_YourPartyIsFull::
	.string "Tu equipo POKéMON está lleno.\n"
	.string "Haz hueco y ven a verme.$"

DayCare_Text_TakeBackWhichMon::
	.string "¿Cuál de los dos POKéMON\n"
	.string "quieres recoger?$"

DayCare_Text_ItWillCostX::
	.string "Si quieres llevarte a tu {STR_VAR_1},\n"
	.string "tendrás que pagar {STR_VAR_2}¥.$"

DayCare_Text_HeresYourMon::
	.string "¡Perfecto!\n"
	.string "Aquí tienes a tu POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} recogió a {STR_VAR_1} de\n"
	.string "la GUARDERÍA POKéMON.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Anda, pero si sólo tienes un POKéMON…\p"
	.string "Vuelve cuando tengas alguno más.$"

DayCare_Text_TakeYourMonBack::
	.string "¿Quieres recoger un POKéMON?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Si me dejas ese POKéMON,\n"
	.string "no podrás entablar combates.\p"
	.string "Vuelve en otra ocasión.$"

DayCare_Text_Huh::
	.string "¿Y esto?$"
