EventTicket_Text_ShowOldSeaMap:
	.string "El ferry a CIUDAD PORTUAL es…\p"
	.string "¿Cómo dice? ¿Se puede navegar hasta\n"
	.string "este lugar del mapa?\p"
	.string "Conozco a alguien que le podrá ayudar\n"
	.string "mejor. Espere, por favor.$"

EventTicket_Text_ThatPass:
	.string "El ferry a CIUDAD PORTUAL es…\p"
	.string "¿Eh? Ese PASE…$"

EventTicket_Text_ShowEonTicket:
	.string "¡Eh, marinero! ¿Eres tú quien ha\n"
	.string "traído ese PASE tan raro?\p"
	.string "Te diré que quieres llegar a una islita\n"
	.string "minúscula muy al sur.\p"
	.string "Quién sabe qué nos encontraremos\n"
	.string "cuando lleguemos. ¡Por todos los\l"
	.string "mares!\p"
	.string "¡Todos a bordo!$"

#if IS_HNS
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh, oye, no hay absolutamente nada que\n"
	.string "hacer en esta isla perdida en el mar.\p"
	.string "¿Y si volvemos a CALAGUA?$"
#else
EventTicket_Text_SouthernIslandSailBack:
	.string "Eh, oye, no hay absolutamente nada que\n"
	.string "hacer en esta isla perdida en el mar.\p"
	.string "¿Y si volvemos a CALAGUA?$"
#endif 


EventTicket_Text_SailHome:
	.string "¡Estupendo!\n"
	.string "¡Rumbo a casa!$"

EventTicket_Text_AsYouLike:
	.string "Bah, bueno, tú sabrás lo que quieres…$"

SouthernIsland_Interior_Text_Sign:
	.string "“Todos los sueños no son más que otra\n"
	.string "realidad. Nunca lo olvides…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Si quieres evitar olvidar tus\n"
	.string "recuerdos, guárdalos en el corazón…”$"
