Trade_Text_LookingForMonWannaTradeForMon::
	.string "¡Busco al POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "¿Quieres cambiarme uno por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "¡Vaya!\n"
	.string "Qué se le va a hacer…$"

Trade_Text_WhatThatsNoMon::
	.string "¿Qué?\n"
	.string "¡Eso no es un {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "¡Eh, gracias!$"

Trade_Text_IsntMyOldMonGreat::
	.string "¿A que mi antiguo {STR_VAR_2} es genial?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "¡Hola! ¿Tendrás por casualidad\n"
	.string "un {STR_VAR_1}?\p"
	.string "¿Aceptarías cambiármelo por\n"
	.string "mi {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Bueno, si no quieres…$"

Trade_Text_ThisIsntMon::
	.string "¿Mmm?\n"
	.string "Eso no es un {STR_VAR_1}.\p"
	.string "Acuérdate de mí si consigues uno.$"

Trade_Text_Thanks::
	.string "¡Gracias!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "El {STR_VAR_2} que te cambié,\n"
	.string "¿se ha hecho más fuerte?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "¡Hola!\n"
	.string "¿Tienes un {STR_VAR_1}?\p"
	.string "¿Quieres cambiármelo por mi\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Qué pena.$"

Trade_Text_ThisIsNoMon::
	.string "…Esto no es un {STR_VAR_1}.\p"
	.string "Si consigues uno, cámbiamelo.$"

Trade_Text_ThanksYoureAPal::
	.string "¡Gracias, eres un amigo!$"

Trade_Text_HowIsMyOldMon::
	.string "¿Qué tal mi antiguo {STR_VAR_2}?\n"
	.string "¡Mi {STR_VAR_1} está genial!$"
