MatchCall_WildBattleText1::
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Hace un rato, vi un {STR_VAR_2},\n"
	.string "pero no pude hacerme con él.\p"
	.string "¡Me faltó tan poco!\n"
	.string "¡En fin, hasta luego!$"

MatchCall_WildBattleText2::
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Intenté atrapar un {STR_VAR_2}\n"
	.string "ideal hace un rato.\p"
	.string "¡Pero se me escapó!\n"
	.string "¡Me llevé un chasco!\p"
	.string "¡Bueno, nos vemos!$"

MatchCall_WildBattleText3::
	.string "¡Eh, oye, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "He estado a puntito de atrapar\n"
	.string "un {STR_VAR_2}, pero nada.\p"
	.string "¡Casi me hago con él!\p"
	.string "Me ha fastidiado el día…\n"
	.string "Bueno, nos vemos.$"

MatchCall_WildBattleText4::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Oye, soy {STR_VAR_1}.\p"
	.string "¿Conoces al POKéMON {STR_VAR_2}?\n"
	.string "Casi me hago con uno.\p"
	.string "Ha sido hace un momento.\n"
	.string "Pensé que lo tenía, pero no.\p"
	.string "Si lo vuelvo a ver, te aseguro\n"
	.string "que no se me escapa.\p"
	.string "Bueno, ya hablaremos.$"

MatchCall_WildBattleText5::
	.string "¡Hola, {PLAYER}{KUN}! Soy {STR_VAR_1}. ¿Has\n"
	.string "capturado algún POKéMON últimamente?\p"
	.string "Hace un rato estuve a punto de\n"
	.string "atrapar uno, pero se escapó.\p"
	.string "¡Bueno, cuídate!$"

MatchCall_WildBattleText6::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "¿Has capturado algún POKéMON?\p"
	.string "El otro día casi atrapo uno.\n"
	.string "Pero se me escabulló.\p"
	.string "Cuídate.$"

MatchCall_WildBattleText7::
	.string "Eh…, ¿{PLAYER}{KUN}?\n"
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "¡Ay, espera, espera! ¡Estoy a\n"
	.string "punto de atrapar un {STR_VAR_2}!…\p"
	.string "¡Aaarrrg! ¡Ha salido por patas!\n"
	.string "¡Por qué poco!$"

MatchCall_WildBattleText8::
	.string "Eh, {PLAYER}{KUN}, ¿qué tal vas?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te ha ido bien atrapando\n"
	.string "POKéMON últimamente?\p"
	.string "Yo casi me hago con uno,\n"
	.string "pero logró escapar.\p"
	.string "¡Tendré que intentarlo otra vez!\n"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText9::
	.string "¡Anda, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué?\n"
	.string "¿Tienes ya muchos POKéMON?\p"
	.string "¡Yo me estoy cansando un poco ya!\n"
	.string "¡Se me escapan todos!\p"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mira, he estado a nada de pillar\n"
	.string "un {STR_VAR_2}…\p"
	.string "Pero me he quedado sin él…\p"
	.string "Tendré que intentarlo de nuevo.\n"
	.string "Nos vemos.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo te va todo?\p"
	.string "Antes intenté capturar un {STR_VAR_2}\n"
	.string "salvaje, pero consiguió huir.\p"
	.string "Me siento derrotado…$"

MatchCall_WildBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Sigues capturando POKéMON?\p"
	.string "Yo he intentado capturarlos,\n"
	.string "pero no es tan fácil.\p"
	.string "¡El camino del POKéMON es profundo!$"

MatchCall_WildBattleText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "¿Has estado capturando POKéMON?\p"
	.string "Yo lo he intentado, pero con\n"
	.string "poco éxito.\p"
	.string "¡El camino del POKéMON es profundo!$"

MatchCall_WildBattleText14::
	.string "¡Eh, {PLAYER}{KUN}! ¿Qué tal?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Ahora mismo, he intentado\n"
	.string "atrapar un {STR_VAR_2}.\p"
	.string "¡Pero se me ha escapado!\n"
	.string "¡Se me ha quedado una cara!…\p"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText15::
	.string "¡Eh, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He estado pensando en ir\n"
	.string "a atrapar algunos POKéMON.\p"
	.string "¡Es que normalmente me cuesta!\n"
	.string "¡Siempre se me ha dado fatal!\p"
	.string "¡A ver si recupero las ganas!\n"
	.string "¡Hala, adiós!$"

MatchCall_NegativeBattleText1::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He intentado ganar a otro\n"
	.string "ENTRENADOR, pero nada.\p"
	.string "Me he desanimado bastante.\n"
	.string "En fin, nos vemos.$"

MatchCall_NegativeBattleText2::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me enfrenté a alguien después\n"
	.string "de nuestro combate.\p"
	.string "Estuve a punto de ganar,\n"
	.string "pero al final perdí. ¡Ay!$"

MatchCall_NegativeBattleText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Acabo de salir hecho polvo de\n"
	.string "un combate.\p"
	.string "¡Creo que tengo que entrenar\n"
	.string "más a mi equipo!$"

MatchCall_NegativeBattleText4::
	.string "Eh, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Ayer lo intenté en otro combate,\n"
	.string "pero no conseguí ganar.\p"
	.string "Mi equipo necesita más\n"
	.string "entrenamiento. Bueno, nos vemos.$"

MatchCall_NegativeBattleText5::
	.string "¡Hola, hola, hola, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal te va todo, eh?\p"
	.string "He estado todo este tiempo\n"
	.string "luchando, pero no he ganado\l"
	.string "demasiadas veces.\p"
	.string "¡No acabo de pillarle el tranquillo!\n"
	.string "Bueno, que te vaya bien.$"

MatchCall_NegativeBattleText6::
	.string "¡Eh, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Te va todo bien?\p"
	.string "Yo he estado luchando un montón,\n"
	.string "pero no he tenido demasiado éxito.\p"
	.string "Me cuesta mantener el ritmo.\n"
	.string "En fin, cuídate.$"

MatchCall_NegativeBattleText7::
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Cómo lo llevas?\p"
	.string "Ayer perdí un combate\n"
	.string "y no se me quita de la cabeza.\p"
	.string "Necesito una estrategia.\n"
	.string "Nos vemos.$"

MatchCall_NegativeBattleText8::
	.string "Eh, {PLAYER}{KUN}, ¿qué tal?\n"
	.string "Sí, soy {STR_VAR_1}.\p"
	.string "¿Qué tal tus POKéMON?\n"
	.string "Yo el otro día perdí un combate.\p"
	.string "¡Necesito esforzarme más!\n"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText9::
	.string "¡Ah, {PLAYER}{KUN}, hola! ¡Soy {STR_VAR_1}!\p"
	.string "¡Escucha, escucha, tienes que oír\n"
	.string "esto!\p"
	.string "Tuve un combate POKéMON hace un rato,\n"
	.string "pero perdí en el último instante.\p"
	.string "¡Ay, me muero de rabia!$"

MatchCall_NegativeBattleText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Acabo de participar en un combate,\n"
	.string "pero he perdido.\p"
	.string "Tengo que dedicarle más tiempo\n"
	.string "a mis POKéMON. ¡Adiós!$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Cómo están tus POKéMON?\p"
	.string "Acabo de perder otro combate.\p"
	.string "Bueno, ¡hasta luego!$"

MatchCall_NegativeBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Sigues combatiendo a tope?\p"
	.string "Yo perdí hace poco, así que he\n"
	.string "estado entrenando a mi equipo de nuevo.\p"
	.string "Volvamos a vernos.$"

MatchCall_NegativeBattleText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Espero que te haya ido bien!\p"
	.string "Hace nada estaba en pleno\n"
	.string "combate.\p"
	.string "¡{PLAYER}{KUN}, no te duermas\n"
	.string "en los laureles!\l"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText14::
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estás bien?\p"
	.string "Yo creo que deberías pasarte\n"
	.string "por tu casa de vez en cuando.\p"
	.string "Hala, te dejo.$"

MatchCall_PositiveBattleText1::
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He luchado con otro ENTRENADOR\n"
	.string "¡y he ganado! ¡He ganado!\p"
	.string "Mi {STR_VAR_2} se ha portado como\n"
	.string "un fiera. ¡Ha sido una pasada!$"

MatchCall_PositiveBattleText2::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ayer luché de nuevo! ¡Y gané!\n"
	.string "¡Qué guay!$"

MatchCall_PositiveBattleText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "¡Soy yo, {STR_VAR_1}!\l"
	.string "¿Qué tal tus combates?\p"
	.string "Yo combatí el otro día,\n"
	.string "¡y mi {STR_VAR_2} estuvo enorme!\p"
	.string "¡La próxima vez que combata contra\n"
	.string "ti, {PLAYER}, no seré yo quien pierda!$"

MatchCall_PositiveBattleText4::
	.string "Hola, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He estado luchando\n"
	.string "y he ganado, pero por muy poco.\p"
	.string "Mi {STR_VAR_2} estuvo bastante\n"
	.string "bien.$"

MatchCall_PositiveBattleText5::
	.string "¡Hola, hola, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal te van las cosas?\n"
	.string "¿Llevas muchos combates?\p"
	.string "¡Yo he ganado uno hace poco!\n"
	.string "¡Mi {STR_VAR_2} es una máquina!\p"
	.string "Tú, ya verás, la próxima vez\n"
	.string "que nos veamos seguro que\l"
	.string "te machaco. ¡Nos vemos!$"

MatchCall_PositiveBattleText6::
	.string "¿Qué pasa, {PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal vas, eh?\p"
	.string "A mí no me ha ido del todo mal.\n"
	.string "Bueno, he ganado un combate.\p"
	.string "Cuando nos veamos otra vez,\n"
	.string "¡ya verás, ya!$"

MatchCall_PositiveBattleText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡Mi {STR_VAR_2} es total!\n"
	.string "¡Acaba de ganarme otro combate!\p"
	.string "¡Estoy deseando enfrentarme\n"
	.string "a ti de nuevo!$"

MatchCall_PositiveBattleText8::
	.string "¡{PLAYER}{KUN}, qué sorpresa!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés estupendamente.\n"
	.string "¡Quería decirte que acabo de ganar\l"
	.string "un combate!\p"
	.string "Mi {STR_VAR_2} se ha esforzado\n"
	.string "un montón para que ganáramos.\p"
	.string "¡Nos vemos!$"

MatchCall_PositiveBattleText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal lo llevan tus POKéMON?\n"
	.string "¡Los míos acaban de ganar\l"
	.string "un combate!\p"
	.string "Mi {STR_VAR_2} ha estado\n"
	.string "espectacular, las cosas como son.\p"
	.string "¡Me hubiera encantado que\n"
	.string "lo vieras! ¡Nos vemos!$"

MatchCall_PositiveBattleText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal te va la vida?\p"
	.string "Mis POKéMON están llenos\n"
	.string "de energía.\p"
	.string "Acabo de ganar un combate\n"
	.string "con ellos. A ver si nos vemos.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Has luchado recientemente?\n"
	.string "¡Yo acabo de ganar de nuevo!\p"
	.string "¡Estoy en racha! ¡Ja, ja, ja, ja!\n"
	.string "Bueno, te dejo.$"

MatchCall_PositiveBattleText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés bien.\n"
	.string "¡Yo estoy hecho un chaval!\p"
	.string "Es que acabo de ganar de nuevo.\n"
	.string "¡Todavía no pienso dejar paso\l"
	.string "a los jóvenes como tú!$"

MatchCall_PositiveBattleText13::
	.string "¡Eh, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que estés bien.\n"
	.string "¡Yo estoy más joven que nunca!\p"
	.string "Acabo de ganar otro combate.\n"
	.string "¡Aún me queda mucho por hacer,\l"
	.string "joven!\p"
	.string "¡Hala!$"

MatchCall_PositiveBattleText14::
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He estado luchando hace poco.\n"
	.string "¡Mi {STR_VAR_2} lo ha hecho\l"
	.string "de escándalo!\p"
	.string "Tendrías que haberlo visto,\n"
	.string "{PLAYER}{KUN}. ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText1::
	.string "¡Eh! ¡{PLAYER}, hola!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo? ¿Que estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "¡Anda, pues entonces tenemos\n"
	.string "que luchar!\l"
	.string "¡Te espero! ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Sí? ¿Estás cerca\n"
	.string "de {STR_VAR_2}?\p"
	.string "¿Te apetece luchar?\n"
	.string "¡Venga, te espero! ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText3::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Oh, ¿estás cerca de\n"
	.string "{STR_VAR_2} ahora mismo?\p"
	.string "¿Te apetece combatir conmigo\n"
	.string "ahora mismo?\p"
	.string "¡No pienso perder otra vez!\n"
	.string "¡Te espero! ¡Hasta pronto!$"

MatchCall_SameRouteBattleRequestText4::
	.string "¿Qué pasa, {PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Por dónde andas?\n"
	.string "¿Eh? ¿Por {STR_VAR_2}?\p"
	.string "¿Luchamos?\n"
	.string "Te espero, ¡hasta ahora!$"

MatchCall_SameRouteBattleRequestText5::
	.string "¡{PLAYER}{KUN}! ¿Cómo vas?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va? ¿Eh? ¿Que andas\n"
	.string "por {STR_VAR_2}?\p"
	.string "¿Y si nos echamos un combate\n"
	.string "de nuevo?\p"
	.string "Espero que vengas.\n"
	.string "¡No tardes!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "¿Cómo van tus POKéMON?\p"
	.string "Ah, ¿sí? ¿Estás por\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues entonces tendremos que\n"
	.string "hacer la revancha.\p"
	.string "Puedo esperar, claro.\n"
	.string "¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText7::
	.string "Eh…, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}…\p"
	.string "¿Que estás por\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues lucha conmigo, anda.\n"
	.string "Ahora mismo, claro.\p"
	.string "Quiero enseñarte mis POKéMON.\n"
	.string "Te espero aquí.$"

MatchCall_SameRouteBattleRequestText8::
	.string "{PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés bien. ¿Estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "¿Querrías aprovechar para\n"
	.string "luchar conmigo?\p"
	.string "Te espero.\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText9::
	.string "¡{PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Todo bien? ¿Que estás cerca de\n"
	.string "{STR_VAR_2}?\p"
	.string "¿No crees que deberíamos\n"
	.string "aprovechar y enfrentarnos?\p"
	.string "¡No tardes mucho, anda!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va? ¿Estás cerca de\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues deberíamos luchar.\p"
	.string "Cuando quieras, aquí estoy.\n"
	.string "¡Date prisa!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Así que estás en\n"
	.string "{STR_VAR_2}…\p"
	.string "Pues tendríamos que luchar,\n"
	.string "¿no crees?\p"
	.string "¡No me falles!\n"
	.string "¡Y date prisa!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¿Por dónde andas? ¿Por\n"
	.string "{STR_VAR_2}? ¡Qué cerca!\p"
	.string "¿Qué me dices a un combate\n"
	.string "aquí y ahora?\p"
	.string "¡Estoy deseándolo!\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que todo vaya bien. ¿Estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "Pues no estás lejos,\n"
	.string "¿por qué no luchamos?\p"
	.string "Te espero, ¿eh?\n"
	.string "Hasta luego.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que estás dónde? ¿Por\n"
	.string "{STR_VAR_2}? ¡Qué cerca!\p"
	.string "¿No crees que deberíamos\n"
	.string "luchar?\p"
	.string "¡No me dejes con las ganas!\n"
	.string "¡Adiós!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Quieres que luchemos de nuevo?\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "¡Te espero!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te gustaría combatir\n"
	.string "conmigo otra vez?\p"
	.string "Me encontrarás por\n"
	.string "{STR_VAR_2}. ¡Te espero!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "¡{PLAYER}! ¿Cómo lo llevas?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Mis POKéMON están mucho\n"
	.string "más fuertes ahora.\p"
	.string "Me gustaría medir sus fuerzas\n"
	.string "con las de tus POKéMON, {PLAYER}.\p"
	.string "¡Vamos a luchar, anda!\p"
	.string "Te espero por\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "¿Cómo te va todo?\p"
	.string "Mis POKéMON se han vuelto bastante\n"
	.string "fuertes últimamente.\p"
	.string "¿Qué te parece si combatimos\n"
	.string "otra vez?\p"
	.string "Quedemos por {STR_VAR_2},\n"
	.string "¿vale?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mis POKéMON están creciendo\n"
	.string "muy bien.\p"
	.string "Me encantaría combatir contigo\n"
	.string "otra vez.\p"
	.string "Os buscaré por {STR_VAR_2}.\n"
	.string "¡Hasta pronto!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "Pensaba que me gustaría otro\n"
	.string "combate contigo. ¿Qué dices?\p"
	.string "Si te apetece combatir,\n"
	.string "ven a {STR_VAR_2}.\p"
	.string "¡Hasta luego!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va todo?\n"
	.string "Mis POKéMON están imparables.\p"
	.string "¿Y si lucháramos otra vez?\p"
	.string "¿Nos vemos por\n"
	.string "{STR_VAR_2}, eh?$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "¡Ey, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mis POKéMON han crecido\n"
	.string "de forma considerable.\p"
	.string "Realmente me encantaría\n"
	.string "luchar de nuevo contigo.\p"
	.string "Te esperaré por\n"
	.string "{STR_VAR_2}. ¡No tardes!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Por dónde andas ahora?\p"
	.string "Mis POKéMON están llenos de vida.\n"
	.string "Creo que están deseando ver\l"
	.string "a los tuyos, {PLAYER}{KUN}.\p"
	.string "Estoy por {STR_VAR_2}.\n"
	.string "Espero que des con nosotros.$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Debo decirte que mis POKéMON\n"
	.string "se han puesto tremendos.\p"
	.string "Me gustaría verlos en combate\n"
	.string "contra ti, {PLAYER}{KUN}.\p"
	.string "Estaremos por {STR_VAR_2}.\n"
	.string "¡Ven a vernos cuando quieras!$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¿Dónde andarás ahora?\p"
	.string "Mis POKéMON están llenos de vida.\n"
	.string "Parece que tienen ganas de ver\l"
	.string "tus POKéMON, {PLAYER}{KUN}.\p"
	.string "Ahora estoy por {STR_VAR_2}.\n"
	.string "Espero que vengas a buscarnos.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Debo decirte que mis POKéMON se han\n"
	.string "vuelto bastante robustos.\p"
	.string "Me gustaría verlos combatir contra\n"
	.string "los tuyos, {PLAYER}{KUN}.\p"
	.string "Estaremos por {STR_VAR_2}.\n"
	.string "¡Ven a vernos cuando quieras!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "¿Están bien tus POKéMON?\p"
	.string "¡Mis POKéMON están tan sanos que\n"
	.string "parece imposible que pierdan!\p"
	.string "Me encantaría combatir contigo\n"
	.string "otra vez.\p"
	.string "Si estás cerca de {STR_VAR_2},\n"
	.string "ven a vernos.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Espero que estés bien.\p"
	.string "¡Ah, sí! Mis POKéMON son\n"
	.string "mucho más fuertes que antes.\p"
	.string "¿No crees que deberíamos\n"
	.string "combatir, {PLAYER}{KUN}?\p"
	.string "Te esperaremos por\n"
	.string "{STR_VAR_2}.\p"
	.string "¡Ven a vernos cuando quieras!$"

MatchCall_PersonalizedText1::
	.string "¡Soy yo, {STR_VAR_1},\n"
	.string "el apasionado de la montaña!\p"
	.string "Bueno, ¿te gustan ahora más\n"
	.string "las montañas?\p"
	.string "Nunca te veo por los montes…\p"
	.string "A ver si la próxima vez que nos\n"
	.string "veamos es por {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Soy {STR_VAR_1}.\n"
	.string "Hola.\p"
	.string "Ahora mismo estaba hablándole\n"
	.string "de ti a una ENTRENADORA.\p"
	.string "Le estaba hablando de alguien\n"
	.string "fuerte que cuida mucho\l"
	.string "a sus POKéMON.\p"
	.string "Espero que todo el mundo acabe\n"
	.string "admirándote.\p"
	.string "¡A ver si volvemos a vernos!$"

MatchCall_PersonalizedText3::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Sabes qué estoy haciendo hoy?\n"
	.string "¡Mirando las olas desde la playa!\p"
	.string "Ay… Tienen un brillo…\n"
	.string "El mar es mucho más bonito\l"
	.string "desde aquí.\p"
	.string "¡Bueno, te dejo, que tengo hambre!$"

MatchCall_PersonalizedText4::
	.string "¡Hola! ¡Treinta años de exploración,\n"
	.string "{STR_VAR_1} a tu servicio!\p"
	.string "Parece que viajas con energía\n"
	.string "por todas partes.\p"
	.string "¿Has descubierto alguna ruina nueva?\n"
	.string "¡Cuéntamelo si es así!\p"
	.string "Y ahora, si me disculpas,\n"
	.string "tengo ruinas que explorar.$"

MatchCall_PersonalizedText5::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Sabes qué hago hoy?\n"
	.string "¡Mirar las olas desde la playa!\p"
	.string "Suspiro… Las olas brillan mucho.\n"
	.string "Desde aquí el mar es lo más bonito.\l"
	.string "Me está entrando hambre, ¡adiós!$"

MatchCall_PersonalizedText6::
	.string "Ñam, ñam…\n"
	.string "Ah, hola, soy {STR_VAR_1}.\l"
	.string "Me encanta comer en la playa.\p"
	.string "Mis POKéMON y yo estamos genial.\n"
	.string "¡Estamos a tope de energía!\l"
	.string "Voy a nadar un rato. ¡Adiós!$"

MatchCall_PersonalizedText7::
	.string "Hola, soy {STR_VAR_1}…\p"
	.string "Estoy hasta el gorro de ser\n"
	.string "ENTRENADOR GUAY…\p"
	.string "Todos piensan que soy un perfecto\n"
	.string "ENTRENADOR, y me agobia\l"
	.string "tener que dar siempre la talla.\p"
	.string "Aunque supongo que forma parte\n"
	.string "de ser ENTRENADOR GUAY.\p"
	.string "Bueno, seguiré entrenándome como\n"
	.string "siempre, lanzaré mi mejor sonrisa\l"
	.string "y lo llevaré lo mejor que pueda.\p"
	.string "Eres la única persona con la que\n"
	.string "puedo hablar de estas cosas.\p"
	.string "Pero no te preocupes, ¡que no voy\n"
	.string "a ponerme a quejarme cuando\l"
	.string "nos veamos la próxima vez!$"

MatchCall_PersonalizedText8::
	.string "¡Ey, soy {STR_VAR_1}!\n"
	.string "¿Qué pasa, eh?\p"
	.string "He estado entrenando mis POKéMON\n"
	.string "para ganarte.\p"
	.string "No pienso perder cuando\n"
	.string "nos enfrentemos de nuevo.\p"
	.string "¿No es guay tener amigos\n"
	.string "ENTRENADORES? ¡A ver si nos vemos!$"

MatchCall_PersonalizedText9::
	.string "Soy {STR_VAR_1}…\n"
	.string "Creo que justo ahora…\l"
	.string "Tienes algo detrás…\p"
	.string "El poder de los POKéMON que\n"
	.string "duermen aquí en el MONTE PÍRICO…\p"
	.string "Me habla sobre ti…\p"
	.string "Corre, camina hacia el frente\n"
	.string "¡y no mires atrás ni una sola vez!…\p"
	.string "Adiós…\n"
	.string "Ja, ja, ja…$"

MatchCall_PersonalizedText10::
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Cómo estás?\p"
	.string "¿No es una maravilla que podamos\n"
	.string "charlar estando lejos?\p"
	.string "Antes, cuando quería hablar con\n"
	.string "alguien, hacía a mi padre llevarme\l"
	.string "donde fuera…\p"
	.string "Bueno, que tengo que hacer cosas.\n"
	.string "Me alegro de haber hablado contigo.$"

MatchCall_PersonalizedText11::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¿Te cuento una cosa?\p"
	.string "A mí me encanta la ZONA SAFARI,\n"
	.string "¡pero me pierdo siempre que voy!\p"
	.string "¡Con tanta hierba!\n"
	.string "¡Con tantos recovecos!\p"
	.string "Bueno, ¡tenía que decírselo\n"
	.string "a alguien!\p"
	.string "En fin, allá que voy otra vez.\n"
	.string "¡A ver si nos vemos!$"

MatchCall_PersonalizedText12::
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Exacto, sí, soy bastante pudiente.\p"
	.string "Más que la última vez\n"
	.string "que nos vimos.\p"
	.string "Y lo que es más: mis POKéMON\n"
	.string "tienen más fuerza aún.\p"
	.string "¡La verdad es que la vida\n"
	.string "me sonríe!\p"
	.string "Ya, ya, es así.\n"
	.string "Eso lo ve cualquiera.\p"
	.string "Oh, perdona, si me disculpas,\n"
	.string "es que tengo que ir a una cena.$"

MatchCall_PersonalizedText13::
	.string "Uf, uf, uf…\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "¿A que no sabes qué estoy viendo?\n"
	.string "Un par de {STR_VAR_2} en combate.\p"
	.string "Creo que voy a intentar hacerme\n"
	.string "con el que gane…\l"
	.string "Uf, uf, uf…\p"
	.string "Eh… estoy liado ahora mismo.\n"
	.string "Te dejo.$"

MatchCall_PersonalizedText14::
	.string "¡Eh, soy {STR_VAR_1}!\p"
	.string "Creo que estoy aburrida ya\n"
	.string "de la NAO ABANDONADA.\p"
	.string "Pero, ya que estoy, me gustaría\n"
	.string "luchar contigo y ganarte.\l"
	.string "Voy a quedarme un poco más.\p"
	.string "Si te apetece, ¿por qué no\n"
	.string "te pasas a verme?\p"
	.string "De hoy no pasa sin que desafíe\n"
	.string "al del camarote de al lado.\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText15::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡El amante del mar!\p"
	.string "¿Sabes lo que creo?\p"
	.string "Creo que los ENTRENADORES\n"
	.string "de mar son los más curtidos.\p"
	.string "Deberías aprender de mí\n"
	.string "y entrenarte en el mar…\p"
	.string "¡Uaaaaaaaa, una ola gigante!\p"
	.string "¡Qué oportunidad para entrenar!\n"
	.string "¡Lo siento, te dejo!$"

MatchCall_PersonalizedText16::
	.string "¡Soy {STR_VAR_1}! Oye, he estado\n"
	.string "enseñándoles karate a mis POKéMON.\p"
	.string "¡Y ahora son mucho mejores\n"
	.string "que yo! ¡Me ganan todo el tiempo!\p"
	.string "Pero, aunque pierda ante los\n"
	.string "POKéMON, con los ENTRENADORES\l"
	.string "seguro que no tengo problema.\p"
	.string "¡Tenemos que luchar de nuevo!\n"
	.string "¿Eeeeeeh?$"

MatchCall_PersonalizedText17::
	.string "Soy yo, {STR_VAR_1}.\n"
	.string "¿Qué tal va tu viaje?\p"
	.string "Bua…, ¿en serio?\n"
	.string "¡Suena que se te va la olla!\p"
	.string "Creo que podría escribir una\n"
	.string "canción con una de tus historias.\p"
	.string "Ey…, ya lo tengo…\n"
	.string "Es como si la estuviera oyendo.\p"
	.string "Voy a ponerme a hacerle\n"
	.string "los arreglos, ¡me piro!$"

MatchCall_PersonalizedText18::
	.string "Soy {STR_VAR_1}…\n"
	.string "Mira, ésta es mi canción:\p"
	.string "Lalala, ¡{STR_VAR_2}, {STR_VAR_2}!\n"
	.string "¿Por qué eres tú {STR_VAR_2}?\l"
	.string "¿Por qué no soy yo {STR_VAR_2}?\l"
	.string "Lalala, ¡{STR_VAR_2} y {STR_VAR_1},\l"
	.string "{STR_VAR_1} y {STR_VAR_2}! Lalala…\p"
	.string "Y ahora vendría el estribillo…$"

MatchCall_PersonalizedText19::
	.string "¡Soy {STR_VAR_1}, ya sabes,\n"
	.string "el experto en acampadas!\p"
	.string "Cuando luchamos, no pude\n"
	.string "evitar perder contra ti.\p"
	.string "En realidad, a mí lo que se me\n"
	.string "da bien son las acampadas.\p"
	.string "Con todo, gane o pierda, me gusta\n"
	.string "luchar cuando estoy de acampada.\p"
	.string "Lucha con nosotros otra vez,\n"
	.string "¿vale? ¡Ah, y vente de acampada!$"

MatchCall_PersonalizedText20::
	.string "Soy yo, yo, ¡{STR_VAR_1}!\p"
	.string "La verdad es que me encantaría\n"
	.string "escalar otras montañas.\p"
	.string "Pero creo que el MONTE CENIZO\n"
	.string "es donde hay más gente,\l"
	.string "sobre todo chicas.\p"
	.string "Si sabes de otro sitio, me dices,\n"
	.string "¿eh?\p"
	.string "¡Bueno, nos vemos, je, je!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Soy {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Eso es todo por hoy…$"

MatchCall_PersonalizedText22::
	.string "Soy {STR_VAR_1}. Hoy, sabía\n"
	.string "que iba a hablar contigo.\p"
	.string "Estoy deseando ganarte,\n"
	.string "no me lo quito de la cabeza.\p"
	.string "¿Ah, sí, que tienes rival?\n"
	.string "Cómo me gustaría ser yo…\p"
	.string "Me alegro de haber hablado\n"
	.string "contigo. Adiós.$"

MatchCall_PersonalizedText23::
	.string "Soy {STR_VAR_1}.\p"
	.string "A veces, siento la presencia\n"
	.string "de los ENTRENADORES fuertes,\l"
	.string "cuando están cerca.\p"
	.string "¿Has pasado por donde yo estaba,\n"
	.string "{PLAYER}{KUN}? A lo mejor has sido tú.\p"
	.string "Espero tu visita.\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText24::
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Se te oye muy bien, {PLAYER}{KUN}.\p"
	.string "He viajado por todo el mundo,\n"
	.string "pero esta región tiene algo.\p"
	.string "Tengo intención de quedarme\n"
	.string "un tiempo. A lo mejor podríamos\l"
	.string "volver a vernos.\p"
	.string "No he podido olvidar lo brillante\n"
	.string "de tu técnica.\p"
	.string "Espero que luchemos de nuevo.$"

MatchCall_PersonalizedText25::
	.string "Snif… Soy… {STR_VAR_1}…\n"
	.string "…Buaaa…\p"
	.string "PETRA me ha echado la bronca en\n"
	.string "clase hoy.\p"
	.string "Pero no es que me caiga mal ni nada.\p"
	.string "PETRA me dice exactamente qué hice\n"
	.string "mal para que aprenda de ello.\p"
	.string "¡Mañana iré a la ESCUELA de\n"
	.string "ENTRENADORES, seguro!\p"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText26::
	.string "Snif… Soy… {STR_VAR_1}…\n"
	.string "Snif…\p"
	.string "Hoy, estábamos en clase\n"
	.string "y PETRA me ha echado.\p"
	.string "Pero no tengo nada en contra\n"
	.string "de ella.\p"
	.string "PETRA siempre me dice lo que\n"
	.string "hago mal y aprendo un montón.\p"
	.string "¡Mañana pienso volver\n"
	.string "a la ESCUELA de ENTRENADORES!\p"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText27::
	.string "¡Hola, soy ANI!\n"
	.string "¡Estoy con mi pupila, MATI!\p"
	.string "Me encanta ocuparme de MATI\n"
	.string "y de los POKéMON. ¡Son adorables!\p"
	.string "¡Me gustaría cuidar de ellos\n"
	.string "como si fueran mis hermanos!\p"
	.string "¡Ah, hola, MATI!\n"
	.string "¿Has traído los bollos?\p"
	.string "¿Cómo? ¿Que te estoy tratando\n"
	.string "como si fueras una esclava?\p"
	.string "Oye, tú fuiste la que perdió,\n"
	.string "así que te toca ir a por el pan.\p"
	.string "¡No es que quiera aprovecharme,\n"
	.string "MATI! ¡Si me caes muy bien!\p"
	.string "Bueno, que tengo que irme.\n"
	.string "¡Vamos a comernos el bocata!$"

MatchCall_PersonalizedText28::
	.string "¡Adoro los POKéMON!\n"
	.string "¡Soy {STR_VAR_1}, del CLUB de FANS!\p"
	.string "¡Tienes que oír esto!\n"
	.string "Mi dulce POKéMON…\p"
	.string "¡Ñic! ¡Jajaja!\n"
	.string "¡No puedo decir más! ¡Es un secreto!\l"
	.string "¡Es demasiado mono para contarlo!\p"
	.string "Ay, mi dulce {STR_VAR_2} me pide\n"
	.string "un {POKEBLOCK}.\p"
	.string "¡Es la imagen de la ternura!\p"
	.string "¡Lo siento, pero ahora no puedo hablar!\n"
	.string "¡Tendrás que oírlo la próxima vez!$"

MatchCall_PersonalizedText29::
	.string "¡Eeeeeh!\p"
	.string "¡Soy {STR_VAR_1}! ¡Voy a hablarte\n"
	.string "sobre mis adorables POKéMON!\p"
	.string "Presta atención, es sobre\n"
	.string "mi adorado {STR_VAR_2}.\p"
	.string "Siempre que alguien lo toma en\n"
	.string "brazos, quiere venirse conmigo.\p"
	.string "Oh… Oh…\n"
	.string "¿Acaso hay algo más maravilloso?\p"
	.string "¡Es que es para comérselo!\p"
	.string "Estoy feliz de haber compartido\n"
	.string "mi alegría contigo.\p"
	.string "Bueno, tengo que marcharme.\n"
	.string "¡Hasta otra!$"

MatchCall_PersonalizedText30::
	.string "Soy… {STR_VAR_1}. La gente me llama\n"
	.string "EXPERTO.\p"
	.string "Pero hay algo que sé. No podría ser\n"
	.string "EXPERTO por mis propias fuerzas.\p"
	.string "Solo con la ayuda de los POKéMON\n"
	.string "puede un ENTRENADOR llegar a ser\l"
	.string "EXPERTO.\p"
	.string "¡Hum! ¡Creo que he dicho algo profundo\n"
	.string "y sabio!\p"
	.string "¡Te dejo con buen ánimo!$"

MatchCall_PersonalizedText31::
	.string "Soy {STR_VAR_1}.\n"
	.string "¡Cómo me alegro de hablar contigo!\p"
	.string "Oye, los baños termales me dejan\n"
	.string "como nueva, ¡me quitan años!\p"
	.string "He luchado con ENTRENADORES\n"
	.string "jóvenes desde que nos vimos,\l"
	.string "pero no hay nadie como tú.\p"
	.string "Seguro que con los años, acabarás\n"
	.string "siendo POKéABU como yo.\l"
	.string "¡Je, je, je!$"

MatchCall_PersonalizedText32::
	.string "¡Yupi! ¡Soy {STR_VAR_1}! ¿Qué tal?\p"
	.string "Quizá sean imaginaciones mías, pero\n"
	.string "cuando gano combates, mis pantalones\l"
	.string "cortos parecen sentirse mejor.\l"
	.string "Materialmente.\p"
	.string "¿Qué quiero decir con eso? Es difícil\n"
	.string "de explicar, pero… A ver cómo lo digo…\l"
	.string "¡Mis pantalones se sienten más\l"
	.string "sedosos!\p"
	.string "Y cuando combatí contra ti, {PLAYER}{KUN},\n"
	.string "mis pantalones se sentían ásperos.\p"
	.string "… … … … … … ¿No te lo habrás creído?\n"
	.string "Jejeje, ¡eso es todo! ¡Adiós!$"

MatchCall_PersonalizedText33::
	.string "¡Ey!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Como siempre, ¡estoy pescando\n"
	.string "a mi bola!\p"
	.string "¿Dónde se podrá pescar además\n"
	.string "de en el mar y los ríos?\p"
	.string "¡Es que me entran ganas de pescar\n"
	.string "por todos lados!\p"
	.string "¡Ah, vaya, hombre!\n"
	.string "¡Se me ha liado el sedal!\p"
	.string "¡Oye, tengo que dejarte! ¡A ver\n"
	.string "si me buscas un sitio para pescar!$"

MatchCall_PersonalizedText34::
	.string "¡Eh, oye! Soy {STR_VAR_1}.\n"
	.string "¿Te lo estás tomando\l"
	.string "con espíritu deportivo?\p"
	.string "Yo siempre me he tomado las\n"
	.string "cosas con calma, desde pequeño.\p"
	.string "Nunca me ha gustado hacer nada\n"
	.string "corriendo y sin pensar.\p"
	.string "Pero, hay que ver lo que son\n"
	.string "las cosas, ahora soy TRIATLETA.\p"
	.string "Nunca sabes por dónde te va\n"
	.string "a llevar la vida, fíjate en mí.\p"
	.string "Ahora te dedicas a ENTRENAR,\n"
	.string "pero ¿quién sabe en el futuro, eh?\p"
	.string "Igual acabas dando clase o te\n"
	.string "conviertes en artista. Mola, ¿eh?\p"
	.string "Bueno, de momento tómatelo\n"
	.string "con deportividad. ¡Ea, nos vemos!$"

MatchCall_PersonalizedText35::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "Ahora mismo voy en bici.\p"
	.string "Me encanta nadar y correr,\n"
	.string "¡pero lo que más me gusta es la bici!\p"
	.string "Siento que todo mi cuerpo se funde\n"
	.string "con el viento.\p"
	.string "¡Me emociona como si volara!\p"
	.string "¡Vale! ¡Hoy voy a batir un nuevo\n"
	.string "récord en el CAMINO de BICIS!\p"
	.string "¡Tú también deberías intentarlo!\n"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText36::
	.string "¡Eh, soy {STR_VAR_1}!\n"
	.string "¡Estoy en pleno triatlón!\p"
	.string "¡Pero, oye, para charlar siempre\n"
	.string "saco tiempo!\p"
	.string "¡Entrenarse con POKéMON\n"
	.string "es lo mejor!\p"
	.string "Nos comunicamos sin necesidad\n"
	.string "de hablar, ¡somos uno!\p"
	.string "¡Es una sensación increíble!\p"
	.string "Ufff… Esto de hablar mientras\n"
	.string "corro… Uff, qué paliza…\l"
	.string "Auuuuff… Oye… te… dejo…$"

MatchCall_PersonalizedText37::
	.string "Eh, soy {STR_VAR_1}.\n"
	.string "Si quieres tener más resistencia,\l"
	.string "entrénate a gran altura.\p"
	.string "Intenta correr en lo alto de\n"
	.string "una montaña. Verás cómo machaca.\p"
	.string "¡Oye, te dejo, que me estoy\n"
	.string "quedando sin aire! ¡Adiós!$"

MatchCall_PersonalizedText38::
	.string "Ah, soy {STR_VAR_1}, hola.\p"
	.string "He estado nadando mucho, pero aún no\n"
	.string "consigo llegar a CIUDAD COLOSALIA.\p"
	.string "Tal vez solo voy en círculos.\p"
	.string "No, no, eso no puede ser.\n"
	.string "Jajaja.\l"
	.string "¡Cuídate!$"

MatchCall_PersonalizedText39::
	.string "Eh, soy {STR_VAR_1}…\n"
	.string "¡Ups!\p"
	.string "¡Plas!\p"
	.string "¡Glu-glu-glu-glu!\p"
	.string "¡Plof!\p"
	.string "¡Fiu-fiu! ¡Fiu-fiu!\p"
	.string "¡Eh! ¡Perdona!\n"
	.string "Acabo de ponerme bronceador.\p"
	.string "¡Y se me ha resbalado el POKéNAV\n"
	.string "de las manos al agua!\p"
	.string "Pero, vaya, el POKéNAV de DEVON es\n"
	.string "resistente. ¡Sobrevivió al chapuzón!\p"
	.string "Bueno, estoy ocupado tomando el sol,\n"
	.string "así que charlemos otro día.$"

MatchCall_PersonalizedText40::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "De todas las pruebas del triatlón,\n"
	.string "la natación es la mejor.\p"
	.string "Pero, como me quede en remojo\n"
	.string "más tiempo, ¡me voy a poner\l"
	.string "como un garbanzo!\p"
	.string "¡Ay, el triatlón es una prueba de\n"
	.string "fuego para la resistencia física!\l"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText41::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo van tus POKéMON?\p"
	.string "Mis POKéMON DRAGÓN parece\n"
	.string "que están a tope. Hasta pronto.$"

MatchCall_PersonalizedText42::
	.string "Soy {STR_VAR_1}.\p"
	.string "Mi {STR_VAR_2} se ha hecho mucho\n"
	.string "más fuerte desde la última\l"
	.string "vez que nos enfrentamos.\p"
	.string "No voy a volver a perder contigo.\n"
	.string "¡Ya verás la próxima vez!\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText43::
	.string "Habla {STR_VAR_1}.\p"
	.string "He seguido con mis estudios\n"
	.string "sobre el arte de esconderse.\p"
	.string "Pero he tenido demasiado éxito.\n"
	.string "Nadie ha podido encontrarme.\l"
	.string "¡Mi éxito me deja solo…\p"
	.string "¡Desaparezco como el humo!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText44::
	.string "Soy {STR_VAR_1}.\n"
	.string "He seguido entrenando mucho\l"
	.string "desde que nos encontramos.\p"
	.string "Mi {STR_VAR_2} se ha hecho\n"
	.string "muy fuerte.\p"
	.string "Lo de entrenar en la playa\n"
	.string "funciona como pensaba. ¡Chao!$"

MatchCall_PersonalizedText45::
	.string "¿Cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me gustaría saber cuándo pararán\n"
	.string "de caer estas cenizas volcánicas…\p"
	.string "Si siguen así, van a tapar\n"
	.string "el dibujo de mi parasol…\p"
	.string "¡Oye, tenemos que vernos otra vez!$"

MatchCall_PersonalizedText46::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "¿Sabías que es más fácil flotar\n"
	.string "en el mar que en una piscina?\p"
	.string "Te quedas quieta y tu cuerpo\n"
	.string "flota solo.\p"
	.string "Pero no estés flotando mucho\n"
	.string "tiempo, no vaya a ser que te\l"
	.string "arrastre la corriente mar adentro.\p"
	.string "A todo esto, ¿dónde estoy?…\n"
	.string "¡Será mejor que me largue!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, ¡hola!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Estoy en las montañas.\p"
	.string "El suelo es demasiado irregular.\n"
	.string "No sé si podré poner la tienda…\p"
	.string "Oh, ¡qué buena idea!\p"
	.string "¡A lo mejor puedo hacer que\n"
	.string "mi POKéMON allane el terreno!\p"
	.string "¡Voy a probar!\n"
	.string "¡Chao!$"

MatchCall_PersonalizedText48::
	.string "¡Ah, hola, hola, soy {STR_VAR_1}!\p"
	.string "¡Estoy criando POKéMON con MAR!\n"
	.string "¡Nos esforzamos mucho!\p"
	.string "¡Si nos esforzamos más, ¿podremos ser\n"
	.string "los número uno? ¡Adiós!$"

MatchCall_PersonalizedText49::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Soy un MARINERO, aunque ahora\n"
	.string "no estoy en el mar.\p"
	.string "Eso me hace preguntarme, ¿cómo\n"
	.string "deberían llamarnos a los MARINEROS\l"
	.string "cuando estamos en tierra firme?\p"
	.string "Es lo que pensaba con la mirada\n"
	.string "perdida más allá de las olas…\p"
	.string "¡Hasta otra!$"

MatchCall_PersonalizedText50::
	.string "Al habla {STR_VAR_1}.\n"
	.string "¿Qué? ¿Ya tienes más POKéMON?\p"
	.string "Si atrapas otro POKéMON,\n"
	.string "no te olvides de enseñármelo.\p"
	.string "De verdad que no voy a pedírtelo.\n"
	.string "¡Te estaré esperando!$"

MatchCall_PersonalizedText51::
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estás criando a tus POKéMON\n"
	.string "en condiciones?\p"
	.string "Aquí donde estoy el aire es puro.\n"
	.string "Es el lugar ideal para criar\l"
	.string "POKéMON, créeme.\p"
	.string "Si vas a dedicarte a criar\n"
	.string "POKéMON, deberías venir\l"
	.string "a {STR_VAR_2}. ¡Cuídate!$"

MatchCall_PersonalizedText52::
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "Le di un {POKEBLOCK} a mi {STR_VAR_2}\n"
	.string "y creo que le ha encantado.\p"
	.string "Parece que no a todos los POKéMON\n"
	.string "les gustan los mismos {POKEBLOCK}S.\p"
	.string "Me parece algo fascinante.\n"
	.string "Porfa, cuídate.$"

MatchCall_PersonalizedText53::
	.string "Habla {STR_VAR_1}.\p"
	.string "Si cooperas con los POKéMON, puedes\n"
	.string "sentirte cómodo en la naturaleza.\p"
	.string "Todos deberían darse cuenta y\n"
	.string "cooperar más con los POKéMON.\p"
	.string "Sería lo ideal. De verdad lo creo.\p"
	.string "¡Creo que vas por buen camino! ¡Hasta\n"
	.string "luego!$"

MatchCall_PersonalizedText54::
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Ya sabes, ¡la ENTRENADORA\l"
	.string "que siempre está preparada!\p"
	.string "{PLAYER}{KUN}, ¿tienes suficientes\n"
	.string "objetos? ¿Están esos POKéMON\l"
	.string "tuyos preparados para la acción?\p"
	.string "Mantener siempre todo a punto\n"
	.string "es el secreto para continuar\l"
	.string "por la buena senda.\p"
	.string "¡Por cierto, voy a comprobar\n"
	.string "mi MOCHILA! ¡No te descuides!$"

MatchCall_PersonalizedText55::
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Por {STR_VAR_2} pasa mucha\n"
	.string "gente y todos los días combato\l"
	.string "contra todo tipo de ENTRENADORES.\p"
	.string "Hoy, por ejemplo, he ganado cinco\n"
	.string "combates y he perdido sólo tres.\p"
	.string "¿Qué tal se te ha dado a ti?\n"
	.string "Me lo cuentas la próxima vez, ¿eh?$"

MatchCall_PersonalizedText56::
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Eso de tener muchos POKéMON BICHO\n"
	.string "me ha dado cierta fama, ya sabes.\p"
	.string "El otro día llevé a la escuela\n"
	.string "los cinco que más me gustan.\p"
	.string "¡Se los enseñé a la chica que\n"
	.string "me gusta y no veas cómo chillaba!\l"
	.string "Ríete, ríete, si quieres.\p"
	.string "¡Yo sólo quería enseñarle lo guays\n"
	.string "que son los POKéMON BICHO!…\p"
	.string "Snif…\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText57::
	.string "¡Ja! ¡Ja! ¡Ja! ¡Ja!\p"
	.string "¡Hola! ¡Soy {STR_VAR_1}! ¡Ja! ¡Ja!\p"
	.string "Intentando charlar…\n"
	.string "Mientras subo…\l"
	.string "Es un ejercicio duro… ¡Ja! ¡Ja!\p"
	.string "¡Uf! ¡Ufff…\n"
	.string "Ahora es más empinado…\l"
	.string "Charlaremos…otro día…\l"
	.string "¡Ja! ¡Ja! ¡Ja!$"

MatchCall_PersonalizedText58::
	.string "¡Ah, hola!\p"
	.string "¡Todavía sigo buscando\n"
	.string "tesoros con LUCI!\p"
	.string "Puede que al final no haya ningún\n"
	.string "tesoro por aquí…\p"
	.string "Pero para mí lo importante\n"
	.string "es poder buscar con LUCI.\p"
	.string "Oh, ¡hola, LUCI!\n"
	.string "¿Po-por qué te has enfadado?\p"
	.string "¡No paso de ti, cariño!\n"
	.string "¡Tú eres la única que me importa!\p"
	.string "{PLAYER}, ¡tengo que dejarte, adiós!$"

MatchCall_PersonalizedText59::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He ido otra vez al GIMNASIO\n"
	.string "de AZULIZA para entrenarme.\p"
	.string "MARCIAL, el LÍDER del GIMNASIO,\n"
	.string "parece ahora más fuerte que antes.\p"
	.string "Creo que se ha fortalecido\n"
	.string "con las embestidas de las olas…\p"
	.string "Pero sigue siendo un tipo genial.\n"
	.string "¡Las mujeres lo adoran!\l"
	.string "Si te digo la verdad, me da envidia.\p"
	.string "Yo me pregunto… ¿Tú crees que\n"
	.string "el JUASPI ese se parece a MARCIAL?\p"
	.string "Ya sabes, todo oloroso y sudoroso,\n"
	.string "siempre en plan chulo con la gente\l"
	.string "y esas cosas.\p"
	.string "Bueno, parece que son mis celos\n"
	.string "los que hablan por mí, ¿verdad?\p"
	.string "Olvida esta conversación,\n"
	.string "¿vale? ¡Hasta otra!$"

MatchCall_PersonalizedText60::
	.string "Es un placer hablar con alguien\n"
	.string "tan joven como tú.\p"
	.string "Seguro que, cuando te hagas mayor,\n"
	.string "seguirán gustándote los POKéMON.\p"
	.string "Por cierto, ¿no te gustaría formar\n"
	.string "una pareja como la nuestra?\p"
	.string "Aunque, claro, {PLAYER}{KUN},\n"
	.string "tú ya cuentas con una relación\l"
	.string "de confianza con tus POKéMON.\p"
	.string "¡Ya sabes perfectamente lo que\n"
	.string "es una relación larga y fructífera!\p"
	.string "¡Ja, ja, ja!\n"
	.string "¡Que no decaiga!$"

MatchCall_PersonalizedText61::
	.string "¡Hola, aquí {STR_VAR_1}!\n"
	.string "¡Acabamos de ganar un combate!\p"
	.string "No solemos ganar, pero ha sido\n"
	.string "contra un NADADOR muy guay.\p"
	.string "¡Mi hermana echaba chispas!\p"
	.string "¡Se hizo la débil para llamar\n"
	.string "la atención!\p"
	.string "Da igual que ganemos o perdamos,\n"
	.string "¡siempre me echa el sermón!\p"
	.string "{PLAYER}{KUN}, ¿por qué no le das\n"
	.string "un toque la próxima vez?\p"
	.string "¡Venga, hasta pronto!$"

MatchCall_PersonalizedText62::
	.string "Soy {STR_VAR_1}, sí.\n"
	.string "Ayer me hice al mar.\p"
	.string "Esperaba descubrir algunas ruinas\n"
	.string "nuevas en un sitio que prometía.\p"
	.string "Pero las olas me devolvían a la\n"
	.string "costa. No había manera, oye.\p"
	.string "Combatiendo tampoco he mejorado…\n"
	.string "Puedes reírte si quieres…,\l"
	.string "pero no pienso rendirme.\p"
	.string "¡Llegará el día en que descubra\n"
	.string "unas ruinas inexploradas!\p"
	.string "¡Eso es todo lo que te digo!\n"
	.string "¡Adiós por ahora!$"

MatchCall_PersonalizedText63::
	.string "¡Ahoy!\n"
	.string "¡Soy yo, {STR_VAR_1}!\l"
	.string "¡Estoy en la RUTA 108!\l"
	.string "¡O sea, donde siempre!\p"
	.string "Hoy me ha pasado nadando\n"
	.string "una NADADORA preciosa.\p"
	.string "¡Así que la he asustado con un grito!\p"
	.string "¡Y me ha lanzado una mirada horrible!\p"
	.string "¡Eso es todo desde la RUTA 108!\n"
	.string "¡Os lo ha contado {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Hoy estoy un pelín ocupada, pero\n"
	.string "supuse que querrías saber que…\l"
	.string "¡He ganado a cinco ENTRENADORES!\p"
	.string "Si sigo así, creo que te voy a ganar\n"
	.string "la próxima vez que nos veamos.\p"
	.string "¡Será un combate digno de ver!\n"
	.string "¡Cuídate hasta ese día!$"

MatchCall_BattleFrontierStreakText1::
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Dicen que te has salido\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Es impresionante!\n"
	.string "¡¿{STR_VAR_3} victorias seguidas?!\l"
	.string "¡Pues sigue, sigue así!$"

MatchCall_BattleFrontierStreakText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "¡Y de tus {STR_VAR_3} victorias\n"
	.string "seguidas en {STR_VAR_2}!\p"
	.string "¡Guau! ¡A ver si me animo algún día!\n"
	.string "¡Cuídate!$"

MatchCall_BattleFrontierStreakText3::
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Ya me han dicho que estás\n"
	.string "creando escuela en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡{STR_VAR_3} victorias seguidas!…\n"
	.string "Menudo récord, ¿no?\p"
	.string "¡A ver cuándo me acerco por ahí!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Será mejor que me aplique!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText5::
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} ganaste\n"
	.string "{STR_VAR_3} veces seguidas?…\p"
	.string "¡Me lo estás poniendo difícil!\n"
	.string "¡Ya nos veremos!$"

MatchCall_BattleFrontierStreakText6::
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen por ahí que has\n"
	.string "ganado {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}…\p"
	.string "¡Será mejor que me ponga las pilas!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText7::
	.string "Esto…, ¿{PLAYER}{KUN}?\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "Dicen que has estado en ese sitio\n"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "Y que ganaste {STR_VAR_3} veces seguidas…\p"
	.string "¡Anda, un POKéMON muy raro!\n"
	.string "¡Te dejo! ¡Me tengo que ir!$"

MatchCall_BattleFrontierStreakText8::
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "¡Eh, ahora que lo pienso, dicen\n"
	.string "que ganaste {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Eso no se oye todos los días!\n"
	.string "¡A ver si me esfuerzo un poco más!$"

MatchCall_BattleFrontierStreakText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡{STR_VAR_3} victorias seguidas en ese\l"
	.string "sitio llamado {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleFrontierStreakText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en ese lugar espantoso\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "¡Menuda carrera que llevas!\n"
	.string "¿Cuántas veces podría ganar yo?…$"

MatchCall_BattleFrontierStreakText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "Me han hablado de ti, y de cómo\n"
	.string "lograste {STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleFrontierStreakText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Me han dicho que ganaste {STR_VAR_3}\n"
	.string "combates seguidos\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleFrontierStreakText14::
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡He oído hablar de ti!\n"
	.string "¿No has ganado {STR_VAR_3} combates\l"
	.string "seguidos en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Adiós!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Dicen que te has salido\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Es impresionante!\n"
	.string "¡¿{STR_VAR_3} victorias seguidas?!\l"
	.string "¡Pues sigue, sigue así!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "¡Y de tus {STR_VAR_3} victorias\n"
	.string "seguidas en {STR_VAR_2}!\p"
	.string "¡Guau! ¡A ver si me animo algún día!\n"
	.string "¡Cuídate!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Ya me han dicho que estás\n"
	.string "creando escuela en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡{STR_VAR_3} victorias seguidas!…\n"
	.string "Menudo récord, ¿no?\p"
	.string "¡A ver cuándo me acerco por ahí!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Será mejor que me aplique!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} ganaste\n"
	.string "{STR_VAR_3} veces seguidas?…\p"
	.string "¡Me lo estás poniendo difícil!\n"
	.string "¡Ya nos veremos!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen por ahí que has\n"
	.string "ganado {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}…\p"
	.string "¡Será mejor que me ponga las pilas!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "Esto…, ¿{PLAYER}{KUN}?\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "Dicen que has estado en ese sitio\n"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "Y que ganaste {STR_VAR_3} veces seguidas…\p"
	.string "¡Anda, un POKéMON muy raro!\n"
	.string "¡Te dejo! ¡Me tengo que ir!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "¡Eh, ahora que lo pienso, dicen que\n"
	.string "ganaste {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Eso no se oye todos los días!\n"
	.string "¡A ver si me esfuerzo un poco más!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡{STR_VAR_3} victorias seguidas en ese\l"
	.string "sitio llamado {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en ese lugar espantoso\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "¡Menuda carrera que llevas!\n"
	.string "¿Cuántas veces podría ganar yo?…$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "Me han hablado de ti, y de cómo\n"
	.string "lograste {STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Me han dicho que ganaste {STR_VAR_3}\n"
	.string "combates seguidos\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡He oído hablar de ti!\p"
	.string "¿No has ganado {STR_VAR_3} combates\n"
	.string "seguidos en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Adiós!$"

MatchCall_BattleDomeText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Has logrado el campeonato\n"
	.string "de {STR_VAR_2} nada menos\l"
	.string "que {STR_VAR_3} veces!\p"
	.string "¡Alucinante! ¡Ya me sacas ventaja!\n"
	.string "¡Hasta pronto!$"

MatchCall_BattleDomeText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Me han hablado de ti!\p"
	.string "Dicen que has ganado {STR_VAR_3} títulos\n"
	.string "en ese horror al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "¡Impresionante! No sé si yo\n"
	.string "tendré valor para tanto…$"

MatchCall_BattleDomeText3::
	.string "¡Eh, hola, {PLAYER}!\n"
	.string "Te habla {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¡Dicen que ya has ganado\n"
	.string "{STR_VAR_3} eventos en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡Venga, a por otro!\n"
	.string "¡Nos veremos pronto!$"

MatchCall_BattleDomeText4::
	.string "Eh, {PLAYER}{KUN}. Habla {STR_VAR_1}.\p"
	.string "He oído que te has proclamado\n"
	.string "campeón en {STR_VAR_2} {STR_VAR_3}\l"
	.string "veces.\p"
	.string "Parece que te esfuerzas mucho.\n"
	.string "¡Intentaré seguirte el ritmo!$"

MatchCall_BattleDomeText5::
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "He oído que has ganado\n"
	.string "{STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleDomeText6::
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, he oído que ya tienes\n"
	.string "{STR_VAR_3} campeonatos de ese lugar\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "POKéMON o te me vas a escapar!$"

MatchCall_BattleDomeText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} has\n"
	.string "ganado {STR_VAR_3} campeonatos?\p"
	.string "Estupendo. Por cierto, ¿has pillado\n"
	.string "últimamente algún POKéMON raro?\p"
	.string "Ah, vale.\n"
	.string "Muy bien, adiós.$"

MatchCall_BattleDomeText8::
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que ya tienes {STR_VAR_3} títulos\n"
	.string "de {STR_VAR_2} en el bolsillo.\p"
	.string "A ver si me pongo a entrenar ya.\n"
	.string "¡Nos veremos!$"

MatchCall_BattleDomeText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me han contado lo de tus {STR_VAR_3}\n"
	.string "campeonatos en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "Me pregunto si alguna vez podré\n"
	.string "llegar a ser yo el campeón…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattleDomeText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Que has ganado {STR_VAR_3} eventos en un\n"
	.string "lugar llamado {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleDomeText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has ganado {STR_VAR_3} eventos\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleDomeText14::
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¿Es verdad lo de tus {STR_VAR_3}\n"
	.string "títulos en {STR_VAR_2}?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattlePikeText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Impresionante!\n"
	.string "¡Hasta luego!$"

MatchCall_BattlePikeText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "Dicen que has logrado pasar\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}.\p"
	.string "¡Voy a tener que esforzarme!\n"
	.string "¡Adiós!$"

MatchCall_BattlePikeText3::
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}. \l"
	.string "¿Cómo te va?\p"
	.string "¡He oído que has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}!\p"
	.string "¡Mucha suerte para la próxima vez!\n"
	.string "¡Y a ver si nos vemos!$"

MatchCall_BattlePikeText4::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen por ahí que has pasado {STR_VAR_3}\n"
	.string "salas en {STR_VAR_2}.\p"
	.string "¡Será mejor que me ponga yo\n"
	.string "también a entrenar en serio!$"

MatchCall_BattlePikeText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me han dicho que has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText6::
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, corre el rumor\n"
	.string "de que has pasado {STR_VAR_3} salas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "POKéMON o te me vas a escapar!$"

MatchCall_BattlePikeText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo? ¿Que has estado\n"
	.string "en {STR_VAR_2} y has pasado\l"
	.string "{STR_VAR_3} salas?\p"
	.string "¡Eso mola un montón!\p"
	.string "¡Anda, un POKéMON muy raro!\n"
	.string "¡Te dejo!$"

MatchCall_BattlePikeText8::
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}.\p"
	.string "¡Es impresionante!\n"
	.string "A ver si me pongo a entrenar ya.\l"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡Que te has pasado {STR_VAR_3}\l"
	.string "salas en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattlePikeText10::
	.string "Eh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de {STR_VAR_2}.\p"
	.string "¿Cuántas salas van ya? ¿{STR_VAR_3}?\n"
	.string "Guau, eso no se oye todos los días.\p"
	.string "Me pregunto si yo podría pasar\n"
	.string "todas las salas…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePikeText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Que te has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattlePikeText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattlePikeText14::
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¿De verdad te has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattlePyramidText1::
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "Has subido {STR_VAR_3} niveles\n"
	.string "dentro de {STR_VAR_2}, ¿eh?\p"
	.string "¡A-lu-ci-nan-te!\n"
	.string "¡Debería probar yo!$"

MatchCall_BattlePyramidText2::
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "Dicen que has conseguido subir\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Genial!\n"
	.string "¡A ver si espabilo!$"

MatchCall_BattlePyramidText3::
	.string "¡Eh, hola, {PLAYER}!\n"
	.string "Te habla {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "Conque ya has subido {STR_VAR_3} niveles\n"
	.string "en {STR_VAR_2}, ¿eh?\p"
	.string "¡Venga, a ver si puedes superarte!\n"
	.string "¡Y a ver si nos vemos!$"

MatchCall_BattlePyramidText4::
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Al habla {STR_VAR_1}.\p"
	.string "He oído que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Espero que no sea demasiado\n"
	.string "tarde para alcanzarte!$"

MatchCall_BattlePyramidText5::
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me han dicho que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText6::
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "POKéMON o te me vas a escapar!$"

MatchCall_BattlePyramidText7::
	.string "¿{PLAYER}{KUN}?\n"
	.string "Habla {STR_VAR_1}.\p"
	.string "¿Estuviste en {STR_VAR_2}\n"
	.string "y subiste {STR_VAR_3} plantas ganando?\p"
	.string "Qué bien. ¿Había algún POKéMON\n"
	.string "raro allí?\p"
	.string "¿No, eh?\n"
	.string "Vale, adiós.$"

MatchCall_BattlePyramidText8::
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Es impresionante!\n"
	.string "A ver si me pongo a entrenar ya.\l"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText9::
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han contado!\n"
	.string "¡Que has subido {STR_VAR_3} niveles\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattlePyramidText10::
	.string "Eh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que has subido {STR_VAR_3}\n"
	.string "niveles en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de {STR_VAR_2}.\p"
	.string "¿Cuántos niveles van ya? ¿{STR_VAR_3}?\n"
	.string "Guau, eso no se oye todos los días.\p"
	.string "Me preguntaba si podría llegar\n"
	.string "yo alguna vez arriba del todo…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePyramidText12::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Es verdad que has subido\n"
	.string "{STR_VAR_3} niveles en un lugar\l"
	.string "llamado {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattlePyramidText13::
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has subido {STR_VAR_3} niveles\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattlePyramidText14::
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡He oído hablar de ti!\p"
	.string "¿No has superado {STR_VAR_3} plantas\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Eres una inspiración!\n"
	.string "¡Hasta la próxima!$"

MatchCall_Text_Mom1::
	.string "MAMÁ: Tu padre y tú… Todos estáis\n"
	.string "fascinados por los POKéMON.\p"
	.string "¿Cuál es el encanto de los POKéMON?\p"
	.string "¿Yo? Adoro a los POKéMON que me\n"
	.string "ayudan con las tareas de cada día.$"

MatchCall_Text_Mom2::
	.string "MAMÁ: ¡Hola, {PLAYER}!\n"
	.string "Tu padre sigue encerrado\l"
	.string "en el GIMNASIO de PETALIA.\p"
	.string "Viene a casa de vez en cuando,\n"
	.string "pero para darse una comilona e\l"
	.string "irse volando de nuevo al GIMNASIO.\p"
	.string "Este hombre…, desde que le ganaste\n"
	.string "tiene el orgullo por los suelos.$"

MatchCall_Text_Mom3::
	.string "MAMÁ: {PLAYER}…\n"
	.string "No te preocupes por mí\l"
	.string "ni por la casa.\p"
	.string "Y no te quites las DEPORTIVAS\n"
	.string "hasta que no se te rompan, cariño.$"

MatchCall_Text_Baoba1::
	.string "BAOBA: ¡{PLAYER}!\n"
	.string "¡La ZONA SAFARI está casi lista!\p"
	.string "¡Serás el primero al que llame\n"
	.string "cuando esté terminada!$"

MatchCall_Text_Baoba2::
	.string "BAOBA: ¡{PLAYER}!\n"
	.string "¡La ZONA SAFARI ya está abierta!\p"
	.string "¡Ven cuando quieras!$"

MatchCall_Text_Roxanne1::
	.string "PETRA: ¡Anda, hola, {PLAYER}!\p"
	.string "Desde que nos vimos,\n"
	.string "no he dejado de entrenarme.\p"
	.string "Aún voy a tardar en poner\n"
	.string "el GIMNASIO a punto.\p"
	.string "Pero, cuando esté listo,\n"
	.string "¡ven a verme para luchar otra vez!$"

MatchCall_Text_Roxanne2::
	.string "PETRA: ¿{PLAYER}, eres tú?\n"
	.string "¡Enhorabuena!\l"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¿Yo? No, aún voy a tardar en poner\n"
	.string "el GIMNASIO a punto.\p"
	.string "Pero, cuando esté listo,\n"
	.string "¡ven a verme para luchar otra vez!$"

MatchCall_Text_Roxanne3::
	.string "PETRA: ¡{PLAYER}!\n"
	.string "¡Ya está listo mi GIMNASIO!\p"
	.string "¡A ver cuándo puedes venirte\n"
	.string "por CIUDAD FÉRRICA!$"

MatchCall_Text_Roxanne4::
	.string "PETRA: {PLAYER}, en el GIMNASIO\n"
	.string "de CIUDAD FÉRRICA, luchar\l"
	.string "es una cuestión de orgullo.$"

MatchCall_Text_Brawly1::
	.string "MARCIAL: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "He aprendido mucho de nuestro\n"
	.string "combate.\p"
	.string "Quiero prepararme antes de volver\n"
	.string "a poner el GIMNASIO en marcha.\p"
	.string "Voy a tardar en recuperar\n"
	.string "fuerzas para llevar el GIMNASIO.\p"
	.string "Pero, si consigo organizarlo\n"
	.string "todo bien, me gustaría luchar\l"
	.string "contigo de nuevo.$"

MatchCall_Text_Brawly2::
	.string "MARCIAL: ¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Enhorabuena!\p"
	.string "¡No dejan de llegar noticias sobre\n"
	.string "tus éxitos!\p"
	.string "Me parece a mí que me hace falta\n"
	.string "entrenarme mucho más.\p"
	.string "Voy a tardar en recuperar\n"
	.string "fuerzas para llevar el GIMNASIO.\p"
	.string "Pero, si consigo organizarlo\n"
	.string "todo bien, me gustaría luchar\l"
	.string "contigo de nuevo.$"

MatchCall_Text_Brawly3::
	.string "MARCIAL: ¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Mi GIMNASIO está como nunca!\p"
	.string "¡A ver si te acercas por AZULIZA\n"
	.string "y luchamos un rato!$"

MatchCall_Text_Brawly4::
	.string "MARCIAL: {PLAYER}{KUN}, no creo que\n"
	.string "me aburra nunca de luchar contigo.$"

MatchCall_Text_Wattson1::
	.string "ERICO: ¡Anda, eres tú!\p"
	.string "Cuando te marchaste, reciclé\n"
	.string "mi sistema de entrenamiento.\p"
	.string "Voy a tomarme mi tiempo antes\n"
	.string "de seguir con el GIMNASIO.\p"
	.string "¡Así que ya te avisaré!\n"
	.string "¡Je, je, je, je!$"

MatchCall_Text_Wattson2::
	.string "ERICO: ¡Jua, jua, jua, jua!\p"
	.string "¡Lo has conseguido de verdad!\n"
	.string "¡Me han llegado noticias tuyas!\p"
	.string "Parece que aún tengo que seguir\n"
	.string "entrenando.\p"
	.string "Diría que necesito un poquito más\n"
	.string "de tiempo para reabrir mi GIMNASIO.\p"
	.string "¡Tendrás que esperar hasta entonces!\n"
	.string "¡Jua, jua, jua, jua!$"

MatchCall_Text_Wattson3::
	.string "ERICO: ¡Eh, oye!\n"
	.string "¡El GIMNASIO ya está!\p"
	.string "¡Vente a MALVALONA cuando\n"
	.string "quieras! ¡Ja, ja, ja, ja!$"

MatchCall_Text_Wattson4::
	.string "ERICO: ¡Ja, ja, ja, ja!\p"
	.string "¡Luchar contigo resulta siempre\n"
	.string "electrizante!$"

MatchCall_Text_Flannery1::
	.string "CANDELA: {PLAYER}…\p"
	.string "Cuando luchamos, me di cuenta\n"
	.string "de lo mucho que me queda\l"
	.string "por aprender.\p"
	.string "Y aún me falta…\p"
	.string "Debo entrenarme de otra forma\n"
	.string "para poder estar al frente\l"
	.string "del GIMNASIO.\p"
	.string "Espero, {PLAYER}, que volvamos\n"
	.string "a enfrentarnos cuando esté lista.$"

MatchCall_Text_Flannery2::
	.string "CANDELA: Hola, ¿{PLAYER}?\n"
	.string "¡Enhorabuena!\p"
	.string "¡La noticia de tu éxito nos ha llegado\n"
	.string "como el calor de un volcán!\p"
	.string "Nuestro entrenamiento avanza muy\n"
	.string "bien por aquí.\p"
	.string "Cuando el GIMNASIO esté listo,\n"
	.string "aparecerá una marca junto a mi nombre\n"
	.string "en la lista de la AGENDA.$"

MatchCall_Text_Flannery3::
	.string "CANDELA: Eh, ¿{PLAYER}?\n"
	.string "¡Ya está listo el GIMNASIO!\p"
	.string "¡Pásate por LAVACALDA para darte\n"
	.string "un bañito en los baños termales\l"
	.string "y combatir conmigo!$"

MatchCall_Text_Flannery4::
	.string "CANDELA: {PLAYER}…\n"
	.string "Estoy convencida de que cada vez\l"
	.string "vas a entrenar mejor.$"

MatchCall_Text_Winona1::
	.string "ALANA: ¡Hola, {PLAYER}!\p"
	.string "Gracias a nuestro combate,\n"
	.string "he podido ver mis puntos débiles.\p"
	.string "Cuando vuelva a estar lista para\n"
	.string "el GIMNASIO, ¡no darás con ellos!$"

MatchCall_Text_Winona2::
	.string "ALANA: ¡Muy bien, {PLAYER}!\p"
	.string "¡Las noticias sobre tu victoria\n"
	.string "en la LIGA POKéMON han llegado\l"
	.string "volando a CIUDAD ARBORADA!\p"
	.string "Pero… la próxima vez que luchemos,\n"
	.string "no creo que salgas tan bien…$"

MatchCall_Text_Winona3::
	.string "ALANA: ¿Eres {PLAYER}?\n"
	.string "¡Nuestro GIMNASIO está en marcha!\p"
	.string "¡Te esperamos en CIUDAD ARBORADA!$"

MatchCall_Text_Winona4::
	.string "ALANA: {PLAYER}…\n"
	.string "A mí no se me caen las alas\l"
	.string "por perder…\p"
	.string "Exacto, como tú tampoco pierdes\n"
	.string "de vista tus sueños.$"

MatchCall_Text_TateLiza1::
	.string "VITO: ¡Anda, es…!\n"
	.string "LETI: ¡{PLAYER}!\p"
	.string "VITO: Estamos entrenándonos\n"
	.string "de nuevo…\l"
	.string "LETI: ¡Para darlo todo\l"
	.string "en el GIMNASIO!\p"
	.string "VITO: Cuando estemos listos…\n"
	.string "LETI: Cuando estemos listos…\p"
	.string "VITO: Aparecerá una marca junto\n"
	.string "a nuestro nombre…\l"
	.string "LETI: En tu AGENDA del MÓVIL.$"

MatchCall_Text_TateLiza2::
	.string "VITO: ¡{PLAYER}, enhorabuena!\n"
	.string "LETI: ¡{PLAYER}, enhorabuena!\p"
	.string "VITO: Aún estamos…\n"
	.string "LETI: ¡Aún estamos entrenándonos!\p"
	.string "VITO: Pero todavía nos falta…\n"
	.string "LETI: Cuando estemos listos…\p"
	.string "VITO: Aparecerá una marca junto\n"
	.string "a nuestro nombre…\l"
	.string "LETI: En tu AGENDA del MÓVIL.$"

MatchCall_Text_TateLiza3::
	.string "VITO: ¡{PLAYER}!\n"
	.string "LETI: ¡{PLAYER}!\p"
	.string "VITO: ¡El GIMNASIO ya está!\n"
	.string "LETI: ¡El GIMNASIO ya está!\p"
	.string "VITO: Podrías venir a vernos…\n"
	.string "LETI: ¡Te esperamos en ALGARIA!$"

MatchCall_Text_TateLiza4::
	.string "VITO: {PLAYER}, nuestro combate…\n"
	.string "LETI: Es una experiencia sin igual.\p"
	.string "VITO: No estaría mal…\n"
	.string "LETI: ¡Que lucháramos de nuevo!$"

MatchCall_Text_Juan1::
	.string "GALANO: Mmm…\n"
	.string "Te llamabas {PLAYER}{KUN}, ¿no?\p"
	.string "Nuestro combate…\n"
	.string "Me recordó a la primera vez\l"
	.string "que me enfrenté con PLUBIO.\p"
	.string "¡A ver si va a resultar que eres\n"
	.string "mejor que PLUBIO!$"

MatchCall_Text_Juan2::
	.string "GALANO: Je, je… {PLAYER}{KUN}…\n"
	.string "Por fin has logrado lo que querías.\p"
	.string "Yo sabía que tenía buen ojo para\n"
	.string "las promesas como tú…\p"
	.string "Luchemos de nuevo. Estás en\n"
	.string "lo más en lo que a posibilidades\l"
	.string "y prestigio se refiere.$"

MatchCall_Text_Juan3::
	.string "GALANO: Eh, je, je… {PLAYER}{KUN}…\p"
	.string "El GIMNASIO de ARRECÍPOLIS\n"
	.string "está a tu disposición.\p"
	.string "Si quieres que nos veamos,\n"
	.string "aquí estoy.$"

MatchCall_Text_Juan4::
	.string "GALANO: {PLAYER}{KUN}…\p"
	.string "Como la buena música, nuestros\n"
	.string "combates resuenan en mí como\l"
	.string "auténtica fuente de inspiración…\p"
	.string "Cuando cierro los ojos, te veo\n"
	.string "componer tu estrategia marcando\l"
	.string "un ritmo ineludible…$"

MatchCall_Text_Sidney::
	.string "SIXTO: ¡Eh, {PLAYER}!\p"
	.string "Si quieres luchar conmigo\n"
	.string "de nuevo, vuelve cuando quieras\l"
	.string "a la LIGA POKéMON.\p"
	.string "¡De aquí no me muevo!\n"
	.string "¡Aquí te espero!$"

MatchCall_Text_Phoebe::
	.string "FÁTIMA: ¡Hola, {PLAYER}!\p"
	.string "¿Qué tal si vuelves por aquí\n"
	.string "algún día?\p"
	.string "Me gustaría ver cuánto se ha\n"
	.string "fortalecido el vínculo con tus\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "NÍVEA: Hola, {PLAYER}.\p"
	.string "Imagino que aún querrás\n"
	.string "aumentar tu fuerza.\p"
	.string "Pues, si te apetece, podríamos\n"
	.string "vernos en la LIGA POKéMON\l"
	.string "para templar los ánimos un poco…$"

MatchCall_Text_Drake::
	.string "DRACÓN: Tu voz me suena…\n"
	.string "Eres {PLAYER}, ¿no?\l"
	.string "Se te oye muy alegre…\p"
	.string "Tengo entendido que hay un sitio\n"
	.string "llamado FRENTE de BATALLA\l"
	.string "en el que se pone a prueba\l"
	.string "a algunos ENTRENADORES.\p"
	.string "Con todo, si quieres combates\n"
	.string "de verdad, ¡ya sabes cómo es\l"
	.string "la LIGA POKéMON!\p"
	.string "¿O no, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "PLUBIO: Hola, {PLAYER}{KUN}.\n"
	.string "¿Has visto ya a MÁXIMO?\p"
	.string "La verdad es que es…\n"
	.string "es un hacha.\p"
	.string "Pero va un poco a su aire,\n"
	.string "no suele combatir mucho.\p"
	.string "Prefiere buscar piedras raras\n"
	.string "por ahí.\p"
	.string "Seguro que está ahora mismo\n"
	.string "cavando en alguna cueva o en algún\l"
	.string "monte escarpado.\p"
	.string "Y a todo esto, ¿una piedra rara\n"
	.string "qué es lo que es?\l"
	.string "Como no sea un METEORITO…$"

MatchCall_Text_MayRayquazaCall:
	.string "¡Bip!\p"
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¡Hace poco he estado en OROMAR!\p"
	.string "Allí vi un POKéMON verde y enorme\n"
	.string "surcando el cielo.\p"
	.string "Oye…\n"
	.string "¡Nunca había visto nada parecido!\p"
	.string "¿Quién sabe? ¡Podría ser\n"
	.string "un gran descubrimiento!\p"
	.string "¡Clic!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "¡Bip!\p"
	.string "BRUNO: ¡Hola, {PLAYER}!\p"
	.string "¡Hace poco he estado en OROMAR!\p"
	.string "Allí vi un POKéMON verde y enorme\n"
	.string "surcando el cielo.\p"
	.string "¡Nunca había visto nada parecido!\p"
	.string "Ojalá lo hubieras visto tú,\n"
	.string "{PLAYER}.\p"
	.string "¡Clic!$"

MatchCall_Text_May1::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "El SR. ARENQUE se ha retirado\n"
	.string "de MARINERO, pero a veces lo veo\l"
	.string "en el mar con su mascota, PEEKO.\p"
	.string "¡Debe de echarlo mucho de menos!$"

MatchCall_Text_May2::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Sabes que PETALIA y AZULIZA\n"
	.string "tienen GIMNASIO, ¿verdad?\p"
	.string "Pero no sé por qué, en el puerto de\n"
	.string "CIUDAD PORTUAL no hay ninguno.\p"
	.string "Creo que cuando construyan allí\n"
	.string "un GIMNASIO, me voy a presentar\l"
	.string "para el puesto de LÍDER.$"

MatchCall_Text_May3::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Te acuerdas de un hombre llamado\n"
	.string "el CORTADOR, en CIUDAD FÉRRICA?\l"
	.string "Tenía allí una casa, ¿recuerdas?\p"
	.string "Pues descubrí que su hermano menor\n"
	.string "vive en MALVALONA.\p"
	.string "¿Adivinas cómo se llama?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "¡El tipo de GOLPE ROCA!$"

MatchCall_Text_May4::
	.string "AURA: ¿{PLAYER}{KUN}?\p"
	.string "TÚNEL FERVERGAL…\n"
	.string "Le pusieron ese nombre porque une\l"
	.string "CIUDAD FÉRRICA y VERDEGAL.$"

MatchCall_Text_May5::
	.string "AURA: {PLAYER}{KUN}, ¿qué tal estás?\p"
	.string "Ahora estoy en la RUTA 111.\p"
	.string "Voy a descansar en casa de una\n"
	.string "abuelita.\p"
	.string "Vive justo al norte\n"
	.string "del desierto.$"

MatchCall_Text_May6::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Has oído hablar de la TORRE\n"
	.string "ESPEJISMO que hay en el desierto?\p"
	.string "Dicen que, como los espejismos,\n"
	.string "aparece y desaparece…\p"
	.string "Ojalá pueda verla.$"

MatchCall_Text_May7::
	.string "AURA: ¡{PLAYER}{KUN}, hola!\n"
	.string "Ahora estoy en la RUTA 119.\p"
	.string "Hay un río enorme y, encima, \n"
	.string "a veces llueve mucho.\p"
	.string "¡Me he empapado!$"

MatchCall_Text_May8::
	.string "AURA: {PLAYER}{KUN}, hola.\p"
	.string "El MONTE PÍRICO es un monumento en\n"
	.string "recuerdo de los POKéMON que ya no\l"
	.string "están físicamente entre nosotros.\p"
	.string "¡Quizás por eso está infestado\n"
	.string "de POKéMON de tipo FANTASMA!$"

MatchCall_Text_May9::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Estaba pensando en acercarme a\n"
	.string "los baños termales de LAVACALDA.\p"
	.string "Pero cerca del DESFILADERO\n"
	.string "me he encontrado con unos\l"
	.string "tipos raros. ¡No te lo recomiendo!$"

MatchCall_Text_May10::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿Has oído la última?\p"
	.string "Dicen que el CAPITÁN BABOR\n"
	.string "descubrió la CAVERNA ABISAL en una\l"
	.string "de sus expediciones submarinas.$"

MatchCall_Text_May11::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿No te parece fantástico?…\p"
	.string "Aunque no tengas barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "el movimiento de un POKéMON.\p"
	.string "¡Pero es que aún hay más!\p"
	.string "¡Hay otro movimiento que te\n"
	.string "permite viajar por el fondo del mar!$"

MatchCall_Text_May12::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\n"
	.string "Espero que todo vaya bien.\p"
	.string "Cuando estuviste en el mar,\n"
	.string "¿pudiste pasar al lado que estaba\l"
	.string "bloqueado?\p"
	.string "Intenta sumergirte bajo el agua\n"
	.string "y sigue a lo largo de las simas.\p"
	.string "Cuando llegues al otro lado,\n"
	.string "vuelve a la superficie. ¡Es fácil!$"

MatchCall_Text_May13::
	.string "AURA: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Cómo va eso?\n"
	.string "¿Estás llenando tu POKéDEX?\p"
	.string "He oído el rumor de que hay\n"
	.string "POKéMON antiguos por ahí.\l"
	.string "¡Y que hay tres ejemplares!\p"
	.string "¡Lo que daría por ver uno!…$"

MatchCall_Text_May14::
	.string "AURA: ¡{PLAYER}{KUN}!\n"
	.string "¡He oído los rumores que corren!\p"
	.string "¿De verdad has vencido al LÍDER\n"
	.string "del GIMNASIO de ARRECÍPOLIS?\p"
	.string "Eso significa que ya\n"
	.string "te queda poco, ¿no?$"

MatchCall_Text_May15::
	.string "AURA: ¡Ya no hay ni un solo\n"
	.string "ENTRENADOR en HOENN que no\l"
	.string "sepa quién eres, {PLAYER}{KUN}!\p"
	.string "Cuando le digo a la gente\n"
	.string "que soy tu amiga, {PLAYER}{KUN},\l"
	.string "¡no veas qué cara ponen!$"

MatchCall_Text_Brendan1::
	.string "BRUNO: ¡Eh, {PLAYER}!\p"
	.string "El SR. ARENQUE se retiró como marinero,\n"
	.string "pero aún lo veo a veces en el mar\l"
	.string "con su PEEKO.\p"
	.string "Supongo que sigue amando\n"
	.string "el mar.$"

MatchCall_Text_Brendan2::
	.string "BRUNO: ¡Eh, {PLAYER}!\p"
	.string "Sabes que PETALIA y AZULIZA\n"
	.string "tienen GIMNASIO, ¿verdad?\p"
	.string "Pero no sé por qué, en el puerto de\n"
	.string "CIUDAD PORTUAL no hay ninguno.\p"
	.string "Creo que cuando construyan allí\n"
	.string "un GIMNASIO, me voy a presentar\l"
	.string "para el puesto de LÍDER.$"

MatchCall_Text_Brendan3::
	.string "BRUNO: ¡Eh, {PLAYER}!\p"
	.string "¿Te acuerdas de un tipo llamado\n"
	.string "el CORTADOR, en CIUDAD FÉRRICA?\l"
	.string "Tenía allí una casa, ¿verdad?\p"
	.string "Pues resulta que su hermano pequeño\n"
	.string "vive en MALVALONA.\p"
	.string "¿Adivinas cómo se llama?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "¡El tipo de GOLPE ROCA!$"

MatchCall_Text_Brendan4::
	.string "BRUNO: Esa voz… ¿{PLAYER}?\p"
	.string "El nombre de TÚNEL FERVERGAL\n"
	.string "se lo pusieron porque une\l"
	.string "CIUDAD FÉRRICA y VERDEGAL.\p"
	.string "¿Lo sabías?$"

MatchCall_Text_Brendan5::
	.string "BRUNO: {PLAYER}, ¿qué hay?\p"
	.string "Eh, estoy en la RUTA 111 ahora.\p"
	.string "Voy a descansar en casa de una\n"
	.string "abuelita al norte del desierto.\p"
	.string "Si andas por la zona, deberías\n"
	.string "visitarla tú también.$"

MatchCall_Text_Brendan6::
	.string "BRUNO: ¡Eh, {PLAYER}!\p"
	.string "¿Has oído hablar de la TORRE\n"
	.string "ESPEJISMO que hay en el desierto?\p"
	.string "Dicen que, como los espejismos,\n"
	.string "aparece y desaparece…\p"
	.string "¡Ojalá pueda verla!$"

MatchCall_Text_Brendan7::
	.string "BRUNO: ¿Quién es? Eh, ¿{PLAYER}?\n"
	.string "Ahora estoy en la RUTA 119.\p"
	.string "Hay un río enorme y, encima, \n"
	.string "a veces llueve mucho.\p"
	.string "¡Estoy calado hasta los huesos!$"

MatchCall_Text_Brendan8::
	.string "BRUNO: ¡{PLAYER}!\p"
	.string "El MONTE PÍRICO es un monumento en\n"
	.string "recuerdo de los POKéMON que ya no\l"
	.string "están físicamente entre nosotros.\p"
	.string "¡Quizás por eso está infestado\n"
	.string "de POKéMON de tipo FANTASMA!$"

MatchCall_Text_Brendan9::
	.string "BRUNO: ¿Qué hay, {PLAYER}?\p"
	.string "Iba camino de los baños\n"
	.string "termales de LAVACALDA.\p"
	.string "Pero cerca del DESFILADERO\n"
	.string "me he encontrado con unos\l"
	.string "tipos con cara de pocos amigos. \p"
	.string "Menudos broncas…\n"
	.string "¡Creo que era el EQUIPO MAGMA!$"

MatchCall_Text_Brendan10::
	.string "BRUNO: ¡Hola, {PLAYER}!\n"
	.string "¿Has oído las últimas noticias?\p"
	.string "Dicen que el CAPITÁN BABOR\n"
	.string "descubrió la CAVERNA ABISAL en una\l"
	.string "de sus expediciones submarinas.$"

MatchCall_Text_Brendan11::
	.string "BRUNO: ¡Eh, {PLAYER}!\n"
	.string "¿No te parece alucinante?…\p"
	.string "Aunque no tengas barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "el movimiento de un POKéMON.\p"
	.string "¡Y hay otro movimiento que te\n"
	.string "permite viajar por el fondo del mar!\p"
	.string "¡Oye, estos POKéMON hacen de todo!$"

MatchCall_Text_Brendan12::
	.string "BRUNO: ¡Ey, {PLAYER}!\n"
	.string "¿Qué tal te va?\p"
	.string "¿Has dado con algún camino que\n"
	.string "conecte con la zona bloqueada?\p"
	.string "Intenta sumergirte bajo el agua\n"
	.string "y sigue a lo largo de las simas.\p"
	.string "Cuando llegues al otro lado, vuelve\n"
	.string "a la superficie. ¡Está chupado!$"

MatchCall_Text_Brendan13::
	.string "BRUNO: ¡Eh, {PLAYER}!\p"
	.string "¿Cómo va eso?\n"
	.string "¿Estás llenando tu POKéDEX?\p"
	.string "He oído el rumor de que hay\n"
	.string "POKéMON antiguos por ahí.\l"
	.string "¡Y que hay tres ejemplares!\p"
	.string "¡Lo que daría por ver uno!$"

MatchCall_Text_Brendan14::
	.string "BRUNO: ¡{PLAYER}!\n"
	.string "¡Me han llegado rumores!\p"
	.string "¿Has vencido al LÍDER del GIMNASIO\n"
	.string "de ARRECÍPOLIS? ¡Genial!\p"
	.string "¡Ya te queda muy poco!$"

MatchCall_Text_Brendan15::
	.string "BRUNO: ¡Ya no hay ni un solo\n"
	.string "ENTRENADOR en HOENN que\l"
	.string "no sepa quién eres, {PLAYER}!\p"
	.string "Cuando le digo a la gente\n"
	.string "que soy tu amigo, {PLAYER},\l"
	.string "¡no veas qué cara de envidia ponen!$"

MatchCall_Text_Wally1::
	.string "BLASCO: ¡Hola, {PLAYER}!\p"
	.string "Cada vez estoy más en forma\n"
	.string "tanto física como mentalmente.\p"
	.string "¡Espero convertirme pronto en un\n"
	.string "ENTRENADOR como tú, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "BLASCO: ¡{PLAYER}, hola!\p"
	.string "Cuando acabaron el TÚNEL\n"
	.string "FERVERGAL, CLARA se puso\l"
	.string "contentísima.$"

MatchCall_Text_Wally3::
	.string "BLASCO: ¡Oh, {PLAYER}!\p"
	.string "Yo… me fui de casa de mi tío en\n"
	.string "VERDEGAL sin avisar a nadie.\p"
	.string "Me pregunto si estará furioso conmigo…\p"
	.string "{PLAYER}, tú entiendes cómo me siento,\n"
	.string "¿verdad?$"

MatchCall_Text_Wally4::
	.string "BLASCO: ¿{PLAYER}?\n"
	.string "¡Soy yo, BLASCO!\p"
	.string "¡El mundo de los ENTRENADORES es\n"
	.string "asombroso!\p"
	.string "¡Cuando llevo mis POKéMON conmigo,\n"
	.string "mucha gente me saluda!\p"
	.string "¡Es como si todos se conectaran\n"
	.string "a través de los POKéMON!$"

MatchCall_Text_Wally5::
	.string "BLASCO: ¿{PLAYER}? ¡Es increíble!\n"
	.string "¿Ese RALTS que capturamos juntos?\l"
	.string "¡Ha evolucionado, {PLAYER}!\p"
	.string "Quizá tengo talento…\p"
	.string "¡Pero no debería creérmelo tanto!\p"
	.string "Al fin y al cabo, ¡a quienes hay que\n"
	.string "alabar es a los POKéMON!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "BLASCO parece estar fuera del\n"
	.string "área de servicio del POKéNAV…$"

MatchCall_Text_Wally7::
	.string "BLASCO: ¡Hola, {PLAYER}!\p"
	.string "Antes de conocerte, apenas\n"
	.string "había salido de casa…\p"
	.string "Y ahora, voy yo solito con mis\n"
	.string "propios POKéMON en busca\l"
	.string "de aventura…\p"
	.string "{PLAYER}…\n"
	.string "Gracias…$"

MatchCall_Text_Scott1::
	.string "TRETO: ¡Eh, {PLAYER}{KUN}!\p"
	.string "¿Que sabes encontrar POKéMON\n"
	.string "en cualquier sitio?\p"
	.string "En la montaña, en el mar, entre la\n"
	.string "hierba alta, ¿en cualquier sitio?\p"
	.string "¡Yo encuentro ENTRENADORES\n"
	.string "en cualquier sitio también!\p"
	.string "Así que te dejo, que voy a buscar\n"
	.string "más. ¡Hala, hala, adiós!$"

MatchCall_Text_Scott2::
	.string "TRETO: Estoy en la RUTA 119.\n"
	.string "¡Está llena de ENTRENADORES!\p"
	.string "Y creo que hay zonas\n"
	.string "de hierba alta por todos lados.\p"
	.string "¡Como voy con pantalón corto,\n"
	.string "me hace unas cosquillas!$"

MatchCall_Text_Scott3::
	.string "TRETO: ¡Oye, {PLAYER}{KUN}!\p"
	.string "¿Has tenido ocasión de subir \n"
	.string "al MONTE PÍRICO?\p"
	.string "Es un monumento natural a\n"
	.string "los POKéMON que nos han dejado.\p"
	.string "Un sitio al que todo ENTRENADOR\n"
	.string "debería subir al menos una vez.$"

MatchCall_Text_Scott4::
	.string "TRETO: ¡Hola, {PLAYER}{KUN}!\p"
	.string "He oído hablar de esas bandas\n"
	.string "extrañas que dan problemas.\p"
	.string "El EQUIPO MAGMA y el EQUIPO AQUA,\n"
	.string "creo que eran.\p"
	.string "Pensaría que habría algunos\n"
	.string "ENTRENADORES hábiles entre ellos.\p"
	.string "…Pero si son unos matones…$"

MatchCall_Text_Scott5::
	.string "TRETO: Eh, hola, {PLAYER}{KUN}.\p"
	.string "¿Habrá buenos ENTRENADORES\n"
	.string "en el fondo del mar?\p"
	.string "Yo no puedo ir a comprobarlo.\n"
	.string "Para empezar, porque no sé nadar.\l"
	.string "Además, yo no crío POKéMON…$"

MatchCall_Text_Scott6::
	.string "TRETO: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "¿Sabías que puedes participar en\n"
	.string "la LIGA POKéMON cuando consigas\l"
	.string "todas las MEDALLAS de GIMNASIO?\p"
	.string "Con tu talento, ganar la LIGA\n"
	.string "va a resultarte pan comido.\p"
	.string "Pero ¿sabes qué es lo mejor\n"
	.string "de todo?\p"
	.string "Bueno, no hay una sola cosa, pero\n"
	.string "no voy a decirte más de momento.\p"
	.string "Lo genial es…, no te lo pierdas,\n"
	.string "lo genial es que…\p"
	.string "¡Cuando ganas la LIGA POKéMON,\n"
	.string "pasas a formar parte\l"
	.string "del HALL de la FAMA!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TRETO parece estar fuera del\n"
	.string "área de servicio del POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPÁ: En CIUDAD FÉRRICA\n"
	.string "hay un señor al que de toda la vida\l"
	.string "han llamado CORTADOR.\p"
	.string "Si estás por la zona,\n"
	.string "podrías hacerle una visita.$"

MatchCall_Text_Norman2::
	.string "PAPÁ: Mm… Te estás haciendo\n"
	.string "cada vez más fuerte, {PLAYER}.\l"
	.string "Muy bien, despacito y buena letra.\p"
	.string "Cuanto más fuerte seas, más lejos\n"
	.string "estarás de MAMÁ y de mí.\l"
	.string "Cada vez estarás más fuera\l"
	.string "del cascarón…\p"
	.string "Es difícil de explicar, cariño.$"

MatchCall_Text_Norman3::
	.string "PAPÁ: Interesante…\n"
	.string "Ya has conseguido 4 MEDALLAS\l"
	.string "de GIMNASIO…\p"
	.string "Ahora no me puedo negar.\n"
	.string "Lucharemos como te dije.\p"
	.string "Ven cuando quieras.\n"
	.string "¡Estoy esperándote!$"

MatchCall_Text_Norman4::
	.string "PAPÁ: ¡{PLAYER}, deberías ir a ver\n"
	.string "a MAMÁ de vez en cuando!\p"
	.string "Voy a quedarme aquí para reforzar\n"
	.string "mi entrenamiento.\p"
	.string "¡No hay más remedio que seguir\n"
	.string "aprendiendo, aunque cueste!$"

MatchCall_Text_Norman5::
	.string "PAPÁ: ¡Eh, hola, {PLAYER}!\p"
	.string "¿Cómo? ¿El SIGNO MAGMA?\n"
	.string "No sé lo que es.\p"
	.string "Pero con ese nombre, debe de tener\n"
	.string "relación con algún volcán.$"

MatchCall_Text_Norman6::
	.string "PAPÁ: ¡Yiiia! ¡Uuuuaaa! ¡Aaaaj!\p"
	.string "¿Mm?… ¡¡{PLAYER}!!\p"
	.string "¡Me has pillado en plena sesión\n"
	.string "de entrenamiento POKéMON!$"

MatchCall_Text_Norman7::
	.string "PAPÁ: ¡{PLAYER}!\p"
	.string "Quién me iba a decir\n"
	.string "que conseguirías ganar\l"
	.string "la LIGA POKéMON…\p"
	.string "¡Pues yo no me pienso\n"
	.string "quedar atrás!$"

MatchCall_Text_Norman8::
	.string "PAPÁ: ¿Mm? ¿{PLAYER}?\n"
	.string "¡Qué sincronización!\p"
	.string "En esta ocasión, te reto\n"
	.string "a luchar conmigo.\p"
	.string "Te espero en el GIMNASIO\n"
	.string "de PETALIA. ¡Ven cuando quieras!$"

MatchCall_Text_Norman9::
	.string "PAPÁ: Uff… Me impresionas,\n"
	.string "{PLAYER}.\l"
	.string "¿Vas a llegar mucho más lejos?$"

MatchCall_Text_Steven1::
	.string "MÁXIMO: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Has estado ya en MALVALONA?\p"
	.string "¡Deberías visitar la TIENDA de BICIS\n"
	.string "y conseguir una BICI CARRERA.\p"
	.string "Luego, intenta explorar a fondo la\n"
	.string "CUEVA GRANITO.\p"
	.string "Quizá hagas algún descubrimiento\n"
	.string "allí.$"

MatchCall_Text_Steven2::
	.string "MÁXIMO: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Ya he conocido a un montón\n"
	.string "de ENTRENADORES.\p"
	.string "Pero tú… Lo tuyo es increíble.\n"
	.string "Eres de lo que no hay.$"

MatchCall_Text_Steven3::
	.string "MÁXIMO: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Cuando vives una aventura con\n"
	.string "tus POKéMON, ¿qué piensas?\p"
	.string "¿Los consideras compañeros\n"
	.string "fuertes?\p"
	.string "¿Los ves como compañeros de\n"
	.string "diversión?\p"
	.string "Según lo que pienses, el\n"
	.string "significado de tu aventura cambia.$"

MatchCall_Text_Steven4::
	.string "MÁXIMO: ¿Hola?\n"
	.string "¿{PLAYER}{KUN}?\p"
	.string "En estos momentos tenemos un lío\n"
	.string "tremendo en el CENTRO ESPACIAL.\p"
	.string "Lo siento, pero no me puedo\n"
	.string "entretener. ¡Hasta luego!$"

MatchCall_Text_Steven5::
	.string "MÁXIMO: ¡Anda!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "No tenemos nada de qué hablar.\n"
	.string "No necesitas que te diga nada.\p"
	.string "Tienes que confiar en ti y hacer\n"
	.string "lo que consideres correcto.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "MÁXIMO parece no recibir\n"
	.string "la llamada…$"

MatchCall_Text_Steven7::
	.string "MÁXIMO: {PLAYER}{KUN}… Enhorabuena\n"
	.string "por entrar en el HALL de la FAMA.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "¡Espero que volvamos a vernos\n"
	.string "en algún sitio!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. ABEDUL: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Me han hablado mucho sobre ti!\p"
	.string "Así que le han puesto AGENDA\n"
	.string "de MÓVIL a tu POKéNAV…\p"
	.string "¡Pues yo me quiero registrar\n"
	.string "también!\p"
	.string "Así, podré echar un ojo a tu\n"
	.string "POKéDEX hasta cuando estés\l"
	.string "por ahí.\p"
	.string "(…)$"

MatchCall_Text_RegisteredBirch:
	.string "Acabas de registrar al PROF.\n"
	.string "ABEDUL en el POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. ABEDUL: Cuando uno tiene la\n"
	.string "POKéDEX y el POKéNAV, estudiar\l"
	.string "POKéMON es más divertido, ¿eh?$"

MatchCall_Text_MrStone1::
	.string "SR. PEÑAS: ¿Sí? ¡{PLAYER}{KUN}!\p"
	.string "¡Anda, te recibo perfectamente,\n"
	.string "el POKéNAV funciona!\p"
	.string "Habrá quienes se registren,\n"
	.string "¡vas a poder llamar a mucha gente!\p"
	.string "¡Qué cara de felicidad!\n"
	.string "¡Se te ve radiante!\p"
	.string "Mm…\n"
	.string "¿Que cómo lo sé?\p"
	.string "¡Pues porque te estoy viendo desde\n"
	.string "la ventana de mi despacho!\p"
	.string "¡Ja, ja, ja, ja!\n"
	.string "¡Nos vemos!$"

MatchCall_Text_MrStone2::
	.string "SR. PEÑAS: ¿Sí? ¡{PLAYER}{KUN}!\p"
	.string "¿Qué ocurre? ¿Ya no te acuerdas\n"
	.string "del pequeño encargo que te hice?\p"
	.string "Te pedí que fueras a AZULIZA\n"
	.string "a llevarle mi carta a MÁXIMO.\p"
	.string "Y que, después, fueras a CIUDAD\n"
	.string "PORTUAL a entregarle el paquete\l"
	.string "al CAP. BABOR.\p"
	.string "Te acuerdas, ¿no?\p"
	.string "Bueno, pues te dejo, que como\n"
	.string "PRESIDENTE tengo mucho que\l"
	.string "hacer. ¡Adiós!$"

MatchCall_Text_MrStone3::
	.string "SR. PEÑAS: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Ah, así que ya has visto a MÁXIMO.\n"
	.string "¡Pues te mereces un regalo!\p"
	.string "Cuando vengas por CIUDAD FÉRRICA\n"
	.string "otra vez, ven a verme a mi oficina.\p"
	.string "¡Aquí te espero!$"

MatchCall_Text_MrStone4::
	.string "SR. PEÑAS: ¡Oh! ¡{PLAYER}{KUN}!\p"
	.string "¿Sabías que DEVON estaba excavando\n"
	.string "el TÚNEL FERVERGAL?\p"
	.string "Pero cerramos la obra para proteger a\n"
	.string "los POKéMON de la zona.\p"
	.string "Es de cajón, la verdad.\p"
	.string "Es más importante dejar que los\n"
	.string "POKéMON vivan en paz que\l"
	.string "preocuparnos por nuestra propia\l"
	.string "comodidad.$"

MatchCall_Text_MrStone5::
	.string "SR. PEÑAS: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "¡Alguien de PETALIA me ha dicho\n"
	.string "que NORMAN es tu padre!\p"
	.string "¡Así no me extraña que tengas\n"
	.string "la capacidad que tienes!$"

MatchCall_Text_MrStone6::
	.string "SR. PEÑAS: ¿Cómo?\p"
	.string "¿Qué te has enfrentado a tu padre\n"
	.string "y le has ganado?\p"
	.string "¡Esto es ya la repanocha!\p"
	.string "¡No tenía ni idea de que contara\n"
	.string "con amigos tan fuera de lo común!\l"
	.string "¡Ja, ja, ja, ja!$"

MatchCall_Text_MrStone7::
	.string "¡Hola!\n"
	.string "Esto es DEVO…\l"
	.string "¡Oh, hola, {PLAYER}!\p"
	.string "Nuestro PRESIDENTE estaba aquí\n"
	.string "hace un momento, pero se ha ido.\p"
	.string "Nuestro PRESIDENTE está muy\n"
	.string "ocupado, pero tú también lo estás,\l"
	.string "¿no, {PLAYER}?$"

MatchCall_Text_MrStone8::
	.string "Mmm… ¿Cómo?…\p"
	.string "GROU… ¿Cómo? ¿…DON?\p"
	.string "Se entrecorta…\n"
	.string "Eh… no te oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "Mmm… ¿Cómo?…\p"
	.string "CAVERN… ¿Cómo? ¿…BISAL?\p"
	.string "Se entrecorta…\n"
	.string "Eh… no te oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "SR. PEÑAS: ¡{PLAYER}{KUN}! ¡Sí, soy yo!\p"
	.string "Sé que tienes mucho lío, pero yo\n"
	.string "también estoy ocupado ¡y no sé\l"
	.string "exactamente qué tienes que hacer!\p"
	.string "En cualquier caso, elige el camino\n"
	.string "que consideres mejor.\p"
	.string "¡Yo te apoyaré siempre!\n"
	.string "¡Cuídate!$"

MatchCall_Text_MrStone11::
	.string "SR. PEÑAS: Mmm…\n"
	.string "¿{PLAYER}{KUN}? ¿Eres tú?\p"
	.string "Tu voz transmite una seguridad\n"
	.string "aplastante…\l"
	.string "¡No te reconocí al principio!\p"
	.string "¡A ver si te pasas por DEVON\n"
	.string "y nos haces una visita!$"
