MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hola, soy el Recordador de\n"
	.string "Movimientos. ¿Quieres aprender\l"
	.string "movimientos nuevos?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Por nivel$"

MoveRelearner_Text_EggMoves:
	.string "Huevo$"

MoveRelearner_Text_TMMoves:
	.string "MT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Tutor$"

MoveRelearner_Text_SeeYa:
	.string "¡NOS VEMOS!$"

MoveRelearner_Text_AnythingElse:
	.string "¿Puedo hacer algo más por ti?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Elige el POKéMON.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "No tienes POKéMON.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Lo siento… Pero un HUEVO no puede\n"
	.string "aprender movimientos.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Perdona…\p"
	.string "Parece que no puedo enseñar ningún\n"
	.string "movimiento a ese POKéMON…$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "movimiento por nivel$"

MoveRelearner_Text_EggMoveLWR::
	.string "movimiento huevo$"

MoveRelearner_Text_TMMoveLWR::
	.string "movimiento de MT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "movimiento de tutor$"

MoveRelearner_Text_MoveLWR::
	.string "MOVER$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "¿Qué {STR_VAR_3} le enseño?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Gracias por usar nuestros servicios.\n"
	.string "¡Vuelve cuando quieras!$"
