MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "¡Guau! ¡Cómo mola mi POKéMON!\n"
	.string "¡Si es que no hay otro igual!\p"
	.string "Yo iba por ahí imitando ese contoneo\n"
	.string "tan gracioso cuando, de repente,\l"
	.string "me encontré con el PRESIDENTE.\p"
	.string "Se me quitó el contoneo de un plumazo.\p"
	.string "Si quieres, puedo enseñar el movimiento \n"
	.string "CONTONEO a uno de tus POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Pero ¿qué pasa contigo?\n"
	.string "¿No sabes verle el fondo a las formas?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Genial, entonces dime, ¿qué POKéMON\n"
	.string "quieres que aprenda CONTONEO?$"

MoveTutor_Text_SwaggerTaught:
	.string "A partir de ahora, prometo imitar\n"
	.string "a mi POKéMON sin contonearme.$"

MoveTutor_Text_RolloutTeach:
	.string "¡Alguna gente se enrolla y algunos\n"
	.string "POKéMON se desenrollan!\p"
	.string "¿Quieres que uno de tus POKéMON\n"
	.string "aprenda a desenrollarse?\p"
	.string "Le puedo enseñar DESENROLLAR\n"
	.string "a uno si tú quieres.$"

MoveTutor_Text_RolloutDeclined:
	.string "Bueno, desde luego, ¡tú no pareces\n"
	.string "estar entre la gente que se enrolla!$"

MoveTutor_Text_RolloutWhichMon:
	.string "¡Qué buen rollo! Sería genial si además\n"
	.string "eligieras uno que se parezca a mí, ¿eh?$"

MoveTutor_Text_RolloutTaught:
	.string "Listo. ¡A desenrollarse se ha dicho!\n"
	.string "¡Hala!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Hay un movimiento que se hace más\n"
	.string "fuerte al usarlo varias veces seguidas.\p"
	.string "¡Es un movimiento de tipo BICHO \n"
	.string "y mola pero que un montón!\p"
	.string "Se llama CORTEFURIA.\n"
	.string "¿Se lo enseño a uno de tus POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Se ve que no estamos en la misma\n"
	.string "onda.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "¡Me encanta pararme a ver\n"
	.string "cómo aumenta de fuerza con el uso!$"

MoveTutor_MimicTeach:
	.string "¡Ay, qué achaques tengo!\p"
	.string "Soy muy joven, pero me encanta imitar\n"
	.string "la forma de hablar de los mayores\l"
	.string "que hay en este pueblo.\p"
	.string "¿Quieres darme una alegría dejándome\n"
	.string "enseñarle el movimiento MIMÉTICO\l"
	.string "a uno de tus POKéMON?$"

MoveTutor_MimicDeclined:
	.string "¡Qué juventud tan desagradecida! ¡Sólo\n"
	.string "quería enseñar MIMÉTICO a un POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "¡Tjó, tjó! ¿De verdad me dejas?\n"
	.string "¡Dime entonces a qué POKéMON\l"
	.string "quieres que se lo enseñe!$"

MoveTutor_Text_MimicTaught:
	.string "El movimiento MIMÉTICO exige paciencia,\n"
	.string "algo que no soléis tener los jóvenes.\p"
	.string "¿Crees que llegarás a usarlo tan bien\n"
	.string "como yo?…$"

MoveTutor_Text_MetronomeTeach:
	.string "¡Quiero comprar un montón de cosas!\n"
	.string "Pero ya me he gastado mi paga…\p"
	.string "Estaría genial que hubiese una forma\n"
	.string "de, con sólo mover el dedo,\l"
	.string "hacer aparecer monedas, ¿eh?\p"
	.string "Si quieres, puedo enseñar a tu POKéMON\n"
	.string "el movimiento METRÓNOMO.\p"
	.string "Puede que no aparezca ninguna moneda,\n"
	.string "pero tu POKéMON sabrá mover el dedo.\l"
	.string "¿Qué me dices?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Estaré aquí por si cambias de idea.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "Cuando tu POKéMON mueva el dedo\n"
	.string "como un METRÓNOMO, podrá pasar\l"
	.string "cualquier cosa.\p"
	.string "¿A que a ti también te encantaría\n"
	.string "hacerlo?$"

MoveTutor_Text_SleepTalkTeach:
	.string "¡Bah! Mi mujer confía en el PODER\n"
	.string "OCULTO para mantenerse despierta.\p"
	.string "Lo mejor es dar una cabezadita y luego\n"
	.string "andar SONÁMBULO, como hago yo.\p"
	.string "¿Quieres que le enseñe a uno de tus\n"
	.string "POKéMON el movimiento SONÁMBULO?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Vale, vale. Conque tú también prefieres\n"
	.string "PODER OCULTO…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Nunca he acabado de entender el truco\n"
	.string "que hace mi mujer con las monedas.\p"
	.string "Me encantaría pillarlo, aunque fuese\n"
	.string "estando SONÁMBULO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Cuando veo lo grande que es el mundo\n"
	.string "desde lo alto de esta terraza…\p"
	.string "Pienso en lo bonito que sería tener más\n"
	.string "de un “yo” para poder vivir otras vidas.\p"
	.string "Claro que eso es imposible.\n"
	.string "Je, je. Qué tontería…\p"
	.string "¡Pero se me ocurre una cosa!\n"
	.string "¿Quieres que uno de tus POKéMON\l"
	.string "aprenda a usar SUSTITUTO?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, ¿no?\p"
	.string "Tu POKéMON habría podido hacer\n"
	.string "una copia de sí mismo, ¿sabes?$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Je, je…\n"
	.string "¿Qué POKéMON quieres que aprenda\l"
	.string "el movimiento SUSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "¡Nosotros, los humanos, deberíamos\n"
	.string "disfrutar al máximo de nuestras vidas!\p"
	.string "¡Espero que tú sí sepas hacerlo!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "¡No puedo más!\p"
	.string "¡Es totalmente inútil!\p"
	.string "¡Soy un ENTRENADOR de tipo LUCHA\n"
	.string "y por mucho que lo intento no\l"
	.string "puedo ganar en el GIMNASIO!\p"
	.string "¡Arrgh! ¡Puño! ¡Puño! ¡Puño!\n"
	.string "¡Puño! ¡Puño! ¡Puño!\p"
	.string "¡¿Qué?! ¡No me mires así!\n"
	.string "¡Solo golpeo el suelo!\p"
	.string "¿O quieres que enseñe PUÑO DINÁMICO\n"
	.string "a tu POKéMON?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "¡Grr! ¿Me estás tomando el pelo?\n"
	.string "¡Toma! ¡Toma! ¡Toma!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "¿Qué? ¿En serio? ¡Qué bien!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "¡Quiero que ganes en el GIMNASIO de\n"
	.string "CIUDAD CELESTE con ese PUÑO DINÁMICO!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Suspiro…\p"
	.string "El LÍDER del GIMNASIO es realmente\n"
	.string "admirable.\p"
	.string "Pero eso también significa que\n"
	.string "tengo muchos rivales por su atención.\p"
	.string "Tiene un atractivo de doble filo.\n"
	.string "Ni siquiera pude llamar su atención.\p"
	.string "¡Por favor, déjame enseñarle a tu\n"
	.string "POKéMON el movimiento DOBLE FILO!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Hasta tú pasas de mí…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Dicen que el amor nos hace fuertes,\n"
	.string "pero conmigo no funciona…\p"
	.string "Voy a dejar de ser tan enamoradiza\n"
	.string "a ver qué pasa.$"

MoveTutor_Text_ExplosionTeach:
	.string "No voy a llegar a nada si me quedo\n"
	.string "en un pueblucho como éste.\p"
	.string "Pero espera y verás. Voy a irme\n"
	.string "a la capital y me haré famoso.\p"
	.string "¡En serio, lo mío va a ser una\n"
	.string "EXPLOSIÓN de popularidad!\p"
	.string "Bueno, ya puestos, ¡puedo enseñarle\n"
	.string "EXPLOSIÓN a uno de tus POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "¡Bah! Tú también pasas de mí porque\n"
	.string "crees que soy un pueblerino, ¿eh?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "Llevo años enseñando a los POKéMON\n"
	.string "a usar EXPLOSIÓN, pero todavía\l"
	.string "me falta ver la mía…\p"
	.string "Quizás sea porque, en el fondo,\n"
	.string "quiero quedarme aquí…$"

MoveTutor_Text_HeadbuttTeach:
	.string "¿Qué estoy haciendo?\p"
	.string "¡Sacudo árboles con CABEZAZO!\p"
	.string "¿Crees que a tu POKéMON también\n"
	.string "le gustaría dar CABEZAZOS?\p"
	.string "Puedo enseñarle el movimiento\n"
	.string "CABEZAZO si quieres. ¡Es divertido!$"
	
MoveTutor_Text_HeadbuttWhichMon:
	.string "¡Qué buen rollo! Sería genial si además\n"
	.string "eligieras uno que se parezca a mí, ¿eh?$"

MoveTutor_Text_HeadbuttDeclined:
	.string "No tienes que ser tímido.\n"
	.string "¡Vamos a darnos cabezazos!$"

MoveTutor_Text_HeadbuttTaught:
	.string "Rattle trees with HEADBUTT.\n"
	.string "Sometimes, sleeping POKéMON fall out.$"
