gOtherText_NewName::
	.string "NUEVO NOMBRE$"

gNameChoice_Green::
	.string "VERDE$"

gNameChoice_Red::
	.string "ROJO$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FUEGO$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "Se explicarán los botones por orden\n"
	.string "de importancia.$"

gControlsGuide_Text_DPad::
	.string "Mueve al personaje principal.\n"
	.string "También sirve para elegir\n"
	.string "distintas opciones.$"

gControlsGuide_Text_AButton::
	.string "Sirve para confirmar, examinar,\n"
	.string "hablar y avanzar el texto.$"

gControlsGuide_Text_BButton::
	.string "Sirve para salir, cancelar una\n"
	.string "elección y un modo.$"

gControlsGuide_Text_StartButton::
	.string "Pulsa este botón para abrir\n"
	.string "el MENÚ.$"

gControlsGuide_Text_SelectButton::
	.string "Sirve para cambiar objetos y usar\n"
	.string "un objeto registrado.$"

gControlsGuide_Text_LRButtons::
	.string "Si necesitas ayuda para jugar o\n"
	.string "saber cómo hacer algo, pulsa\n"
	.string "el botón L o R.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Ahora dime. ¿Eres un chico?\n"
	.string "¿O eres una chica?$"

gPikachuIntro_Text_Page1::
	.string "En el mundo al que vas a entrar,\n"
	.string "vivirás una gran aventura como\n"
	.string "protagonista.\n"
	.string "\n"
	.string "Habla con la gente y examina todo\n"
	.string "lo que veas, en pueblos, caminos o\n"
	.string "cuevas. Reúne información y pistas\n"
	.string "de todas las fuentes.$"

gPikachuIntro_Text_Page2::
	.string "Se abrirán nuevos caminos si ayudas\n"
	.string "a quien lo necesita, superas retos\n"
	.string "y resuelves misterios.\n"
	.string "\n"
	.string "A veces otros te desafiarán y las\n"
	.string "criaturas salvajes te atacarán.\n"
	.string "Sé valiente y sigue adelante.$"

gPikachuIntro_Text_Page3::
	.string "Durante tu aventura, esperamos que\n"
	.string "trates con todo tipo de personas y\n"
	.string "crezcas como persona.\n"
	.string "Ese es nuestro mayor objetivo.\n"
	.string "\n"
	.string "¡Pulsa el botón A y que comience\n"
	.string "tu aventura!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "¡Hola!\n"
	.string "¡Me alegro de conocerte!\p"
	.string "¡Bienvenido al mundo de los POKéMON!\p"
	.string "Me llamo OAK.\p"
	.string "La gente me conoce cariñosamente\n"
	.string "como el PROFESOR POKéMON.\p"
	.string "$"

gOakSpeech_Text_ThisWorld::
	.string "Este mundo…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…está habitado en todas partes por\n"
	.string "criaturas llamadas POKéMON.\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon::
	.string "Para algunos, los POKéMON son\n"
	.string "mascotas. Otros los usan para luchar.\p"
	.string "En cuanto a mí…\p"
	.string "Estudio a los POKéMON como profesión.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Pero antes, háblame un poco\n"
	.string "de ti.\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Empecemos por tu nombre.\n"
	.string "¿Cómo te llamas?\p"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Bien…\n"
	.string "Así que te llamas {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Este es mi nieto.\p"
	.string "Es tu rival desde que erais\n"
	.string "bebés.\p"
	.string "…Eh, ¿cómo se llamaba?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "El nombre de tu rival, ¿cuál era?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Eh, ¿era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "¡Eso es! ¡Ya me acuerdo!\n"
	.string "¡Se llama {RIVAL}!\p"
	.string "$"

gOakSpeech_Text_LetsGo::
	.string "¡{PLAYER}!\p"
	.string "Tu propia leyenda POKéMON está\n"
	.string "a punto de comenzar.\p"
	.string "¡Te esperan un mundo de sueños y\n"
	.string "aventuras con POKéMON! ¡Vamos!$"
