gText_Oak_Welcome::
	.string "¡Hola! ¡Perdona por hacerte esperar!\p"
	.string "¡Bienvenido al mundo de los POKéMON!\p"
	.string "Me llamo OAK.\p"
	.string "La gente me llama el PROFESOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Esto es lo que llamamos un “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Este mundo está habitado por unas\n"
	.string "criaturas llamadas POKéMON.\p"
	.string "Las personas y los POKéMON viven\n"
	.string "juntos y se ayudan mutuamente.\p"
	.string "Hay quien juega con los POKéMON y hay\n"
	.string "quien lucha con ellos.\p"
	.string "Pero aún no lo sabemos todo sobre los\n"
	.string "POKéMON.\p"
	.string "Todavía quedan muchos misterios por\n"
	.string "resolver. Por eso estudio a los\l"
	.string "POKéMON todos los días.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "¿Tú quién eres?$"

gText_Oak_BoyOrGirl::
	.string "¿Eres un chico? ¿O eres una chica?$"

gText_Oak_WhatChallenge::
	.string "¿Qué desafío quieres afrontar?$"

gText_Oak_ChallengeSelected::
	.string "¡Me parece el nivel de desafío\n"
	.string "adecuado!$"

gText_Oak_WhatsYourName::
	.string "¿Y cómo te llamas?$"

gText_Oak_SoItsPlayer::
	.string "¡Oh! ¿Así que te llamas {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, ¿estás listo?\p"
	.string "Tu propia aventura está a punto de\n"
	.string "comenzar.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Vivirás momentos divertidos y\n"
	.string "desafíos difíciles.\p"
	.string "¡Te espera un mundo de sueños y\n"
	.string "aventuras con los POKéMON! ¡Vamos!\p"
	.string "¡Ya nos veremos!\p"
	.string "$"
