Text_BootUpPC:
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Has accedido al PC de {PLAYER}.\p"
	.string "$"

gText_AccessedLanettesPC::
	.string "Accedió al PC de AREDIA.$"

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"
