Text_BootUpPC:
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accedió al PC de alguien.$"

gText_StorageSystemOpened::
	.string "Acceso al Sistema de Almacenamiento\n"
	.string "de POKéMON concedido.$"

gText_AccessedPlayersPC::
	.string "Has accedido al PC de {PLAYER}.\p"
	.string "$"

gText_AccessedLanettesPC::
	.string "Accedió al PC de AREDIA.$"

gText_AccessedBillsPC::
	.string "Has accedido al PC de BILL.$"
