gBirchDexRatingText_AreYouCurious::
	.string "PROF. ABEDUL: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber cómo llevas\n"
	.string "la POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "¿Mmm? Ah, todavía no has atrapado\n"
	.string "suficientes POKéMON como para que\l"
	.string "merezca la pena.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Mmmm…\p"
	.string "Así que has visto {STR_VAR_1} POKéMON\n"
	.string "y has atrapado {STR_VAR_2} POKéMON.$"

gBirchDexRatingText_LessThan10::
	.string "Deberías ir más a las zonas de\n"
	.string "hierba alta para buscar POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Vas cogiéndole el tranquillo, pero a\n"
	.string "partir de ahora cuesta más…$"

gBirchDexRatingText_LessThan30::
	.string "Algunos POKéMON sólo aparecen en\n"
	.string "ciertas zonas. Tienes que insistir.$"

gBirchDexRatingText_LessThan40::
	.string "Bueno, podría estar más llena, pero\n"
	.string "ya empieza a parecer una POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Esto va sobre ruedas.\n"
	.string "Sigue así.$"

gBirchDexRatingText_LessThan60::
	.string "¿Estás usando CAÑAS?\n"
	.string "Hay muchos POKéMON en el mar…$"

gBirchDexRatingText_LessThan70::
	.string "En vez de limitarte a atrapar\n"
	.string "POKéMON, ¿por qué no los haces\l"
	.string "evolucionar?$"

gBirchDexRatingText_LessThan80::
	.string "Esta POKéDEX va a ser fantástica.\n"
	.string "Lo presiento…$"

gBirchDexRatingText_LessThan90::
	.string "Has atrapado todos éstos…\n"
	.string "¡Tienes buena mano!$"

gBirchDexRatingText_LessThan100::
	.string "¿Has visitado la ZONA SAFARI?\p"
	.string "Dicen que hay algunos POKéMON\n"
	.string "que sólo se pueden atrapar allí.$"

gBirchDexRatingText_LessThan110::
	.string "Por fin has llegado a las 100 especies.\p"
	.string "¡Esta POKéDEX es impresionante!$"

gBirchDexRatingText_LessThan120::
	.string "¿Sabes que se pueden encontrar\n"
	.string "ciertos POKéMON usando\l"
	.string "GOLPE ROCA?$"

gBirchDexRatingText_LessThan130::
	.string "Intercambiar POKéMON con tus\n"
	.string "amigos es una manera fácil de\l"
	.string "conseguir más.$"

gBirchDexRatingText_LessThan140::
	.string "Me han dicho que algunos POKéMON\n"
	.string "evolucionan gracias al amor que\l"
	.string "sienten por sus ENTRENADORES.$"

gBirchDexRatingText_LessThan150::
	.string "No tenía ni idea de que había\n"
	.string "tantas especies de POKéMON en\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "A veces, algunos POKéMON aparecen\n"
	.string "en gran número.\p"
	.string "Es casi como una plaga, pero no hay\n"
	.string "mejor momento para atraparlos.$"

gBirchDexRatingText_LessThan170::
	.string "Mirando tu POKéDEX puedes hacerte\n"
	.string "una buena idea de los POKéMON que\l"
	.string "viven en la región de HOENN.$"

gBirchDexRatingText_LessThan180::
	.string "Yo diría que ya se te puede\n"
	.string "considerar un PROFESOR POKéMON…\l"
	.string "¡y bueno!$"

gBirchDexRatingText_LessThan190::
	.string "¡Con una POKéDEX tan completa, se\n"
	.string "puede decir que eres todo un\l"
	.string "profesional en la materia!$"

gBirchDexRatingText_LessThan200::
	.string "Estás a punto de acabar la\n"
	.string "POKéDEX.\l"
	.string "La cosa se pone emocionante.$"

gBirchDexRatingText_DexCompleted::
	.string "¡Felicidades!\n"
	.string "¡Tu POKéDEX está completa!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Mmmm…\n"
	.string "A escala nacional…\p"
	.string "has visto {STR_VAR_1} POKéMON y\n"
	.string "has atrapado {STR_VAR_2} POKéMON.$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: ¡Me alegro de verte! ¿Qué tal va\n"
	.string "tu POKéDEX?\p"
	.string "A ver, déjame echar un vistazo.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Tu progreso con la POKéDEX es:\p"
	.string "{STR_VAR_1} POKéMON vistos y\n"
	.string "{STR_VAR_2} POKéMON capturados.\p"
	.string "{FONT_NORMAL}Valoración del PROF. OAK:$"

PokedexRating_Text_LessThan10::
	.string "Aún te queda mucho por hacer.\p"
	.string "¡Métete en cada zona de hierba que\n"
	.string "veas y busca POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "¡Parece que vas por buen camino!\p"
	.string "Le he dado a uno de mis AYUDANTES una\n"
	.string "MO de DESTELLO. ¡No te olvides de ir a\l"
	.string "por ella!$"

PokedexRating_Text_LessThan30::
	.string "¡A tu POKéDEX aún le falta un poco de\n"
	.string "volumen!\p"
	.string "¡Intenta atrapar otras especies de\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Bien, ¡se nota que te estás\n"
	.string "esforzando!\p"
	.string "Le he dado a uno de mis AYUDANTES un\n"
	.string "BUSCAOBJETOS. ¡No te olvides de\l"
	.string "recogerlo!$"

PokedexRating_Text_LessThan50::
	.string "¡Tu POKéDEX va bastante bien!\p"
	.string "Le he dado a uno de mis AYUDANTES una\n"
	.string "MONEDA AMULETO. ¡No te olvides de\l"
	.string "recogerla!$"

PokedexRating_Text_LessThan60::
	.string "¡Ah, por fin has superado las 50\n"
	.string "especies!\p"
	.string "Le he dado a uno de mis AYUDANTES un\n"
	.string "REPARTIR EXP. ¡No te olvides de ir a\l"
	.string "por él!$"

PokedexRating_Text_LessThan70::
	.string "¡Jojó! ¡Esta POKéDEX se está\n"
	.string "volviendo de lo más respetable!$"

PokedexRating_Text_LessThan80::
	.string "¡Muy bien!\p"
	.string "¡Creo que si vas a pescar conseguirás\n"
	.string "aún más POKéMON!$"

PokedexRating_Text_LessThan90::
	.string "¡Maravilloso! A ver si lo adivino… Te\n"
	.string "gusta coleccionar cosas, ¿verdad?$"

PokedexRating_Text_LessThan100::
	.string "¡Estoy impresionado! ¡Debe de haber\n"
	.string "sido difícil!$"

PokedexRating_Text_LessThan110::
	.string "¡Por fin has llegado a las 100\n"
	.string "especies! ¡No me creo lo bueno que\l"
	.string "eres!$"

PokedexRating_Text_LessThan120::
	.string "¡Incluso tienes las formas\n"
	.string "evolucionadas de los POKéMON! ¡Genial!$"

PokedexRating_Text_LessThan130::
	.string "¡Excelente! ¡Intercambia con tus\n"
	.string "amigos para conseguir más!$"

PokedexRating_Text_LessThan140::
	.string "¡Extraordinario! ¡Te has convertido en\n"
	.string "todo un profesional!$"

PokedexRating_Text_LessThan150::
	.string "¡No tengo nada más que decir! ¡Ahora\n"
	.string "el PROFESOR POKéMON eres tú!$"

PokedexRating_Text_Complete::
	.string "¡Tu POKéDEX está completa del todo!\n"
	.string "¡¡Enhorabuena!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Y tu POKéDEX NACIONAL tiene:\p"
	.string "{STR_VAR_1} POKéMON vistos y\n"
	.string "{STR_VAR_2} POKéMON capturados.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "¡Tengo muchas ganas de verte\n"
	.string "completar la POKéDEX NACIONAL!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Por fin…\p"
	.string "¡Por fin has completado la POKéDEX!\p"
	.string "¡Es magnífica! ¡Es una hazaña\n"
	.string "realmente fantástica!$"

PokedexRating_Text_Wroooaaarrr::
	.string "¡Groooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "¡Gracias, {PLAYER}! ¡De verdad,\n"
	.string "gracias! ¡Has hecho realidad mi sueño!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: ¡Ah, bienvenido!\p"
	.string "Dime, ¿qué tal va tu POKéDEX?\p"
	.string "¡Juajajá!\p"
	.string "En realidad ya sé cómo va, ¡pero me\n"
	.string "encanta verla de todos modos!\p"
	.string "A ver…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Has encontrado ya la casa del SR.\n"
	.string "POKéMON? Está en la RUTA 30,\p"
	.string "¡no tiene pérdida!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: ¡{PLAYER}{KUN}!\p"
	.string "¡Ven rápido! ¡Ha pasado algo terrible!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber qué tal va tu POKéDEX?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber qué tal va tu POKéDEX\n"
	.string "NACIONAL?$"

gJohtoDexRatingText_LessThan10::
	.string "¡Busca POKéMON en zonas de hierba!$"

gJohtoDexRatingText_LessThan20::
	.string "Bien. Ya veo que sabes cómo usar las\n"
	.string "POKé BALL.$"

gJohtoDexRatingText_LessThan35::
	.string "Lo estás haciendo bien, pero tienes un\n"
	.string "largo camino por recorrer aún.\p"
	.string "$"

gJohtoDexRatingText_LessThan50::
	.string "Por fin estás entrando en ritmo. Esto\n"
	.string "promete.\p"
	.string "$"

gJohtoDexRatingText_LessThan65::
	.string "Ya veo que te estás esforzando.\p"
	.string "Tu POKéDEX empieza a llenarse.$"

gJohtoDexRatingText_LessThan80::
	.string "Los estás entrenando bien. Ya sabes\n"
	.string "que algunos POKéMON no evolucionan\l"
	.string "solo\p"
	.string "luchando contra otros, ¿verdad?$"

gJohtoDexRatingText_LessThan95::
	.string "¿Tienes una caña de pescar? Hay\n"
	.string "POKéMON que solo se pueden\p"
	.string "encontrar pescando.$"

gJohtoDexRatingText_LessThan110::
	.string "¡Excelente! ¡Veo que se te da bien\n"
	.string "coleccionar cosas!\p"
	.string "$"

gJohtoDexRatingText_LessThan125::
	.string "Algunos POKéMON sólo aparecen a\n"
	.string "ciertas horas del día.$"

gJohtoDexRatingText_LessThan140::
	.string "Veo que tienes muchos más POKéMON\n"
	.string "registrados que antes. ¡Así se hace!\p"
	.string "$"

gJohtoDexRatingText_LessThan155::
	.string "¡Impresionante! No sólo atrapas\p"
	.string "POKéMON, también evolucionan.$"

gJohtoDexRatingText_LessThan170::
	.string "Si aprendes a usar bien las POKé BALLS\n"
	.string "especiales que hace CÉSAR,\p"
	.string "¡atraparás POKéMON con más facilidad!$"

gJohtoDexRatingText_LessThan185::
	.string "Cuando intercambias POKéMON, también\n"
	.string "puedes intercambiar información. ¡Tus\p"
	.string "amigos pueden ayudarte mucho!$"

gJohtoDexRatingText_LessThan200::
	.string "¿Estás cambiando tus POKéMON?\p"
	.string "¡Es duro hacerlo en solitario!$"

gJohtoDexRatingText_LessThan215::
	.string "¡Guau! ¡Ya tienes 200! ¡Tu POKéDEX es\n"
	.string "estupenda!\p"
	.string "$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "Has demostrado que eres capaz. No hay\n"
	.string "nada de qué preocuparse.\p"
	.string "Sigue atrapando POKéMON como hasta\n"
	.string "ahora.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Tu POKéDEX va camino de llenarse.\p"
	.string "Esta POKéDEX se puede considerar el\n"
	.string "diario de tu aventura.$"

gJohtoDexRatingText_LessThan260::
	.string "¡Tienes tantos POKéMON! ¡Me has\n"
	.string "ayudado mucho en mis estudios!$"

gJohtoDexRatingText_LessThan275::
	.string "¡Magnífico! ¡Tienes lo necesario para\n"
	.string "convertirte algún día en un gran\p"
	.string "PROFESOR POKéMON!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "¡Tu POKéDEX es increíble!\p"
	.string "¡Eres muy profesional!$"

gJohtoDexRatingText_Complete::
	.string "¡Uau! ¡Esa es una POKéDEX de JOHTO\n"
	.string "completa!\p"
	.string "¡Gracias a ti, {PLAYER}, la POKéDEX de\n"
	.string "JOHTO está completa!\p"
	.string "Uau… ¡Has hecho un trabajo increíble!$"

gNationalDexRatingText_LessThan100::
	.string "Todavía te queda mucho para llegar a\n"
	.string "la meta. ¡No tires la toalla jamás!\p"
	.string "$"

gNationalDexRatingText_LessThan150::
	.string "Ten siempre presente que hay POKéMON\n"
	.string "que solo aparecen a una hora del día\l"
	.string "determinada.\p"
	.string "$"

gNationalDexRatingText_LessThan200::
	.string "¡Si rompes rocas, puede que salgan de\n"
	.string "un salto algunos POKéMON\p"
	.string "que estaban escondidos!$"

gNationalDexRatingText_LessThan250::
	.string "¡Es maravilloso que hayas podido\n"
	.string "reunir tantos POKéMON!\p"
	.string "El camino que tienes por delante es\n"
	.string "largo. ¡Sigue así!$"

gNationalDexRatingText_LessThan300::
	.string "Si usas GOLPE CABEZA para sacudir los\n"
	.string "árboles, a veces cae un POKéMON.\p"
	.string "$"

gNationalDexRatingText_LessThan350::
	.string "A muchos POKéMON que no se\n"
	.string "encuentran en la región de JOHTO les\l"
	.string "gusta reunirse\p"
	.string "en la ZONA SAFARI.$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "Hay lugares ocultos por todo el\n"
	.string "mundo con POKéMON raros\p"
	.string "e inusuales. ¡Intenta\n"
	.string "encontrarlos todos!$"

gNationalDexRatingText_LessThan435::
	.string "No pensé que llegarías hasta aquí.\p"
	.string "$"

gNationalDexRatingText_LessThan465::
	.string "A partir de aquí es el momento de la\n"
	.string "verdad. ¡No te rindas!\p"
	.string "$"

gNationalDexRatingText_LessThan475::
	.string "¡Te falta un pelín! ¡Espero lo máximo\n"
	.string "de ti!\p"
	.string "$"

gNationalDexRatingText_LessThanMaxDex::
	.string "Hasta ahora, nunca había conocido un\n"
	.string "ENTRENADOR tan increíble como tú.\p"
	.string "$"

gNationalDexRatingText_Complete::
	.string "¡Excelente! ¡Es una POKéDEX NACIONAL\n"
	.string "increíble!\p"
	.string "Uau…{PAUSE 10}\p"
	.string "¡Has estado a la altura de mis\n"
	.string "expectativas de maravilla!\p"
	.string "No, las has superado, {PLAYER}. ¡Te has\n"
	.string "convertido en un ENTRENADOR\l"
	.string "increíble!\p"
	.string "¡Gracias, {PLAYER}!$"
