gBirchDexRatingText_AreYouCurious::
	.string "PROF. ABEDUL: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber cómo llevas\n"
	.string "la POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Mmmm…\p"
	.string "Así que has visto {STR_VAR_1} POKéMON\n"
	.string "y has atrapado {STR_VAR_2} POKéMON.$"

gBirchDexRatingText_LessThan10::
	.string "Deberías ir más a las zonas de\n"
	.string "hierba alta para buscar POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Vas cogiéndole el tranquillo, pero a\n"
	.string "partir de ahora cuesta más…$"

gBirchDexRatingText_LessThan30::
	.string "Algunos POKéMON sólo aparecen en\n"
	.string "ciertas zonas. Tienes que insistir.$"

gBirchDexRatingText_LessThan40::
	.string "Bueno, podría estar más llena, pero\n"
	.string "ya empieza a parecer una POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Esto va sobre ruedas.\n"
	.string "Sigue así.$"

gBirchDexRatingText_LessThan60::
	.string "¿Estás usando CAÑAS?\n"
	.string "Hay muchos POKéMON en el mar…$"

gBirchDexRatingText_LessThan70::
	.string "En vez de limitarte a atrapar\n"
	.string "POKéMON, ¿por qué no los haces\l"
	.string "evolucionar?$"

gBirchDexRatingText_LessThan80::
	.string "Esta POKéDEX va a ser fantástica.\n"
	.string "Lo presiento…$"

gBirchDexRatingText_LessThan90::
	.string "Has atrapado todos éstos…\n"
	.string "¡Tienes buena mano!$"

gBirchDexRatingText_LessThan100::
	.string "¿Has visitado la ZONA SAFARI?\p"
	.string "Dicen que hay algunos POKéMON\n"
	.string "que sólo se pueden atrapar allí.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "¿Sabes que se pueden encontrar\n"
	.string "ciertos POKéMON usando\l"
	.string "GOLPE ROCA?$"

gBirchDexRatingText_LessThan130::
	.string "Intercambiar POKéMON con tus\n"
	.string "amigos es una manera fácil de\l"
	.string "conseguir más.$"

gBirchDexRatingText_LessThan140::
	.string "Me han dicho que algunos POKéMON\n"
	.string "evolucionan gracias al amor que\l"
	.string "sienten por sus ENTRENADORES.$"

gBirchDexRatingText_LessThan150::
	.string "No tenía ni idea de que había\n"
	.string "tantas especies de POKéMON en\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "A veces, algunos POKéMON aparecen\n"
	.string "en gran número.\p"
	.string "Es casi como una plaga, pero no hay\n"
	.string "mejor momento para atraparlos.$"

gBirchDexRatingText_LessThan170::
	.string "Mirando tu POKéDEX puedes hacerte\n"
	.string "una buena idea de los POKéMON que\l"
	.string "viven en la región de HOENN.$"

gBirchDexRatingText_LessThan180::
	.string "Yo diría que ya se te puede\n"
	.string "considerar un PROFESOR POKéMON…\l"
	.string "¡y bueno!$"

gBirchDexRatingText_LessThan190::
	.string "¡Con una POKéDEX tan completa, se\n"
	.string "puede decir que eres todo un\l"
	.string "profesional en la materia!$"

gBirchDexRatingText_LessThan200::
	.string "Estás a punto de acabar la\n"
	.string "POKéDEX.\l"
	.string "La cosa se pone emocionante.$"

gBirchDexRatingText_DexCompleted::
	.string "¡Felicidades!\n"
	.string "¡Tu POKéDEX está completa!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Mmmm…\n"
	.string "A escala nacional…\p"
	.string "has visto {STR_VAR_1} POKéMON y\n"
	.string "has atrapado {STR_VAR_2} POKéMON.$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Have you found MR. POKéMON's\n"
	.string "home yet? It is on ROUTE 30,\p"
	.string "you can't miss it!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Get here quick! Something\n"
	.string "awful has happened!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "National POKéDEX is coming along?$"

gJohtoDexRatingText_LessThan10::
	.string "¡Busca POKéMON en zonas de hierba!$"

gJohtoDexRatingText_LessThan20::
	.string "Bien. Ya veo que sabes cómo usar las\n"
	.string "POKé BALL.$"

gJohtoDexRatingText_LessThan35::
	.string "Lo estás haciendo bien, pero tienes un\n"
	.string "largo camino por recorrer aún.\p"
	.string "$"

gJohtoDexRatingText_LessThan50::
	.string "Por fin estás entrando en ritmo. Esto\n"
	.string "promete.\p"
	.string "$"

gJohtoDexRatingText_LessThan65::
	.string "Ya veo que te estás esforzando.\p"
	.string "Tu POKéDEX empieza a llenarse.$"

gJohtoDexRatingText_LessThan80::
	.string "You're training them well. You know\n"
	.string "some POKéMON don't evolve just by\p"
	.string "battling with others, right?$"

gJohtoDexRatingText_LessThan95::
	.string "Do you have a Fishing Rod?\n"
	.string "There are some POKéMON that can\p"
	.string "only be found by fishing!$"

gJohtoDexRatingText_LessThan110::
	.string "¡Excelente! ¡Veo que se te da bien\n"
	.string "coleccionar cosas!\p"
	.string "$"

gJohtoDexRatingText_LessThan125::
	.string "Algunos POKéMON sólo aparecen a\n"
	.string "ciertas horas del día.$"

gJohtoDexRatingText_LessThan140::
	.string "Veo que tienes muchos más POKéMON\n"
	.string "registrados que antes. ¡Así se hace!\p"
	.string "$"

gJohtoDexRatingText_LessThan155::
	.string "¡Impresionante! No sólo atrapas\p"
	.string "POKéMON, también evolucionan.$"

gJohtoDexRatingText_LessThan170::
	.string "If you can learn how to use the\n"
	.string "custom Poké Balls made by Kurt\p"
	.string "effectively, you'll be able to catch\n"
	.string "POKéMON better!$"

gJohtoDexRatingText_LessThan185::
	.string "When you trade POKéMON, you can\n"
	.string "also trade information. Your\p"
	.string "friends can really help you!$"

gJohtoDexRatingText_LessThan200::
	.string "¿Estás cambiando tus POKéMON?\p"
	.string "¡Es duro hacerlo en solitario!$"

gJohtoDexRatingText_LessThan215::
	.string "¡Guau! ¡Ya tienes 200! ¡Tu POKéDEX es\n"
	.string "estupenda!\p"
	.string "$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "You've proven yourself capable.\n"
    .string "There's nothing to worry about.\p"
    .string "Keep catching POKéMON the way\n"
    .string "you've been doing so far.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Your POKéDEX is well on the way to\n"
	.string "being filled up.\p"
	.string "This POKéDEX can be considered a\n"
	.string "journal of your adventure.$"

gJohtoDexRatingText_LessThan260::
	.string "¡Tienes tantos POKéMON! ¡Me has\n"
	.string "ayudado mucho en mis estudios!$"

gJohtoDexRatingText_LessThan275::
	.string "Magnificent! You have the ability\n"
	.string "to become a great POKéMON\p"
	.string "Professor someday!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "¡Tu POKéDEX es increíble!\p"
	.string "¡Eres muy profesional!$"

gJohtoDexRatingText_Complete::
	.string "Wow!\n"
	.string "That is a complete Johto POKéDEX!\p"  
	.string "Thanks to you, {PLAYER}, the Johto\n"
	.string "POKéDEX is complete!\p"
	.string "Wow...\n"
	.string "You've done an incredible job!$"

gNationalDexRatingText_LessThan100::
	.string "Todavía te queda mucho para llegar a\n"
	.string "la meta. ¡No tires la toalla jamás!\p"
	.string "$"

gNationalDexRatingText_LessThan150::
	.string "Ten siempre presente que hay POKéMON\n"
	.string "que solo aparecen a una hora del día\l"
	.string "determinada.\p"
	.string "$"

gNationalDexRatingText_LessThan200::
	.string "If you break rocks, some POKéMON\n"
	.string "that were hiding there might come\p"
	.string "jumping out!$"

gNationalDexRatingText_LessThan250::
	.string "That's wonderful you've been able\n"
	.string "to gather this many POKéMON!\p"
	.string "The path ahead is long. Keep up the\n"
	.string "great work!$"

gNationalDexRatingText_LessThan300::
	.string "Si usas GOLPE CABEZA para sacudir los\n"
	.string "árboles, a veces cae un POKéMON.\p"
	.string "$"

gNationalDexRatingText_LessThan350::
	.string "A lot of POKéMON not found in the\n"
	.string "Johto region like to congregate\p"
	.string "at the Safari Zone$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "There are hidden locations all\n"
	.string "over the world containing rare\p"
	.string "and unusual POKéMON, try to find\n"
	.string "them all!$"

gNationalDexRatingText_LessThan435::
	.string "No pensé que llegarías hasta aquí.\p"
	.string "$"

gNationalDexRatingText_LessThan465::
	.string "A partir de aquí es el momento de la\n"
	.string "verdad. ¡No te rindas!\p"
	.string "$"

gNationalDexRatingText_LessThan475::
	.string "¡Te falta un pelín! ¡Espero lo máximo\n"
	.string "de ti!\p"
	.string "$"

gNationalDexRatingText_LessThanMaxDex::
	.string "Hasta ahora, nunca había conocido un\n"
	.string "ENTRENADOR tan increíble como tú.\p"
	.string "$"

gNationalDexRatingText_Complete::
	.string "Excellent! That is an amazing\n"
	.string "National POKéDEX!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "You've lived up to my\n"
	.string "expectations wonderfully!\p"
	.string "No, you've exceeded them, {PLAYER}.\n"
	.string "You've become an amazing Trainer!\p"
	.string "Thank you, {PLAYER}!$"
