Questionnaire_Text_FillOut::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

Questionnaire_Text_ThankYou::
	.string "Gracias por rellenar el\n"
	.string "cuestionario. Usaremos tus\l"
	.string "respuestas a modo de referencia.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué va el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué van los EVENTOS MISTERIOSOS.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder a los EVENTOS MISTERIOSOS.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Thank you for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "There is a ticket here for you.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "It appears to be for use at\n"
	.string "the LILYCOVE CITY port.\p"
	.string "Why not give it a try and see what\n"
	.string "it is about?$"
