	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡AVISO!\p"
	.string "Ya hay guardada otra partida\n"
	.string "distinta.\p"
	.string "Si guardas ahora, se perderá por\n"
	.string "completo la aventura de la otra\l"
	.string "partida, incluidos los objetos y los\l"
	.string "POKéMON.\p"
	.string "¿Seguro que quieres guardar ahora y\n"
	.string "sobrescribir la otra partida?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Cambia la memoria\n"
	.string "de seguridad.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
