CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "¡Un POKéMATÓN!\p"
	.string "Hazles una foto a los miembros\n"
	.string "de tu equipo POKéMON y decora\p"
	.string "el reverso de tu FICHA\n"
	.string "de ENTRENADOR.\p"
	.string "Sólo cuesta 50¥.\n"
	.string "¿Quieres probar?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "No tengo suficiente dinero...$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "¿Cómo quieres que salga la foto?$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "A ver...\n"
	.string "Una sonrisita para la cámara...\p"
	.string "¡Foto va!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "¡Ya se han revelado las fotos!\n"
	.string "¡Échale un vistazo a tu FICHA\l"
	.string "de ENTRENADOR!$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Je, je... He coleccionado\n"
	.string "un montón de CROMOS. ¡Me gustaría\l"
	.string "que los viera todo el mundo!$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "¡Hola, me alegro de verte por\n"
	.string "aquí! ¡Estupendo, estupendo!\p"
	.string "Mira, mira, ¿ves, ves?\n"
	.string "Éstos son mis CROMOS.\l"
	.string "¡Mira cuántos tengo!\p"
	.string "Sé que quieres alguno.\n"
	.string "Se te nota.\p"
	.string "Te daré un CROMO si me cuentas\n"
	.string "algo sorprendente sobre ti.\p"
	.string "¿Qué me dices?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Vamos a cotillear un poco. Si me\n"
	.string "cuentas algo, te doy un CROMO.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "¡Anda, mira a quién tenemos aquí!\n"
	.string "¡Lo más cotilla de la zona!\p"
	.string "¿De qué vienes a hablarme?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA!\p"
	.string "¡Qué guay!\n"
	.string "Toma, te lo has ganado.$"

FourIsland_House2_Text_WowHoFLow::
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA más de una vez!\p"
	.string "¡Impresionante!\n"
	.string "Toma, te lo has ganado.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA muchas veces!\l"
	.string "¡Es impresionante! \p"
	.string "¡La LIGA POKéMON es tuya!\n"
	.string "Toma, te lo has ganado.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "¡Venga ya! ¿De verdad has entrado\n"
	.string "tantas veces en el HALL de la\l"
	.string "FAMA?\p"
	.string "¡Eres la repera!\n"
	.string "Toma, te lo has ganado a pulso.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "Se ha puesto el CROMO del\n"
	.string "HALL de la FAMA en tu FICHA\l"
	.string "de ENTRENADOR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Anda, ¿hay HUEVOS POKéMON?\n"
	.string "¡No lo sabía!\p"
	.string "¡Qué bueno! ¡Es genial!\n"
	.string "Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowEggsLow::
	.string "¿Has conseguido que se abrieran\n"
	.string "todos esos HUEVOS?\l"
	.string "¡Deben de encantarte!\p"
	.string "¡Me parece alucinante, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "¡Guau, has conseguido que se\n"
	.string "abrieran un montón de HUEVOS!\p"
	.string "¡Eres una máquina con los HUEVOS,\n"
	.string "sí, sí! Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "¡Qué pasada!... ¿De verdad que\n"
	.string "has conseguido que se abrieran\l"
	.string "tantos HUEVOS?\p"
	.string "¡Lo tuyo con los HUEVOS no es\n"
	.string "normal! ¡Qué barbaridad!\p"
	.string "¡Me dejas sin palabras! Toma,\n"
	.string "no tengo más remedio que dártelo.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "Se ha puesto el CROMO de los\n"
	.string "HUEVOS en tu FICHA de ENTRENADOR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oye, te ha ido bien luchando\n"
	.string "con tus amigos, ¿eh?\p"
	.string "¡Eres muy fuerte, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Oye, te ha ido muy bien luchando\n"
	.string "con tus amigos, ¿eh?\p"
	.string "¡Eres realmente fuerte, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Oye, te ha ido más que bien\n"
	.string "luchando con tus amigos, ¿eh?\p"
	.string "¿Y no se han enfadado contigo?\n"
	.string "Toma, anda, te lo mereces.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "¡Alucinante!... ¡Has ganado\n"
	.string "muchísimas veces!\p"
	.string "¡No sé lo que me entra de pensar\n"
	.string "lo fuerte que eres!\p"
	.string "¡Eres invencible! Toma, no tengo\n"
	.string "más remedio que dártelo.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "Se ha puesto el CROMO\n"
	.string "de la VICTORIA en tu FICHA\l"
	.string "de ENTRENADOR.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"
