Route3_Text_ColtonRematchIntro::
	.string "¡Eh!\n"
	.string "¡Te vi en el BOSQUE VERDE!$"

Route3_Text_BenRematchIntro::
	.string "¡Hola! ¡Me encantan los pantalones\n"
	.string "cortos! ¡Son cómodos y fáciles de\l"
	.string "llevar!\p"
	.string "¡Tú también deberías llevar\n"
	.string "pantalones cortos!$"

Route3_Text_JaniceRematchIntro::
	.string "¡Disculpa!\n"
	.string "No dejas de mirarme, ¿verdad?$"

Route3_Text_GregRematchIntro::
	.string "Eres ENTRENADOR, ¿verdad?\n"
	.string "¡Pues vamos al grano!$"

Route3_Text_SallyRematchIntro::
	.string "Esa mirada que me echas…\n"
	.string "¡Me intriga tanto!$"

Route3_Text_CalvinRematchIntro::
	.string "¡Eh! ¿Qué te pasa?\n"
	.string "¡Sigues sin llevar pantalones cortos!$"

Route3_Text_JamesRematchIntro::
	.string "Combatiré contigo con el POKéMON\n"
	.string "que empecé a criar.$"

Route3_Text_RobinRematchIntro::
	.string "¡Ay!\n"
	.string "¿Me has empujado?$"

Route4_Text_CrissyRematchIntro::
	.string "Siempre capturo POKéMON seta\n"
	.string "en el MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "¡Oh! ¡Eres ese niño entrometido que\n"
	.string "nos estuvo espiando!$"

Route6_Text_NancyRematchIntro::
	.string "¡Disculpa! ¿No te dije que esta es\n"
	.string "una conversación privada?\p"
	.string "¡No deberías escuchar a escondidas,\n"
	.string "persona maleducada!$"

Route6_Text_KeigoRematchIntro::
	.string "Estoy buscando algo bueno que no\n"
	.string "sea un POKéMON BICHO, pero…$"

Route6_Text_JeffRematchIntro::
	.string "¿Eh?\n"
	.string "¿Quieres ir conmigo otra vez?$"

Route6_Text_IsabelleRematchIntro::
	.string "¿Yo?\n"
	.string "Bueno, vale. Jugaré esta vez.$"

Route6_Text_ElijahRematchIntro::
	.string "¡Eh, cuánto tiempo!\n"
	.string "¿Has mejorado?$"

Route8_Text_AidanRematchIntro::
	.string "Se te dan bien los POKéMON, pero\n"
	.string "¿qué tal vas en química?$"

Route8_Text_StanRematchIntro::
	.string "¡Muy bien!\n"
	.string "¡Juguemos otra partida!$"

Route8_Text_GlennRematchIntro::
	.string "Hace falta estrategia para ganar\n"
	.string "en los combates.\p"
	.string "¿Estás siguiendo mi consejo?$"

Route8_Text_PaigeRematchIntro::
	.string "He reunido muchos NIDORAN.\n"
	.string "No quiero que evolucionen, pero…$"

Route8_Text_LeslieRematchIntro::
	.string "El colegio es divertido, pero sigo\n"
	.string "pensando que los POKéMON también.$"

Route8_Text_AndreaRematchIntro::
	.string "¡MEOWTH y PERSIAN son tan monos,\n"
	.string "miau, miau, miau!$"

Route8_Text_MeganRematchIntro::
	.string "Quizá parezcamos tontos aquí\n"
	.string "plantados, pero aún puedo combatir.$"

Route8_Text_RichRematchIntro::
	.string "¡Soy un jugador trotamundos!\n"
	.string "¡Llevo una racha de victorias!$"

Route8_Text_JuliaRematchIntro::
	.string "¿Qué POKéMON es mono, redondo\n"
	.string "y esponjoso?\p"
	.string "Ya lo sabes, ¿verdad?$"

Route8_Text_RicardoRematchIntro::
	.string "Mi bici sigue dando problemas, tío.$"

Route8_Text_JarenRematchIntro::
	.string "¡Vale, chaval!\n"
	.string "¡No esperes piedad esta vez!$"

Route8_Text_EliRematchIntro::
	.string "TITA: ¡Nuestro poder de gemelos\n"
	.string "ha mejorado aún más!$"

Route8_Text_AnneRematchIntro::
	.string "LIN: ¡Nuestro poder de gemelas\n"
	.string "se ha reforzado!$"

Route9_Text_AliciaRematchIntro::
	.string "¿Vamos a combatir otra vez?\n"
	.string "¡Esta vez eres mío!$"

Route9_Text_ChrisRematchIntro::
	.string "No he olvidado que ibas con\n"
	.string "esos POKéMON tan guapos.$"

Route9_Text_DrewRematchIntro::
	.string "Voy por el TÚNEL ROCA hacia\n"
	.string "LAVANDA…\p"
	.string "Pero todo el mundo me para\n"
	.string "en el camino…$"

Route9_Text_CaitlinRematchIntro::
	.string "¡No te atrevas a tratarme con\n"
	.string "condescendencia hoy!\n"
	.string "¡Jugamos en serio!$"

Route9_Text_JeremyRematchIntro::
	.string "¡Buajaja!\n"
	.string "¡Genial! ¡Me aburría otra vez, eh!$"

Route9_Text_BriceRematchIntro::
	.string "¡Jajaja!\n"
	.string "¡Un duro pequeñajo, como siempre!$"

Route9_Text_BrentRematchIntro::
	.string "¡Me levantaba temprano todos los\n"
	.string "días para criar a mis POKéMON desde\l"
	.string "capullos!$"

Route9_Text_AlanRematchIntro::
	.string "¡Jajajaja!\n"
	.string "¡Esta vez ganaré yo!$"

Route9_Text_ConnerRematchIntro::
	.string "¡A ganar, mis superPOKéMON BICHO!$"

Route10_Text_MarkRematchIntro::
	.string "Vaya, ¿has vuelto aquí?\n"
	.string "¿Serás POKéMANÍACO tú también?\l"
	.string "¿Quieres ver mi colección?$"

Route10_Text_ClarkRematchIntro::
	.string "¡Ja-jajá-já!\n"
	.string "¡No puedo parar de estornudar!$"

Route10_Text_HermanRematchIntro::
	.string "¡Hola, chaval!\n"
	.string "¿Te enseñé mis POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "Fui a otro GIMNASIO POKéMON.\p"
	.string "…Pero perdí, como siempre.$"

Route10_Text_TrentRematchIntro::
	.string "¡Ah!\n"
	.string "¡Qué delicioso es el aire de montaña!\l"
	.string "¡Es tan bueno que no me puedo ir!$"

Route10_Text_CarolRematchIntro::
	.string "Me empieza a dar vueltas la cabeza.\n"
	.string "Llevo demasiado rato de excursión…$"

Route11_Text_HugoRematchIntro::
	.string "¡Gane, pierda o empate!\n"
	.string "¡Ahora, la revancha!$"

Route11_Text_JasperRematchIntro::
	.string "Competir es la mayor emoción.\n"
	.string "¡Aún no me canso!$"

Route11_Text_EddieRematchIntro::
	.string "Ya lo sabes, ¿verdad?\n"
	.string "Vamos, ¡pero sin hacer trampas!$"

Route11_Text_BraxtonRematchIntro::
	.string "¡Hola!\p"
	.string "¡Pero ten cuidado!\n"
	.string "¡Aún estoy tendiendo cables!$"

Route11_Text_DillonRematchIntro::
	.string "Me hice ENTRENADOR hace poco.\n"
	.string "Pero creo que puedo ganar.$"

Route11_Text_DirkRematchIntro::
	.string "¡Fuajaja!\n"
	.string "¡Nunca he perdido!\p"
	.string "…¡Y si perdí, lo he olvidado!$"

Route11_Text_DarianRematchIntro::
	.string "Nunca he ganado antes…\p"
	.string "Quizá esté destinado a seguir así…$"

Route11_Text_YasuRematchIntro::
	.string "Soy el mejor de mi clase.\n"
	.string "¡Entreno cada mañana y cada noche!$"

Route11_Text_BernieRematchIntro::
	.string "¡Cuidado con los cables con corriente!$"

Route11_Text_DaveRematchIntro::
	.string "Crié a mis POKéMON con cuidado.\n"
	.string "Ya deberían estar listos.\l"
	.string "Esta vez también deberían ganar.$"

Route12_Text_NedRematchIntro::
	.string "¡Sí!\n"
	.string "¡Ha picado algo!\l"
	.string "¡P-podría ser el bueno!$"

Route12_Text_ChipRematchIntro::
	.string "Por fin has llegado.\n"
	.string "Pescar es un juego de espera.$"

Route12_Text_JustinRematchIntro::
	.string "Sigo sin encontrar una PIEDRA LUNAR…\n"
	.string "¿La has encontrado tú?$"

Route12_Text_LucaRematchIntro::
	.string "La electricidad siempre ha sido\n"
	.string "mi especialidad.\p"
	.string "Aunque no sé nada de los POKéMON\n"
	.string "del mar.$"

Route12_Text_HankRematchIntro::
	.string "¡El LOCO de la PESCA contra el\n"
	.string "CHAVAL POKéMON!\l"
	.string "¡Otra ronda, a luchar!$"

Route12_Text_ElliotRematchIntro::
	.string "Me encanta pescar, no me\n"
	.string "malinterpretes. Pero ojalá tuviera más\l"
	.string "trabajo… …¡Es difícil dejar de pescar!$"

Route12_Text_AndrewRematchIntro::
	.string "¿Qué pica?\p"
	.string "¡Nunca lo sabrás si no me ganas!$"

Route12_Text_JesRematchIntro::
	.string "ARE: Hoy ganaré aquí y le\n"
	.string "pediré matrimonio a AGA.$"

Route12_Text_GiaRematchIntro::
	.string "AGA: Eh, ARE…\n"
	.string "Llevo mucho tiempo esperando.\p"
	.string "¡Si ganamos hoy, me casaré contigo!$"

Route13_Text_SebastianRematchIntro::
	.string "¡Mis POKéMON pájaro te recuerdan!$"

Route13_Text_SusieRematchIntro::
	.string "¡Quiero ser la mejor ENTRENADORA\n"
	.string "mientras sea niña!$"

Route13_Text_ValerieRematchIntro::
	.string "¡Guau!\n"
	.string "¡Tienes más MEDALLAS geniales!$"

Route13_Text_GwenRematchIntro::
	.string "Mis POKéMON, que han crecido muy\n"
	.string "lindos, desean reencontrarse contigo.$"

Route13_Text_AlmaRematchIntro::
	.string "Vacié mis ahorros y compré más\n"
	.string "CARBURANTE.$"

Route13_Text_PerryRematchIntro::
	.string "No voy a perder esta vez.\n"
	.string "¡El viento sopla a mi favor!$"

Route13_Text_LolaRematchIntro::
	.string "¿Oh, has vuelto?\p"
	.string "Claro, jugaré otra vez contigo,\n"
	.string "cariño.$"

Route13_Text_SheilaRematchIntro::
	.string "¿No puedes olvidar que combatiste\n"
	.string "conmigo?$"

Route13_Text_JaredRematchIntro::
	.string "¿Qué miras?$"

Route13_Text_RobertRematchIntro::
	.string "Siempre elijo POKéMON pájaro.\n"
	.string "Me he dedicado a ellos.$"

Route14_Text_CarterRematchIntro::
	.string "Usé MTs para enseñar buenos\n"
	.string "movimientos a mis POKéMON.$"

Route14_Text_MitchRematchIntro::
	.string "Mis POKéMON pájaro deberían estar\n"
	.string "listos para combatir esta vez.$"

Route14_Text_BeckRematchIntro::
	.string "¿Usas MTs con tus POKéMON?\n"
	.string "Solo llevarlas encima no sirve de nada.$"

Route14_Text_MarlonRematchIntro::
	.string "¿Has enseñado a tus POKéMON pájaro\n"
	.string "cómo hacer VUELO?\p"
	.string "¡Podrás surcar el cielo con él!\n"
	.string "Pruébalo.$"

Route14_Text_DonaldRematchIntro::
	.string "La leyenda de los espejismos alados…\n"
	.string "¿La has oído, verdad?$"

Route14_Text_BennyRematchIntro::
	.string "La verdad es que no me apetece, pero\n"
	.string "vale. ¡Vamos!$"

Route14_Text_LukasRematchIntro::
	.string "¡Eh!\n"
	.string "¡Me acuerdo de ti!\p"
	.string "¡Venga, venga!\n"
	.string "¡Vamos, vamos, vamos!$"

Route14_Text_IsaacRematchIntro::
	.string "Otra vez aquí, ¿eh?\n"
	.string "Cállate y combate.$"

Route14_Text_GeraldRematchIntro::
	.string "Venimos aquí en bici por los\n"
	.string "espacios abiertos.$"

Route14_Text_MalikRematchIntro::
	.string "¿Combate POKéMON, verdad?\n"
	.string "¡Genial! ¡A rugir!$"

Route14_Text_KiriRematchIntro::
	.string "LENA: TEA, espero que ganemos hoy.$"

Route14_Text_JanRematchIntro::
	.string "TEA: ¡LENA, allá vamos!\n"
	.string "¡Esta vez ganaremos seguro!$"

Route15_Text_KindraRematchIntro::
	.string "Voy a seguir combatiendo con los\n"
	.string "POKéMON que conseguí en intercambios.$"

Route15_Text_BeckyRematchIntro::
	.string "Pareces amable, así que creo que\n"
	.string "puedo ganarte.\p"
	.string "¡Lo intentaré una vez más!$"

Route15_Text_EdwinRematchIntro::
	.string "Cuando silbo, los POKéMON pájaro\n"
	.string "se reúnen a mi alrededor.\p"
	.string "¡Son increíblemente monos!$"

Route15_Text_ChesterRematchIntro::
	.string "¿Mm? ¡Mis pájaros tiemblan!\n"
	.string "Espera, ¿no eres ese ENTRENADOR…?$"

Route15_Text_GraceRematchIntro::
	.string "¡Oh, qué cosita más mona!\n"
	.string "¡Eres como un POKéMON adorable!\l"
	.string "¡Ya me acuerdo de ti!$"

Route15_Text_OliviaRematchIntro::
	.string "Crío POKéMON para protegerme\n"
	.string "porque vivo sola.\p"
	.string "Eso no ha cambiado.$"

Route15_Text_ErnestRematchIntro::
	.string "¡Eh, chaval! ¡Venga!\n"
	.string "¡Los conseguí de un perdedor!$"

Route15_Text_AlexRematchIntro::
	.string "¡Si pierdes contra mí, suelta todo\n"
	.string "tu dinero, chaval!$"

Route15_Text_CeliaRematchIntro::
	.string "¿Qué mola y qué se lleva?\n"
	.string "Intercambiar POKéMON, claro.$"

Route15_Text_YazminRematchIntro::
	.string "¿Quieres jugar otra vez con\n"
	.string "mis POKéMON?$"

Route15_Text_MyaRematchIntro::
	.string "TINA: Hola, siempre nos encontramos,\n"
	.string "¿verdad?\p"
	.string "¿Me ayudas a entrenar otra vez\n"
	.string "a mi hermano pequeño?$"

Route15_Text_RonRematchIntro::
	.string "TIN: Mi hermana se ha vuelto\n"
	.string "más poderosa…$"

Route16_Text_LaoRematchIntro::
	.string "¿Qué quieres?$"

Route16_Text_KojiRematchIntro::
	.string "¡Bonita BICI!\n"
	.string "¡Dámela rápido!$"

Route16_Text_LukeRematchIntro::
	.string "Sal a jugar, ratoncito.\n"
	.string "¡Te trataré bien!$"

Route16_Text_HideoRematchIntro::
	.string "¡Eh, espera un segundo!\n"
	.string "¡No me llames y luego salgas corriendo!$"

Route16_Text_CamronRematchIntro::
	.string "¡Tengo hambre y mal humor!\n"
	.string "¡Necesito un saco de boxeo!$"

Route16_Text_RubenRematchIntro::
	.string "¡Hola!\n"
	.string "¡Nos lo vamos a pasar genial!$"

Route16_Text_JedRematchIntro::
	.string "JOEL: ¿Vienes a ver nuestro amor,\n"
	.string "que no conoce límites?$"

Route16_Text_LeaRematchIntro::
	.string "LIZ: A veces, la intensidad de\n"
	.string "nuestro amor me da miedo.$"

Route17_Text_RaulRematchIntro::
	.string "Te dije que no se hace rico rápido\n"
	.string "combatiendo con niños.$"

Route17_Text_IsaiahRematchIntro::
	.string "Estoy muy orgulloso de mi cuerpo,\n"
	.string "chaval. ¡Vamos!$"

Route17_Text_VirgilRematchIntro::
	.string "¿Sales a pasear?$"

Route17_Text_BillyRematchIntro::
	.string "¡Somos MOTEROS!\n"
	.string "¡Mandamos en las carreteras, tío!$"

Route17_Text_NikolasRematchIntro::
	.string "¡VOLTORB te va a electrizar en\n"
	.string "serio hoy!$"

Route17_Text_ZeekRematchIntro::
	.string "He subido de nivel a mi POKéMON,\n"
	.string "pero no evoluciona. ¿Por qué?$"

Route17_Text_JamalRematchIntro::
	.string "¡Aaah! ¡Necesito hacer ejercicio\n"
	.string "y quitarme de verdad estos michelines!$"

Route17_Text_CoreyRematchIntro::
	.string "¡Sé un rebelde!$"

Route17_Text_JaxonRematchIntro::
	.string "Sí, esa es una buena BICI.\n"
	.string "¿Cómo se maneja?$"

Route17_Text_WilliamRematchIntro::
	.string "¡Lárgate, chaval!\n"
	.string "¡Estoy hecho polvo!$"

Route18_Text_WiltonRematchIntro::
	.string "He estado revisando todas las zonas\n"
	.string "de hierba en busca de POKéMON nuevos.\p"
	.string "Pero no siempre es fácil…$"

Route18_Text_RamiroRematchIntro::
	.string "¡Kurukukukú!\n"
	.string "¿Mejora mi reclamo de pájaro?$"

Route18_Text_JacobRematchIntro::
	.string "Ya te lo advertí, ¡este es mi\n"
	.string "territorio!\p"
	.string "No quiero que vengas por aquí.$"

Route19_Text_RichardRematchIntro::
	.string "Casi estoy listo para salir\n"
	.string "a nadar.$"

Route19_Text_ReeceRematchIntro::
	.string "¡Espera! ¡Más despacio!\n"
	.string "¿Y si te da un infarto?$"

Route19_Text_MatthewRematchIntro::
	.string "¡Me encanta nadar!\n"
	.string "Supongo que tú eres de surfear.$"

Route19_Text_DouglasRematchIntro::
	.string "¿Qué hay más allá del horizonte?\n"
	.string "¿Lo has visto?$"

Route19_Text_DavidRematchIntro::
	.string "Intenté bucear de nuevo en busca\n"
	.string "de POKéMON, pero otra vez nada.$"

Route19_Text_TonyRematchIntro::
	.string "Miro el mar para olvidar todo lo\n"
	.string "malo que me ha pasado.\p"
	.string "…¡Como perder contra ti la última vez!$"

Route19_Text_AnyaRematchIntro::
	.string "Tú siempre vas montado en tu\n"
	.string "POKéMON…\p"
	.string "Parece tan relajante.\n"
	.string "¿Me lo das si gano?$"

Route19_Text_AliceRematchIntro::
	.string "¡Nadar es genial!\n"
	.string "¡Las quemaduras de sol, no!$"

Route19_Text_AxleRematchIntro::
	.string "¡Estas aguas son traicioneras!\n"
	.string "¡No deberías volver aquí!$"

Route19_Text_ConnieRematchIntro::
	.string "Vine nadando aquí con mis amigos…\n"
	.string "Estoy cansada… ¿De verdad tenemos\l"
	.string "que combatir otra vez?$"

Route19_Text_LiaRematchIntro::
	.string "CATI: Mi hermano se acaba de hacer\n"
	.string "ENTRENADOR, ¿sabes?\p"
	.string "Quiero que mejore, así que necesito\n"
	.string "tu ayuda otra vez.$"

Route19_Text_LucRematchIntro::
	.string "TEC: Mi hermana mayor me enseñó\n"
	.string "todo sobre POKéMON.\p"
	.string "¿Seré mejor?$"

Route20_Text_BarryRematchIntro::
	.string "El agua es poco profunda aquí.\n"
	.string "Hay mucha gente nadando.$"

Route20_Text_ShirleyRematchIntro::
	.string "¿Te da envidia que esté de\n"
	.string "vacaciones en ESPUMA?$"

Route20_Text_TiffanyRematchIntro::
	.string "Me encanta flotar con los peces\n"
	.string "aquí entre las olas.$"

Route20_Text_IreneRematchIntro::
	.string "¿Tú también estabas de vacaciones?$"

Route20_Text_DeanRematchIntro::
	.string "¡Mira qué físico!\p"
	.string "¡Está aún más fuerte que antes!$"

Route20_Text_DarrinRematchIntro::
	.string "¿Por qué montas en un POKéMON?\n"
	.string "¿Aún no has aprendido a nadar?$"

Route20_Text_RogerRematchIntro::
	.string "Vine aquí montado en mi POKéMON\n"
	.string "pájaro.$"

Route20_Text_NoraRematchIntro::
	.string "Mi novio me regaló perlas grandes.\n"
	.string "¡Y han crecido aún más!$"

Route20_Text_MissyRematchIntro::
	.string "Vine nadando desde ISLA CANELA.\n"
	.string "No fue fácil, como dije.$"

Route20_Text_MelissaRematchIntro::
	.string "ISLA CANELA, al oeste, tiene un\n"
	.string "LABORATORIO de POKéMON.\p"
	.string "Mi papá trabaja allí.$"

Route21_North_Text_RonaldRematchIntro::
	.string "¿Quieres saber si pican los peces?$"

Route21_North_Text_WadeRematchIntro::
	.string "¡He vuelto a pescar un montón!\n"
	.string "¿Quieres volver a intentarlo?$"

Route21_North_Text_SpencerRematchIntro::
	.string "¡El mar limpia mi cuerpo y mi alma!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "¡Hoy también he venido a nadar!$"

Route21_South_Text_JackRematchIntro::
	.string "Capturé mis POKéMON en el mar.\n"
	.string "Y ahí es donde los entreno.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Ahora mismo estoy en otro triatlón.$"

Route21_South_Text_RolandRematchIntro::
	.string "¡Ahh!\n"
	.string "¡Siente el sol y el viento!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Eh, para ya.\n"
	.string "¡Siempre espantas a los peces!$"

Route21_South_Text_NolanRematchIntro::
	.string "Hazme compañía hasta que pique algo.$"

Route21_North_Text_LilRematchIntro::
	.string "ÍA: ¿Eh? ¿Otro combate?\n"
	.string "IAN, ¿no puedes hacerlo tú solo?$"

Route21_North_Text_IanRematchIntro::
	.string "IGOR: Mi hermana sigue siendo un\n"
	.string "desastre.\p"
	.string "¡Ayúdame a ponerla en forma!$"

Route25_Text_JoeyRematchIntro::
	.string "¡No perderé mientras esté aquí!$"

Route25_Text_DanRematchIntro::
	.string "Papá me llevó a una gran fiesta en\n"
	.string "el S.S. LIN en CIUDAD CARMÍN.$"

Route25_Text_FlintRematchIntro::
	.string "Soy un tipo genial.\n"
	.string "¡Tengo novia!\p"
	.string "¡Esta vez le demostraré lo genial\n"
	.string "que soy!$"

Route25_Text_KelseyRematchIntro::
	.string "¡Hola!\n"
	.string "¡Mi novio es genial!\l"
	.string "¡Hoy estoy en forma!$"

Route25_Text_ChadRematchIntro::
	.string "Tenía el presentimiento… ¡Sabía que\n"
	.string "tenía que combatirte otra vez!$"

Route25_Text_HaleyRematchIntro::
	.string "Mi amiga tiene muchos POKéMON monos.\n"
	.string "¡Qué envidia!$"

Route25_Text_FranklinRematchIntro::
	.string "Acabo de entrenar en el MT. MOON,\n"
	.string "¡pero aún me quedan fuerzas!$"

Route25_Text_NobRematchIntro::
	.string "Un POKéMANÍACO vive en el cabo.\n"
	.string "¿Has visto su colección?$"

Route25_Text_WayneRematchIntro::
	.string "¿Vas a ver a BILL otra vez?\n"
	.string "¡Primero combatimos!$"

Route24_Text_ShaneRematchIntro::
	.string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_EthanRematchIntro::
	.string "¡Vale!\n"
	.string "¡Voy a aplastarte!$"

Route24_Text_ReliRematchIntro::
	.string "Siempre pareces muy ocupado…\n"
	.string "¿No te cansas?$"

Route24_Text_TimmyRematchIntro::
	.string "Debes de adorar venir al\n"
	.string "PUENTE PEPITA.$"

Route24_Text_AliRematchIntro::
	.string "La vez que combatimos…\p"
	.string "Aunque fui el segundo de la fila,\n"
	.string "fui el mejor, ¿verdad?$"

Route24_Text_CaleRematchIntro::
	.string "¡La gente lo llama PUENTE PEPITA!\p"
	.string "¡Ya nos has vencido, así que no puedes\n"
	.string "afrontar el desafío…\p"
	.string "…Pero eres bienvenido a combatir\n"
	.string "con nosotros otra vez.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Tumbada, mecida por las olas…\n"
	.string "No noto cómo pasa el tiempo…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "¡Hace un tiempo precioso!\n"
	.string "Intentaré no estropearlo.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Me empieza a doler la quemadura\n"
	.string "de sol…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "La montaña del ave de fuego proyecta\n"
	.string "una enorme sombra…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "¡Tengo la fuerte sensación de que\n"
	.string "esta vez puedo ganar!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "¡Espera! ¡Espera un segundo!\n"
	.string "¡Seguro que he pescado uno grande!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "¿Me ayudarás otra vez con mi\n"
	.string "entrenamiento?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "¡No hemos faltado ni un solo día\n"
	.string "al entrenamiento!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Cada mañana, antes del desayuno,\n"
	.string "nado alrededor de esta isla…\l"
	.string "¡Tres veces!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "¡Vístete adecuadamente para el\n"
	.string "combate!\n"
	.string "¡Quítate ese atuendo frívolo, dije!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Sabes, todo sabe genial cuando\n"
	.string "estás en plena naturaleza.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "He vuelto a comer demasiado, así\n"
	.string "que ¿combatís con nosotras para hacer\l"
	.string "ejercicio?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "PÍA: ¡Mi hermano mayor y yo\n"
	.string "formamos una pareja genial!\p"
	.string "¡Esta vez no perderemos!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "FER: ¡Junto con PÍA, no tememos\n"
	.string "a nada!\p"
	.string "¡Esta vez te lo demostraremos!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "¿Vamos a combatir otra vez?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "¿De dónde vienes y adónde\n"
	.string "vas?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Pronto quiero nadar sin mi\n"
	.string "flotador.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "¡Yupi, yupi!\n"
	.string "¡POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Ay, ¿no te lo dije ya?\n"
	.string "¡Por favor, aléjate de mí!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "FELI: ¡Nos hemos hecho más fuertes!\n"
	.string "¡Muchísimo!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MATI: ¡Hoy no podrás vencernos!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "¡Oh, hola!\p"
	.string "¿Estás criando a tus POKéMON en un\n"
	.string "buen entorno?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Con estas manos crearé mi\n"
	.string "victoria hoy.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "¿Tengo que repetirlo?\n"
	.string "Estoy intentando pintar.\l"
	.string "¡Por favor, no te cruces en mi vista!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "No he progresado…\n"
	.string "Sigo sin encontrar el ángulo adecuado…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "¿Me darás otra oportunidad de\n"
	.string "medir mi ingenio con el tuyo?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "Casi han terminado de construir\n"
	.string "la piscina para mis POKéMON.\p"
	.string "Tienes que venir a visitarnos.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Soy buen corredor.\n"
	.string "¡Me he vuelto aún más rápido!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "¡Vaya, amigo!\n"
	.string "¡Disfrutemos juntos de este rato!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Soy el mayor de los HERMANOS PÁJARO.\n"
	.string "¿Me recuerdas?\p"
	.string "¡Así es, soy el que ama a las aves\n"
	.string "por sus picos!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Soy el mediano de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Soy el que ama las alas.\n"
	.string "¡Combatamos otra vez!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Soy el menor de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Amo a las aves por su plumón.\n"
	.string "¡No pensé que volvería a verte!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Sigo sin tener suerte.\n"
	.string "¡Un combate sería un cambio de aires!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Uf… Uf…\p"
	.string "He vuelto a nadar de un tirón desde\n"
	.string "el puerto de ISLA SEIS.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Siempre apareces mientras estoy\n"
	.string "nadando.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "ALI: ¡Hoy tengamos otro combate\n"
	.string "marino dos contra dos!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "ROS: ¡Mi hermana mayor y yo somos\n"
	.string "mucho más duros que antes!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…¿Eh?\p"
	.string "¡Imagino mi casa, pero TELETRANSPORTE\n"
	.string "siempre me trae aquí!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Oh, hola.\n"
	.string "Sopla otra vez una brisa agradable.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Jejeje, vuelvo a practicar en\n"
	.string "secreto.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "¿Qué, estás harto de ver\n"
	.string "NADADORES como yo?\p"
	.string "Ay, ¡no me odies!\n"
	.string "Combate otra vez conmigo.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Suspiro…\n"
	.string "Mi novio vuelve a estar ocupado…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Anda, dime, ¿dónde están las\n"
	.string "montañas por esta zona?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MARU: ¡Hola, POKéMON!\n"
	.string "¡Es hora de jugar otra vez!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MÍA: ¡Hola, POKéMON!\n"
	.string "¡Es hora de combatir otra vez!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Parece que aún hay muchos secretos\n"
	.string "sin resolver en este mundo.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hola, ¿no nos conocimos antes?\n"
	.string "¿Qué te hizo volver?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Se dice que hay piedras misteriosas\n"
	.string "en esta isla.\p"
	.string "¿Has descubierto algo desde que\n"
	.string "nos vimos?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "¡Una revancha contigo, tan arriba!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Conozco bastante bien el terreno\n"
	.string "por estos alrededores.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Percibí tu llegada.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "En algún lugar de esta isla duermen\n"
	.string "POKéMON peculiares.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "¡Kiajaja!\p"
	.string "Volver no cambiará nada.\n"
	.string "¡Te quitaré de en medio sin esfuerzo!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "¡Hola! Eres miembro de mi club\n"
	.string "de fans, ¿verdad?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Esta isla es demasiado extensa…\n"
	.string "Patrullarla es un rollo…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "¡No perdono a quienes maltratan\n"
	.string "a los POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "ELE: Me uniré a RUS y combatiremos\n"
	.string "juntos otra vez.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "RUS: Cuando estoy con ELE, siento\n"
	.string "que nunca podríamos perder, jamás.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Combatamos otra vez.\n"
	.string "¡Estoy en plena forma!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "No importa si tienes los POKéMON\n"
	.string "más fuertes…\p"
	.string "¡No sirve de nada si no sabes\n"
	.string "usarlos como es debido!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Trabajo para proteger el medio\n"
	.string "ambiente. ¡A cambio, la naturaleza\l"
	.string "me protege!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Cada vez que nos vemos, llevas\n"
	.string "esas zapatillas tan chulas.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Debes de haberte hecho más fuerte.\n"
	.string "¡Déjame combatir contigo, por favor!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Recibí la mejor educación posible\n"
	.string "para ser así de fuerte.\p"
	.string "Esta vez no perderé.\n"
	.string "¡De ninguna manera!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LINO: ¡Mi querida ABA, juntos\n"
	.string "ganaremos seguro!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "ABA: ¡No voy a fallarle a mi\n"
	.string "mentor LINO! ¡Vamos a ganar!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "¿Has descubierto algo sobre esta\n"
	.string "cámara de piedra?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Se dice que un POKéMON místico\n"
	.string "duerme aquí dentro.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Mi profesora me está enseñando a\n"
	.string "pintar un poco más.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Hoy, además de nuestra lección,\n"
	.string "vinimos a ver otra vez la cámara.$"
