LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "¡Hola! Tú has participado en un\n"
	.string "CONCURSO POKéMON, ¿verdad?\l"
	.string "Se ve por los POKéMON que tienes.\p"
	.string "Soy reportero. Trabajo en una historia\n"
	.string "sobre los CONCURSOS POKéMON.\p"
	.string "¿Podría hacerte unas preguntas?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "¿Sí?\n"
	.string "Muchas gracias.\p"
	.string "¿Podrías describirme el CONCURSO\n"
	.string "en el que has participado?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ajá, entiendo.\n"
	.string "Un comentario muy edificante.\p"
	.string "Te haces una buena idea de lo\n"
	.string "que fue el CONCURSO.\p"
	.string "Tengo otra pregunta…\p"
	.string "Cuando oyes la palabra “{STR_VAR_2}”,\n"
	.string "¿qué te pasa por la mente?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Ya veo.\p"
	.string "Así que imaginas el concepto de\n"
	.string "“{STR_VAR_2}” así…\p"
	.string "¡Gracias!\n"
	.string "Resulta inspirador.\p"
	.string "Creo que puedo escribir una buena\n"
	.string "historia sobre los CONCURSOS POKéMON.\p"
	.string "Y quizás, sólo quizás, esta historia\n"
	.string "llegue a salir en la tele.\l"
	.string "¡Espero que no te la pierdas si sale!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, qué decepción…\p"
	.string "Bueno, si te encuentras con una buena\n"
	.string "historia, ven a contármela, porfa.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Estoy deseando que participes en\n"
	.string "otro CONCURSO POKéMON.$"

gTVBravoTrainerText00::
	.string "¡Sí! ¡Es la hora de BRAVO ENTRENADOR!\p"
	.string "Hoy vamos a analizar un POKéMON de\n"
	.string "{STR_VAR_1}.\p"
	.string "Este POKéMON presume de un rango\n"
	.string "{STR_VAR_3} en la categoría\l"
	.string "{STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "¡Más datos sobre {STR_VAR_2},\n"
	.string "el POKéMON {STR_VAR_1}!\p"
	.string "{STR_VAR_2}… ¡Vaya mote!\p"
	.string "¡Sin duda alguna, es un mote que por sí\n"
	.string "solo evoca “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Pero lo mejor es que cuando {STR_VAR_1}\n"
	.string "presentó el POKéMON al CONCURSO,\l"
	.string "nos las arreglamos para conseguir\l"
	.string "unas apasionadas declaraciones.$"

gTVBravoTrainerText03::
	.string "Una vez finalizado el CONCURSO,\n"
	.string "{STR_VAR_1} nos dijo “¡{STR_VAR_2}!”\l"
	.string "con una enorme sonrisa.\p"
	.string "Nada más natural, pues el POKéMON de\n"
	.string "{STR_VAR_1} quedó en el puesto {STR_VAR_3}\l"
	.string "del CONCURSO.\p"
	.string "Esa declaración es ideal para {STR_VAR_1}\n"
	.string "en estos momentos, está claro.$"

gTVBravoTrainerText04::
	.string "Una vez finalizado el CONCURSO,\n"
	.string "{STR_VAR_1} nos dijo “{STR_VAR_2}”\l"
	.string "con cierto tono de amargura.\p"
	.string "Nada más natural, pues el POKéMON de\n"
	.string "{STR_VAR_1} quedó en el puesto {STR_VAR_3}\l"
	.string "del CONCURSO.\p"
	.string "{STR_VAR_1} ha expresado su decepción\n"
	.string "con mucho acierto, está claro.$"

gTVBravoTrainerText05::
	.string "¿No os gustaría saber también qué\n"
	.string "piensa {STR_VAR_1} que es {STR_VAR_2}?\p"
	.string "¡A nosotros sí!\n"
	.string "¡Por eso se lo preguntamos!\p"
	.string "Y la respuesta es muy clara:\n"
	.string "“¡{STR_VAR_3}!”.\p"
	.string "Eso es lo que el concepto de {STR_VAR_2}\n"
	.string "representa para {STR_VAR_1}.$"

gTVBravoTrainerText06::
	.string "El último movimiento {STR_VAR_2} que\n"
	.string "usó {STR_VAR_1} es la viva expresión\l"
	.string "de “{STR_VAR_3}”.$"

gTVBravoTrainerText07::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "¡Confío en que podamos ver a\n"
	.string "{STR_VAR_1} subir a lo más alto!\p"
	.string "¡Esto es todo por hoy!\n"
	.string "¡Nos despedimos hasta la próxima!$"

gTVBravoTrainerText08::
	.string "¡Más datos sobre {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hello! You're the TRAINER who just had\n"
	.string "a battle, right?\p"
	.string "I'm gathering interviews with TRAINERS\n"
	.string "all over the place.\p"
	.string "May I get a few words from you about\n"
	.string "your impressions on battling?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "You will? Really?\n"
	.string "Thank you!\l"
	.string "Then, uh…\p"
	.string "How did things turn out in\n"
	.string "the BATTLE TOWER today?\p"
	.string "Were you satisfied with the battle?\n"
	.string "Or are you unhappy?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Sorry we disturbed you.\p"
	.string "Please give us an interview the next\n"
	.string "time you visit the BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Well, of course!\p"
	.string "That unmistakable look of satisfaction\n"
	.string "on your face…\p"
	.string "It's obvious that you've had a great\n"
	.string "battle.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, I see…\p"
	.string "Well, it certainly is difficult to make a\n"
	.string "battle turn out exactly as planned.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, may I ask one more question?\p"
	.string "If you were to describe your\n"
	.string "impressions about this battle with\l"
	.string "one saying, what would it be?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, that is stunningly cool!\p"
	.string "That's a great line!\n"
	.string "I hope you'll do great next time, too.\p"
	.string "I hope to see you again!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, I see…\p"
	.string "Still, being the silent type is also\n"
	.string "cool, isn't it?\p"
	.string "I hope you'll give me the opportunity\n"
	.string "to share your thoughts again!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "I'll be looking forward to your\n"
	.string "next battle!$"

BravoTrainerBattleTower_Text_Intro::
	.string "¡Sí! ¡Es la hora de BRAVO ENTRENADOR!\p"
	.string "Hoy vamos a analizar a {STR_VAR_1},\n"
	.string "que afrontó el desafío de la TORRE\l"
	.string "BATALLA.\p"
	.string "Para el desafío, {STR_VAR_1} inscribió\n"
	.string "a un {STR_VAR_2} de armas tomar.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La pareja estableció un nuevo récord\n"
	.string "de {STR_VAR_2} victorias seguidas en el\l"
	.string "{STR_VAR_1} de la competición.\l"
	.string "¡Impresionante!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Ambos acabaron por caer ante\n"
	.string "{STR_VAR_1} en el combate número {STR_VAR_2}.\l"
	.string "Fue una pelea muy reñida.\p"
	.string "Es simplemente mala suerte enfrentarse\n"
	.string "a {STR_VAR_1} tan pronto en la serie\l"
	.string "de combates clasificatorios…\p"
	.string "Pedimos que nos hiciera partícipes de\n"
	.string "sus impresiones con respecto a\l"
	.string "la lucha contra {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "La pareja lo ganó todo derrotando por\n"
	.string "completo al {STR_VAR_2} de\l"
	.string "{STR_VAR_1}. ¡Bravo, ENTRENADOR!\p"
	.string "Derrotar hasta a {STR_VAR_1}… ¡Es\n"
	.string "increíble! ¡Simplemente asombroso!\p"
	.string "Le pedimos al ENTRENADOR sus\n"
	.string "impresiones sobre el momento de\l"
	.string "gloria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Tras una racha de victorias, la pareja\n"
	.string "sucumbió por fin ante el {STR_VAR_2}\l"
	.string "de {STR_VAR_1}, su último obstáculo.\p"
	.string "¡Buen intento, ENTRENADOR!\p"
	.string "Aun así, hay que reconocerlo. No se\n"
	.string "ven muchas combinaciones famosas\l"
	.string "como {STR_VAR_1} y {STR_VAR_2}.\p"
	.string "Le pedimos al ENTRENADOR sus\n"
	.string "impresiones sobre combatir contra la\l"
	.string "famosa pareja.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Esto es lo que nos dijo:\n"
	.string "“¡Ha estado bien!”.\p"
	.string "¡Es lo que llamo una respuesta\n"
	.string "positiva! ¡Bravo!\p"
	.string "¿No es simplemente extraordinario\n"
	.string "poder combatir a tu gusto?\p"
	.string "En cualquier caso, supe lo bien que se\n"
	.string "sentía cuando oí lo siguiente:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Esto es lo que nos dijo:\n"
	.string "“Ha estado mal…”.\p"
	.string "Era presa del decaimiento mientras\n"
	.string "hacía estas declaraciones. Es natural…\p"
	.string "Aun así, ningún combate puede estar\n"
	.string "nunca bien del todo, ¿no es cierto?\p"
	.string "En cualquier caso, supe lo mal que se\n"
	.string "sentía cuando oí lo siguiente:$"

BravoTrainerBattleTower_Text_None1::
	.string "Nada$"

BravoTrainerBattleTower_Text_None2::
	.string "Nada$"

BravoTrainerBattleTower_Text_None3::
	.string "Nada$"

BravoTrainerBattleTower_Text_None4::
	.string "Nada$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "¿No es genial?\p"
	.string "En mi opinión expresa toda la alegría\n"
	.string "que siente {STR_VAR_2}.\p"
	.string "Ese combate contra {STR_VAR_3}\n"
	.string "al final… Es lo que se llama un\l"
	.string "“{STR_VAR_1}”, sin duda.$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "¿No es muy apropiado?\p"
	.string "Ese combate contra {STR_VAR_3}\n"
	.string "al final… Sólo puede describirse como\l"
	.string "“{STR_VAR_1}”, claro.\p"
	.string "La decepción de {STR_VAR_2} queda\n"
	.string "reflejada alta y clara, así es.$"

BravoTrainerBattleTower_Text_Outro::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "¡Confío en que podamos ver a\n"
	.string "{STR_VAR_1} subir a lo más alto!\p"
	.string "¡Esto es todo por hoy!\n"
	.string "¡Nos despedimos hasta la próxima!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "It's plain to see that you lavish your\n"
	.string "love on your {STR_VAR_1}.\p"
	.string "Okay, it's named {STR_VAR_2}.\p"
	.string "Can I ask you a favor?\p"
	.string "I'm a TV reporter, and I'm running\n"
	.string "a survey on POKéMON.\p"
	.string "Would you be willing to answer a few\n"
	.string "simple questions for me?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Great! Thank you!\p"
	.string "Okay, here goes.\n"
	.string "I just need quick answers, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "When you first met {STR_VAR_1},\n"
	.string "what did you feel?\p"
	.string "How would you describe your feelings\n"
	.string "at the time?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Your {STR_VAR_1} is cared for lovingly.\p"
	.string "If you were to liken it to something\n"
	.string "that you like, what would it be?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "This question also relates to your\n"
	.string "beloved {STR_VAR_1}.\p"
	.string "What was it about {STR_VAR_1} that\n"
	.string "attracted you?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, that makes sense.\p"
	.string "The next question might be a little\n"
	.string "on the tough side.\p"
	.string "Here goes…\p"
	.string "What do POKéMON mean to you?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "I see!\p"
	.string "Hmhm…\p"
	.string "Okay!\n"
	.string "Thanks for helping me out.\p"
	.string "It was fun and enlightening\n"
	.string "chatting with you.\p"
	.string "It's possible that our interview will\n"
	.string "end up on TV. Tune in and check!\p"
	.string "Okay, that's all.\n"
	.string "Bye-bye!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, okay…\p"
	.string "Well, if you get the urge to tell me\n"
	.string "about POKéMON, I'll be here!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "I enjoy this job--you get to learn\n"
	.string "about POKéMON by doing interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hi, you seem to be very close to your\n"
	.string "{STR_VAR_1}.\p"
	.string "Do you know what?\n"
	.string "I'm a TV reporter.\p"
	.string "I travel around interviewing people\n"
	.string "about POKéMON.\p"
	.string "I'm wondering if you'd be willing to tell\n"
	.string "me a little about your {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, thank you!\p"
	.string "Okay, then, please tell me anything\n"
	.string "you'd like about your {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "That's an interesting account.\p"
	.string "You really are tight with {STR_VAR_1},\n"
	.string "aren't you?\p"
	.string "I get the feeling that your account\n"
	.string "will make a great TV story.\p"
	.string "I promise that I'll turn this into\n"
	.string "an entertaining show.\l"
	.string "Keep your eyes out for it.\p"
	.string "Okay, that's all.\n"
	.string "Bye-bye!$"

gTVFanClubOpinionsText00::
	.string "¡SOMOS el CLUB de FANS de POKéMON!\p"
	.string "¡Estamos en el aire!\p"
	.string "En este programa recogemos vuestras\n"
	.string "opiniones, ¡y yo las grito por vosotros!\l"
	.string "¿A que es un concepto fantástico?\p"
	.string "Hoy os traemos este reportaje de\n"
	.string "nuestro reportero, al que enviamos\l"
	.string "al CLUB de FANS de POKéMON.\p"
	.string "¿Y quién es el fan de POKéMON\n"
	.string "de hoy?\p"
	.string "… … … … … … … …\p"
	.string "¡{STR_VAR_1}!\p"
	.string "Veamos qué tiene que decir {STR_VAR_1}\n"
	.string "sobre {STR_VAR_3} el {STR_VAR_2}.\p"
	.string "Y yo gritaré esas palabras de amor\n"
	.string "¡en voz alta por la tele!\p"
	.string "¡Hoo-ha!\p"
	.string "¡Gritemos!$"

gTVFanClubOpinionsText01::
	.string "Hemos preguntado a {STR_VAR_1}: “Cuando\n"
	.string "viste por primera vez a {STR_VAR_2},\l"
	.string "¿qué fue lo que sentiste?”.\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Es una declaración impactante!\p"
	.string "¿No os trae recuerdos de esos felices\n"
	.string "días que dejasteis atrás?$"

gTVFanClubOpinionsText02::
	.string "Hemos preguntado a {STR_VAR_1}: “¿Qué\n"
	.string "tenía {STR_VAR_2} que te atrajo tanto\l"
	.string "desde el principio?”.\p"
	.string "Y respondió…\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Una declaración espectacular!\p"
	.string "Es una clara muestra de la fuerza\n"
	.string "del amor que siente por su {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Y veamos… ¿Qué fue de ese {STR_VAR_2}\n"
	.string "lo que tanto atrajo a {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Qué declaración tan\n"
	.string "espectacular!\p"
	.string "¡El amor del ENTRENADOR por el\n"
	.string "{STR_VAR_2} se nota alto y claro!$"

gTVFanClubOpinionsText04::
	.string "¿Eh? Ah, aún hay más. ¡Vamos a verlo!\p"
	.string "A ver…\p"
	.string "Le preguntamos a {STR_VAR_1}: “¿Qué\n"
	.string "significan los POKéMON para ti?”\p"
	.string "… … … … … …\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Bravo!\p"
	.string "¡Es el mejor grito que he oído hoy!\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Dan ganas de gritarlo en voz alta una\n"
	.string "y otra vez!\p"
	.string "Ya que hemos gritado de lo lindo, es\n"
	.string "hora de despedirnos hasta la próxima.\p"
	.string "¡Gritemos todos una última vez! ¡Todos\n"
	.string "juntos!\p"
	.string "“¡{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "¡SOMOS EL CLUB de FANS de POKéMON!\p"
	.string "¡Estamos en el aire!\p"
	.string "Hoy vamos a pasarlo como enanos\n"
	.string "con LA HORA DE LAS POKéCARTAS.\p"
	.string "De todas las emocionantes historias\n"
	.string "de POKéMON y ENTRENADORES, ¿cuál \l"
	.string "captará nuestra atención hoy?\p"
	.string "A ver…\p"
	.string "¡Ésta!\p"
	.string "¡Empezaremos con esta carta!\p"
	.string "Una carta de {STR_VAR_1} sobre su\n"
	.string "querido {STR_VAR_2}.\p"
	.string "Veamos con qué pasión expresa su\n"
	.string "amor por {STR_VAR_2}…\l"
	.string "Ajá…$"

gTVFanClubText01::
	.string "¡Vaya!\n"
	.string "¡Esta carta es una obra de arte!$"

gTVFanClubText02::
	.string "¡Me encantó, así que aquí va otra vez!$"

gTVFanClubText03::
	.string "¡Cuando algo está bien escrito, se\n"
	.string "puede leer hasta el aburrimiento!$"

gTVFanClubText04::
	.string "La parte que dice “{STR_VAR_3}” es\n"
	.string "la que añade más contenido emocional.\p"
	.string "Es una carta magnífica que expresa\n"
	.string "sentimientos realmente profundos.$"

gTVFanClubText05::
	.string "¡Sobre todo esa parte de “{STR_VAR_3}”!\p"
	.string "¡Me encanta cómo se usa “{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Por cierto, no es que vaya a cambiarme\n"
	.string "la vida, pero “{STR_VAR_3}” es\l"
	.string "una expresión genial.\p"
	.string "He usado “{STR_VAR_3}” cada\n"
	.string "dos por tres últimamente.$"

gTVFanClubText07::
	.string "Si tuviera que puntuar esta carta,\n"
	.string "le daría {STR_VAR_3} puntos.\p"
	.string "¡La próxima vez espero que la\n"
	.string "carta sea aún mejor, {STR_VAR_1}!\p"
	.string "Oh… ¿Sabes qué hora es?\n"
	.string "¡Hora de decir hasta luego, Lucas!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Do you perhaps like POKéMON?\p"
	.string "I'm on assignment with the TV network.\p"
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, you will?\n"
	.string "Thank you!\p"
	.string "Then, please, tell me anything of\n"
	.string "interest that you experienced recently\l"
	.string "involving POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, I see…\p"
	.string "Well, if you do have an interesting\n"
	.string "story to tell, please let me know.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, what an uplifting story!\p"
	.string "I'll be sure to get your story told\n"
	.string "on television.\p"
	.string "It should be aired sometime, I think,\n"
	.string "so please look forward to it.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "I've got a good story for a TV program.\p"
	.string "I'd better write it up in a hurry!$"

gTVRecentHappeningsText00::
	.string "Hola, es la hora de ÚLTIMAS NOVEDADES.\p"
	.string "Para los ENTRENADORES POKéMON, cada\n"
	.string "día es un cuento de hadas.\p"
	.string "Queremos presentaros algunos de\n"
	.string "esos cuentos POKéMON.\p"
	.string "Hoy os traemos la historia del\n"
	.string "ENTRENADOR {STR_VAR_1}.\p"
	.string "¿Qué ha vivido {STR_VAR_1} últimamente?\n"
	.string "Vamos a averiguarlo.\p"
	.string "Veamos…$"

gTVRecentHappeningsText01::
	.string "¿No es asombroso?\p"
	.string "Esta historia te da una clara idea de\n"
	.string "lo que le ha pasado a {STR_VAR_1}, casi\l"
	.string "como si lo hubiésemos vivido nosotros.$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}” añade\n"
	.string "matices y profundidad a la historia.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}” sitúa\n"
	.string "la historia en contexto.\l"
	.string "Nos permite imaginar la escena.$"

gTVRecentHappeningsText04::
	.string "La parte de la historia que dice\n"
	.string "“{STR_VAR_3}” es\l"
	.string "altamente expresiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} nos ha deleitado con una\n"
	.string "maravillosa historia sobre POKéMON.\p"
	.string "Y ahora la historia de {STR_VAR_1} está\n"
	.string "grabada a fuego en nuestra mente.\p"
	.string "Esto es todo por hoy.\n"
	.string "¡Hasta el próximo programa!$"

gTVMassOutbreakText00::
	.string "¡Saludos, telespectadores! Es la hora\n"
	.string "de las NOTICIAS POKéMON.\p"
	.string "Acabamos de recibir la noticia de un\n"
	.string "suceso muy poco común.\p"
	.string "Se han recibido informes de una\n"
	.string "aparición masiva de {STR_VAR_2} cerca\l"
	.string "de {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, como sabréis, es un\n"
	.string "POKéMON raro y difícil de encontrar.\p"
	.string "Suena a una oportunidad única para\n"
	.string "ver la misteriosa aparición de\l"
	.string "{STR_VAR_2} en libertad.\p"
	.string "Eso es todo en las NOTICIAS POKéMON.$"

gTV3CheersForPokeblocksText00::
	.string "PRESENTADOR: ¡Esperamos que estéis de\n"
	.string "buen humor, llega la “CATA de {POKEBLOCK}S”!\p"
	.string "Hoy examinamos el {POKEBLOCK} preparado\n"
	.string "por {STR_VAR_1} y compañía.\p"
	.string "Sin más dilación, voy a dárselo a mi\n"
	.string "POKéMON gourmet GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: ¡Gubi, gubiii!\p"
	.string "PRESENTADORA: ¡Muy {STR_VAR_1}! \n"
	.string "¡GULPIN dice que está “{STR_VAR_2}”!\p"
	.string "¡Muchas gracias, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Las habilidades de {STR_VAR_1}\n"
	.string "no acaban de convencernos.\p"
	.string "Si mezclara BAYAS mejor, el sabor\n"
	.string "de este {POKEBLOCK} sería excelente.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: ¡Gubi, gubiii!\p"
	.string "PRESENTADORA: Demasiado {STR_VAR_1}…\n"
	.string "¡GULPIN dice que está “{STR_VAR_2}”!\p"
	.string "Parece que los errores de {STR_VAR_3}\n"
	.string "afectaron a la calidad de la mezcla…$"

gTV3CheersForPokeblocksText04::
	.string "Es una lástima que los esfuerzos de\n"
	.string "{STR_VAR_1} hayan sido inútiles.\p"
	.string "¡Esperemos que {STR_VAR_2} lo haga\n"
	.string "mejor la próxima vez!$"

gTV3CheersForPokeblocksText05::
	.string "¡No os perdáis la próxima emisión!\n"
	.string "¡Os esperamos en la CATA de {POKEBLOCK}S!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hi, there!\p"
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "I see, I see. That's what you think\n"
	.string "about the TRAINER.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "How strong would you rate {STR_VAR_1}\n"
	.string "on a scale of one hundred?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, I see!\n"
	.string "You should meet {STR_VAR_1} sometime.\l"
	.string "I'm sure you'll become a fan, too!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "I see, I see.\p"
	.string "Thank you!\n"
	.string "That's very useful to know.\p"
	.string "I'll share this information with other\n"
	.string "{STR_VAR_1} fans and discuss it.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "There's going to be a TV special on\n"
	.string "{STR_VAR_1} very soon.\p"
	.string "I hope you catch it!$"

gTVTrainerFanClubSpecialText00::
	.string "CLUB de FANS de ENTRENADORES\n"
	.string "¡ESPECIAL {STR_VAR_1}!\p"
	.string "Esta es una presentación especial\n"
	.string "para los fans de {STR_VAR_1} de todo\l"
	.string "HOENN.\p"
	.string "Hoy nos preguntamos: “¿Qué piensa la\n"
	.string "gente de {STR_VAR_1}?”\p"
	.string "Le hicimos la pregunta a {STR_VAR_2}\n"
	.string "como representante de los\l"
	.string "ENTRENADORES.\p"
	.string "Preguntamos: “En una palabra, ¿cómo\n"
	.string "describirías a {STR_VAR_1}?”\p"
	.string "La respuesta: “{STR_VAR_3}.”\p"
	.string "¡Enhorabuena, {STR_VAR_2}! ¡Qué\n"
	.string "opinión tan perspicaz!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.” ¡Suena de\n"
	.string "maravilla!\p"
	.string "{STR_VAR_2} también puntuó la fuerza\n"
	.string "de {STR_VAR_1} de 0 a 100.$"

gTVTrainerFanClubSpecialText01::
	.string "¡Ha conseguido nada menos que\n"
	.string "{STR_VAR_3} puntos! ¡Menuda puntuación!\p"
	.string "Es obvio que {STR_VAR_2} tiene a\n"
	.string "{STR_VAR_1} en muy alta estima.$"

gTVTrainerFanClubSpecialText02::
	.string "¡Ha conseguido {STR_VAR_3} puntos!\n"
	.string "¡No está nada mal!\p"
	.string "{STR_VAR_2} debe considerar a\n"
	.string "{STR_VAR_1} como un rival.$"

gTVTrainerFanClubSpecialText03::
	.string "¡Ha conseguido {STR_VAR_3} puntos!\n"
	.string "No es para echar cohetes.\p"
	.string "{STR_VAR_2} no debe admirar\n"
	.string "demasiado a {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText04::
	.string "Sólo ha conseguido esta puntuación:\n"
	.string "¡{STR_VAR_3}! No podría ser peor.\p"
	.string "Está claro que {STR_VAR_2} tiene a\n"
	.string "{STR_VAR_1} en poca consideración.$"

gTVTrainerFanClubSpecialText05::
	.string "¡Y esto es todo, amigos!\p"
	.string "Creo que todos hemos aprendido algo\n"
	.string "nuevo sobre {STR_VAR_1}.\p"
	.string "Para terminar, os dejo con las\n"
	.string "palabras de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Y ahora, es la hora de…\n"
	.string "EL PROGRAMA del INSPECTOR de MOTES.\p"
	.string "Le leo el futuro a tu POKéMON a partir\n"
	.string "del mote que le has puesto.\p"
	.string "Lo que ofrezco son consejos, y\n"
	.string "consejos muy útiles.\p"
	.string "Hoy leeré el mote {STR_VAR_3} del\n"
	.string "POKéMON {STR_VAR_2} de {STR_VAR_1}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Este mote es…$"

gTVNameRaterText01::
	.string "Este mote denota un gran talento\n"
	.string "en muchos sentidos.\p"
	.string "Animo a quien lo puso a ser valiente\n"
	.string "y aceptar muchos desafíos…$"

gTVNameRaterText02::
	.string "Este mote complementa perfectamente\n"
	.string "a quien lo puso, {STR_VAR_1}.\p"
	.string "Sugiere que se forjará una amistad\n"
	.string "perfecta al cabo del tiempo…$"

gTVNameRaterText03::
	.string "Este mote se adapta a la personalidad\n"
	.string "propia de su POKéMON.\p"
	.string "Si se le entrena correctamente, este\n"
	.string "POKéMON llegará a lo más alto…$"

gTVNameRaterText04::
	.string "Este mote potenciará el lado cariñoso\n"
	.string "y compasivo de su POKéMON.\p"
	.string "Si se le entrena correctamente, este\n"
	.string "POKéMON será realmente adorable…$"

gTVNameRaterText05::
	.string "Un mote muy bonito que anuncia\n"
	.string "grandeza futura.\p"
	.string "Me intriga qué le deparará el futuro\n"
	.string "a este POKéMON.$"

gTVNameRaterText06::
	.string "Este mote favorecerá la fuerza\n"
	.string "y belleza de su POKéMON.\p"
	.string "Este POKéMON será robusto y estará\n"
	.string "en forma durante mucho tiempo…$"

gTVNameRaterText07::
	.string "Este gran mote hará que su POKéMON\n"
	.string "sea muy activo.\p"
	.string "Yo diría que este POKéMON será muy\n"
	.string "bueno en los combates…$"

gTVNameRaterText08::
	.string "Este atractivo mote concederá\n"
	.string "un gran encanto a su POKéMON.\p"
	.string "Sin duda este POKéMON será el rey\n"
	.string "de los CONCURSOS POKéMON…$"

gTVNameRaterText09::
	.string "El mote {STR_VAR_1} proviene de\n"
	.string "la letra “{STR_VAR_3}”.\p"
	.string "Esta letra está apoyada por la primera\n"
	.string "letra, “{STR_VAR_2}”, que le otorga una\l"
	.string "gran solidez como mote…$"

gTVNameRaterText10::
	.string "El mote {STR_VAR_1} es de lo más\n"
	.string "armonioso y agradable.\p"
	.string "La presencia de las letras “{STR_VAR_2}” y\n"
	.string "“{STR_VAR_3}” le da mucha clase…$"

gTVNameRaterText11::
	.string "El mote {STR_VAR_1} transmite una\n"
	.string "sensación de sublime fluidez.\p"
	.string "Desde la letra inicial “{STR_VAR_2}” hasta\n"
	.string "“{STR_VAR_3}” es una auténtica maravilla…$"

gTVNameRaterText12::
	.string "Vamos a examinar otros ejemplos\n"
	.string "de buenos motes, ¿de acuerdo?$"

gTVNameRaterText13::
	.string "Por ejemplo: toma parte del nombre del\n"
	.string "ENTRENADOR, en este caso {STR_VAR_1},\l"
	.string "y añade el bonito mote {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "El mote {STR_VAR_2}{STR_VAR_3} también\n"
	.string "puede funcionar muy bien.$"

gTVNameRaterText15::
	.string "Se puede usar el nombre de la especie\n"
	.string "del POKéMON, {STR_VAR_2}, como base\l"
	.string "para crear el mote {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} también sería\n"
	.string "un mote efectivo.$"

gTVNameRaterText17::
	.string "Lo que hay que evitar siempre es usar\n"
	.string "el nombre de otra especie de POKéMON.\p"
	.string "Por ejemplo, evita tomar el nombre de\n"
	.string "{STR_VAR_2} para crear el mote {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Eso no está nada bien.$"

gTVNameRaterText18::
	.string "Debo decir que {STR_VAR_1} es un\n"
	.string "muy buen mote.\p"
	.string "Espero que el ENTRENADOR siga\n"
	.string "tratando a {STR_VAR_1} con cariño.\p"
	.string "Eso es todo por hoy.\n"
	.string "Que volvamos a vernos.$"

gTVPokemonAnglerText00::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "PRESENTADORA: ¡Hola! Hoy vamos\n"
	.string "a aprender cómo pescar {STR_VAR_2}.\p"
	.string "GURÚ PESCADOR, ¿qué consejo puedes\n"
	.string "darnos para atrapar {STR_VAR_2}?\p"
	.string "GURÚ PESCADOR: ¿Pescar {STR_VAR_2}?\n"
	.string "Pues hay que ser muy paciente.\l"
	.string "Eso es lo básico.\p"
	.string "¿Has visto a {STR_VAR_1} en acción?\n"
	.string "Es un ejemplo perfecto.\p"
	.string "Ya se le han escapado…\n"
	.string "{STR_VAR_3} POKéMON.\p"
	.string "Pero {STR_VAR_1} espera. No se rinde.\n"
	.string "Así ha de ser para pescar {STR_VAR_2}.\p"
	.string "PRESENTADORA: Entiendo…\p"
	.string "¡Oh! ¡{STR_VAR_1} se ha hecho con un\n"
	.string "escurridizo {STR_VAR_2}!\p"
	.string "¡Se diría que se le van a saltar\n"
	.string "las lágrimas de pura alegría!\p"
	.string "Viéndole, me entran unas ganas\n"
	.string "tremendas de ponerme a pescar.\p"
	.string "Queridos telespectadores, ¿por qué no\n"
	.string "intentamos todos pescar {STR_VAR_2}?\p"
	.string "Os deseo una buena pesca a todos.\n"
	.string "Hasta nuestro próximo programa.$"

gTVPokemonAnglerText01::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "PRESENTADORA: ¡Hola! Hoy vamos\n"
	.string "a aprender cómo pescar {STR_VAR_2}.\p"
	.string "GURÚ PESCADOR, ¿qué consejo puedes\n"
	.string "darnos para atrapar {STR_VAR_2}?\p"
	.string "GURÚ PESCADOR: ¿Pescar {STR_VAR_2}?\n"
	.string "Pues hay que tirar de la\l"
	.string "CAÑA con fuerza.\p"
	.string "¿Has visto a {STR_VAR_1} en acción?\n"
	.string "¿Ves cómo sostiene la CAÑA?\p"
	.string "Ya ha conseguido pescar {STR_VAR_3}\n"
	.string "POKéMON seguidos.\p"
	.string "PRESENTADORA: Impresionante…\n"
	.string "¡Es un as de la CAÑA!\p"
	.string "Al ver su magnífica técnica, me entran\n"
	.string "muchas ganas de ponerme a pescar.\p"
	.string "Queridos telespectadores, ¿por qué no\n"
	.string "intentamos todos pescar {STR_VAR_2}?\p"
	.string "Os deseo una buena pesca a todos.\n"
	.string "Hasta nuestro próximo programa.$"

gTVPokemonTodayFailedText00::
	.string "¡Hola!\p"
	.string "¡Es la hora de POKéMON HOY!\p"
	.string "HERMANA MAYOR: ¡Hola! ¿Está todo el\n"
	.string "mundo de buen humor hoy?\p"
	.string "Hoy vamos a ver al POKéMON\n"
	.string "{STR_VAR_2} de {STR_VAR_1}.\p"
	.string "HERMANO MAYOR: ¡Sí! ¡Eso es lo que\n"
	.string "vamos a hacer!$"

gTVPokemonTodayFailedText01::
	.string "Y, ya que mencionas su nombre,\n"
	.string "¿a que no sabes una cosa?\p"
	.string "PIBITA, ¡he visto a {STR_VAR_1} en\n"
	.string "acción con mis propios ojos!\p"
	.string "PIBITA: ¿Y qué has visto?\p"
	.string "PIBE: Bien, yo tenía que viajar\n"
	.string "a {STR_VAR_2}, ¿no?\p"
	.string "Fue entonces cuando me crucé\n"
	.string "con {STR_VAR_1}, que intentaba atrapar\l"
	.string "al POKéMON {STR_VAR_3}, pero…$"

gTVPokemonTodayFailedText02::
	.string "¡el POKéMON logró escapar!\p"
	.string "Usó este número de POKé BALLS\n"
	.string "para nada: {STR_VAR_2}.\p"
	.string "¡Deberías haber visto la expresión\n"
	.string "de frustración en la cara de {STR_VAR_1}\l"
	.string "cuando el POKéMON huyó!$"

gTVPokemonTodayFailedText03::
	.string "¡{STR_VAR_1} la pifió y debilitó\n"
	.string "al POKéMON!\p"
	.string "Usó este número de POKé BALLS\n"
	.string "para nada: {STR_VAR_2}.\p"
	.string "¡Deberías haber visto la expresión\n"
	.string "de consternación en la cara de {STR_VAR_1}\l"
	.string "cuando el POKéMON se debilitó!$"

gTVPokemonTodayFailedText04::
	.string "PIBITA: ¡Pero bueno!\n"
	.string "¡Eso no está bien!\p"
	.string "¡No deberías burlarte\n"
	.string "de las desgracias ajenas!\p"
	.string "Pobre {STR_VAR_1}…\n"
	.string "¡Qué lástima!\p"
	.string "PIBE: Tienes razón…\n"
	.string "Ha estado mal por mi parte.$"

gTVPokemonTodayFailedText05::
	.string "HERMANA MAYOR: Bufufu…\p"
	.string "HERMANO MAYOR: ¡Eh!\n"
	.string "¡Tú también te has reído!\p"
	.string "HERMANA MAYOR: ¡¿Eh?!\p"
	.string "¡Yo no me he reído!\n"
	.string "¡De verdad que no!\p"
	.string "Ay, pobre {STR_VAR_1}.\n"
	.string "¡Qué pena!\p"
	.string "HERMANO MAYOR: …$"

gTVPokemonTodayFailedText06::
	.string "HERMANA MAYOR: ¡Basta de tonterías!\n"
	.string "Veamos el POKéMON de hoy…\p"
	.string "¿Eh? ¿Ya se nos acaba el tiempo?\p"
	.string "¡Vaya! ¡Hoy no hemos podido hablar de\n"
	.string "ningún POKéMON!\p"
	.string "HERMANO MAYOR: ¡Hasta la próxima!\p"
	.string "HERMANA MAYOR: ¡Eh, no acabes el\n"
	.string "programa sin mí!$"

gTVPokemonTodaySuccessfulText00::
	.string "¡Hola!\p"
	.string "¡Es la hora de POKéMON HOY!\p"
	.string "HERMANA MAYOR: ¡Hola! ¿Está todo el\n"
	.string "mundo de buen humor hoy?\p"
	.string "Hoy vamos a ver al POKéMON\n"
	.string "{STR_VAR_2} de {STR_VAR_1}.\p"
	.string "HERMANO MAYOR: ¡Sí! ¡Eso es lo que\n"
	.string "vamos a hacer!$"

gTVPokemonTodaySuccessfulText01::
	.string "HERMANA MAYOR: ¡{STR_VAR_1} le puso el\n"
	.string "mote {STR_VAR_3} al {STR_VAR_2}!\p"
	.string "¡Parece que {STR_VAR_3} recibe\n"
	.string "buenos cuidados y mucho cariño!$"

gTVPokemonTodaySuccessfulText02::
	.string "HERMANO MAYOR: ¡El ENTRENADOR tuvo\n"
	.string "que lanzar este número de POKé BALLS:\l"
	.string "{STR_VAR_3}!\p"
	.string "¡Al final hizo falta una {STR_VAR_2}\n"
	.string "para capturarlo!$"

gTVPokemonTodaySuccessfulText03::
	.string "PIBITA: Si fue tan fácil de atrapar,\n"
	.string "ha debido de ser el destino el que\l"
	.string "ha unido a {STR_VAR_1} y a {STR_VAR_2}.$"

gTVPokemonTodaySuccessfulText04::
	.string "PIBITA: ¡Guau! ¡Realmente fantástico!\p"
	.string "Pero sabes lo que dicen, cuanto más\n"
	.string "trabajo cuesta atrapar un POKéMON,\l"
	.string "más cariño se le coge…$"

gTVPokemonTodaySuccessfulText05::
	.string "HERMANA MAYOR: ¡El {STR_VAR_2} de\n"
	.string "{STR_VAR_1} es un POKéMON memorable\l"
	.string "porque hizo falta una valiosa MASTER\l"
	.string "BALL!\p"
	.string "HERMANO MAYOR: ¡Guau! ¡Eso es genial!\p"
	.string "HERMANA MAYOR: ¡{STR_VAR_1} debía de\n"
	.string "querer mucho a ese {STR_VAR_2},\l"
	.string "seguro!$"

gTVPokemonTodaySuccessfulText06::
	.string "HERMANO MAYOR: Y ponerle el mote\n"
	.string "{STR_VAR_3} a ese {STR_VAR_2}…\p"
	.string "Te haces una buena idea del talento\n"
	.string "de ENTRENADOR de {STR_VAR_1}.\p"
	.string "HERMANA MAYOR: ¡Opino igual!$"

gTVPokemonTodaySuccessfulText07::
	.string "¡En su lugar, yo pondría ese mote\n"
	.string "a algún {STR_VAR_3}, por ejemplo!\p"
	.string "PIBE: ¡Eso podría ser el inicio\n"
	.string "de una nueva moda!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2}, el {STR_VAR_1}.\n"
	.string "¿No va junto estupendamente?\p"
	.string "Las letras y todo lo demás le pegan\n"
	.string "perfectamente al POKéMON {STR_VAR_1}.\p"
	.string "PIBE: ¡Y tanto!$"

gTVPokemonTodaySuccessfulText09::
	.string "Por lo que sé, ningún ENTRENADOR\n"
	.string "ha llamado jamás {STR_VAR_2}\l"
	.string "a un {STR_VAR_1}.\p"
	.string "PIBE: ¡Esto muestra una vez más su\n"
	.string "extraordinario gusto eligiendo motes!$"

gTVPokemonTodaySuccessfulText10::
	.string "La próxima vez que atrape un POKéMON,\n"
	.string "lo llamaré {STR_VAR_2}.\p"
	.string "PIBE: ¿Sí? ¡Yo también!\n"
	.string "¡Ese mote, {STR_VAR_2}, me chifla!$"

gTVPokemonTodaySuccessfulText11::
	.string "PIBITA: ¡Oh, no!\n"
	.string "¡Mira la hora!\p"
	.string "Me temo que esto es todo por hoy.\n"
	.string "¡Hasta el próximo programa!\p"
	.string "PIBE: ¡Recuerda que el próximo\n"
	.string "POKéMON estrella podría ser el tuyo!$"

SmartShopper_Text_Intro::
	.string "¡Hola!\p"
	.string "Es la hora del POKéCOMPRADOR DEL DÍA.\p"
	.string "ENTREVISTADOR: ¿Cómo estáis todos?\p"
	.string "Hoy vamos a visitar una tienda\n"
	.string "en {STR_VAR_2}.\p"
	.string "Comprobemos qué se ha estado\n"
	.string "vendiendo últimamente.$"

SmartShopper_Text_ClerkNormal::
	.string "Entrevistemos al encargado para\n"
	.string "sacar algo de información.\p"
	.string "Hola, ¿qué tal va el negocio?\p"
	.string "ENCARGADO: Oh, de rechupete.\p"
	.string "Últimamente vendemos {STR_VAR_2}\n"
	.string "estupendamente.\p"
	.string "De hecho, el otro día {STR_VAR_1}, sin ir\n"
	.string "más lejos, compró {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "ENTREVISTADOR: ¿El ENTRENADOR\n"
	.string "compró {STR_VAR_3} {STR_VAR_2}?\l"
	.string "¡Menudo cargamento!\p"
	.string "Si me permite, {STR_VAR_1} debía de\n"
	.string "estar abasteciéndose para un largo\l"
	.string "viaje a lugares lejanos.\p"
	.string "¡Para viajar, los {STR_VAR_2} son tan\n"
	.string "importantes!$"

SmartShopper_Text_RandomComment2::
	.string "ENTREVISTADOR: Hablando del objeto\n"
	.string "{STR_VAR_2}, yo compré {STR_VAR_3}\l"
	.string "últimamente.\p"
	.string "¡Al fin y al cabo, {STR_VAR_2} es\n"
	.string "un gran objeto!$"

SmartShopper_Text_RandomComment3::
	.string "ENTREVISTADOR: ¡¿{STR_VAR_2}?!\n"
	.string "¡¿Y encima {STR_VAR_3}?!\p"
	.string "Nunca pensé que nadie podría\n"
	.string "comprar tanto de eso.\p"
	.string "Yo sólo me puedo comprar una\n"
	.string "o dos unidades cada vez…$"

SmartShopper_Text_RandomComment4::
	.string "ENTREVISTADOR: ¡Una vez compré\n"
	.string "{STR_VAR_2} y un montón, además!\p"
	.string "Pero resultó ser demasiado.\n"
	.string "Al final me arrepentí…\p"
	.string "Desde entonces sólo compro lo\n"
	.string "estrictamente necesario…\p"
	.string "¡Huy!\p"
	.string "¡Si yo no tengo que hablar de mí!$"

SmartShopper_Text_SecondItem::
	.string "ENCARGADO: ¡{STR_VAR_1} también compró\n"
	.string "{STR_VAR_2} y nada menos que {STR_VAR_3}!\p"
	.string "ENTREVISTADOR: Muy inteligente.\n"
	.string "{STR_VAR_2} es una gran elección.$"

SmartShopper_Text_ThirdItem::
	.string "ENCARGADO: Y el ENTRENADOR también\n"
	.string "compró {STR_VAR_3} del objeto\l"
	.string "{STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "ENCARGADO: Además, fue durante\n"
	.string "las rebajas. Una gran compra.$"

SmartShopper_Text_OutroNormal::
	.string "ENTREVISTADOR: Hmm… ¡{STR_VAR_1}\n"
	.string "parece toda una experta en buenas\l"
	.string "compras!\p"
	.string "En total, las compras de {STR_VAR_1}\n"
	.string "sumaron…\p"
	.string "¡¿¥{STR_VAR_2}?! ¡Qué cifra tan\n"
	.string "asombrosa!\p"
	.string "¡Ups! ¡Se nos acaba el tiempo! ¡Hasta\n"
	.string "la próxima emisión!$"

SmartShopper_Text_IsVIP::
	.string "ENCARGADO: No hay mejor cliente que\n"
	.string "{STR_VAR_1}. No cabe ninguna duda.$"

SmartShopper_Text_ClerkMax::
	.string "Entrevistemos al encargado para\n"
	.string "saber más.\p"
	.string "Hola, ¿cómo va el negocio?\p"
	.string "ENCARGADO: Ay, el negocio va\n"
	.string "increíble. Casi nos desborda.\p"
	.string "Últimamente, un ENTRENADOR llamado\n"
	.string "{STR_VAR_1} compró el objeto\l"
	.string "{STR_VAR_2} al por mayor.\p"
	.string "El ENTRENADOR casi agotó nuestras\n"
	.string "existencias de {STR_VAR_2}.\p"
	.string "Nunca imaginé que un cliente fuera a\n"
	.string "necesitar tantos {STR_VAR_2}. ¡Es\l"
	.string "inaudito!\p"
	.string "ENTREVISTADOR: ¿Entonces serán unos\n"
	.string "100 o 200 vendidos?\p"
	.string "ENCARGADO: ¡Oh, no, muchos más!\p"
	.string "ENTREVISTADOR: ¡Madre mía!\n"
	.string "¡{STR_VAR_1} debe de ser un cliente\l"
	.string "especial!\p"
	.string "ENCARGADO: {STR_VAR_1} es un cliente\n"
	.string "VIP, sin ninguna duda.$"

SmartShopper_Text_OutroMax::
	.string "ENTREVISTADOR: Mmmm…\n"
	.string "Es absolutamente increíble…\p"
	.string "¿Pero por qué querría ningún\n"
	.string "ENTRENADOR tal cantidad?\p"
	.string "¿Por qué?\p"
	.string "Es un misterio insondable, pero no\n"
	.string "tenemos tiempo de investigarlo.\l"
	.string "¡Hasta el próximo programa!\p"
	.string "Aunque {STR_VAR_1} me desconcierta…$"

gTVWorldOfMastersText00::
	.string "EL MUNDO de los MAESTROS\p"
	.string "Hola, telespectadores.\p"
	.string "Quizá conozcáis a un ENTRENADOR\n"
	.string "llamado {STR_VAR_1}.\p"
	.string "{STR_VAR_1} es famoso por ser un\n"
	.string "maestro capturando POKéMON.\p"
	.string "La búsqueda de POKéMON de\n"
	.string "{STR_VAR_1} se basa por completo en\l"
	.string "rastrear a pie.\p"
	.string "Un día memorable, el ENTRENADOR\n"
	.string "recorrió unos {STR_VAR_2} pasos.\p"
	.string "¡El total de POKéMON capturados ese\n"
	.string "día llegó a la impresionante cifra de\l"
	.string "{STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Tamaña proeza ha debido de ser\n"
	.string "posible gracias a la confianza\l"
	.string "que le tiene su {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Atrapó el último {STR_VAR_3} del día\n"
	.string "cerca de {STR_VAR_2}.\p"
	.string "Ese POKéMON parece ser especialmente\n"
	.string "bueno obteniendo récords.\p"
	.string "Todo ENTRENADOR cualificado\n"
	.string "debería enfrentarse a este POKéMON.\p"
	.string "Eso es todo por hoy.\n"
	.string "¡Hasta el próximo programa!$"

gTVTodaysRivalTrainerText00::
	.string "¡MI RIVAL HOY, TU RIVAL MAÑANA!\p"
	.string "¡Hola, ENTRENADORES POKéMON!\n"
	.string "¿Cómo estáis todos?\p"
	.string "¡Hoy, como solemos hacer a menudo,\n"
	.string "analizaremos a uno de nuestros rivales!$"

gTVTodaysRivalTrainerText07::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que ahora anda por {STR_VAR_3}.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está en una BASE SECRETA.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "El rival de hoy es {STR_VAR_1}.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} POKéMON en la POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está ahora en el ferry.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} POKéMON en la POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "¿Y con cuántas MEDALLAS cuenta\n"
	.string "ya nuestro rival? ¡Pues con {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Pero nuestro rival aún no\n"
	.string "ha obtenido ninguna MEDALLA.$"

gTVTodaysRivalTrainerText03::
	.string "Eso sí, no ha obtenido ningún SÍMBOLO\n"
	.string "del FRENTE de BATALLA por el momento.$"

gTVTodaysRivalTrainerText04::
	.string "Veamos cuántos símbolos del\n"
	.string "FRENTE de BATALLA posee.\p"
	.string "Símbolos de oro: ¡{STR_VAR_1}!\n"
	.string "Símbolos de plata: ¡{STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "El FRENTE de BATALLA ha recompensado\n"
	.string "a nuestro rival con PUNTOS de BATALLA.\l"
	.string "Concretamente, ha obtenido {STR_VAR_1} PB.$"

gTVTodaysRivalTrainerText06::
	.string "Bueno, ¿qué tal lo estáis haciendo\n"
	.string "vosotros comparado con {STR_VAR_1}?\p"
	.string "¡La aventura aún no ha acabado!\p"
	.string "¡Queridos e intrépidos ENTRENADORES!\p"
	.string "¡No os durmáis y seguid ampliando\n"
	.string "esa ventaja sobre vuestros rivales!$"

TrendWatcher_Text_Intro::
	.string "¡LO MÁS AZULIZA, LO MÁS IN!\p"
	.string "PRESENTADOR: ¿Cómo lo lleváis, gente?\n"
	.string "Aquí os ponemos al día de lo que se dice\l"
	.string "entre los más guays de AZULIZA.\p"
	.string "Hoy, nuestro invitado es este genio\n"
	.string "de la tercera edad que presume de\l"
	.string "saber todo, todito sobre AZULIZA.\p"
	.string "Anciano: Ése soy yo.\p"
	.string "PRESENTADOR: Vamos al grano, escribano.\p"
	.string "¿Qué es lo que más les mola decir\n"
	.string "a los guays de AZULIZA?\p"
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "PRESENTADOR: ¿Has dicho…\n"
	.string "{STR_VAR_1} {STR_VAR_2}?\p"
	.string "Anciano: Bueno, eso decían.\p"
	.string "Aunque {STR_VAR_1} {STR_VAR_2}\n"
	.string "nunca acabó de cuajar.\p"
	.string "¿Y quieres saber por qué?\p"
	.string "PRESENTADOR: Ah, no. Lo que queremos\n"
	.string "saber es lo que más se lleva ahora…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "es lo que {STR_VAR_3} de VILLA RAÍZ\l"
	.string "me dijo que estaba de moda…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "es lo que {STR_VAR_3} de VILLA RAÍZ\l"
	.string "me dijo que estaba de moda…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Pero la cosa no acabó de pegar fuerte.\p"
	.string "¡Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "¡Concurso {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Traté de enseñárselo a toda la peña\n"
	.string "lo mejor que pude, pero…\p"
	.string "Quizás eso de {STR_VAR_1} rallaba\n"
	.string "un poco…\p"
	.string "PRESENTADOR: Oye, abuelo, te he dicho\n"
	.string "que yo quiero saber lo que mola ahora…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Anciano: ¡{STR_VAR_3}!\n"
	.string "¡Anda, dime algo que tenga más fuerza\l"
	.string "que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Anciano: ¡{STR_VAR_3}!\n"
	.string "¡Anda, dime algo que tenga más fuerza\l"
	.string "que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "PRESENTADOR: Eh… ¡Bueno, ahí lo tenéis,\n"
	.string "todos vosotros, amigos de lo más!\p"
	.string "{STR_VAR_1} {STR_VAR_2}… Esto…\n"
	.string "¡No acabó de cuajar en AZULIZA!\p"
	.string "No hay tiempo para más. ¡Nos vemos!\p"
	.string "Anciano: ¡{STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "¡LOS TESOROS DE HOENN!\p"
	.string "¡Hola, amigos y amigas televidentes!\n"
	.string "¿Seguís buscando ese objeto perdido?\p"
	.string "¡Como siempre, vamos a examinar\n"
	.string "las cartas que nos llegan de testigos\l"
	.string "que al menos han visto alguno!\p"
	.string "Hoy vamos a leer esta carta.\n"
	.string "Dice así: “¡{STR_VAR_1}, qué envidia!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "¡Vaya, será mejor que veamos esta\n"
	.string "carta! Os la leo.\p"
	.string "…Queridos INVESTIGADORES,\n"
	.string "espero que estéis bien.\p"
	.string "Hace poco vi a {STR_VAR_2} por\n"
	.string "{STR_VAR_3}.\p"
	.string "El ENTRENADOR encontró el objeto\n"
	.string "{STR_VAR_1}. Me dio envidia.\p"
	.string "…En fin, ¡buen trabajo, {STR_VAR_2}!\p"
	.string "Telespectadores, que esto os motive\n"
	.string "a activar vuestros ZAHORÍES y buscar.\p"
	.string "¡Espero emocionantes noticias\n"
	.string "de todos vosotros!$"

gTVHoennTreasureInvestigatorsText02::
	.string "¡Vaya, será mejor que veamos esta\n"
	.string "carta! Os la leo.\p"
	.string "…Queridos INVESTIGADORES,\n"
	.string "espero que estéis bien.\p"
	.string "Hace poco vi a {STR_VAR_2} en un ferry.\p"
	.string "El ENTRENADOR encontró el objeto\n"
	.string "{STR_VAR_1}. Me dio envidia.\p"
	.string "…En fin, ¡buen trabajo, {STR_VAR_2}!\p"
	.string "Telespectadores, que esto os motive\n"
	.string "a activar vuestros ZAHORÍES y buscar.\p"
	.string "¡Espero emocionantes noticias\n"
	.string "de todos vosotros!$"

gTVFindThatGamerText00::
	.string "¡CASI SÍ, CASI NO!\p"
	.string "¡Hola, incansables jugadores!\n"
	.string "¿Cómo va la suerte en esa {STR_VAR_2}?\p"
	.string "Como solemos hacer, hoy nos hemos\n"
	.string "fijado en alguien muy especial que\l"
	.string "ha visitado nuestro CASINO.\p"
	.string "Hoy, nuestro jugador número 1 es…\n"
	.string "¡{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "¡{STR_VAR_1} ganó en la {STR_VAR_2}\n"
	.string "nada menos que {STR_VAR_3} FICHAS!\p"
	.string "“Cuando viene, hay que asegurarse\n"
	.string "de tener suficientes FICHAS.”\p"
	.string "¡Eso es lo que dicen los crupier del\n"
	.string "CASINO cuando hablan de {STR_VAR_1}!\p"
	.string "Queridos amigos, controlad las FICHAS\n"
	.string "como hace {STR_VAR_1} cuando vengáis\l"
	.string "al CASINO a jugar a la {STR_VAR_2}.\p"
	.string "¡Y eso es todo desde aquí, desde\n"
	.string "el CASINO donde “casi” no pierde nadie!\p"
	.string "¡Hasta la próxima!$"

gTVFindThatGamerText02::
	.string "¡{STR_VAR_1} jugó a la {STR_VAR_2}\n"
	.string "y perdió {STR_VAR_3} FICHAS!\p"
	.string "“Cuando viene por aquí,\n"
	.string "hacemos el agosto en FICHAS.”\p"
	.string "¡Eso es lo que dicen los crupier del\n"
	.string "CASINO cuando hablan de {STR_VAR_1}!$"

gTVFindThatGamerText03::
	.string "Queridos amigos, controlad las FICHAS\n"
	.string "como hace {STR_VAR_1} cuando vengáis\l"
	.string "al CASINO a jugar a la {STR_VAR_2}.\p"
	.string "¡Y eso es todo desde aquí, desde\n"
	.string "el CASINO donde “casi” no pierde nadie!\p"
	.string "¡Hasta la próxima!$"

gTVBreakingNewsText00::
	.string "¡ESPECIAL INFORMATIVO!$"

gTVBreakingNewsText01::
	.string "¡{STR_VAR_2} raro capturado por\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Conectamos en directo desde las\n"
	.string "cercanías de {STR_VAR_3}!\p"
	.string "¡{STR_VAR_1} acaba de capturar aquí\n"
	.string "un {STR_VAR_2} raro!$"

gTVBreakingNewsText02::
	.string "Cuando {STR_VAR_1} se encontró\n"
	.string "con el raro ejemplar de {STR_VAR_2},\l"
	.string "sacó a su POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Capturarlo le costó\n"
	.string "{STR_VAR_1} de sus POKé BALLS.\p"
	.string "Al final, logró encerrar al POKéMON\n"
	.string "en una {STR_VAR_2}.$"

gTVBreakingNewsText04::
	.string "En ese instante, {STR_VAR_2} resonó\n"
	.string "con los rugidos de alegría triunfal de\l"
	.string "{STR_VAR_1}.\p"
	.string "Debo decir que siento un poco de\n"
	.string "envidia de {STR_VAR_1}. Me encantaría\l"
	.string "rugir también.\p"
	.string "…¡Termina así la conexión en directo\n"
	.string "desde el feliz escenario!$"

gTVBreakingNewsText05::
	.string "¡{STR_VAR_1} no logra capturar un\n"
	.string "{STR_VAR_2} raro!\p"
	.string "¡Conectamos en directo desde las\n"
	.string "cercanías de {STR_VAR_3}!\p"
	.string "¡Fue aquí donde {STR_VAR_1} no logró\n"
	.string "capturar un {STR_VAR_2} raro!$"

gTVBreakingNewsText06::
	.string "Cuando {STR_VAR_1} se encontró\n"
	.string "con el raro ejemplar de {STR_VAR_2},\l"
	.string "sacó a su POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "Cuando tenía todo a su favor, ordenó\n"
	.string "a {STR_VAR_2} usar {STR_VAR_1}.\p"
	.string "Sin quererlo, ese movimiento debilitó\n"
	.string "al POKéMON que pretendía capturar…$"

gTVBreakingNewsText12::
	.string "Sin embargo, {STR_VAR_1} debió de\n"
	.string "pasarlo mal al ver al {STR_VAR_2} raro.\p"
	.string "Quizás por eso ordenó a {STR_VAR_3}\n"
	.string "atacar.\p"
	.string "Sin quererlo, al atacar debilitó\n"
	.string "al POKéMON que pretendía capturar…$"

gTVBreakingNewsText08::
	.string "En ese instante, {STR_VAR_2}\n"
	.string "resonó con los gritos de frustración\l"
	.string "de {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "Sin embargo, a {STR_VAR_1} parece que\n"
	.string "se le acabaron las POKé BALLS.\p"
	.string "El ENTRENADOR tuvo que abandonar\n"
	.string "el combate con el {STR_VAR_2} raro.\p"
	.string "En ese instante, {STR_VAR_3}\n"
	.string "resonó con los gritos de frustración\l"
	.string "de {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "Sin embargo, el {STR_VAR_2} huyó\n"
	.string "sin previo aviso.\p"
	.string "En ese instante, {STR_VAR_3}\n"
	.string "resonó con los gritos de frustración\l"
	.string "de {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "Debo reconocer que yo también comparto\n"
	.string "la desesperación de {STR_VAR_1}…\p"
	.string "Y, con este lamento, nos despedimos\n"
	.string "de todos hasta una nueva ocasión.$"

gTVSecretBaseVisitText00::
	.string "¡Hola, queridos amigos!\n"
	.string "Es hora de hacer otra de nuestras\l"
	.string "VISITAS A LA BASE SECRETA.\p"
	.string "Hoy visitaremos la BASE SECRETA\n"
	.string "de {STR_VAR_1}.\p"
	.string "¿Qué toque especial le habrá dado\n"
	.string "{STR_VAR_1} a su BASE SECRETA?\p"
	.string "¡Vamos a verlo!\n"
	.string "Mmm…$"

gTVSecretBaseVisitText01::
	.string "¡Oh!\n"
	.string "¡Qué maravilla!\p"
	.string "Aquí ha puesto su {STR_VAR_2}…\n"
	.string "¡Vaya, no esperaba encontrar aquí\l"
	.string "una cosa así!$"

gTVSecretBaseVisitText02::
	.string "¡Oh!\n"
	.string "¡Fantástico!\p"
	.string "¡No hay ni un solo mueble!\n"
	.string "¡Ni siquiera un adorno!\p"
	.string "¡Esto sí que es una declaración\n"
	.string "de principios decorativos!\p"
	.string "¡Minimalismo extremo, sí,\n"
	.string "un minimalismo impresionante!\p"
	.string "Me descubro ante ti, {STR_VAR_1}.\n"
	.string "¡Quién si no!$"

gTVSecretBaseVisitText03::
	.string "¡Ah, ya veo!\n"
	.string "¡Lo veo perfectamente!\p"
	.string "Has puesto aquí tu {STR_VAR_2}…\n"
	.string "¡La idea está clara!$"

gTVSecretBaseVisitText04::
	.string "¡Oh! ¡Ya lo veo!\n"
	.string "¡Lo veo con total claridad!\p"
	.string "¡Este espacio se mantiene\n"
	.string "deliberadamente libre de muebles!\p"
	.string "¡Transmite un mensaje eficaz!$"

gTVSecretBaseVisitText05::
	.string "¡Aaaaah!\p"
	.string "¡Excelente poner su {STR_VAR_2}\n"
	.string "al lado de su {STR_VAR_3}!\p"
	.string "¡El resultado es sin duda\n"
	.string "una combinación magnífica!$"

gTVSecretBaseVisitText06::
	.string "¡Aaaaah!\p"
	.string "Al colocar aquí su {STR_VAR_2},\n"
	.string "justo aquí…\p"
	.string "¡Su presencia llena por completo\n"
	.string "la BASE SECRETA!$"

gTVSecretBaseVisitText07::
	.string "¡Aaaaah!\p"
	.string "Aquí no hay colocado nada.\p"
	.string "Este espacio vacío tiene un impacto\n"
	.string "en toda la BASE SECRETA.$"

gTVSecretBaseVisitText08::
	.string "¡Oh!\n"
	.string "¡Ahí viene {STR_VAR_1}!\l"
	.string "¡Desafiemos al ENTRENADOR!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "¡Extraordinario!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus POKéMON han estado realmente\n"
	.string "a la altura del título de CAMPEÓN.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme dureza.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText10::
	.string "¡Bravo!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus POKéMON han estado\n"
	.string "realmente magníficos.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme tenacidad.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText11::
	.string "¡Sí!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus POKéMON sin duda han sido\n"
	.string "entrenados de manera equilibrada.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme seriedad.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText12::
	.string "¡Bien, muy bien!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus POKéMON han demostrado tener\n"
	.string "un gran potencial de crecimiento.\p"
	.string "Sin duda {STR_VAR_1} tiene depositadas\n"
	.string "en ellos todas sus esperanzas.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText13::
	.string "Debo decir que ¡qué magnífica\n"
	.string "BASE SECRETA!\p"
	.string "Telespectadores, si tenéis ocasión,\n"
	.string "visitad la BASE SECRETA de {STR_VAR_1}.\p"
	.string "¡Hasta la próxima, os digo adiós!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "¡Qué emoción!\n"
	.string "¡Qué nervios!\p"
	.string "Es el… \n"
	.string "¡ESPECIAL LOTERÍA POKéMON!\p"
	.string "¡Hola! Estamos aquí, en directo, desde\n"
	.string "el DESPACHO de LOTERÍA POKéMON\l"
	.string "situado en la planta baja del CENTRO\l"
	.string "COMERCIAL de CALAGUA.\p"
	.string "¡Como siempre sucede, hoy ha aparecido\n"
	.string "otro afortunado ENTRENADOR!\p"
	.string "En esta ocasión, la suerte ha ido para…\n"
	.string "¡{STR_VAR_1}!\p"
	.string "¡{STR_VAR_1} ha ganado nada menos que\n"
	.string "el {STR_VAR_2} y se lleva a casa\l"
	.string "su correspondiente {STR_VAR_3}!\p"
	.string "¡{STR_VAR_1}!\n"
	.string "¡Enhorabuena!\p"
	.string "Queridos amigos, no lo olvidéis \n"
	.string "¡vosotros podéis ser los siguientes!\p"
	.string "¡Todos los que trabajamos aquí\n"
	.string "esperamos vuestra visita!\p"
	.string "¡Ha sido una retransmisión en directo\n"
	.string "desde el CENTRO COMERCIAL de CALAGUA,\l"
	.string "donde encontraréis la más amplia\l"
	.string "selección de objetos de todo HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "¡EL SEMINARIO de COMBATE POKéMON!\p"
	.string "Analizamos combates para ver qué\n"
	.string "lecciones podemos aprender de otros.\p"
	.string "El caso de estudio de hoy es el\n"
	.string "combate de {STR_VAR_1}.\p"
	.string "El {STR_VAR_2} de {STR_VAR_1} combatía\n"
	.string "contra un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Y usó el movimiento {STR_VAR_3}\n"
	.string "contra {STR_VAR_2}…\p"
	.string "Mmm… ¡Pero {STR_VAR_1}!\n"
	.string "¡Eso es justo lo que no debiste hacer!$"

gTVThePokemonBattleSeminarText02::
	.string "Aparte de ese movimiento mal empleado,\n"
	.string "ese {STR_VAR_1} también conocía$"

gTVThePokemonBattleSeminarText03::
	.string "los movimientos {STR_VAR_1},\n"
	.string "{STR_VAR_2} y {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "los movimientos {STR_VAR_1}\n"
	.string "y {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "el movimiento {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Así que, en esa situación, ¿qué debería\n"
	.string "haber usado un buen ENTRENADOR?…\p"
	.string "¡Claro!\n"
	.string "¡El movimiento {STR_VAR_1}!\p"
	.string "El movimiento {STR_VAR_1} habría\n"
	.string "sido mucho mejor que {STR_VAR_2}.\p"
	.string "¡Queridos telespectadores, aprended de\n"
	.string "este error y combatid con inteligencia!\p"
	.string "¡Hasta el próximo programa!$"

gTVTrainerFanClubText00::
	.string "¡Todos juntos!\n"
	.string "¡CLUB de FANS de ENTRENADORES!\p"
	.string "PRESENTADOR: ¿Cómo va ese ritmo?\n"
	.string "Hoy hemos reunido a los fans del\l"
	.string "superpopular ENTRENADOR {STR_VAR_1}.\p"
	.string "FANS: ¡Wuuuuaaaaah!\p"
	.string "FANS: ¡{STR_VAR_1}!\p"
	.string "PRESENTADOR: ¡Todos!\n"
	.string "¡¿Qué os parece {STR_VAR_1}?!\p"
	.string "FANS: ¡Adoramos a {STR_VAR_1}!\p"
	.string "PRESENTADOR: ¡¿Qué es lo que adoráis\n"
	.string "de {STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: ¡Su forma tan genial de\n"
	.string "lanzar POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: ¡Su adorable forma de correr!$"

gTVTrainerFanClubText03::
	.string "FANS: ¡Cómo se pone duro el\n"
	.string "ENTRENADOR cuando la cosa se pone\l"
	.string "dura!$"

gTVTrainerFanClubText04::
	.string "FANS: ¡Los conocimientos del\n"
	.string "ENTRENADOR sobre POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: ¡La bondad del ENTRENADOR\n"
	.string "hacia todos los POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: ¡Las asombrosas técnicas del\n"
	.string "ENTRENADOR montando en BICI!$"

gTVTrainerFanClubText07::
	.string "FANS: ¡El impresionante estilo de\n"
	.string "compra de objetos del ENTRENADOR!$"

gTVTrainerFanClubText08::
	.string "FANS: ¡La encantadora forma del\n"
	.string "ENTRENADOR de poner motes a los\l"
	.string "POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: ¡El ingenioso estilo del\n"
	.string "ENTRENADOR decorando una BASE\l"
	.string "SECRETA!$"

gTVTrainerFanClubText10::
	.string "FANS: ¡La audaz forma del\n"
	.string "ENTRENADOR de usar MTs!$"

gTVTrainerFanClubText11::
	.string "PRESENTADOR: Ya lo veis, tenía razón:\n"
	.string "¡{STR_VAR_1} está pegando muy fuerte!\p"
	.string "Entre los FANS de {STR_VAR_1},\n"
	.string "hay un grito muy especial.\p"
	.string "PRESENTADOR: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "FANS: ¡{STR_VAR_2}!\p"
	.string "FANS: ¡{STR_VAR_3}!\p"
	.string "FANS: ¡{STR_VAR_2}!\p"
	.string "FANS: ¡{STR_VAR_3}!\p"
	.string "PRESENTADOR: Eso es, si alguien dice,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Responded: “¡{STR_VAR_2}!\n"
	.string "¡{STR_VAR_3}!”\p"
	.string "¡Suena de una manera especial!\n"
	.string "¡Ahora veo por qué la gente\l"
	.string "se hace FAN de {STR_VAR_1}!\p"
	.string "¡Y ahora todos, desde vuestras casas!\n"
	.string "¡Gritemos juntos a la vez!\p"
	.string "PRESENTADOR: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "FANS: ¡{STR_VAR_2}!\p"
	.string "FANS: ¡{STR_VAR_3}!\p"
	.string "FANS: ¡{STR_VAR_2}!\p"
	.string "FANS: ¡{STR_VAR_3}!\p"
	.string "PRESENTADOR: Y ahora me despido\n"
	.string "dándole las gracias a todos los\l"
	.string "FANS de {STR_VAR_1} por venir.\l"
	.string "¡Hasta otra!\p"
	.string "PRESENTADOR: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "FANS: ¡{STR_VAR_2}!\p"
	.string "FANS: ¡{STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "¡DESCUBRE a los MONOS! ¡POKéMON con\n"
	.string "CINTAS!\p"
	.string "Hola, mis dulces telespectadores.\p"
	.string "¡Seguro que estáis de acuerdo: un\n"
	.string "POKéMON con CINTAS es simplemente\l"
	.string "divino!\p"
	.string "Hoy quiero compartir con vosotros un\n"
	.string "POKéMON precioso que vi mientras\l"
	.string "paseaba por la ciudad.\p"
	.string "El POKéMON bonito de hoy es el\n"
	.string "{STR_VAR_2} de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "¿Que cuántas CINTAS llevaba puestas?\n"
	.string "¡Esa monada de {STR_VAR_2} llevaba {STR_VAR_3}!\p"
	.string "Creo que eso dice mucho sobre cuánto\n"
	.string "adora {STR_VAR_1} a su POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "¡{STR_VAR_2} llevaba puestas nada más\n"
	.string "y nada menos que {STR_VAR_3} CINTAS!\p"
	.string "Creo que eso lo dice todo sobre cuánto\n"
	.string "adora {STR_VAR_1} a su POKéMON.$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "¡{STR_VAR_2} lleva puestas {STR_VAR_3} CINTAS!\n"
	.string "¿Podéis creerlo?\p"
	.string "¡Lo de {STR_VAR_1} es\n"
	.string "un amor de coleccionista!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Pero echemos un vistazo de cerca\n"
	.string "a las CINTAS que lleva {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Llama especialmente la atención\n"
	.string "la CINTA CAMPEÓN.\p"
	.string "{STR_VAR_2} la recibió al entrar\n"
	.string "en el HALL de la FAMA.\p"
	.string "Realmente consigue realzar\n"
	.string "el valor de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA CAMPEÓN!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Llama especialmente la atención\n"
	.string "la CINTA CARISMA.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el CONCURSO de CARISMA.\p"
	.string "Realmente consigue realzar\n"
	.string "el carisma de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA CARISMA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Llama especialmente la atención\n"
	.string "la CINTA BELLEZA.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el CONCURSO de BELLEZA.\p"
	.string "Realmente consigue realzar\n"
	.string "la belleza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA BELLEZA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Llama especialmente la atención\n"
	.string "la CINTA DULZURA.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el CONCURSO de DULZURA.\p"
	.string "Realmente consigue realzar\n"
	.string "la dulzura de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA DULZURA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Llama especialmente la atención\n"
	.string "la CINTA INGENIO.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el CONCURSO de INGENIO.\p"
	.string "Realmente consigue realzar\n"
	.string "el ingenio de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA INGENIO!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Llama especialmente la atención\n"
	.string "la CINTA DUREZA.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el CONCURSO de DUREZA.\p"
	.string "Realmente consigue realzar\n"
	.string "la dureza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA DUREZA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Llama especialmente la atención\n"
	.string "la CINTA TRIUNFO.\p"
	.string "{STR_VAR_2} la recibió por sus hazañas\n"
	.string "en la TORRE BATALLA.\p"
	.string "Realmente consigue realzar\n"
	.string "la grandeza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA TRIUNFO!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Llama especialmente la atención\n"
	.string "la CINTA VICTORIA.\p"
	.string "{STR_VAR_2} la recibió por sus hazañas\n"
	.string "en la TORRE BATALLA.\p"
	.string "Realmente consigue realzar\n"
	.string "la enorme grandeza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA VICTORIA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Llama especialmente la atención\n"
	.string "la CINTA del ARTISTA.\p"
	.string "{STR_VAR_2} la recibió por hacer\n"
	.string "de modelo para un artista.\p"
	.string "Realmente consigue realzar\n"
	.string "el encanto de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA del ARTISTA!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Llama especialmente la atención\n"
	.string "la CINTA del ESFUERZO.\p"
	.string "{STR_VAR_2} la recibió por su gran\n"
	.string "dedicación y su trabajo.\p"
	.string "Realmente consigue realzar\n"
	.string "la determinación de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la CINTA del ESFUERZO!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_Outro::
	.string "¡Ay!…\p"
	.string "CINTAS y POKéMON…\n"
	.string "¡Se complementan tan bien!\p"
	.string "Antes de desmayarme,\n"
	.string "¡adiós y que la belleza os posea!$"

gTVPokemonNewsBattleFrontierText00::
	.string "¡Saludos a nuestros telespectadores!\n"
	.string "Es la hora de las NOTICIAS POKéMON.\p"
	.string "Nos ha llegado la última hora\n"
	.string "desde el FRENTE de BATALLA.$"

gTVPokemonNewsBattleFrontierText01::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE INDIVIDUAL\l"
	.string "de la TORRE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE DOBLE\l"
	.string "de la TORRE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE MÚLTIPLE\l"
	.string "de la TORRE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE MULTIJUGADOR\l"
	.string "con CONEXIÓN de la TORRE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el TORNEO de COMBATES INDIVIDUALES\l"
	.string "de la CÚPULA BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el TORNEO de COMBATES DOBLES\l"
	.string "de la CÚPULA BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el TORNEO de COMBATES\l"
	.string "con TRUEQUE INDIVIDUALES\l"
	.string "de la FÁBRICA BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el TORNEO de COMBATES\l"
	.string "con TRUEQUE DOBLES\l"
	.string "de la FÁBRICA BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío de la ELECCIÓN de COMBATES\l"
	.string "de la SIERPE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del TORNEO con JUEZ\l"
	.string "del DOJO BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE sin TUTELA\l"
	.string "INDIVIDUAL del PALACIO BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del COMBATE sin TUTELA\l"
	.string "DOBLE del PALACIO BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío de la EXPEDICIÓN de\l"
	.string "COMBATES de la PIRÁMIDE BATALLA.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "¡Y a los tres POKéMON: {STR_VAR_1},\n"
	.string "{STR_VAR_2} y {STR_VAR_3}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText15::
	.string "¡Y a los dos POKéMON: {STR_VAR_1}\n"
	.string "y {STR_VAR_2}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText16::
	.string "¡Y a los cuatro POKéMON: {STR_VAR_1}!\p"
	.string "¡{STR_VAR_2}!\p"
	.string "¡{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "¡Y {STR_VAR_1}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText18::
	.string "¡Esperemos que {STR_VAR_1} y sus leales\n"
	.string "POKéMON sigan cosechando éxitos!\p"
	.string "¡Esto es todo desde NOTICIAS POKéMON!$"

gTVWhatsNo1InHoennTodayText00::
	.string "¿QUIÉN ES EL N.º 1 DE HOENN?\n"
	.string "¡Sí, aquí estamos otra vez!\p"
	.string "¡Hola, amigos telespectadores!\n"
	.string "¿Estáis esforzándoos todos al máximo\l"
	.string "en lo que estáis haciendo?\p"
	.string "¡Veamos a quién nombramos hoy el\n"
	.string "ENTRENADOR más constante del día!\p"
	.string "El ENTRENADOR n.º 1\n"
	.string "de hoy es… ¡{STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "En un solo día, {STR_VAR_1} hizo girar\n"
	.string "las TRAGAPERRAS del CASINO\l"
	.string "{STR_VAR_2} veces.\p"
	.string "Mientras jugaba, se oyó a {STR_VAR_1}\n"
	.string "murmurar: “Para mí, los rodillos ni\l"
	.string "siquiera se mueven…” ¿A que es\l"
	.string "interesante?$"

gTVWhatsNo1InHoennTodayText02::
	.string "¿Cuántas veces jugó {STR_VAR_1}\n"
	.string "a la RULETA del CASINO\l"
	.string "en un solo día? ¡{STR_VAR_2}!\p"
	.string "Mientras jugaba, {STR_VAR_1} gritó:\n"
	.string "“¡Que decida la bola!”\p"
	.string "Su mirada estaba fija y en el rostro\n"
	.string "se podía apreciar la concentración.$"

gTVWhatsNo1InHoennTodayText03::
	.string "¡En un solo día, {STR_VAR_1} se enfrentó\n"
	.string "a {STR_VAR_2} POKéMON salvajes!\p"
	.string "Al parecer, los POKéMON de {STR_VAR_1}\n"
	.string "se han hecho increíblemente fuertes.\p"
	.string "¡Están ansiosos por combatir como sea\n"
	.string "en cualquier lugar y a cualquier hora!$"

gTVWhatsNo1InHoennTodayText04::
	.string "¡En un solo día, {STR_VAR_1} hizo girar\n"
	.string "la LICUABAYAS {STR_VAR_2} veces!\p"
	.string "Hacia el final, hasta {STR_VAR_1}\n"
	.string "parecía marearse.\p"
	.string "¡El ENTRENADOR se tambaleaba\n"
	.string "como un SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "¡En un solo día, {STR_VAR_1} plantó\n"
	.string "{STR_VAR_2} BAYAS!\p"
	.string "Como resultado, la ropa de {STR_VAR_1}\n"
	.string "quedó llena de tierra.\p"
	.string "Donde plantó el ENTRENADOR han\n"
	.string "brotado incontables flores.\p"
	.string "Se dice que las flores calman\n"
	.string "las emociones de las personas.$"

gTVWhatsNo1InHoennTodayText06::
	.string "¡En un solo día, {STR_VAR_1} recogió\n"
	.string "{STR_VAR_2} BAYAS!\p"
	.string "¡La MOCHILA de {STR_VAR_1} se llenó\n"
	.string "tanto de BAYAS que el ENTRENADOR\l"
	.string "apenas podía andar después!$"

gTVWhatsNo1InHoennTodayText07::
	.string "¡En un solo día, {STR_VAR_1} consiguió\n"
	.string "{STR_VAR_2} PUNTOS de BATALLA!\p"
	.string "{STR_VAR_1} estuvo luego sopesando\n"
	.string "cambiar sus PUNTOS de BATALLA\l"
	.string "por algún objeto o algún adorno\l"
	.string "que le gustase.\p"
	.string "Dicen que sonreía mientras pensaba\n"
	.string "en lo que podía elegir.$"

gTVWhatsNo1InHoennTodayText08::
	.string "¡Bueno! ¿Qué os parece?\p"
	.string "¡{STR_VAR_1}!\n"
	.string "¡N.º 1 de los ENTRENADORES!\p"
	.string "¡Aprended de {STR_VAR_1}, amigos!\n"
	.string "¡Vosotros también podéis ser el n.º 1!$"

TVSecretBaseSecrets_Text_Intro::
	.string "¡LOS SECRETOS DE LAS BASES SECRETAS!\p"
	.string "¿Queréis saber a qué se dedican los\n"
	.string "ENTRENADORES en sus BASES SECRETAS?\p"
	.string "Hoy tenemos un reportaje sobre\n"
	.string "la BASE SECRETA de {STR_VAR_1}.\p"
	.string "¡Oh, parece que {STR_VAR_2} acaba\n"
	.string "de llegar para hacer una visita!\p"
	.string "¡Vamos a echar un vistazo!\p"
	.string "¿Qué hará ahora {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "¿Y qué hará {STR_VAR_2} después?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "¿Y ahora? ¿Qué hará {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Al final, {STR_VAR_2} ha dado {STR_VAR_3} pasos\n"
	.string "en la BASE SECRETA de {STR_VAR_1}\l"
	.string "antes de salir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Mmm…\p"
	.string "La BASE SECRETA de {STR_VAR_1} no\n"
	.string "ha interesado demasiado a {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "Parece que {STR_VAR_2} ha disfrutado\n"
	.string "de la BASE SECRETA de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "Vaya, parece que a {STR_VAR_2} le\n"
	.string "encanta la BASE SECRETA de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "¡Y no olvidéis que también podéis\n"
	.string "visitar la BASE SECRETA de {STR_VAR_1}!\p"
	.string "¡Esperamos teneros con nosotros\n"
	.string "en el próximo programa! ¡Adiós!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "¡Se ha parado!\p"
	.string "¡No mueve ni un dedo!\p"
	.string "¿Tanto le habrá impresionado\n"
	.string "la BASE SECRETA de {STR_VAR_1}?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "¡Se ha parado!\p"
	.string "¡No mueve ni un dedo!\p"
	.string "¿Será el cansancio?\n"
	.string "¿Se estará aburriendo?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "¡El visitante se ha sentado en\n"
	.string "una silla! ¡El visitante está sentado!\p"
	.string "¡Mirad qué cara de satisfacción!\p"
	.string "¡Esa silla debe de ser muy cómoda\n"
	.string "para provocar esa reacción!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "¡Se ha puesto a jugar con un globo!\p"
	.string "¡Ha estallado!\n"
	.string "¡El globo ha estallado!\p"
	.string "¡Parece que se ha llevado\n"
	.string "un buen susto!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "¡Ha entrado en una TIENDA!\p"
	.string "¡Está correteando un poco!\p"
	.string "¡Vaya, parece que está jugueteando!\p"
	.string "¡Parece que le sorprende el tamaño\n"
	.string "de la TIENDA!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "¡El visitante está examinando\n"
	.string "una planta en maceta!\p"
	.string "¡El visitante tiene un gusto\n"
	.string "sorprendentemente maduro!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "¡El visitante está examinando\n"
	.string "un ESCUDO DE ORO!\p"
	.string "¡Los ojos del visitante parecen\n"
	.string "brillar de asombro!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "¡El visitante está examinando\n"
	.string "un ESCUDO PLATA!\p"
	.string "¡El visitante parece tener\n"
	.string "los ojos como platos!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "¡El visitante está examinando\n"
	.string "un ADORNO CRISTAL!\p"
	.string "¡Oh, no!\p"
	.string "¡El visitante lo está tocando!\p"
	.string "¡Se está llenando de huellas\n"
	.string "dactilares…!$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "¡Se pone a ver la televisión!\p"
	.string "¡Parece que tenemos otro teleadicto!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "¡Se encuentra con una BOLA de LODO!\p"
	.string "¡Se muestra radiante!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "¡Oh!\p"
	.string "¡Parece que está buscando algo\n"
	.string "dentro de su MOCHILA!\p"
	.string "¡Ha sacado algo!\n"
	.string "Es una especie de… ¡{STR_VAR_2}!\p"
	.string "¡Mirad cómo sonríe mientras sostiene\n"
	.string "su {STR_VAR_2} en la mano!\p"
	.string "¡Igual que en un anuncio de la tele!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Ha echado mano de un cojín…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "¡Y ha empezado a darle golpes!\p"
	.string "¿Será cosa del estrés?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…¡lo abraza con fuerza!\p"
	.string "¿Estará el visitante contento\n"
	.string "por algo?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "¡El visitante está charlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a tener\n"
	.string "un combate!\p"
	.string "Y…\p"
	.string "¡Es el visitante!\n"
	.string "¡El visitante ha ganado fuera de casa!\p"
	.string "¡El visitante está haciendo\n"
	.string "un baile de la victoria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "¡El visitante está charlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a tener\n"
	.string "un combate!\p"
	.string "Y…\p"
	.string "¡Es {STR_VAR_1}!\n"
	.string "¡El visitante ha perdido!\p"
	.string "¡El visitante parece abatido!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "¡El visitante está charlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a tener\n"
	.string "un combate!\p"
	.string "Y…\p"
	.string "¡No, el visitante se ha negado!\p"
	.string "¡Al final no habrá combate!\p"
	.string "¿Le habrá parecido poco atractivo\n"
	.string "{STR_VAR_1} al visitante?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "¡El visitante mira fijamente\n"
	.string "un póster!\p"
	.string "¿Será del gusto del visitante\n"
	.string "el póster?\p"
	.string "…Pero… Hay algo inquietante\n"
	.string "en las miradas del visitante.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "¡El visitante ha pisado un TAPETE\n"
	.string "MUSICAL!\p"
	.string "…Hmm… ¡El visitante ha compuesto una\n"
	.string "melodía graciosa!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "¡El visitante está charlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "¡Parece que van a tener\n"
	.string "un combate!\p"
	.string "Y…\p"
	.string "¡Es un empate!\n"
	.string "¡Nada se resuelve!\p"
	.string "¡Ambos ENTRENADORES parecen muy\n"
	.string "decepcionados!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "¡El visitante ha pisado\n"
	.string "un TAPETE GIRO!\p"
	.string "¡Parece que el visitante está mareado!\p"
	.string "¡El visitante se tambalea!\n"
	.string "¡Cuidado!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "¡El visitante está alcanzando\n"
	.string "un ADORNO ARENA!\p"
	.string "¡Oh!\p"
	.string "¡Se ha desmoronado!\n"
	.string "¡Se ha deshecho!\p"
	.string "¡El visitante parece avergonzado\n"
	.string "y culpable!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "¡El visitante está pasando el dedo por\n"
	.string "un escritorio!\p"
	.string "¡Al parecer, el visitante desaprueba\n"
	.string "el polvo!\p"
	.string "¡El visitante se preocupa\n"
	.string "sorprendentemente por el orden!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "¡El visitante mira un LADRILLO!\p"
	.string "Quizá el visitante esté pensando\n"
	.string "en el objeto que hay sobre el LADRILLO.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "El visitante camina por\n"
	.string "la TABLA.\p"
	.string "El visitante no deja de mirar abajo.\p"
	.string "El visitante parece ser\n"
	.string "sorprendentemente tímido y cauto.$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "¡El visitante mira con atención\n"
	.string "una VALLA!\p"
	.string "¿Se le habrá ocurrido al visitante\n"
	.string "una nueva idea para una trampa?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "¡El visitante ha pisado\n"
	.string "un TAPETE BRILLO!\p"
	.string "¡El visitante está adoptando\n"
	.string "varias poses!\p"
	.string "¡El visitante parece fantasear\n"
	.string "con ser un ídolo!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "¡Está mirando con curiosidad\n"
	.string "un NEUMÁTICO!\p"
	.string "¿Estará pensando en el coche\n"
	.string "que podría llevarlo?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "¡Se ha subido a un PODIO!\p"
	.string "¡Y ahora está viendo desde arriba\n"
	.string "la BASE SECRETA de {STR_VAR_1}!\p"
	.string "Y…\p"
	.string "¡Ha emitido una especie de rugido!\n"
	.string "¡Está rugiendo!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "¡El visitante se ha lanzado de cabeza\n"
	.string "contra una PUERTA RARA!\p"
	.string "¡El visitante se ríe a carcajadas!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "¡El visitante está hablando con un\n"
	.string "MUÑECO!\p"
	.string "…Da un poco de miedo…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "¡Está subiendo por la escalera\n"
	.string "de un TOBOGÁN!\p"
	.string "Y…\p"
	.string "¡Se ha tirado!\p"
	.string "¡Parece que está recordando\n"
	.string "los viejos y buenos tiempos!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "¡El visitante está subiendo por la\n"
	.string "escalera de un TOBOGÁN!\p"
	.string "Y…\p"
	.string "¡El visitante ha vuelto a bajar\n"
	.string "por la escalera!\p"
	.string "¿Se habrá acobardado de repente\n"
	.string "el visitante?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "¡El visitante ha pisado\n"
	.string "un TAPETE MUELLE!\p"
	.string "¡El visitante ha saltado una vez!\p"
	.string "¡Dos veces!\p"
	.string "¡Y ha aterrizado con éxito!\p"
	.string "¡El visitante aplaude!\n"
	.string "¡Qué actuación en solitario!$"

gTVSafariFanClubText00::
	.string "¡CLUB SAFARI!\p"
	.string "REPORTERO: ¡Hola, queridos primates!\n"
	.string "¿Aún os queda una SAFARI BALL vacía?\p"
	.string "¡Como podéis imaginar, estoy en la ZONA\n"
	.string "SAFARI, plagada de POKéMON increíbles!\p"
	.string "¡Hoy tenemos con nosotros a alguien\n"
	.string "que trabaja como GUÍA del SAFARI!\p"
	.string "Dime, colega, ¿qué tal lo están haciendo\n"
	.string "los ENTRENADORES que andan por aquí?$"

gTVSafariFanClubText01::
	.string "GUÍA: Parece que todos se esfuerzan\n"
	.string "al máximo.\p"
	.string "{STR_VAR_1} lo está haciendo\n"
	.string "especialmente bien.\p"
	.string "Pues antes, {STR_VAR_1} capturó\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Se le dan bien los {POKEBLOCK}S.\n"
	.string "Esa vez usó {STR_VAR_2}, creo.$"

gTVSafariFanClubText03::
	.string "Eso sí, ¡no ha usado ni un solo {POKEBLOCK}!\n"
	.string "¡Ni uno solo!\p"
	.string "Eso sí que es saber hacer las cosas.$"

gTVSafariFanClubText04::
	.string "REPORTERO: ¿En serio? ¡Vaya!\p"
	.string "¡Parece que {STR_VAR_1} tiene instinto\n"
	.string "cazador para esto del SAFARI!\p"
	.string "GUÍA: ¡Ojalá vuelva otro día\n"
	.string "y nos enseñe su técnica!$"

gTVSafariFanClubText05::
	.string "GUÍA: Parece que a nadie le va muy\n"
	.string "bien.\p"
	.string "{STR_VAR_1} lo pasó especialmente mal.\p"
	.string "Pues antes, el ENTRENADOR solo\n"
	.string "consiguió capturar {STR_VAR_2}\l"
	.string "POKéMON.$"

gTVSafariFanClubText06::
	.string "GUÍA: Parece que a nadie le va\n"
	.string "muy bien.\p"
	.string "{STR_VAR_1} lo pasó especialmente mal.\p"
	.string "Pues antes, el ENTRENADOR no\n"
	.string "capturó ni un POKéMON. ¡Ni uno!$"

gTVSafariFanClubText07::
	.string "Y eso que usó {POKEBLOCK}S.\n"
	.string "Concretamente {STR_VAR_2}, si mal no recuerdo.\p"
	.string "Pero, oye, más le valdría practicar\n"
	.string "un poco más con ellos.$"

gTVSafariFanClubText08::
	.string "Creo que habría tenido más suerte\n"
	.string "si hubiese usado {POKEBLOCK}S, \l"
	.string "pero no los usó para nada.$"

gTVSafariFanClubText09::
	.string "REPORTERO: ¿En serio? ¡Vaya!\p"
	.string "¡Creo que {STR_VAR_1} necesita mejorar\n"
	.string "su instinto cazador en el SAFARI!\p"
	.string "GUÍA: ¡Ojalá vuelva más veces,\n"
	.string "a ver si le pilla el tranquillo!$"

gTVSafariFanClubText10::
	.string "REPORTERO: ¡Así es!\n"
	.string "¡Uno debe saber afrontar los retos!\p"
	.string "¡Queridos teleprimates, visitad\n"
	.string "el SAFARI y despertad vuestro\l"
	.string "instinto cazador recolector!\p"
	.string "¡Hasta la próxima!$"

ContestLiveUpdates_Text_Intro::
	.string "¡ÚLTIMA HORA de CONCURSOS POKéMON!\p"
	.string "PRESENTADOR: ¡Saludos a todos!\p"
	.string "Estamos emitiendo en directo desde\n"
	.string "el lugar donde se ha celebrado\l"
	.string "el último CONCURSO de {STR_VAR_1}.\p"
	.string "Nos rodea un público enfervorizado\n"
	.string "que se resiste a marcharse.\p"
	.string "Espectador: ¡Arriba {STR_VAR_2}!\p"
	.string "Espectador: ¡Viva {STR_VAR_3}!\p"
	.string "PRESENTADOR: Como podéis\n"
	.string "oír, el POKéMON {STR_VAR_2} de\l"
	.string "{STR_VAR_3} ha ganado el CONCURSO.\p"
	.string "Espectador: ¡{STR_VAR_2},\n"
	.string "eres increíble!\p"
	.string "Espectador: ¡{STR_VAR_3},\n"
	.string "sigue así!\p"
	.string "PRESENTADOR: Ahora vamos a recoger\n"
	.string "las impresiones de algunos fans.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Espectador: ¡{STR_VAR_2} ha arrasado\n"
	.string "tanto en la primera como\l"
	.string "en la segunda votación!\p"
	.string "¡{STR_VAR_2} ha nacido para ganar!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Espectador: ¡{STR_VAR_2} no tuvo un\n"
	.string "gran resultado en la primera votación,\l"
	.string "pero recuperó puestos en la segunda!\p"
	.string "{STR_VAR_2} logró sorprender\n"
	.string "a todos. ¡Hurra!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Espectador: {STR_VAR_2} tuvo una\n"
	.string "actuación consistente tanto en la\l"
	.string "primera como en la segunda votación.\p"
	.string "{STR_VAR_3} y {STR_VAR_2} forman\n"
	.string "un equipo extraordinario.$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Espectador: En lo que respecta a\n"
	.string "{STR_VAR_1}, {STR_VAR_2} es alucinante.\p"
	.string "Pero espero que haga mejores\n"
	.string "exhibiciones la próxima vez.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Espectador: Cuando {STR_VAR_2} se puso\n"
	.string "nervioso, lo animé todo lo que pude.\p"
	.string "Quisiera poder decir a {STR_VAR_2}\n"
	.string "que ha estado espectacular.$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Espectador: La exhibición de\n"
	.string "{STR_VAR_2} me ha dejado sin habla.\p"
	.string "¡{STR_VAR_2}, eres grande!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Espectador: El combo que ha realizado\n"
	.string "{STR_VAR_2} ha sido excepcional.\p"
	.string "¡Me ha llegado a lo más hondo!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Espectador: ¡La exhibición ganadora\n"
	.string "de {STR_VAR_2} me ha impresionado!$"

ContestLiveUpdates_Text_WasCool::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "tener mucho carisma!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "poseer una gran belleza!$"

ContestLiveUpdates_Text_WasCute::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "poseer una gran dulzura!$"

ContestLiveUpdates_Text_WasSmart::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "tener mucho ingenio!$"

ContestLiveUpdates_Text_WasTough::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "gran dureza!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Espectador: ¡La exhibición ganadora\n"
	.string "de {STR_VAR_2} me sigue impresionando!$"

ContestLiveUpdates_Text_VeryCool::
	.string "¡{STR_VAR_2}, tu carisma\n"
	.string "es inconmensurable!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "¡{STR_VAR_2}, tu belleza\n"
	.string "no tiene igual!$"

ContestLiveUpdates_Text_VeryCute::
	.string "¡{STR_VAR_2}, no hay quien\n"
	.string "te supere en dulzura!$"

ContestLiveUpdates_Text_VerySmart::
	.string "¡{STR_VAR_2}, tu ingenio\n"
	.string "es sobresaliente!$"

ContestLiveUpdates_Text_VeryTough::
	.string "¡{STR_VAR_2}, no hay quien\n"
	.string "te gane en dureza!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Espectador: Incluso cuando {STR_VAR_2}\n"
	.string "detuvo sus exhibiciones,\l"
	.string "no podía apartar los ojos de él.\p"
	.string "Ese {STR_VAR_2} me tiene a cuadros.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Espectador: Cuando {STR_VAR_2} se\n"
	.string "asustó por el atractivo de otro\l"
	.string "POKéMON, estuve a punto de llorar.\p"
	.string "¡{STR_VAR_2}, fuiste resistente! ¡Así\n"
	.string "se hace!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Espectador: Oh…\n"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¿Cómo logra hacerlo tan bien?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "PRESENTADOR: Bueno, ya lo veis. ¡Este\n"
	.string "lugar está lleno de fans del\l"
	.string "{STR_VAR_1}!\p"
	.string "También debo mencionar que otro\n"
	.string "POKéMON, el {STR_VAR_3} de\l"
	.string "{STR_VAR_2}, me llamó la atención.\p"
	.string "El {STR_VAR_3} de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Su nerviosismo le impidió exhibirse\n"
	.string "en la segunda votación.\p"
	.string "Esperamos que {STR_VAR_1} haga al \n"
	.string "menos una exhibición la próxima vez.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Acabó en último lugar tanto en la\n"
	.string "primera como en la segunda votación.\p"
	.string "Esperamos que {STR_VAR_1} entrene mejor\n"
	.string "a {STR_VAR_2} y nos haga olvidar este\l"
	.string "vergonzoso último puesto.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "No consiguió sacar partido del\n"
	.string "entusiasmo del público y hacer\l"
	.string "una exhibición adecuada.\p"
	.string "Esperamos que {STR_VAR_1} aprenda\n"
	.string "a conectar mejor con el público\l"
	.string "y a avivar su interés la próxima vez.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Aunque logró el primer puesto en la\n"
	.string "primera votación, su exhibición en\l"
	.string "la segunda no acabó de cuajar.\p"
	.string "De hecho, sufrió una derrota\n"
	.string "inesperada y humillante.\p"
	.string "Seguro que {STR_VAR_1} está planteándose\n"
	.string "cómo exhibirse de forma más eficaz.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "El público no llegó a emocionarse\n"
	.string "con las exhibiciones que realizó\l"
	.string "en la segunda votación.\p"
	.string "Esperamos que deje de preocuparse\n"
	.string "por los demás POKéMON y aprenda\l"
	.string "a conectar mejor con el público.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Perdió ante el {STR_VAR_2} de\n"
	.string "{STR_VAR_1} por un estrecho margen.\p"
	.string "Debe de ser desgarrador estar tan\n"
	.string "cerca de la victoria y fallar.\p"
	.string "No me sorprendería que {STR_VAR_3}\n"
	.string "estuviera llorando por este\l"
	.string "resultado.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Decepcionó al JUEZ al repetir\n"
	.string "las mismas exhibiciones.\p"
	.string "Se trata de un error imperdonable en\n"
	.string "cualquier CONCURSO y lo ha pagado caro.\p"
	.string "{STR_VAR_1} debería avergonzarse\n"
	.string "de una actuación tan pobre.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} hizo un esfuerzo valiente,\n"
	.string "pero…\p"
	.string "Todo fue en vano, acabó en última\n"
	.string "posición.\p"
	.string "{STR_VAR_1} debería aprender de esta\n"
	.string "derrota y aprovechar lo aprendido.$"

ContestLiveUpdates_Text_Outro::
	.string "Me gustaría terminar este programa\n"
	.string "con nuestra despedida habitual a los\l"
	.string "ganadores.\p"
	.string "Esta vez, ¡son {STR_VAR_1} y el\n"
	.string "{STR_VAR_2}!\p"
	.string "PRESENTADOR: ¿Estáis todos listos?\n"
	.string "¡Todos juntos!\p"
	.string "PÚBLICO: ¡{STR_VAR_1}! ¡{STR_VAR_2}!\n"
	.string "¡Enhorabuena! ¡Sois los ganadores del\l"
	.string "CONCURSO!$"

gTVPokemonBattleUpdateText00::
	.string "¡ÚLTIMA HORA de COMBATES POKéMON!\p"
	.string "¡Os traemos los resultados de los\n"
	.string "combates POKéMON más recientes!$"

gTVPokemonBattleUpdateText01::
	.string "{STR_VAR_1} y {STR_VAR_2} se han\n"
	.string "enfrentado en un emocionante\l"
	.string "COMBATE {STR_VAR_3}.\p"
	.string "¡Dicho enfrentamiento concluyó\n"
	.string "con la victoria de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "En el combate, el {STR_VAR_2} de\n"
	.string "{STR_VAR_1} ¡fue una fuerza\l"
	.string "formidable usando {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "El {STR_VAR_2} de {STR_VAR_1} tuvo una\n"
	.string "actuación floja que le hizo mucho daño.$"

gTVPokemonBattleUpdateText04::
	.string "¡Felicidades por la victoria,\n"
	.string "{STR_VAR_1}!\p"
	.string "A {STR_VAR_2}, le deseamos más\n"
	.string "suerte la próxima vez.\p"
	.string "¡Y así ponemos fin a este episodio de\n"
	.string "la ÚLTIMA HORA de COMBATES POKéMON!$"

gTVPokemonBattleUpdateText05::
	.string "Los equipos de {STR_VAR_1} y\n"
	.string "{STR_VAR_2} midieron sus fuerzas\l"
	.string "en un COMBATE MÚLTIPLE.\p"
	.string "¡Dicho enfrentamiento concluyó con\n"
	.string "la victoria del equipo de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText06::
	.string "¡El {STR_VAR_2} del equipo de\n"
	.string "{STR_VAR_1} se impuso con claridad\l"
	.string "meridiana e hizo uso de {STR_VAR_3}!$"

gTVPokemonBattleUpdateText07::
	.string "El {STR_VAR_3} del equipo de {STR_VAR_2}\n"
	.string "tuvo una actuación mediocre que\l"
	.string "dejó mucho que desear.\p"
	.string "¡Felicidades por la victoria\n"
	.string "de tu equipo, {STR_VAR_1}!\p"
	.string "Al equipo de {STR_VAR_2}, le deseamos\n"
	.string "más suerte la próxima vez.\p"
	.string "¡Y así ponemos fin a este episodio de\n"
	.string "la ÚLTIMA HORA de COMBATES POKéMON!$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! We've just spotted a tough-\n"
	.string "looking TRAINER here of all places!\p"
	.string "Okay, roll camera!\n"
	.string "Let's get this interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! You're {PLAYER}! Hi!\n"
	.string "Do you remember us from last time?\p"
	.string "Can you show us how much stronger\n"
	.string "you've become? Okay, cue interview!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: My eyes didn't lie!\n"
	.string "I did discover an astonishing TRAINER!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Awesome! Awesome!\n"
	.string "Who are you?!\p"
	.string "I knew we were onto something wild\n"
	.string "when we spotted you!\p"
	.string "Oh, please let me explain. We travel\n"
	.string "around everywhere interviewing all\l"
	.string "sorts of TRAINERS.\p"
	.string "So, would you give us a bit of your time\n"
	.string "for an interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Remember? That's the quote you gave\n"
	.string "us as the battle clincher last time.\p"
	.string "I never, ever forget stuff like that!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "The last time we battled, you stomped\n"
	.string "us before we could brace ourselves…\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "The last time we battled, didn't you\n"
	.string "throw a POKé BALL at us?\p"
	.string "We were shocked! So we told everyone,\n"
	.string "just everyone, about it!\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "The last time we battled, your item\n"
	.string "skills cleverly did us in.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "The last time we battled, we managed\n"
	.string "to look respectable.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "You will?\n"
	.string "Thank you!\p"
	.string "Okay, I need you to describe your\n"
	.string "feelings about our battle, but it\l"
	.string "has to be short and sweet. Go!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, yeah!\n"
	.string "That's the perfect clincher!\p"
	.string "I get the feeling that this will make\n"
	.string "a great TV show.\p"
	.string "There's a chance that they'll air this\n"
	.string "on TV, so make sure to look for us!\p"
	.string "Okay!\n"
	.string "We'll be seeing you!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "Okay, but don't give up!\n"
	.string "We'll be keeping an eye out for you!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: We'll be keeping an eye out\n"
	.string "for you!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Is there a strong TRAINER\n"
	.string "anywhere with a lot of POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, you are something!\p"
	.string "You've gotten a lot stronger--a lot--\n"
	.string "since we last battled.\p"
	.string "We were right about you when we\n"
	.string "spotted you as a hot TRAINER.\p"
	.string "So, anyway, what do you think?\n"
	.string "Are you willing to give us an interview\l"
	.string "this time?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: That was an intense battle!\n"
	.string "Did you get all that on camera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hey, lookie here! A tough-looking\n"
	.string "TRAINER here, of all places!\l"
	.string "Camera's rolling!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hey, lookie here!\n"
	.string "I remember you!\p"
	.string "I'll get this battle all on this\n"
	.string "here camera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: You're a natural!\n"
	.string "Got me some prime footage right here!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Do you only have the one POKéMON\n"
	.string "and that's it?\p"
	.string "If you had more POKéMON, it'd make for\n"
	.string "better footage, but…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Yep, we sure spotted a hot TRAINER.\n"
	.string "This is a huge scoop for us!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Yep, I got it all.\n"
	.string "That whole battle's on camera.$"

gTVInSearchOfTrainersText00::
	.string "OPERACIÓN ENTRENADOR…\p"
	.string "GABI: ¡Hola! Hoy hemos visitado\n"
	.string "la zona cercana a {STR_VAR_1}.\p"
	.string "Nuestra esperanza era encontrar\n"
	.string "algún nuevo talento desconocido.\p"
	.string "Hoy hemos descubierto\n"
	.string "a una nueva promesa: {PLAYER}.\p"
	.string "Tenía algo que captó nuestro interés\n"
	.string "desde el primer momento…$"

gTVInSearchOfTrainersText01::
	.string "Ya habíamos luchado contra {PLAYER},\n"
	.string "pero ahora podemos atestiguar que\l"
	.string "ha mejorado mucho desde entonces.\p"
	.string "¡Desde el primer momento, supimos\n"
	.string "que era alguien especial!$"

gTVInSearchOfTrainersText02::
	.string "La mejor manera de determinar\n"
	.string "la fuerza de un ENTRENADOR es…\p"
	.string "Bueno, la más rápida es luchando.\n"
	.string "¡Así abrimos nuestra investigación!\p"
	.string "Y…\p"
	.string "así fue como entablamos combate\n"
	.string "con {PLAYER}.\p"
	.string "En una actuación espectacular, nos\n"
	.string "arrolló, aplastó y dejó hechos polvo.\p"
	.string "{PLAYER} es impresionantemente fuerte.\p"
	.string "Quisiera compartir con vosotros\n"
	.string "mis apreciaciones sobre el combate.$"

gTVInSearchOfTrainersText03::
	.string "La combinación de {STR_VAR_1}\n"
	.string "y {STR_VAR_3} es simplemente divina.\p"
	.string "Ambos, {STR_VAR_1} y {STR_VAR_3},\n"
	.string "se apoyan mutuamente sin flaquear.\p"
	.string "¡Verlos en acción es maravilloso!\p"
	.string "El último movimiento usado\n"
	.string "en el combate fue {STR_VAR_2}.\p"
	.string "El movimiento {STR_VAR_2} simboliza\n"
	.string "perfectamente la amistad que\l"
	.string "hay entre {STR_VAR_1} y {STR_VAR_3}.$"

gTVInSearchOfTrainersText04::
	.string "Perdí algo de confianza en mí como\n"
	.string "consecuencia de ese combate.\p"
	.string "Nos derrotaron antes incluso de que\n"
	.string "pudiéramos preparar un ataque…\l"
	.string "Una victoria aplastante…\p"
	.string "A pesar de todo, los combates\n"
	.string "de {PLAYER} son dignos de verse.\p"
	.string "Recomiendo a todo ENTRENADOR seguro\n"
	.string "de sí que se enfrente a {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Sólo se puede decir una cosa…\n"
	.string "¡Ni se te ocurra lanzar otra POKé BALL\l"
	.string "mientras luches contra un ENTRENADOR!\p"
	.string "{PLAYER} es muy fuerte, cierto, pero no\n"
	.string "tiene ni idea de las reglas más básicas.\p"
	.string "Quisiera pedir algo a nuestro público…\p"
	.string "Si veis a {PLAYER}, ¡recordadle\n"
	.string "lo que hay que hacer!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} parece poder leer las mentes\n"
	.string "de sus rivales.\p"
	.string "¡Siempre acierta con el momento\n"
	.string "de usar uno u otro objeto!$"

gTVInSearchOfTrainersText07::
	.string "A decir verdad, yo antes pensaba\n"
	.string "que se me daba bien todo esto…\p"
	.string "Aunque acabamos perdiendo, el combate\n"
	.string "fue muy reñido hasta el final.\p"
	.string "¡Así que no te pienses que lo vas a\n"
	.string "tener chupado la próxima vez, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Tras nuestro combate, le pedimos a\n"
	.string "{PLAYER} un resumen breve.\p"
	.string "El ENTRENADOR respondió:\n"
	.string "“{STR_VAR_1}.”\p"
	.string "Los POKéMON de {PLAYER}, {STR_VAR_2} y\n"
	.string "{STR_VAR_3}… Y “{STR_VAR_1}”…\p"
	.string "¡Mmm! ¡Qué profundo! ¡Hay un\n"
	.string "significado profundo tras esa cita!\p"
	.string "No es de extrañar: un buen ENTRENADOR\n"
	.string "tiene buenas cosas que decir.\p"
	.string "¡Eso es todo por hoy! ¡Hasta la\n"
	.string "próxima emisión!$"

ContestLadyShow_Text_Intro::
	.string "¡ÚLTIMA HORA de CONCURSOS POKéMON!\p"
	.string "PRESENTADOR: Sentimos\n"
	.string "interrumpir la programación habitual\l"
	.string "y os damos la bienvenida.\p"
	.string "¡Emitimos en directo desde el\n"
	.string "lugar de celebración del último\l"
	.string "CONCURSO de {STR_VAR_1}!\p"
	.string "Espectadores: (?)\p"
	.string "PRESENTADOR: ¡Oh, parece que\n"
	.string "los participantes vienen hacia aquí!\p"
	.string "¡Intentemos conseguir una\n"
	.string "entrevista para los telespectadores!\p"
	.string "Espectadores: (?)\n"
	.string "(!)$"

ContestLadyShow_Text_Won::
	.string "PRESENTADOR: ¡Disculpa! ¡Gracias por\n"
	.string "acompañarnos en directo!\p"
	.string "¿Puedo felicitarte por tu victoria?\p"
	.string "¿Cuál fue el factor clave de la\n"
	.string "asombrosa victoria de hoy?\p"
	.string "BELLEZA: ¡Hoy dimos lo mejor de\n"
	.string "nosotros, mi {STR_VAR_2} y yo!\p"
	.string "Pero seguro que no lo habríamos\n"
	.string "conseguido sin toda la ayuda que\l"
	.string "recibimos antes del CONCURSO.\p"
	.string "PRESENTADOR: ¿Tienes a alguien\n"
	.string "especial con quien compartir tu\l"
	.string "alegría? ¡Dilo en directo!\p"
	.string "BELLEZA: ¡Eh, vosotros ahí fuera!\p"
	.string "¡{STR_VAR_3}! ¿Estás viendo? ¡Lo\n"
	.string "hemos conseguido! ¡Gracias!$"

ContestLadyShow_Text_Lost::
	.string "PRESENTADOR: ¡Disculpa y gracias\n"
	.string "por estar con nosotros en directo!\p"
	.string "El resultado debe de haberte\n"
	.string "desilusionado. ¿Algún comentario?\p"
	.string "BELLA: Es desolador…\n"
	.string "{STR_VAR_2} y yo nos esforzamos mucho.\p"
	.string "Pero siento que hemos decepcionado\n"
	.string "a todos aquellos que nos han\l"
	.string "apoyado para llegar hasta aquí.\p"
	.string "PRESENTADOR: Sin ánimo de\n"
	.string "ofender, el colorido de este POKéMON\l"
	.string "es algo pobretón.\p"
	.string "BELLA: {STR_VAR_3}, cuánto lo siento…\n"
	.string "La próxima vez lo haré mejor, de verdad.\l"
	.string "Snif, snif… ¡Buaaaa!\p"
	.string "Espectadores: ¿Lo habéis visto?\n"
	.string "¡Pobre chica!\p"
	.string "PRESENTADOR: Vaya… Ejem…\p"
	.string "¡Bueno, esto ha sido todo por hoy!\n"
	.string "¡Gracias por conectar con nosotros!$"

ContestLadyShow_Text_LostBadly::
	.string "PRESENTADOR: ¡Disculpa y gracias\n"
	.string "por estar con nosotros en directo!\p"
	.string "¿Qué tal ha ido tu participación\n"
	.string "en este CONCURSO?\p"
	.string "BELLA: Fatal del verbo fatal…\n"
	.string "Mi {STR_VAR_2} no logró meterse al\l"
	.string "público en el bolsillo, no sé por qué.\p"
	.string "PRESENTADOR: Sin ánimo de\n"
	.string "ofender, el colorido de este POKéMON\l"
	.string "parece algo desvaído.\p"
	.string "BELLA: Snif, snif… ¡Buaaaa!\p"
	.string "Espectadores: ¿Lo habéis visto?\n"
	.string "¡Pobre chica!\p"
	.string "PRESENTADOR: Vaya… Ejem…\p"
	.string "¡Bueno, esto ha sido todo por hoy!\n"
	.string "¡Gracias por conectar con nosotros!$"
