Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "¡Auch! ¡Tropecé con un POKéMON\n"
	.string "rocoso, GEODUDE!$"

Route4_Text_CrissyIntro::
	.string "Vine al MT. MOON en busca de\n"
	.string "POKéMON seta.$"

Route4_Text_CrissyDefeat::
	.string "¡Oh! ¡Mi pobre hongo POKéMON!$"

Route4_Text_CrissyPostBattle::
	.string "¡Puede que no haya más hongos\n"
	.string "por aquí!\p"
	.string "Creo que ya los tengo todos.$"

Route4_Text_MtMoonEntrance::
	.string "MT. MOON:\n"
	.string "Entrada al túnel$"

Route4_Text_RouteSign::
	.string "RUTA 4:\n"
	.string "MT. MOON - CIUDAD CELESTE$"

Text_MegaPunchTeach::
	.string "¡Un puñetazo con rabia\n"
	.string "contenida!\p"
	.string "¡Condimentado con fuerza\n"
	.string "descomunal!\p"
	.string "¡Cuando no queda energía,\n"
	.string "MEGAPUÑO es el ataque definitivo!\p"
	.string "¿Qué?\n"
	.string "¿Se lo enseño a algún POKéMON?$"

Text_MegaPunchDeclined::
	.string "Volverás cuando entiendas el valor\n"
	.string "de MEGAPUÑO.$"

Text_MegaPunchWhichMon::
	.string "¿A qué POKéMON quieres que se\n"
	.string "lo enseñe?$"

Text_MegaPunchTaught::
	.string "¡Ya usamos los puños de la\n"
	.string "misma forma!\p"
	.string "¡Hala, vete antes de que le entren\n"
	.string "ganas de luchar a mi colega:\l"
	.string "es un flipado de las patadas!$"

Text_MegaKickTeach::
	.string "¡Una patada de feroz brutalidad!\p"
	.string "¡Cargada de poder destructivo!\p"
	.string "Al fin y al cabo, ¡MEGAPATADA es\n"
	.string "el ataque definitivo!\l"
	.string "¿No te parece?\p"
	.string "¡Vale!\n"
	.string "¡Se lo enseñaré a tu POKéMON!$"

Text_MegaKickDeclined::
	.string "Volverás arrastrándote cuando\n"
	.string "comprendas el valor de MEGAPATADA.$"

Text_MegaKickWhichMon::
	.string "¿A qué POKéMON quieres que se\n"
	.string "lo enseñe?$"

Text_MegaKickTaught::
	.string "¡Ya damos patadas de la\n"
	.string "misma forma!\p"
	.string "¡Hala, vete antes de que le entren\n"
	.string "ganas de luchar a mi colega:\l"
	.string "es un flipado de los puñetazos!$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "¡Anda, la MEDALLA ROCA!\n"
	.string "Te la ha dado BROCK, ¿no?\p"
	.string "BROCK es, además de fuerte, guay.\n"
	.string "Todos lo respetan y admiran mucho.\p"
	.string "Yo quiero ser LÍDER de GIMNASIO\n"
	.string "como él.$"
