SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "¡Bonjour!\n"
	.string "¡Soy el camarero de este barco!\p"
	.string "¡Encantado de servirte en todo\n"
	.string "lo que quieras!\p"
	.string "… … …\n"
	.string "¡Ah! ¡Tienes cara de ser una persona\l"
	.string "fuerte y discreta!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "Los pasajeros están inquietos por\n"
	.string "este largo viaje.\p"
	.string "¡Los más aburridos podrían\n"
	.string "desafiarte!$"

