FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mi abuelo está en casa de mi hermano\p"
	.string "BILL, en CABO CELESTE.$"

FuchsiaCity_House1_Text_Youngster:
	.string "He visto a unos POKéMON lentos y\n"
	.string "raros en el CAMINO DE BICIS.$"

