BattleFrontier_Lounge4_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook_hns::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns:
	.string "¿Entrevistarán hoy a algún ENTRENADOR\n"
	.string "de los buenos?$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns:
	.string "Si abriese un restaurante aquí,\n"
	.string "seguro que me forraba.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns:
	.string "¡Uf!…\p"
	.string "Necesito tomarme estos descansos\n"
	.string "después de unos combates tan duros…\p"
	.string "Pero lo que no puedo es dejar de pensar\n"
	.string "en estrategias y movimientos.$"

