VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Soy el TÍO PESCA- DOR, el mayor de los\n"
	.string "HERMANOS PESCADORES.\p"
	.string "¿Conoces al GURÚ PESCADOR del LAGO DE\n"
	.string "LA FURIA?\p"
	.string "Sueña con ver el MAGIKARP más grande\n"
	.string "del mundo.\p"
	.string "Si no te importa, ¿podrías mostrarle\n"
	.string "todos los MAGIKARP que captures?\p"
	.string "Quién sabe, podrías capturar el\n"
	.string "MAGIKARP de sus sueños.$"

VermilionCity_House1_Text_Photo:
	.string "Es una foto de gente pescando…\p"
	.string "Lo están pasando muy bien…$"
