SSAnne_2F_Room2_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room2_EventScript_Dale::
	trainerbattle_single TRAINER_FISHERMAN_DALE, SSAnne_2F_Room2_Text_DaleIntro, SSAnne_2F_Room2_Text_DaleDefeat
	msgbox SSAnne_2F_Room2_Text_DalePostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_2F_Room2_EventScript_Brooks::
	trainerbattle_single TRAINER_GENTLEMAN_BROOKS, SSAnne_2F_Room2_Text_BrooksIntro, SSAnne_2F_Room2_Text_BrooksDefeat
	msgbox SSAnne_2F_Room2_Text_BrooksPostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_2F_Room2_Text_BrooksIntro::
	.string "¡Competir contra los jóvenes\n"
	.string "me mantiene como un chaval!$"

SSAnne_2F_Room2_Text_BrooksDefeat::
	.string "¡Buena pelea!\n"
	.string "¡Vuelvo a sentirme joven!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
	.string "¡Hace 15 años, yo habría ganado!$"

SSAnne_2F_Room2_Text_DaleIntro::
	.string "¡Mira lo que he pescado!$"

SSAnne_2F_Room2_Text_DaleDefeat::
	.string "¡Estoy acabado!$"

SSAnne_2F_Room2_Text_DalePostBattle::
	.string "¿Una fiesta?\p"
	.string "La fiesta del crucero debe de\n"
	.string "haber terminado.$"

