Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
	.string "Tengo que hacer ejercicio y calentar\n"
	.string "antes de salir a nadar.$"

Route19_Text_RichardDefeat::
	.string "¡Ya estoy calentado!$"

Route19_Text_RichardPostBattle::
	.string "¡Gracias, chaval!\n"
	.string "Estoy listo para nadar.$"

Route19_Text_ReeceIntro::
	.string "¡Espera! ¡Más despacio!\n"
	.string "¡Te va a dar un infarto!$"

Route19_Text_ReeceDefeat::
	.string "¡Uuh!\n"
	.string "¡Qué fría!$"

Route19_Text_ReecePostBattle::
	.string "¡Cuidado con TENTACOOL!\n"
	.string "¡Como te pique, no veas!$"

Route19_Text_MatthewIntro::
	.string "¡Me gusta nadar!\n"
	.string "¿Y a ti?$"

Route19_Text_MatthewDefeat::
	.string "¡Planchazo!$"

Route19_Text_MatthewPostBattle::
	.string "¡Puedo ganar a los POKéMON\n"
	.string "nadando!$"

Route19_Text_DouglasIntro::
	.string "¿Qué habrá más allá del horizonte?$"

Route19_Text_DouglasDefeat::
	.string "¡Glup!$"

Route19_Text_DouglasPostBattle::
	.string "¡Veo un par de islas!$"

Route19_Text_DavidIntro::
	.string "Intenté bucear en busca de POKéMON,\n"
	.string "pero no hubo manera.$"

Route19_Text_DavidDefeat::
	.string "¡Socorro!$"

Route19_Text_DavidPostBattle::
	.string "¡Tienes que pescar a los POKéMON\n"
	.string "del mar!$"

Route19_Text_TonyIntro::
	.string "¡Miro al mar para olvidar!$"

Route19_Text_TonyDefeat::
	.string "¡Uuh!\n"
	.string "¡Traumático!$"

Route19_Text_TonyPostBattle::
	.string "¡Miro al mar para olvidar!$"

Route19_Text_AnyaIntro::
	.string "¡Qué POKéMON tan guay!\n"
	.string "¿Me lo darás si gano?$"

Route19_Text_AnyaDefeat::
	.string "¡Oh! ¡He perdido!$"

Route19_Text_AnyaPostBattle::
	.string "Queda un largo camino hasta\n"
	.string "las ISLAS ESPUMA...\p"
	.string "Yo quiero volver a FUCSIA...$"

Route19_Text_AliceIntro::
	.string "¡Nadar es genial! ¡Pero no me\n"
	.string "gusta quemarme al sol!$"

Route19_Text_AliceDefeat::
	.string "¡Qué horror!$"

Route19_Text_AlicePostBattle::
	.string "Mi novio quería nadar hasta\n"
	.string "las ISLAS ESPUMA.$"

Route19_Text_AxleIntro::
	.string "¡Estas aguas son traicioneras!$"

Route19_Text_AxleDefeat::
	.string "¡Qué peligro!$"

Route19_Text_AxlePostBattle::
	.string "¡Me ha dado un calambre! ¡Glup!$"

Route19_Text_ConnieIntro::
	.string "He venido nadando hasta aquí,\n"
	.string "pero ya me he cansado.$"

Route19_Text_ConnieDefeat::
	.string "Estoy agotada...$"

Route19_Text_ConniePostBattle::
	.string "Si tuviera que montarme en un\n"
	.string "POKéMON para surcar el mar,\l"
	.string "elegiría a LAPRAS.\p"
	.string "LAPRAS es enorme, si te subes\n"
	.string "encima, seguro que no te mojas.$"

Route19_Text_RouteSign::
	.string "RUTA MARINA 19:\n"
	.string "CIUDAD FUCSIA - ISLAS ESPUMA$"

Route19_Text_LiaIntro::
	.string "CATI: Yo cuido de mi hermano.\n"
	.string "Acaba de hacerse ENTRENADOR.$"

Route19_Text_LiaDefeat::
	.string "CATI: ¡Ésa no es forma de tratar\n"
	.string "a mi hermanito!$"

Route19_Text_LiaPostBattle::
	.string "CATI: ¿Tienes un hermano pequeño?\p"
	.string "Espero que le enseñes cosas.$"

Route19_Text_LiaNotEnoughMons::
	.string "CATI: A mi hermano y a mí nos\n"
	.string "gustaría luchar contigo.\p"
	.string "¿Tienes dos POKéMON?$"

Route19_Text_LucIntro::
	.string "TEC: Mi hermana mayor me ha\n"
	.string "enseñado a nadar y a entrenar\l"
	.string "POKéMON.$"

Route19_Text_LucDefeat::
	.string "TEC: ¡Hala, alguien más fuerte\n"
	.string "que mi hermana!$"

Route19_Text_LucPostBattle::
	.string "TEC: ¡Mi hermana mayor es muy\n"
	.string "fuerte y simpática! ¡Es guay!$"

Route19_Text_LucNotEnoughMons::
	.string "TEC: Si no es con mi hermana,\n"
	.string "no lucharé contigo.\p"
	.string "Además, necesitas dos POKéMON.$"
