FiveIsland_House2_Frlg_MapScripts::
	.byte 0

FiveIsland_House2_EventScript_OldMan::
	msgbox FiveIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
	end

FiveIsland_House2_Text_MeadowBelongedToFamily::
	.string "Ese PRADO ha pertenecido a nuestra\n"
	.string "familia durante generaciones.\p"
	.string "Debí haber construido una mansión\n"
	.string "gigante en él.\p"
	.string "¡Sería mejor que dejar que esos\n"
	.string "gamberros lo arrasen!$"

