SSAnne_Deck_Frlg_MapScripts::
	.byte 0

SSAnne_Deck_EventScript_Youngster::
	msgbox SSAnne_Deck_Text_ShipDepartingSoon, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_BaldingMan::
	msgbox SSAnne_Deck_Text_FeelSeasick, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_Sailor::
	msgbox SSAnne_Deck_Text_ScrubbingDecksHardWork, MSGBOX_NPC
	end

SSAnne_Deck_EventScript_Edmond::
	trainerbattle_single TRAINER_SAILOR_EDMOND, SSAnne_Deck_Text_EdmondIntro, SSAnne_Deck_Text_EdmondDefeat
	msgbox SSAnne_Deck_Text_EdmondPostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_Deck_EventScript_Trevor::
	trainerbattle_single TRAINER_SAILOR_TREVOR, SSAnne_Deck_Text_TrevorIntro, SSAnne_Deck_Text_TrevorDefeat
	msgbox SSAnne_Deck_Text_TrevorPostBattle, MSGBOX_AUTOCLOSE
	end

SSAnne_Deck_Text_ShipDepartingSoon::
	.string "¡Se acabó la fiesta!\n"
	.string "¡El barco zarpará pronto!$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
	.string "¡Limpiar las cubiertas es\n"
	.string "un trabajo duro!$"

SSAnne_Deck_Text_FeelSeasick::
	.string "¡Uff! Me siento fatal...\p"
	.string "He salido a tomar el aire.$"

SSAnne_Deck_Text_EdmondIntro::
	.string "¡Eh, colega!\p"
	.string "¡Bailemos una jota!$"

SSAnne_Deck_Text_EdmondDefeat::
	.string "¡Eres impresionante!$"

SSAnne_Deck_Text_EdmondPostBattle::
	.string "¿Cuántos tipos de POKéMON crees\n"
	.string "que hay?$"

SSAnne_Deck_Text_TrevorIntro::
	.string "¡Eh, hola!\n"
	.string "¿Tienes mareo?$"

SSAnne_Deck_Text_TrevorDefeat::
	.string "¡No he estado muy atento!$"

SSAnne_Deck_Text_TrevorPostBattle::
	.string "Mi papá decía que hay 100 tipos\n"
	.string "de POKéMON. Pero yo creo que\l"
	.string "hay más.$"

