Route21_North_Frlg_MapScripts::
	.byte 0

Route21_North_Text_RonaldIntro::
	.string "¿Quieres saber si los peces pican?$"

Route21_North_Text_RonaldDefeat::
	.string "¡Vale, vale!$"

Route21_North_Text_RonaldPostBattle::
	.string "¡No puedo pescar nada bueno!\n"
	.string "¡No hay ni un POKéMON bueno!$"

Route21_North_Text_WadeIntro::
	.string "¡Tengo una gran red!\n"
	.string "¿Quieres probarla?$"

Route21_North_Text_WadeDefeat::
	.string "¡MAGIKARP, qué bochorno!$"

Route21_North_Text_WadePostBattle::
	.string "¡Se ve que sólo pesco MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "¡El mar limpia mi cuerpo y mi\n"
	.string "alma!$"

Route21_North_Text_SpencerDefeat::
	.string "¡Aaayyy!$"

Route21_North_Text_SpencerPostBattle::
	.string "¡He conseguido a mi POKéMON\n"
	.string "en el mar, y aquí lo entreno!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "¡Yo también vengo a nadar\n"
	.string "de vez en cuando!$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "¡Guaaa!$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "¿Que parezco flotar con facilidad?\n"
	.string "¡No te metas donde no te llaman!$"
