ViridianCity_School_Frlg_MapScripts::
	.byte 0

ViridianCity_School_EventScript_Lass::
	lock
	faceplayer
	msgbox ViridianCity_School_Text_TryingToMemorizeNotes
	closemessage
	applymovement LOCALID_SCHOOL_LASS, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	release
	end

ViridianCity_School_EventScript_Woman::
	lock
	faceplayer
	msgbox ViridianCity_School_Text_ReadBlackboardCarefully
	closemessage
	applymovement LOCALID_SCHOOL_WOMAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

ViridianCity_School_EventScript_Notebook::
	lockall
	msgbox ViridianCity_School_Text_NotebookFirstPage
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, ViridianCity_School_EventScript_StopReadingNotebook
	msgbox ViridianCity_School_Text_NotebookSecondPage
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, ViridianCity_School_EventScript_StopReadingNotebook
	msgbox ViridianCity_School_Text_NotebookThirdPage
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, ViridianCity_School_EventScript_StopReadingNotebook
	msgbox ViridianCity_School_Text_NotebookFourthPage
	applymovement LOCALID_SCHOOL_LASS, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	textcolor NPC_TEXT_COLOR_FEMALE
	msgbox ViridianCity_School_Text_HeyDontLookAtMyNotes
	releaseall
	end

ViridianCity_School_EventScript_StopReadingNotebook::
	releaseall
	end

ViridianCity_School_EventScript_Blackboard::
	lockall
	msgbox ViridianCity_School_Text_BlackboardListsStatusProblems
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ChooseBlackboardTopic::
	message ViridianCity_School_Text_ReadWhichTopic
	waitmessage
	multichoicegrid 7, 1, MULTI_STATUS_INFO, 3, FALSE
	switch VAR_RESULT
	case 0, ViridianCity_School_EventScript_ReadSleep
	case 1, ViridianCity_School_EventScript_ReadPoison
	case 2, ViridianCity_School_EventScript_ReadParalysis
	case 3, ViridianCity_School_EventScript_ReadBurn
	case 4, ViridianCity_School_EventScript_ReadFreeze
	case 5, ViridianCity_School_EventScript_ExitBlackboard
	case 127, ViridianCity_School_EventScript_ExitBlackboard
	end

ViridianCity_School_EventScript_ReadSleep::
	msgbox ViridianCity_School_Text_ExplainSleep
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ReadBurn::
	msgbox ViridianCity_School_Text_ExplainBurn
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ReadPoison::
	msgbox ViridianCity_School_Text_ExplainPoison
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ReadFreeze::
	msgbox ViridianCity_School_Text_ExplainFreeze
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ReadParalysis::
	msgbox ViridianCity_School_Text_ExplainParalysis
	goto ViridianCity_School_EventScript_ChooseBlackboardTopic
	end

ViridianCity_School_EventScript_ExitBlackboard::
	releaseall
	end

ViridianCity_School_Text_TryingToMemorizeNotes::
	.string "Estoy intentando memorizar todos\n"
	.string "mis apuntes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
	.string "¡Muy bien!\p"
	.string "¡No olvides leer la pizarra con\n"
	.string "mucha atención!$"

ViridianCity_School_Text_NotebookFirstPage::
	.string "A ver qué pone en el cuaderno...\p"
	.string "Primera página...\p"
	.string "Las POKé BALLS son para atrapar\n"
	.string "a los POKéMON.\p"
	.string "Puedes llevar hasta 6 POKéMON.\p"
	.string "Los ENTRENADORES son la gente\n"
	.string "que entrena y hace pelear a sus\l"
	.string "POKéMON.$"

ViridianCity_School_Text_NotebookSecondPage::
	.string "Segunda página...\p"
	.string "¡Un POKéMON sano no es tan fácil\n"
	.string "de atrapar, conviene debilitarlo\l"
	.string "primero!\p"
	.string "¡Los venenos, las quemaduras y\n"
	.string "otros daños son muy efectivos!$"

ViridianCity_School_Text_NotebookThirdPage::
	.string "Tercera página...\p"
	.string "Los ENTRENADORES POKéMON luchan\n"
	.string "contra otros, en combates POKéMON.\p"
	.string "Lo cierto es que la victoria tiene\n"
	.string "un sabor muy dulce.\p"
	.string "En los GIMNASIOS siempre se están\n"
	.string "librando combates POKéMON.$"

ViridianCity_School_Text_NotebookFourthPage::
	.string "Cuarta página...\p"
	.string "El objetivo de todo ENTRENADOR\n"
	.string "es derrotar a los 8 mejores\l"
	.string "LÍDERES de GIMNASIO.\p"
	.string "Si lo consigue, podrá desafiar...\p"
	.string "¡Al ALTO MANDO de la LIGA\n"
	.string "POKéMON!$"

ViridianCity_School_Text_TurnThePage::
	.string "¿Paso la página?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
	.string "NIÑA: ¡Oye!\n"
	.string "¡No mires mis apuntes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
	.string "La pizarra indica los cambios de\n"
	.string "las CARACTERÍSTICAS de los\l"
	.string "POKéMON durante los combates.$"

ViridianCity_School_Text_ReadWhichTopic::
	.string "¿Sobre qué tema te gustaría leer?$"

ViridianCity_School_Text_ExplainSleep::
	.string "¡Un POKéMON no puede atacar si\n"
	.string "está dormido!\p"
	.string "¡Los POKéMON seguirán dormidos\n"
	.string "incluso después de pelear!\p"
	.string "¡Usa DESPERTAR y se despertarán!$"

ViridianCity_School_Text_ExplainBurn::
	.string "Toda quemadura reduce la fuerza\n"
	.string "del ATAQUE y va restando PS.\p"
	.string "Las quemaduras permanecerán tras\n"
	.string "el combate.\p"
	.string "¡ANTIQUEMAR curará las\n"
	.string "quemaduras!$"

ViridianCity_School_Text_ExplainPoison::
	.string "Todo POKéMON envenenado\n"
	.string "seguirá perdiendo energía.\p"
	.string "El veneno sigue haciendo efecto\n"
	.string "tras el combate.\p"
	.string "¡Usa un ANTÍDOTO para curar\n"
	.string "el envenenamiento!$"

ViridianCity_School_Text_ExplainFreeze::
	.string "¡Todo POKéMON congelado no podrá\n"
	.string "moverse!\p"
	.string "Y permanecerá congelado tras el\n"
	.string "combate.\p"
	.string "¡Usa el ANTIHIELO para\n"
	.string "descongelar a los POKéMON!$"

ViridianCity_School_Text_ExplainParalysis::
	.string "¡La parálisis podría anular ciertos\n"
	.string "movimientos!\p"
	.string "Y permanece tras el combate.\p"
	.string "Usa ANTIPARALIZAR para liberar a\n"
	.string "los POKéMON que estén paralizados.$"

