SafariZone_East_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker::
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan::
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end

SafariZone_East_Text_HowManyDidYouCatch::
	.string "¿Cuántos has capturado? ¡Yo estoy\n"
	.string "agotado de tanto trabajar!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
	.string "¡Capturé un CHANSEY!\p"
	.string "¡Y por eso todos mis esfuerzos\n"
	.string "han merecido la pena!$"

SafariZone_East_Text_TiredFromAllTheFun::
	.string "¡Ufff!\n"
	.string "¡Estoy agotado de tanta diversión!$"

