CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "¡Jejeje!\p"
	.string "Las tragaperras dan muchísimo\n"
	.string "dinero.$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "¡JEFE!\p"
	.string "¡Hoy hemos enviado otros dos mil\n"
	.string "POKéMON como premios de las\l"
	.string "tragaperras!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "¡No toques el cartel del CASINO!\p"
	.string "¡No hay ningún interruptor secreto\n"
	.string "detrás!$"

