PewterCity_House2_Frlg_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
	.string "Los POKéMON aprenden técnicas\n"
	.string "nuevas a medida que crecen.\p"
	.string "Pero algunos movimientos tienen\n"
	.string "que enseñárselos las personas.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
	.string "Un POKéMON es más fácil de capturar\n"
	.string "si tiene un problema de estado.\p"
	.string "Sueño, veneno, quemadura o parálisis…\n"
	.string "Todos son eficaces.\p"
	.string "¡Pero capturar POKéMON nunca es\n"
	.string "algo seguro!$"

