TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "He perfeccionado el último\n"
	.string "movimiento de este tipo...\p"
	.string "Bueno, y ahora, ¿a quién se lo\n"
	.string "enseño?\p"
	.string "Mmmm...\p"
	.string "Ese {STR_VAR_1} tuyo...$"

Text_JustMistaken::
	.string "No, no...\n"
	.string "Me he equivocado...$"

Text_AllowMeToTeachMonUltimateMove::
	.string "¡Anda, éste es!\n"
	.string "¡Éste es el POKéMON!\p"
	.string "¡Este {STR_VAR_1} se merece\n"
	.string "aprender mi último movimiento!\p"
	.string "¿Te parece bien?\p"
	.string "¿Quieres que le enseñe\n"
	.string "mi {STR_VAR_2} a tu {STR_VAR_1}?$"

Text_YouRejectIt::
	.string "¡Aah! ¿Lo rechazas?\n"
	.string "¡No, no me disuadirás!$"

Text_LetMeConferUltimateMove::
	.string "¿Lo permites?\p"
	.string "Entonces, déjame conferir mi\n"
	.string "{STR_VAR_2} definitivo a tu\l"
	.string "{STR_VAR_1}.\p"
	.string "¡Ggggrah-auuuu!$"

Text_TaughtMove::
	.string "Qué emoción...\p"
	.string "No pensé que llegara a enseñar\n"
	.string "al final el movimiento...$"

Text_MakeBestUseOfMove::
	.string "¡Te imploro que aproveches al\n"
	.string "máximo ese movimiento y ganes poder!$"

Text_PassedOnEverythingIKnow::
	.string "Uf, uf, uf…\p"
	.string "Ahora no tengo remordimientos.\n"
	.string "He transmitido todo lo que sé.\p"
	.string "Ahora puedo vivir el resto de mi vida\n"
	.string "sabiendo que mi labor está hecha.$"

Text_FeelRejuvenated::
	.string "Tras transmitirte mi saber, sentí\n"
	.string "mucho alivio.\p"
	.string "De hecho, ¡me siento rejuvenecido,\n"
	.string "como si volviera a ser joven!$"
