CeladonCity_DepartmentStore_5F_hns_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CeladonDeptElevator_OnFrame
	.byte 0

CeladonDeptStore5_EventScript_Receptionist::
	lock
	faceplayer
	goto_if_set FLAG_GOT_FRUSTRATION, CeladonDeptStore5_EventScript_Receptionist_Already
	msgbox CeladonDeptStore_Text_5FReceptionistOhYourMon, MSGBOX_DEFAULT
	closemessage
	specialvar VAR_RESULT, GetLeadMonFriendshipScore
	goto_if_lt VAR_RESULT, FRIENDSHIP_50_TO_99, CeladonDeptStore5_EventScript_Receptionist_GiveFrustration
	msgbox CeladonDeptStore_Text_5FReceptionistPutInSomeMoreEffort, MSGBOX_DEFAULT
	closemessage
	release
	end

CeladonDeptStore5_EventScript_Receptionist_GiveFrustration::
	giveitem ITEM_TM_FRUSTRATION
	setflag FLAG_GOT_FRUSTRATION
	msgbox CeladonDeptStore_Text_5FReceptionistItLooksEvilHowAboutThisTM, MSGBOX_DEFAULT
	closemessage
	release
	end

CeladonDeptStore5_EventScript_Receptionist_Already::
	msgbox CeladonDeptStore_Text_5FReceptionistWait, MSGBOX_DEFAULT
	closemessage
	release
	end

CeladonDeptStore_Text_5FReceptionistOhYourMon:
	.string "Te doy la bienvenida.\p"
	.string "¡Oh, tu POKéMON…!\p"
	.string "$"

CeladonDeptStore_Text_5FReceptionistWait:
	.string "¡Espera, si ya te he dado esa MT!$"

CeladonDeptStore_Text_5FReceptionistPutInSomeMoreEffort:
	.string "Mmmm…\n"
	.string "No está mal, pero tampoco muy bien.\p"
	.string "Tendrías que esforzarte un\n"
	.string "poco más, ¿no te parece?$"

CeladonDeptStore_Text_5FReceptionistItLooksEvilHowAboutThisTM:
	.string "Parece malvado. ¿Qué te parece esta\n"
	.string "MT para él?$"

CeladonDept5_EventScript_Gent::
	msgbox CeladonDeptStore5F_Text_Gentleman, MSGBOX_NPC
	end
CeladonDept5_EventScript_Sailor::
	msgbox CeladonDeptStore5F_Text_Sailor, MSGBOX_NPC
	end
CeladonDept5_EventScript_Teacher::
	msgbox CeladonDeptStore5F_Text_Teacher, MSGBOX_NPC
	end
CeladonDept5_EventScript_Directory::
	msgbox CeladonDeptStore5F_Text_Directory, MSGBOX_SIGN
	end

CeladonDeptStore5_EventScript_Falkner::
	lock
	faceplayer
	msgbox CeladonDeptStore5_Text_Falkner, MSGBOX_DEFAULT
	closemessage
	fadescreenswapbuffers FADE_TO_BLACK
	setflag FLAG_HIDE_CELADON_FALKNER
	removeobject LOCALID_CELADON_FALKNER
	fadescreenswapbuffers FADE_FROM_BLACK
	clearflag FLAG_HIDE_DOJO_FALKNER
	release
	end

CeladonDeptStore5_Text_Falkner:
	.string "{PLAYER}. No esperaba verte por aquí.\p"
	.string "Estoy comprando cosas para mis\n"
	.string "POKéMON pájaro.\p"
	.string "Si quieres volver a enfrentarte a mí,\n"
	.string "estaré en el DOJO de CIUDAD AZAFRÁN.$"

CeladonDeptStore5F_Text_Gentleman:
	.string "Quiero comprar objetos que aumenten\n"
	.string "las habilidades de mis POKéMON. ¡Pero\l"
	.string "no tengo dinero!$"

CeladonDeptStore5F_Text_Sailor:
	.string "Quiero un MÁS PP para subir los PP de\n"
	.string "los movimientos. Pero no se puede\l"
	.string "comprar…$"

CeladonDeptStore5F_Text_Teacher:
	.string "Si usas objetos en tus POKéMON, se\n"
	.string "pondrán contentos.\p"
	.string "Aunque hay algunos que no les gustan.$"

CeladonDeptStore5F_Text_Directory:
	.string "P4: FARMACIA$"
