Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "¡No compensa luchar con niños!$"

Route17_Text_RaulDefeat::
	.string "¡Qué chasco!$"

Route17_Text_RaulPostBattle::
	.string "¡Por el CAMINO de BICIS\n"
	.string "hay cosas estupendas!\p"
	.string "¡Se puede ganar mucha pasta\n"
	.string "vendiendo lo que se encuentra!$"

Route17_Text_IsaiahIntro::
	.string "Estoy muy orgulloso de mi cuerpo,\n"
	.string "chaval. ¡Venga!$"

Route17_Text_IsaiahDefeat::
	.string "¡Uauuu!$"

Route17_Text_IsaiahPostBattle::
	.string "¡Podría echarte de aquí de un\n"
	.string "barrigazo!$"

Route17_Text_VirgilIntro::
	.string "¿Te diriges a CIUDAD FUCSIA?$"

Route17_Text_VirgilDefeat::
	.string "¡Me has dejado atrás del todo!$"

Route17_Text_VirgilPostBattle::
	.string "¡Me encanta correr cuesta abajo!$"

Route17_Text_BillyIntro::
	.string "¡Somos los MOTORISTAS!\n"
	.string "¡Las estrellas de la autopista!$"

Route17_Text_BillyDefeat::
	.string "¡Qué trompazo!$"

Route17_Text_BillyPostBattle::
	.string "¿Vas en busca de aventuras?$"

Route17_Text_NikolasIntro::
	.string "¡Deja que VOLTORB te dé un poco\n"
	.string "de su energía!$"

Route17_Text_NikolasDefeat::
	.string "¡Qué bajón!$"

Route17_Text_NikolasPostBattle::
	.string "¡Atrapé mis VOLTORB en la\n"
	.string "CENTRAL de ENERGÍA abandonada!$"

Route17_Text_ZeekIntro::
	.string "¡Mi POKéMON no evoluciona!\n"
	.string "¿Por qué será?$"

Route17_Text_ZeekDefeat::
	.string "¡Tú tienes la culpa!$"

Route17_Text_ZeekPostBattle::
	.string "Puede que ciertos POKéMON\n"
	.string "necesiten PIEDRAS para\l"
	.string "evolucionar.$"

Route17_Text_JamalIntro::
	.string "¡Necesito un poco de ejercicio!$"

Route17_Text_JamalDefeat::
	.string "¡Uf!\n"
	.string "¡Buen entrenamiento!$"

Route17_Text_JamalPostBattle::
	.string "¡Seguro que he perdido peso!$"

Route17_Text_CoreyIntro::
	.string "¡Sé rebelde!$"

Route17_Text_CoreyDefeat::
	.string "¡Aaaargh!$"

Route17_Text_CoreyPostBattle::
	.string "¡Prepárate para luchar por tus ideas!$"

Route17_Text_JaxonIntro::
	.string "¡Bonita BICI!\n"
	.string "¿Cómo se conduce?$"

Route17_Text_JaxonDefeat::
	.string "¡Caramba!$"

Route17_Text_JaxonPostBattle::
	.string "¡La pendiente dificulta\n"
	.string "la conducción!$"

Route17_Text_WilliamIntro::
	.string "¡Lárgate, chaval!\n"
	.string "¡Estoy agotado!$"

Route17_Text_WilliamDefeat::
	.string "¿Te has quedado a gusto?$"

Route17_Text_WilliamPostBattle::
	.string "¡Necesito dormir un rato!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "¡Aviso!\p"
	.string "¡Ojo con las cosas que hay\n"
	.string "por el suelo!$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "PISTAS ENTRENADOR\p"
	.string "Todo POKéMON es único.\p"
	.string "Hasta los POKéMON del mismo tipo\n"
	.string "y nivel crecen a diferente ritmo.$"

Route17_Text_PressBToStayInPlace::
	.string "PISTAS ENTRENADOR\p"
	.string "Pulsa el Botón B para no moverte\n"
	.string "sobre una pendiente.$"

Route17_Text_RouteSign::
	.string "RUTA 17:\n"
	.string "CIUDAD AZULONA - CIUDAD FUCSIA$"

Route17_Text_DontThrowGameThrowBalls::
	.string "¡Aviso!\p"
	.string "¡No tires el juego, mejor tira\n"
	.string "POKé BALLS!$"

Route17_Text_CyclingRoadSign::
	.string "CAMINO DE BICIS\n"
	.string "¡La pendiente termina aquí!$"

