Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "¿Quién está ahí?\n"
	.string "¡Deja de espiarnos!$"

Route6_Text_RickyDefeat::
	.string "¡Sencillamente, no puedo ganar!$"

Route6_Text_RickyPostBattle::
	.string "(Pues sí que...)$"

Route6_Text_NancyIntro::
	.string "¡Perdona!\n"
	.string "¡Esta conversación es privada!$"

Route6_Text_NancyDefeat::
	.string "¡Odio perder!$"

Route6_Text_NancyPostBattle::
	.string "(Pues sí que...)$"

Route6_Text_KeigoIntro::
	.string "No hay muchos bichos por aquí.$"

Route6_Text_KeigoDefeat::
	.string "¡No!\n"
	.string "¿Estás de broma?$"

Route6_Text_KeigoPostBattle::
	.string "Me gustan los bichos. Voy a\n"
	.string "regresar al BOSQUE VERDE.$"

Route6_Text_JeffIntro::
	.string "¿Qué?\n"
	.string "¿Quieres hablar conmigo?$"

Route6_Text_JeffDefeat::
	.string "Qué fastidio…\n"
	.string "No he podido superar tu desafío…$"

Route6_Text_JeffPostBattle::
	.string "Debería llevar más POKéMON\n"
	.string "conmigo. Me sentiré más seguro.$"

Route6_Text_IsabelleIntro::
	.string "¿Yo?\n"
	.string "Pues vale. ¡Jugaré!$"

Route6_Text_IsabelleDefeat::
	.string "Simplemente no ha funcionado…$"

Route6_Text_IsabellePostBattle::
	.string "¡Quiero ser más fuerte!\n"
	.string "¿Cuál es tu secreto?$"

Route6_Text_ElijahIntro::
	.string "¡Jamás te había visto por aquí!\n"
	.string "¿Eres fuerte?$"

Route6_Text_ElijahDefeat::
	.string "¡Eres demasiado fuerte!$"

Route6_Text_ElijahPostBattle::
	.string "¿Es débil mi POKéMON o soy yo\n"
	.string "muy malo?$"

Route6_Text_UndergroundPathSign::
	.string "VÍA SUBTERRÁNEA:\n"
	.string "CIUDAD CELESTE - CIUDAD CARMÍN$"

