SixIsland_OutcastIsland_Frlg_MapScripts::
	.byte 0

SixIsland_OutcastIsland_EventScript_Rocket::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
	end

SixIsland_OutcastIsland_Text_RocketIntro::
	.string "Por aquí no hay ni un sólo\n"
	.string "POKéMON raro. ¡Ni uno!\p"
	.string "¡Estoy hasta el gorro de buscar!\n"
	.string "¡Te ha tocado pagar el mosqueo,\l"
	.string "lo siento!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "¡¿Qué?!$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "Tú no has visto ningún POKéMON\n"
	.string "raro, ¿no?$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "¡Qué mala suerte tengo hoy!\n"
	.string "¡Igual la cosa cambia si luchamos!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "Nada, hoy no tengo suerte…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "¡Pero es que no puedo volver\n"
	.string "a casa con las manos vacías!$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "Ufff... Ufff...\p"
	.string "Vengo nadando desde el PUERTO\n"
	.string "de ISLA EXTA sin parar.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "Ufff...\n"
	.string "Ufff...$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "Solo voy por la mitad…\n"
	.string "Estoy agotado…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "No es fácil sacar POKéMON mientras\n"
	.string "se nada, ¿lo sabías?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "He perdido, pero seguro que\n"
	.string "nadando no me ganas.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "¿Vas a la isla que hay al norte?\n"
	.string "Yo no vi nada de interés.$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "ALI: ¡Vamos a echarnos un combate\n"
	.string "disfrutando de la brisa marina!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "ALI: ¡Eres increíble! ¡Además\n"
	.string "no te hace falta nadie de apoyo!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "ALI: Prefiero mil veces el mar\n"
	.string "antes que la piscina.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "ALI: ¿Quieres luchar con nosotros?\p"
	.string "Pues te hacen falta dos POKéMON\n"
	.string "por lo menos para luchar.$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "ROS: Hermanita, ¡ayuda!\n"
	.string "¡Lucha conmigo!$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "ROS: Hermanita, ¡qué fuerte es!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "ROS: Yo me agarro a mi hermanita,\n"
	.string "porque no hago pie.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "ROS: ¡Lucha con mi hermanita\n"
	.string "y conmigo!\p"
	.string "Ah..., ¿no tienes dos POKéMON?\n"
	.string "Entonces, no.$"
