Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "¡Usa las MT para enseñar a tus\n"
	.string "POKéMON buenos movimientos!$"

Route14_Text_CarterDefeat::
	.string "Aún no lo hago lo bastante bien.$"

Route14_Text_CarterPostBattle::
	.string "Tienes MO, ¿no? Los POKéMON\n"
	.string "jamás olvidarán esos movimientos.$"

Route14_Text_MitchIntro::
	.string "Mis pájaros POKéMON deberían\n"
	.string "poder luchar.$"

Route14_Text_MitchDefeat::
	.string "¡No estoy listo!$"

Route14_Text_MitchPostBattle::
	.string "Necesitan saber mejores ataques.$"

Route14_Text_BeckIntro::
	.string "Venden MTs en el CENTRO COMERCIAL\n"
	.string "de AZULONA.\p"
	.string "Las MTs no son muy raras, pero\n"
	.string "pocos tienen MOs.$"

Route14_Text_BeckDefeat::
	.string "¡Qué mala suerte!$"

Route14_Text_BeckPostBattle::
	.string "Enseña a tus POKéMON ataques\n"
	.string "de sus mismos tipos para conseguir\l"
	.string "más potencia.$"

Route14_Text_MarlonIntro::
	.string "¿Has enseñado a VOLAR a tus\n"
	.string "pájaros POKéMON?\p"
	.string "¡Es genial para ir por el cielo!$"

Route14_Text_MarlonDefeat::
	.string "¡Derribado entre llamas!$"

Route14_Text_MarlonPostBattle::
	.string "¡Adoro a los pájaros POKéMON!\n"
	.string "¡Son los que me gusta criar!$"

Route14_Text_DonaldIntro::
	.string "¿Has oído hablar de los\n"
	.string "misteriosos seres alados?$"

Route14_Text_DonaldDefeat::
	.string "¿Qué?\n"
	.string "¿Cómo he podido perder?$"

Route14_Text_DonaldPostBattle::
	.string "Los misteriosos seres alados son\n"
	.string "legendarios pájaros POKéMON.\p"
	.string "Hay tres: ARTICUNO, ZAPDOS\n"
	.string "y MOLTRES.$"

Route14_Text_BennyIntro::
	.string "¡No me apetece!\n"
	.string "Pero vale.$"

Route14_Text_BennyDefeat::
	.string "¡Lo sabía!$"

Route14_Text_BennyPostBattle::
	.string "¡No es que sea tan importante\n"
	.string "ganar o perder!$"

Route14_Text_LukasIntro::
	.string "¡Venga, venga!\n"
	.string "¡Vamos, vamos! ¡Adelante!$"

Route14_Text_LukasDefeat::
	.string "¡Arg!\n"
	.string "¡He perdido! ¡Lárgate!$"

Route14_Text_LukasPostBattle::
	.string "¿Qué, qué, qué?\n"
	.string "¿Qué quieres?$"

Route14_Text_IsaacIntro::
	.string "Necesito matar el tiempo.\n"
	.string "Cállate y combate.$"

Route14_Text_IsaacDefeat::
	.string "¿Qué?\n"
	.string "¿¡Tú!?$"

Route14_Text_IsaacPostBattle::
	.string "¡Entrenar POKéMON es un rollo!$"

Route14_Text_GeraldIntro::
	.string "¡Salimos por aquí porque hay\n"
	.string "más espacio!$"

Route14_Text_GeraldDefeat::
	.string "¡Descalificado!$"

Route14_Text_GeraldPostBattle::
	.string "¡Muy bien!\n"
	.string "¡Tus POKéMON son superfuertes!\p"
	.string "¡La fuerza mola!\n"
	.string "¡Y tú lo sabes!$"

Route14_Text_MalikIntro::
	.string "¿Combate POKéMON?\n"
	.string "¡Genial! ¡A rugir!$"

Route14_Text_MalikDefeat::
	.string "¡Hecho polvo!$"

Route14_Text_MalikPostBattle::
	.string "¡Ya sabes quién ganaría\n"
	.string "si peleáramos tú y yo!$"

Route14_Text_RouteSign::
	.string "RUTA 14:\n"
	.string "CIUDAD FUCSIA, al oeste$"

Route14_Text_KiriIntro::
	.string "LENA: TEA, vamos a poner todo\n"
	.string "de nuestra parte.$"

Route14_Text_KiriDefeat::
	.string "LENA: Vaya, snif, snif...\n"
	.string "Hemos perdido, ¿verdad?$"

Route14_Text_KiriPostBattle::
	.string "LENA: ¿Hemos perdido por mi culpa?$"

Route14_Text_KiriNotEnoughMons::
	.string "LENA: Lucharemos cuando tengas\n"
	.string "dos POKéMON.$"

Route14_Text_JanIntro::
	.string "TEA: LENA, ¡vamos allá!\n"
	.string "¡A por todas!$"

Route14_Text_JanDefeat::
	.string "TEA: ¡Eeeh! ¡No es justo!$"

Route14_Text_JanPostBattle::
	.string "TEA: ¡LENA, no llores! ¡Ya lo\n"
	.string "haremos mejor la próxima vez!$"

Route14_Text_JanNotEnoughMons::
	.string "TEA: ¿Quieres luchar?\n"
	.string "¡Te hacen falta dos POKéMON!$"
