SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "SARA: ¿Adónde habrá ido mi novio,\n"
	.string "ERIK?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Estoy capturando POKéMON para\n"
	.string "llevármelos de regalo a casa.$"

