Route20_Frlg_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route20_OnTransition
	.byte 0

Route20_OnTransition::
	call_if_unset FLAG_STOPPED_SEAFOAM_B3F_CURRENT, Route20_EventScript_ResetSeafoamBouldersForB3F
	call_if_unset FLAG_STOPPED_SEAFOAM_B4F_CURRENT, Route20_EventScript_ResetSeafoamBouldersForB4F
	end

Route20_EventScript_ResetSeafoamBouldersForB3F::
	clearflag FLAG_HIDE_SEAFOAM_1F_BOULDER_1
	clearflag FLAG_HIDE_SEAFOAM_1F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B1F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B1F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B2F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B2F_BOULDER_2
	setflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_2
	return

Route20_EventScript_ResetSeafoamBouldersForB4F::
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_3
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_4
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_5
	clearflag FLAG_HIDE_SEAFOAM_B3F_BOULDER_6
	setflag FLAG_HIDE_SEAFOAM_B4F_BOULDER_1
	setflag FLAG_HIDE_SEAFOAM_B4F_BOULDER_2
	return

Route20_EventScript_SeafoamIslandsSign::
	msgbox Route20_Text_SeafoamIslands, MSGBOX_SIGN
	end

Route20_Text_BarryIntro::
	.string "El agua es poco profunda aquí.\n"
	.string "Hay mucha gente nadando.$"

Route20_Text_BarryDefeat::
	.string "¡Splash!$"

Route20_Text_BarryPostBattle::
	.string "¡Ojalá pudiera subirme a mi\n"
	.string "POKéMON!$"

Route20_Text_ShirleyIntro::
	.string "¡Las ISLAS ESPUMA son una fácil\n"
	.string "salida!$"

Route20_Text_ShirleyDefeat::
	.string "¡Déjalo ya!$"

Route20_Text_ShirleyPostBattle::
	.string "Hay una enorme caverna debajo\n"
	.string "de esta isla.$"

Route20_Text_TiffanyIntro::
	.string "¡Me gusta flotar en el agua\n"
	.string "rodeada de peces!$"

Route20_Text_TiffanyDefeat::
	.string "¡Auchh!$"

Route20_Text_TiffanyPostBattle::
	.string "¿Quieres flotar conmigo?$"

Route20_Text_IreneIntro::
	.string "¿También estás de vacaciones?$"

Route20_Text_IreneDefeat::
	.string "¡Qué insensible eres!$"

Route20_Text_IrenePostBattle::
	.string "¡Las ISLAS ESPUMA eran antes\n"
	.string "una sola isla!$"

Route20_Text_DeanIntro::
	.string "¡Mira qué cuerpazo!$"

Route20_Text_DeanDefeat::
	.string "¡Qué ridículo!$"

Route20_Text_DeanPostBattle::
	.string "¡Debí haber fortalecido a mis\n"
	.string "POKéMON, no a mí!$"

Route20_Text_DarrinIntro::
	.string "¿Por qué te has subido a un\n"
	.string "POKéMON? ¿No sabes nadar?$"

Route20_Text_DarrinDefeat::
	.string "¡Ay!\n"
	.string "¡Torpedeado!$"

Route20_Text_DarrinPostBattle::
	.string "¡Subirse a un POKéMON es muy\n"
	.string "divertido!$"

Route20_Text_RogerIntro::
	.string "Vine aquí montado en mi POKéMON\n"
	.string "pájaro.$"

Route20_Text_RogerDefeat::
	.string "¡Oh, no!\n"
	.string "¿Y ahora qué hago?$"

Route20_Text_RogerPostBattle::
	.string "¡Mis pájaros están hechos polvo\n"
	.string "para VOLAR de nuevo!$"

Route20_Text_NoraIntro::
	.string "¡Mi novio me dio unas perlas\n"
	.string "muy grandes!$"

Route20_Text_NoraDefeat::
	.string "¡Oh, no!\n"
	.string "¡Mis perlas estaban en ellas!$"

Route20_Text_NoraPostBattle::
	.string "¿Crecerán más mis perlas dentro\n"
	.string "de un CLOYSTER?$"

Route20_Text_MissyIntro::
	.string "¡Vengo nadando desde ISLA\n"
	.string "CANELA! ¡Qué paliza!$"

Route20_Text_MissyDefeat::
	.string "¡Estoy tan decepcionada!$"

Route20_Text_MissyPostBattle::
	.string "¡Los POKéMON invadieron una casa\n"
	.string "abandonada en ISLA CANELA!\p"
	.string "Es la que llaman MANSIÓN\n"
	.string "POKéMON.$"

Route20_Text_MelissaIntro::
	.string "En ISLA CANELA, al oeste, hay\n"
	.string "un LABORATORIO POKéMON.\p"
	.string "Mi papi trabaja allí.$"

Route20_Text_MelissaDefeat::
	.string "¡Espera!\n"
	.string "¡Vas demasiado deprisa!$"

Route20_Text_MelissaPostBattle::
	.string "¡ISLA CANELA es volcánica!\p"
	.string "Dicen que surgió tras la erupción\n"
	.string "de un volcán.$"

Route20_Text_SeafoamIslands::
	.string "ISLAS ESPUMA$"

Route20_Text_MistyTrainsHere::
	.string "Por aquí hay muchos ENTRENADORES\n"
	.string "fuertes y POKéMON del tipo AGUA.\p"
	.string "Dicen que MISTY, del GIMNASIO\n"
	.string "de CELESTE, se entrena por aquí.$"
