SafariZone_East_Frlg_MapScripts::
	.byte 0

SafariZone_East_EventScript_RestHouseSign::
	msgbox SafariZone_East_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_East_EventScript_TrainerTips::
	msgbox SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk, MSGBOX_SIGN
	end

SafariZone_East_EventScript_AreaSign::
	msgbox SafariZone_East_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_East_Text_RestHouse::
	.string "CASA de DESCANSO$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
	.string "PISTAS ENTRENADOR\p"
	.string "El tiempo restante solo disminuye\n"
	.string "mientras caminas.$"

SafariZone_East_Text_AreaSign::
	.string "ZONA 1\n"
	.string "OESTE: ZONA CENTRAL$"

