DiglettsCave_NorthEntrance_Frlg_MapScripts::
	.byte 0

DiglettsCave_NorthEntrance_EventScript_Hiker::
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
	end

DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
	.string "Entré en el TÚNEL ROCA, pero está\n"
	.string "oscuro como boca de lobo y da miedo.\p"
	.string "Si pudiera conseguir un POKéMON que\n"
	.string "usara DESTELLO para iluminarlo…$"

