@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Está repleta de libros sobre POKéMON.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "Un MAPA de la ciudad.$"

Text_PokeMartShelf::
	.string "¡Uau! ¡Montones de cosas de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Los platos están bien colocados en\n"
	.string "fila.$"

Text_Kitchen::
	.string "¡Huele de maravilla! Alguien ha estado\n"
	.string "cocinando.$"

Text_Dresser::
	.string "Es una cómoda muy bien hecha. Caben\n"
	.string "muchas cosas.$"

Text_Snacks::
	.string "Aquí hay un montón de aperitivos.$"

Text_PokemartSign::
	.string "¡Todo lo que necesitas!\n"
	.string "TIENDA POKéMON$"

Text_PokecenterSign::
	.string "¡Cura a tus POKéMON!\n"
	.string "CENTRO POKéMON$"

Text_Indigo_UltimateGoal::
	.string "MESETA AÑIL\p"
	.string "¡La meta suprema de los ENTRENADORES!\n"
	.string "SEDE DE LA LIGA POKéMON$"

Text_Indigo_HighestAuthority::
	.string "MESETA AÑIL\p"
	.string "¡La máxima autoridad POKéMON!\n"
	.string "SEDE DE LA LIGA POKéMON$"

Text_Food::
	.string "Debe de estar lleno de todo tipo de\n"
	.string "cosas deliciosas para comer.$"

Text_Blueprints::
	.string "Es una especie de plano. Está lleno de\n"
	.string "diagramas y texto.$"

Text_Painting::
	.string "Es un bonito cuadro de un POKéMON.\n"
	.string "Parece que se siente bien.$"

Text_PowerPlantMachine::
	.string "¿Qué será esta máquina? ¡Mejor no\n"
	.string "tocarla!$"

Text_Telephone::
	.string "Es un teléfono. Mejor no usarlo.$"

Text_Computer::
	.string "Son todo palabras complicadas y\n"
	.string "números que no tienen sentido…$"

Text_AdvertisingPoster::
	.string "Es un cartel publicitario de todo tipo\n"
	.string "de productos.$"

Text_TastyFood::
	.string "¡Oh, qué bien huele! ¡Te puede rugir el\n"
	.string "estómago!$"

Text_TrashBin::
	.string "Dentro de esto…\n"
	.string "……\p"
	.string "¡No hay nada!$"

Text_Cup::
	.string "Es una taza con una marca de POKéMON.$"

Text_PolishedWindow::
	.string "La ventana está muy bien limpia.$"

Text_BeautifulSkyWindow::
	.string "Al otro lado de la ventana…\p"
	.string "El cielo se ve de una belleza\n"
	.string "fantástica.$"

Text_BlinkingLights::
	.string "Unas luces de colores se encienden y\n"
	.string "se apagan.$"

Text_NeatlyLinedUpTools::
	.string "Todo tipo de herramientas están bien\n"
	.string "colocadas en fila.$"

Text_ImpressiveMachine::
	.string "Es una especie de máquina. Es muy\n"
	.string "impresionante.$"

Text_VideoGame::
	.string "¡Es el último videojuego! ¡Tiene muy\n"
	.string "buena pinta!$"

Text_Burglary::
	.string "Hay claras señales de robo…$"

Text_PlayerFacingTVScreen::
	.string "¡Hay un POKéMON en la tele! Parece que\n"
	.string "se lo está pasando bien.$"
