ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "Nunca, jamás, debes ir solo al\n"
	.string "BOSQUE BAYA.\p"
	.string "¿Por qué?\n"
	.string "Hay fantasmas allí.$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "¡Papá me miente y no me deja\n"
	.string "salir a jugar!$"

