PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "Los secretos del espacio...\n"
	.string "Los misterios de la tierra...\p"
	.string "Hay tantas cosas de las que\n"
	.string "sabemos tan poco...\p"
	.string "Pero eso debería movernos a\n"
	.string "investigar más y no tirar la toalla.\p"
	.string "Y hablando de movimiento...\p"
	.string "¿Conoces el MOV. SÍSMICO?\n"
	.string "¿Quieres que se lo enseñe a algún\l"
	.string "POKéMON?$"

Text_SeismicTossDeclined::
	.string "¿Ah, no?\n"
	.string "Seguro que vuelves a pedírmelo.$"

Text_SeismicTossWhichMon::
	.string "¿A qué POKéMON quieres que\n"
	.string "le enseñe MOV. SÍSMICO?$"

Text_SeismicTossTaught::
	.string "Espero que no tires la toalla.\n"
	.string "Sigue así.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "¿La PIEDRA LUNAR?\p"
	.string "¿Por qué es tan especial?\n"
	.string "Yo no le veo nada del otro mundo.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "¡20 de julio de 1969!\p"
	.string "Ese día la humanidad pisó la luna\n"
	.string "por primera vez.\p"
	.string "Compré una tele en color solo para\n"
	.string "poder ver esa noticia.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "Ahora tenemos una exposición sobre\n"
	.string "el espacio.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "¡Quiero un PIKACHU!\n"
	.string "¡Es tan mono!\p"
	.string "¡Le pedí a mi padre que me\n"
	.string "atrapara uno!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "¡Sí, pronto tendrás a tu\n"
	.string "PIKACHU!... $"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "NAVE ESPACIAL$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "Meteorito caído en el MT. MOON.\n"
	.string "(¿PIEDRA LUNAR?)$"

