SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "¡Ah, sí! ¡Vi a unos POKéMON\n"
	.string "transportando a gente por el agua!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "Los árboles pequeños se pueden\n"
	.string "talar con el movimiento CORTE.\p"
	.string "¡Pero recuerda esto!\n"
	.string "¡CORTE es una técnica MO!\p"
	.string "Una vez aprendida, no es tan fácil\n"
	.string "de olvidar.$"

