SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Puedes quedarte con cualquier objeto\n"
	.string "que encuentres en la ZONA SAFARI.\p"
	.string "Pero se te acabará el tiempo si\n"
	.string "intentas conseguirlos todos a la vez.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Ve a la parte más profunda de la\n"
	.string "ZONA SAFARI. ¡Ganarás un premio!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Mi EEVEE evolucionó en FLAREON.\p"
	.string "Pero el EEVEE de un amigo se\n"
	.string "transformó en VAPOREON. ¿Por qué será?$"

