Route2_ViridianForest_SouthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
	.string "¿Vas al BOSQUE VERDE?\n"
	.string "Es un laberinto natural.\l"
	.string "Ten cuidado de no perderte.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
	.string "RATTATA es pequeño, pero no\n"
	.string "subestimes su mordisco perverso.\p"
	.string "¿Ya has capturado alguno?$"

