SaffronCity_Tunnel_NS_hns_MapScripts::
	.byte 0

SaffronCity_Tunnel_NS_EventScript_BaldingMan::
	lock
	faceplayer
	goto_if_set FLAG_ITEM_UNDERGROUND_PATH_TM_EXPLOSION, SaffronCity_Tunnel_NS_EventScript_BaldingManAfter
	msgbox SaffronCity_Tunnel_NS_Text_BaldingManIntro, MSGBOX_DEFAULT
	checkitem ITEM_RAGE_CANDY_BAR
	goto_if_eq VAR_RESULT, TRUE, SaffronCity_Tunnel_NS_EventScript_BaldingManDetected
	closemessage
	release
	end

SaffronCity_Tunnel_NS_EventScript_BaldingManDetected::
	playse SE_PIN
	applymovement LOCALID_SAFFRONTUNNEL_UNCLE_RAGE, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_SAFFRONTUNNEL_UNCLE_RAGE
	msgbox SaffronCity_Tunnel_NS_Text_BaldingManCandybarDetected, MSGBOX_DEFAULT
	removeitem ITEM_RAGE_CANDY_BAR
	msgbox SaffronCity_Tunnel_NS_Text_BaldingManGaveCandybar, MSGBOX_DEFAULT
	giveitem ITEM_TM_EXPLOSION
	setflag FLAG_ITEM_UNDERGROUND_PATH_TM_EXPLOSION
SaffronCity_Tunnel_NS_EventScript_BaldingManAfter::
	msgbox SaffronCity_Tunnel_NS_Text_BaldingManGaveTm, MSGBOX_DEFAULT
	closemessage
	release
	end

SaffronCity_Tunnel_NS_Text_BaldingManIntro:
	.string "No tengas miedo, no soy mala persona.\p"
	.string "Un sitio como este… atrae a gente con\n"
	.string "malas intenciones.\p"
	.string "Tarde o temprano acabarían causando\n"
	.string "problemas…\p"
	.string "Solo de pensarlo me pongo furioso.$"

SaffronCity_Tunnel_NS_Text_BaldingManCandybarDetected:
	.string "¡Ajá! ¡Eso es un CARAMELO FURIA!\p"
	.string "¿Me lo das? ¡Por favor!$"

SaffronCity_Tunnel_NS_Text_BaldingManGaveCandybar:
	.string "{PLAYER} le ha dado el CARAMELO FURIA\n"
	.string "al tipo del camino subterráneo.\p"
	.string "¡Ñam!\p"
	.string "¡Qué rabia!\p"
	.string "¡Pero qué bueno está!\p"
	.string "¡Ñam, ñam!\p"
	.string "¡Aaargh! ¡Me pone furioso!\p"
	.string "¡Ñam, ñam!\p"
	.string "Aaargh…\p"
	.string "…… ¡Uf!\p"
	.string "¡Me siento mucho mejor! ¡Gracias por el\n"
	.string "caramelo!\p"
	.string "¡Quiero que te quedes esto!$"

SaffronCity_Tunnel_NS_Text_BaldingManGaveTm:
	.string "La MT64 contiene…\p"
	.string "tic-\n"
	.string "            tac\l"
	.string "tic-\l"
	.string "            tac\l"
	.string "tic-\l"
	.string "            tac\l"
	.string "tic-\l"
	.string "            tac\l"
	.string "tic…\l"
	.string "……\l"
	.string "……\l"
	.string "¡¡¡CA-BUM!!!$"

