Akala_House_hns_MapScripts::
	.byte 0


Alola_Akala_House_OldWoman::
	lock
	faceplayer
	msgbox Alola_Akala_House_OldWoman_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Alola_Akala_House_OldWoman_Text_0:
	.string "¡Le digo a mi marido todos los días que\n"
	.string "no dé de comer a los NATU, pero nunca\l"
	.string "me hace caso!\p"
	.string "Un día de estos se traerá a casa uno\n"
	.string "de esos bichos, ¡lo sé!$"
