@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Esta GUARDERÍA es mía.\p"
	.string "¿Quieres que cuide de alguno\n"
	.string "de tus POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Vuelve en otro momento.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "¿Qué POKéMON quieres que cuide?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Vale...\n"
	.string "Vuelve cuando quieras.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Muy bien, cuidaré de {STR_VAR_1}\n"
	.string "un rato.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Vuelve dentro de un rato.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "¿Ya de vuelta?\p"
	.string "Tu {STR_VAR_1} aún necesita de mis\n"
	.string "cuidados.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Me debes {STR_VAR_2}¥ por devolverte\n"
	.string "este POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "¡Gracias!\n"
	.string "¡Aquí está tu POKéMON!$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} recuperó a {STR_VAR_1}\n"
	.string "del CUIDADOR.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Sólo tienes un POKéMON contigo.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Si me dejas ese POKéMON, no\n"
	.string "podrás entablar combates.$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "¡Tu {STR_VAR_1} ha crecido mucho!\p"
	.string "¡Su nivel ha subido {STR_VAR_2}!\p"
	.string "¿No soy genial?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "¡No tienes sitio para este POKéMON!$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "¡Oye, no tienes bastante dinero!$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "¿Quieres que\n"
	.string "veamos el tuyo?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "Lo siento, pero no puedo guardar\n"
	.string "POKéMON que sepan una MO.$"
