Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "¡Uff!... Voy a descansar.\n"
	.string "Ufff...\p"
	.string "¡Ese túnel a CELESTE es agotador!$"

Route3_Text_ColtonIntro::
	.string "¡Nos vimos en el BOSQUE VERDE!$"

Route3_Text_ColtonDefeat::
	.string "¡Has ganado otra vez!$"

Route3_Text_ColtonPostBattle::
	.string "¡Hay otros tipos de POKéMON\n"
	.string "diferentes a los del bosque!$"

Route3_Text_BenIntro::
	.string "¡Hola!\n"
	.string "¡Me gustan los pantalones cortos!\p"
	.string "¡Son muy cómodos!$"

Route3_Text_BenDefeat::
	.string "¡No me lo puedo creer!$"

Route3_Text_BenPostBattle::
	.string "¿Estás guardando a tus POKéMON\n"
	.string "en el PC?\p"
	.string "¡Cada CAJA puede tener 30\n"
	.string "POKéMON!$"

Route3_Text_JaniceIntro::
	.string "Estabas mirándome, ¿verdad?$"

Route3_Text_JaniceDefeat::
	.string "¡Eres de lo que no hay!$"

Route3_Text_JanicePostBattle::
	.string "¡Deja de mirarme si no quieres\n"
	.string "luchar!$"

Route3_Text_GregIntro::
	.string "¿Entrenas POKéMON?\n"
	.string "¡Pues luchemos!$"

Route3_Text_GregDefeat::
	.string "¡Con nuevos POKéMON te habría\n"
	.string "ganado!$"

Route3_Text_GregPostBattle::
	.string "¡Si una CAJA de POKéMON del PC\n"
	.string "está llena, cambia a otra CAJA!$"

Route3_Text_SallyIntro::
	.string "Esa mirada que me echaste…\n"
	.string "¡Es tan intrigante!$"

Route3_Text_SallyDefeat::
	.string "¡Sé amable!$"

Route3_Text_SallyPostBattle::
	.string "¡Para evitar luchar, procura que\n"
	.string "no te vean!$"

Route3_Text_CalvinIntro::
	.string "¡Oye!\n"
	.string "¡No llevas pantalón corto!$"

Route3_Text_CalvinDefeat::
	.string "¡He perdido!\n"
	.string "¡He perdido!$"

Route3_Text_CalvinPostBattle::
	.string "Llevo pantalones cortos hasta\n"
	.string "en invierno.$"

Route3_Text_JamesIntro::
	.string "¡Puedes luchar contra mis nuevos\n"
	.string "POKéMON!$"

Route3_Text_JamesDefeat::
	.string "¡Estoy acabado!$"

Route3_Text_JamesPostBattle::
	.string "¡Los POKéMON entrenados son más\n"
	.string "fuertes que los salvajes!$"

Route3_Text_RobinIntro::
	.string "¡Oye!\n"
	.string "¿Por qué me has tocado?$"

Route3_Text_RobinDefeat::
	.string "¿Eso es todo?$"

Route3_Text_RobinPostBattle::
	.string "La RUTA 4 está debajo del MT.\n"
	.string "MOON.$"

Route3_Text_RouteSign::
	.string "RUTA 3:\n"
	.string "HACIA EL MT. MOON$"

