OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "Tumbada, mecida por las olas…\n"
	.string "Es exquisito.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "He perdido…\n"
	.string "Qué mal me siento.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "El mar está agradablemente cálido\n"
	.string "por aquí.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "La corriente marina arrastra cosas\n"
	.string "buenas a esta playa.\p"
	.string "Por eso vengo a menudo a recorrer\n"
	.string "la orilla en busca de tesoros.$"

