Route15_Frlg_MapScripts::
	.byte 0

Route15_EventScript_RouteSign::
	msgbox Route15_Text_RouteSign, MSGBOX_SIGN
	end

Route15_Text_KindraIntro::
	.string "¡Déjame probar los POKéMON\n"
	.string "que acabo de cambiar!$"

Route15_Text_KindraDefeat::
	.string "¡No ha sido suficiente!$"

Route15_Text_KindraPostBattle::
	.string "No puedes variar el mote de ningún\n"
	.string "POKéMON que hayas cambiado.\p"
	.string "¡El ENTRENADOR original es el\n"
	.string "único que puede!$"

Route15_Text_BeckyIntro::
	.string "¡Pareces manejable!\n"
	.string "¡Creo que podría vencerte!\p"
	.string "¡Voy a intentarlo!$"

Route15_Text_BeckyDefeat::
	.string "No, ¡muy mal!$"

Route15_Text_BeckyPostBattle::
	.string "¡Me dan miedo los MOTORISTAS,\n"
	.string "son gamberros, horribles!$"

Route15_Text_EdwinIntro::
	.string "¡Silbando puedo llamar a los\n"
	.string "pájaros POKéMON!$"

Route15_Text_EdwinDefeat::
	.string "¡Ay!\n"
	.string "¡Qué tragedia!$"

Route15_Text_EdwinPostBattle::
	.string "Puede que no esté hecho para\n"
	.string "luchar contra otros.$"

Route15_Text_ChesterIntro::
	.string "Mis pájaros están temblando.\n"
	.string "Eres muy fuerte, ¿no?$"

Route15_Text_ChesterDefeat::
	.string "¡Lo que pensaba!$"

Route15_Text_ChesterPostBattle::
	.string "No sé si decirte esto, supongo\n"
	.string "que ya lo sabes...\p"
	.string "¿Sabías que los movimientos\n"
	.string "como TERREMOTO o FISURA\l"
	.string "no afectan a los pájaros?$"

Route15_Text_GraceIntro::
	.string "¡Oh, qué cosita más mona!\n"
	.string "¡Eres como un POKéMON adorable!$"

Route15_Text_GraceDefeat::
	.string "¡Tú también parecías tan mono!$"

Route15_Text_GracePostBattle::
	.string "Te perdono.\n"
	.string "Puedo con ello.\l"
	.string "Ya soy una chica mayor.$"

Route15_Text_OliviaIntro::
	.string "¡Cuido POKéMON porque vivo sola\n"
	.string "y hacen que me sienta segura!$"

Route15_Text_OliviaDefeat::
	.string "Para mí, los POKéMON no son\n"
	.string "ganar o perder.$"

Route15_Text_OliviaPostBattle::
	.string "¡Me gusta ir a casa para estar\n"
	.string "con mis POKéMON!\p"
	.string "Es una tranquilidad...$"

Route15_Text_ErnestIntro::
	.string "¡Oye! ¡Ven aquí!\n"
	.string "¡Mira esto!$"

Route15_Text_ErnestDefeat::
	.string "¿Por qué no?$"

Route15_Text_ErnestPostBattle::
	.string "¡Sólo se vive una vez, y yo vivo\n"
	.string "como un forajido!\l"
	.string "¡NORMAS del TEAM ROCKET!$"

Route15_Text_AlexIntro::
	.string "¡Suelta todo tu dinero si pierdes\n"
	.string "contra mí, chaval!$"

Route15_Text_AlexDefeat::
	.string "¡No puede ser!$"

Route15_Text_AlexPostBattle::
	.string "¡Oye, que lo del dinero era broma!\n"
	.string "¡No me hagas caso!$"

Route15_Text_CeliaIntro::
	.string "¿Qué mola?\n"
	.string "¡Cambiar POKéMON!$"

Route15_Text_CeliaDefeat::
	.string "¡He dicho cambiar!$"

Route15_Text_CeliaPostBattle::
	.string "¡Cambio POKéMON con mis amigos!$"

Route15_Text_YazminIntro::
	.string "¿Quieres jugar con mis POKéMON?$"

Route15_Text_YazminDefeat::
	.string "¡Estaba demasiado impaciente!$"

Route15_Text_YazminPostBattle::
	.string "¡Me entrenaré con gente más débil!$"

Route15_Text_RouteSign::
	.string "RUTA 15:\n"
	.string "CIUDAD FUCSIA, al oeste$"

Route15_Text_MyaIntro::
	.string "TINA: Eres genial. ¿Luchamos para\n"
	.string "que aprenda mi hermano?$"

Route15_Text_MyaDefeat::
	.string "TINA: ¡TIN, concéntrate! ¡Hay que\n"
	.string "concentrarse en lo que se hace!$"

Route15_Text_MyaPostBattle::
	.string "TINA: Tenemos que hacer algo,\n"
	.string "¡debemos entrenarnos más!$"

Route15_Text_MyaNotEnoughMons::
	.string "TINA: ¿Quieres desafiarnos?\n"
	.string "¡Pues necesitas dos POKéMON!$"

Route15_Text_RonIntro::
	.string "TIN: Mi hermana se asusta cuando\n"
	.string "perdemos.$"

Route15_Text_RonDefeat::
	.string "TIN: Vaya, hermanita, lo siento...$"

Route15_Text_RonPostBattle::
	.string "TIN: Mi hermana se pone un poco\n"
	.string "pesada...$"

Route15_Text_RonNotEnoughMons::
	.string "TIN: ¿Te gustaría luchar\n"
	.string "con nosotros?\p"
	.string "¡Pues vente con dos POKéMON!$"
