CeladonCity_DepartmentStore_3F_Frlg_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
	goto EventScript_CounterTutor
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
	.string "¡Los POKéMON capturados tienen un\n"
	.string "N.º IDENTIDAD y un EO, el nombre\p"
	.string "del ENTRENADOR ORIGINAL\n"
	.string "que lo atrapó!$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
	.string "¡Muy bien!\p"
	.string "¡Mi compañero va a cambiarme su\n"
	.string "KANGASKHAN por mi GRAVELER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
	.string "¡Un GRAVELER!\p"
	.string "¡Me gustan los GRAVELER!\n"
	.string "¡Los colecciono!\p"
	.string "¿Qué?\p"
	.string "¡GRAVELER se transformó en otro\n"
	.string "POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
	.string "¡Puedes identificar a los POKéMON\n"
	.string "que hayas cambiado por su N.º ID!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
	.string "¡Es una SUPER NINTENDO!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
	.string "Un juego de rol.\n"
	.string "¡Genial! ¡Pero no tengo tiempo!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
	.string "¡Un juego de deportes!\n"
	.string "¡A mi padre le gustan!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
	.string "¡Un juego de puzzles!\n"
	.string "¡Parece muy adictivo!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
	.string "¡Un juego de lucha!\n"
	.string "¡Parece muy difícil!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
	.string "P2: VIDEOJUEGOS$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
	.string "¡Rojo y Verde!\n"
	.string "¡Dos juegos de POKéMON!$"

Text_CounterTeach::
	.string "¡Hola! ¡Ya me he acabado\n"
	.string "POKéMON!\p"
	.string "¿Tú no? ¿Quieres que te enseñe\n"
	.string "un movimiento?\p"
	.string "He pensado en CONTADOR.\p"
	.string "¡No te voy a enseñar el que acabo\n"
	.string "de aprender, claro!$"

Text_CounterDeclined::
	.string "¿No te interesa? Bueno, vuelve\n"
	.string "si cambias de opinión.$"

Text_CounterWhichMon::
	.string "¿A qué POKéMON quieres que\n"
	.string "le enseñe CONTADOR?$"

Text_CounterTaught::
	.string "¿Estás usando el movimiento\n"
	.string "CONTADOR que le enseñé\l"
	.string "a tu POKéMON?$"
