Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "¿Eres como los POKéMANÍACOS?\n"
	.string "¿Quieres ver mi colección?$"

Route10_Text_MarkDefeat::
	.string "¿Qué?\n"
	.string "¡No estoy enfadado!$"

Route10_Text_MarkPostBattle::
	.string "¡En casa tengo más POKéMON\n"
	.string "superraros!$"

Route10_Text_ClarkIntro::
	.string "¡Ja-jajá-já!$"

Route10_Text_ClarkDefeat::
	.string "¡Ja-jaja!\n"
	.string "¡No me estoy riendo!\l"
	.string "¡Es a-a-a-lergia! ¡Ja-ja-ja-chís!$"

Route10_Text_ClarkPostBattle::
	.string "¡Ja-ja-ja-chís!\n"
	.string "¡Achís!\l"
	.string "¡Ñic! ¡Snif!$"

Route10_Text_HermanIntro::
	.string "¡Eh, hola!\n"
	.string "¿Quieres ver mis POKéMON?$"

Route10_Text_HermanDefeat::
	.string "¡Oh, no!\n"
	.string "¡Mis POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "No me caes bien.\n"
	.string "¡No me gusta nadie mejor que yo!$"

Route10_Text_HeidiIntro::
	.string "He estado varias veces en un\n"
	.string "GIMNASIO POKéMON.\p"
	.string "¡Y he perdido siempre!$"

Route10_Text_HeidiDefeat::
	.string "¡Oh!\n"
	.string "¡Después de todo mi entrenamiento!$"

Route10_Text_HeidiPostBattle::
	.string "Vi a unos POKéMANÍACOS merodeando.\p"
	.string "¿Te lo imaginas? ¿Ellos?\n"
	.string "¿Aquí arriba, en las montañas?$"

Route10_Text_TrentIntro::
	.string "¡Ah!\n"
	.string "¡Me encanta el aire de montaña!$"

Route10_Text_TrentDefeat::
	.string "¡Me ha despejado la cabeza!$"

Route10_Text_TrentPostBattle::
	.string "A mí el aire de la montaña\n"
	.string "me atonta.$"

Route10_Text_CarolIntro::
	.string "Me siento un poco mareado.\n"
	.string "Hace tiempo que no hago senderismo.$"

Route10_Text_CarolDefeat::
	.string "Estoy demasiado cansado.\n"
	.string "No estaba para esto.$"

Route10_Text_CarolPostBattle::
	.string "¡Estos POKéMON son tan toscos!\p"
	.string "¡Debería haber alguno rosa con\n"
	.string "bonitas flores!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "TÚNEL ROCA\n"
	.string "Desvío hacia PUEBLO LAVANDA.$"

Route10_Text_RockTunnel::
	.string "TÚNEL ROCA$"

Route10_Text_PowerPlant::
	.string "CENTRAL ENERGÍA$"

