SixIsland_House_Frlg_MapScripts::
	.byte 0

SixIsland_House_EventScript_OldMan::
	msgbox SixIsland_House_Text_GoodPlaceForNatureAndHistory, MSGBOX_NPC
	end

SixIsland_House_Text_GoodPlaceForNatureAndHistory::
	.string "Aquí la gente joven no encuentra\n"
	.string "nada de su interés.\p"
	.string "Pero éste es un lugar único por la\n"
	.string "naturaleza y la historia que tiene.\p"
	.string "Relájate y disfruta de la estancia.$"

