Route13_Frlg_MapScripts::
	.byte 0

Route13_EventScript_TrainerTips1::
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
	end

Route13_EventScript_TrainerTips2::
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
	end

Route13_EventScript_RouteSign::
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
	end

Route13_Text_SebastianIntro::
	.string "¡Mis POKéMON pájaro quieren\n"
	.string "combatir contigo!$"

Route13_Text_SebastianDefeat::
	.string "¿Mi combinación de PIDGEY y\n"
	.string "PIDGEOTTO ha perdido?$"

Route13_Text_SebastianPostBattle::
	.string "Mis POKéMON parecen felices aunque\n"
	.string "hayan perdido.$"

Route13_Text_SusieIntro::
	.string "Dicen que soy bueno para ser un niño.$"

Route13_Text_SusieDefeat::
	.string "¡Oh!\n"
	.string "¡He perdido!$"

Route13_Text_SusiePostBattle::
	.string "Quiero ser un buen ENTRENADOR.\n"
	.string "Entrenaré duro, ya verás.$"

Route13_Text_ValerieIntro::
	.string "¡Guau!\n"
	.string "¡Tus MEDALLAS son geniales!$"

Route13_Text_ValerieDefeat::
	.string "¡No es suficiente!$"

Route13_Text_ValeriePostBattle::
	.string "Conseguiste esas MEDALLAS de\n"
	.string "los LÍDERES de GIMNASIO. ¡Lo sé!$"

Route13_Text_GwenIntro::
	.string "Mis lindos POKéMON desean\n"
	.string "conocerte.$"

Route13_Text_GwenDefeat::
	.string "¡Bien hecho!\n"
	.string "¡Has ganado de calle!$"

Route13_Text_GwenPostBattle::
	.string "Hay que hacer combatir a los POKéMON\n"
	.string "para fortalecerlos.$"

Route13_Text_AlmaIntro::
	.string "Una vez encontré CARBURANTE en una\n"
	.string "cueva mientras exploraba.$"

Route13_Text_AlmaDefeat::
	.string "¡Oh, qué pena!\n"
	.string "¡Acabo de equivocarme!$"

Route13_Text_AlmaPostBattle::
	.string "El CARBURANTE aumentó la VELOCIDAD\n"
	.string "de mis POKéMON.$"

Route13_Text_PerryIntro::
	.string "No voy a perder.\n"
	.string "¡No con el viento a mi favor!$"

Route13_Text_PerryDefeat::
	.string "¡El viento ha cambiado!$"

Route13_Text_PerryPostBattle::
	.string "Estoy rendido.\n"
	.string "Creo que VOLARÉ a casa.$"

Route13_Text_LolaIntro::
	.string "Claro, jugaré contigo, cariño.$"

Route13_Text_LolaDefeat::
	.string "¡Oh!\n"
	.string "¡Pequeña fiera!$"

Route13_Text_LolaPostBattle::
	.string "Me pregunto qué será más fuerte,\n"
	.string "un POKéMON macho o hembra.$"

Route13_Text_SheilaIntro::
	.string "¿Quieres combatir con unos\n"
	.string "POKéMON conmigo?$"

Route13_Text_SheilaDefeat::
	.string "¿Ya se acabó?$"

Route13_Text_SheilaPostBattle::
	.string "En realidad no sé nada de POKéMON.\p"
	.string "Los que uso… ¡los elegí por\n"
	.string "su aspecto!$"

Route13_Text_JaredIntro::
	.string "¿Qué miras?$"

Route13_Text_JaredDefeat::
	.string "¡Caray!\n"
	.string "¡Se me han pelado los engranajes!$"

Route13_Text_JaredPostBattle::
	.string "¡Lárgate!$"

Route13_Text_RobertIntro::
	.string "Siempre elijo POKéMON pájaro.\n"
	.string "Me he dedicado a ellos.$"

Route13_Text_RobertDefeat::
	.string "¡Sin energía!$"

Route13_Text_RobertPostBattle::
	.string "Ojalá pudiera volar como PIDGEY y\n"
	.string "PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Mira, mira!\n"
	.string "¡Mira a la izquierda de ese poste!$"

Route13_Text_SelectToSwitchItems::
	.string "PISTAS ENTRENADOR\p"
	.string "Usa SELECT para cambiar objetos en\n"
	.string "la ventana de OBJETOS.$"

Route13_Text_RouteSign::
	.string "RUTA 13\n"
	.string "Al norte: PUENTE SILENCIO$"

