#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("ZAFIRO");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBÍ");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("ESMERALDA");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("AQUILES");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAGNO");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRUNO");
const u8 gText_ExpandedPlaceholder_May[] = _("AURA");
const u8 gText_ExpandedPlaceholder_Red[] = _("ROJO");
const u8 gText_ExpandedPlaceholder_Green[] = _("VERDE");
const u8 gText_ExpandedPlaceholder_Silver[] = _("PLATA");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("HUEVO");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("JUGADOR"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("TIEMPO");
const u8 gText_Badges[] = _("MEDALLAS"); // Unused
const u8 gText_AButton[] = _("Botón A"); // Unused
const u8 gText_BButton[] = _("Botón B"); // Unused
const u8 gText_RButton[] = _("Botón R"); // Unused
const u8 gText_LButton[] = _("Botón L"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ Cruz de Control"); // Unused
const u8 gText_LButtonRButton[] = _("Botón L  Botón R"); // Unused
const u8 gText_Controls[] = _("CONTROLES"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}ELEGIR {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}SEGUIR");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}OK {B_BUTTON}ATRÁS");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}ELEGIR {A_BUTTON}OK {B_BUTTON}SALIR");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}ELEGIR {A_BUTTON}{B_BUTTON}SALIR");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}SALIR");
const u8 gText_Boy[] = _("CHICO");
const u8 gText_Girl[] = _("CHICA");
const u8 gText_ThisIsAPokemon[] = _("Esto es lo que llamamos un “POKéMON”.{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("POKéMON (?)");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???,? m");
const u8 gText_UnkWeight[] = _("????,? lbs.");
const u8 gText_UnkWeightMetric[] = _("???,? kg");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   kg."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("GRITO DE");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("COMPARADO CON ");
const u8 gText_PokedexRegistration[] = _("Registro en la POKéDEX completado.");
const u8 gText_HTHeight[] = _("ALT.");
const u8 gText_WTWeight[] = _("PESO");
const u8 gText_SearchingPleaseWait[] = _("Buscando…\nUn momento.");
const u8 gText_SearchCompleted[] = _("Búsqueda lista.");
const u8 gText_NoMatchingPkmnWereFound[] = _("No se ha encontrado ningún POKéMON.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Busca POKéMON según los\nparámetros elegidos.");
const u8 gText_SwitchPokedexListings[] = _("Ordenar la POKéDEX.");
const u8 gText_ReturnToPokedex[] = _("Vuelve a la POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Elige modo de POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Elige el orden de la POKéDEX.");
const u8 gText_ListByFirstLetter[] = _("Ordena por la inicial del nombre.\nSolo POKéMON vistos.");
const u8 gText_ListByBodyColor[] = _("Ordena por color.\nSolo POKéMON vistos.");
const u8 gText_ListByType[] = _("Ordena por tipo.\nSolo capturados.");
const u8 gText_ExecuteSearchSwitch[] = _("Buscar u ordenar.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("DEX JOHTO");
#else
const u8 gText_DexHoennTitle[] = _("POKéDEX HOENN");
#endif
const u8 gText_DexNatTitle[] = _("DEX NACIONAL");
const u8 gText_DexSortNumericalTitle[] = _("POKéDEX JOHTO");
const u8 gText_DexSortAtoZTitle[] = _("POKéDEX HOENN");
const u8 gText_DexSortHeaviestTitle[] = _("POKéDEX NACIONAL");
const u8 gText_DexSortLightestTitle[] = _("MODO NUMÉRICO");
const u8 gText_DexSortTallestTitle[] = _("MODO A-Z");
const u8 gText_DexSortSmallestTitle[] = _("MODO + PESADO");
const u8 gText_DexSearchAlphaABC[] = _("MODO + LIGERO");
const u8 gText_DexSearchAlphaDEF[] = _("MODO + ALTO");
const u8 gText_DexSearchAlphaGHI[] = _("MODO + BAJO");
const u8 gText_DexSearchAlphaJKL[] = _("ABC");
const u8 gText_DexSearchAlphaMNO[] = _("DEF");
const u8 gText_DexSearchAlphaPQR[] = _("GHI");
const u8 gText_DexSearchAlphaSTU[] = _("JKL");
const u8 gText_DexSearchAlphaVWX[] = _("MNO");
const u8 gText_DexSearchAlphaYZ[] = _("PQR");
const u8 gText_DexSearchColorRed[] = _("STU");
const u8 gText_DexSearchColorBlue[] = _("VWX");
const u8 gText_DexSearchColorYellow[] = _("YZ");
const u8 gText_DexSearchColorGreen[] = _("ROJO");
const u8 gText_DexSearchColorBlack[] = _("AZUL");
const u8 gText_DexSearchColorBrown[] = _("AMARILLO");
const u8 gText_DexSearchColorPurple[] = _("VERDE");
const u8 gText_DexSearchColorGray[] = _("NEGRO");
const u8 gText_DexSearchColorWhite[] = _("MARRÓN");
const u8 gText_DexSearchColorPink[] = _("MORADO");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("GRIS");
#else
const u8 gText_DexHoennDescription[] = _("BLANCO");
#endif
const u8 gText_DexNatDescription[] = _("ROSA");
const u8 gText_DexSortNumericalDescription[] = _("POKéDEX de JOHTO");
const u8 gText_DexSortAtoZDescription[] = _("POKéDEX de HOENN");
const u8 gText_DexSortHeaviestDescription[] = _("POKéDEX nacional");
const u8 gText_DexSortLightestDescription[] = _("Los POKéMON aparecen según su\nnúmero.");
const u8 gText_DexSortTallestDescription[] = _("Los POKéMON vistos y capturados\naparecen por orden alfabético.");
const u8 gText_DexSortSmallestDescription[] = _("Los POKéMON capturados aparecen\ndel más pesado al más ligero.");
const u8 gText_DexEmptyString[] = _("Los POKéMON capturados aparecen\ndel más ligero al más pesado.");
const u8 gText_DexSearchDontSpecify[] = _("Los POKéMON capturados aparecen\ndel más alto al más bajo.");
const u8 gText_DexSearchTypeNone[] = _("Los POKéMON capturados aparecen\ndel más bajo al más alto.");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _("INDIFERENTE"); // Unused
const u8 gText_WelcomeToHOF[] = _("NO TIENE");
const u8 gText_HOFDexRating[] = _("POKéMON vistos: ¡{STR_VAR_1}!\nPOKéMON capturados: ¡{STR_VAR_2}!\p¡Evaluación de la POKéDEX\ndel PROF. ABEDUL!\pPROF. ABEDUL: A ver…\p");
const u8 gText_HOFDexSaving[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_HOFCorrupted[] = _("¡Bienvenido al HALL DE LA FAMA!");
const u8 gText_HOFNumber[] = _("POKéMON vistos: ¡{STR_VAR_1}!\nPOKéMON capturados: ¡{STR_VAR_2}!\p¡Evaluación de la POKéDEX\ndel PROF. ABEDUL!\pPROF. ABEDUL: A ver…\p");
const u8 gText_LeagueChamp[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_Number[] = _("Los datos del HALL DE LA FAMA\nestán dañados.");
const u8 gText_Level[] = _("HALL DE LA FAMA N.º {STR_VAR_1}");
const u8 gText_IdNumberSlash[] = _("¡CAMPEÓN DE LIGA!\n¡ENHORABUENA!"); // Unused
const u8 gText_Name[] = _("N.º ");
const u8 gText_IDNumber[] = _("Nv. ");
const u8 gText_BirchInTrouble[] = _("N.º ID /");
const u8 gText_ConfirmStarterChoice[] = _("NOMBRE");
const u8 gText_Pokemon4[] = _("N.º ID"); // Unused
const u8 gText_FlyToWhere[] = _("¡El PROF. ABEDUL está en apuros!\n¡Saca un POKéMON y ayúdale!");
const u8 gMenuText_Use[] = _("¿Eliges este POKéMON?");
const u8 gMenuText_Toss[] = _("POKéMON");
const u8 gMenuText_Register[] = _("¿Adónde?");
const u8 gMenuText_Give[] = _("USAR");
const u8 gMenuText_Confirm[] = _("TIRAR");
const u8 gText_Cancel[] = _("REGISTRAR");
const u8 gText_Cancel2[] = _("DAR");
const u8 gText_EmptyString2[] = _("ACEPTAR");
const u8 gText_None[] = _("SALIR");
const u8 gText_FiveMarks[] = _("SALIR");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("NO TIENE");
const u8 gText_TwoDashes[] = _("?????");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Vuelve al menú\nanterior.");
const u8 gText_WhatWouldYouLike[] = _("¿Qué quieres hacer?");
const u8 gMenuText_Give2[] = _("DAR");
const u8 gText_xVar1[] = _("Vuelve al menú\nanterior.");
const u8 gText_Berry2[] = _("¿Qué quieres hacer?"); // Unused
const u8 gText_Coins[] = _("DAR");
const u8 gText_CloseBag[] = _("SALIR");
const u8 gText_Var1IsSelected[] = _(" BAYA");
const u8 gText_CantWriteMail[] = _("{STR_VAR_1} FICHAS");
const u8 gText_NoPokemon[] = _("SALIR");
const u8 gText_MoveVar1Where[] = _("{STR_VAR_1}\nelegido.");
const u8 gText_Var1CantBeHeld[] = _("No puedes\nescribir aquí.");
const u8 gText_TossHowManyVar1s[] = _("No hay\nPOKéMON.");
const u8 gText_ThrewAwayVar2Var1s[] = _("¿Mover\n{STR_VAR_1}\nadónde?");
const u8 gText_ConfirmTossItems[] = _("No se puede llevar {STR_VAR_1}.");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("¿Tirar cuántos\n{STR_VAR_1}?");
#else
    const u8 gText_DadsAdvice[] = _("Has tirado {STR_VAR_2}\n{STR_VAR_1}.");
#endif
const u8 gText_PlayerUsedVar2[] = _("¿Seguro que quieres\ntirar {STR_VAR_2}\n{STR_VAR_1}?");
const u8 gText_RepelEffectsLingered[] = _("Consejo de ELM…\n¡{PLAYER}, cada cosa a su tiempo\ly en su lugar!{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Consejo de PAPÁ…\n¡{PLAYER}, cada cosa a su tiempo\ly en su lugar!{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("{PLAYER} ha usado\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("Pero el efecto del REPELENTE\nanterior aún dura.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheBattle[] = _("Pero aún dura el efecto\ndel Incienso anterior.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThePokemonList[] = _("¡CAJA llena!{PAUSE_UNTIL_PRESS}");
const u8 gText_TheShop[] = _("al campo");
const u8 gText_ThePC[] = _("al combate");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("al EQUIPO");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("a la tienda"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("al PC"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("Volver\n{STR_VAR_1}."),
    [POCKET_BERRIES] =      COMPOUND_STRING("OBJETOS"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("POKé BALLS"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("MT y MO"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("BAYAS"),
    [POCKET_TREASURES] =    COMPOUND_STRING("OBJ. CLAVE"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("MEDICINAS");
const u8 gText_NumberItem_HM[] = _("COMBATE");

const u8 gText_ShopBuy[] = _("TESOROS");
const u8 gText_ShopSell[] = _("VENDER");
const u8 gText_ShopQuit[] = _("SALIR");
const u8 gText_ThatItemIsSoldOut[] = _("COMPRAR");
const u8 gText_SoldOut[] = _("VENDER");
const u8 gText_InBagVar1[] = _("SALIR");
const u8 gText_QuitShopping[] = _("Lo siento, ese objeto se ha agotado.{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1CertainlyHowMany[] = _("AGOTADO");
const u8 gText_Var1CertainlyHowMany2[] = _("TIENES: {STR_VAR_1}");
const u8 gText_Var1AndYouWantedVar2[] = _("Salir de\nla tienda.");
const u8 gText_Var1AndYouWantedVar2BP[] = _("¿{STR_VAR_1}? Muy bien.\n¿Cuántos quieres?");
const u8 gText_Var1IsItThatllBeVar2[] = _("¿{STR_VAR_1}? Muy bien.\n¿Cuántos quieres?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("¿{STR_VAR_1}? ¿Querías {STR_VAR_2}?\nSerán ¥{STR_VAR_3}.");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("¿{STR_VAR_1}? ¿Querías {STR_VAR_2}?\nSerán {STR_VAR_3} PB.");
const u8 gText_HereYouGoThankYou[] = _("{STR_VAR_1}, ¿verdad?\nSon ¥{STR_VAR_2}. ¿Lo quieres?");
const u8 gText_ThankYouIllSendItHome[] = _("¿Querías {STR_VAR_1}?\nSon ¥{STR_VAR_2}. ¿Te parece bien?");
const u8 gText_ThanksIllSendItHome[] = _("¿Querías {STR_VAR_1}?\nSon {STR_VAR_2} PB. ¿Te parece bien?");
const u8 gText_YouDontHaveMoney[] = _("¡Aquí tienes!\nMuchas gracias.");
const u8 gText_YouDontHaveEnoughBP[] = _("¡Gracias!\nTe lo enviaré al PC de tu casa.");
const u8 gText_DontHaveEnoughVar1[] = _("¡Gracias!\nTe lo enviaré a tu PC de casa.");
const u8 gText_Var1SureHowMany[] = _("No tienes suficiente dinero.{PAUSE_UNTIL_PRESS}");
const u8 gText_xOne[] = _("No tienes suficientes\nPB.{PAUSE_UNTIL_PRESS}");
const u8 gText_xFive[] = _("No tienes suficientes\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("¿{STR_VAR_1}? Claro.\n¿Cuántos quieres?");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("x1");
const u8 gText_KurtGettingStarted[] = _("x5");
const u8 gText_ExitMenu[] = _("¿Y querías {STR_VAR_2}?\nSerán {STR_VAR_3} bayas.");
const u8 gText_NoMoreRoomForThis[] = _("¿Y querías {STR_VAR_2}?\nSerá {STR_VAR_3} baya.");
const u8 gText_SpaceForVar1Full[] = _("CÉSAR: ¡Me pongo ahora mismo!");
const u8 gText_AnythingElseICanHelp[] = _("SALIR");
const u8 gText_CanIHelpWithAnythingElse[] = _("No te cabe más\nde este objeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBall[] = _("No hay sitio para más {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("¿Puedo ayudarte en algo\nmás?");
const u8 gText_CantBuyKeyItem[] = _("¿Puedo ayudarte en algo más?");
const u8 gText_HowManyToSell[] = _("Te regalo también una HONOR BALL.{PAUSE_UNTIL_PRESS}");
const u8 gText_ICanPayVar1[] = _("Te regalo también\n{STR_VAR_1} HONOR BALLS.{PAUSE_UNTIL_PRESS}");
const u8 gText_TurnedOverVar1ForVar2[] = _("¿{STR_VAR_2}?\nEso no lo compro.{PAUSE_UNTIL_PRESS}");
const u8 gText_PokedollarVar1[] = _("¿{STR_VAR_2}?\n¿Cuántos quieres vender?");
const u8 gText_HP3[] = _("Te doy ¥{STR_VAR_1}.\n¿Te parece bien?");
const u8 gText_SpAtk3[] = _("Has entregado {STR_VAR_2}\ny has recibido ¥{STR_VAR_1}.");
const u8 gText_SpDef3[] = _("DEF. ESP.");
const u8 gText_WontHaveEffect[] = _("PS");
const u8 gText_NextFusionMon[] = _("AT. ESP.");
const u8 gText_CantBeUsedOnPkmn[] = _("DEF. ESP.");
const u8 gText_PkmnCantSwitchOut[] = _("No tendrá ningún efecto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("Elige {PKMN} a fusionar.");
const u8 gText_PkmnAlreadySelected[] = _("No se puede usar con\nese POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("¡{STR_VAR_1} no puede\nretirarse!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("¡{STR_VAR_1} ya está\ncombatiendo!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("{STR_VAR_1} ya ha sido\nelegido.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("¡{STR_VAR_1} no tiene\nfuerzas para luchar!{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("¡No puedes cambiar un POKéMON\nde {STR_VAR_1} por uno tuyo!{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("¡Un HUEVO no lucha!{PAUSE_UNTIL_PRESS}");
const u8 gText_MailSentToPC[] = _("No se puede usar hasta que\nconsigas otra MEDALLA.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("No pueden participar más de\n{STR_VAR_1} POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("¿Enviar la CARTA\nretirada a tu PC?");
const u8 gText_RemoveMailBeforeItem[] = _("La CARTA se ha enviado a tu PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("¡El BUZÓN del PC\nestá lleno!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("Si retiras la CARTA, se perderá\nel mensaje. ¿Seguro?");
const u8 gText_PkmnNotHolding[] = _("Hay que retirar la CARTA antes\nde darle un objeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("{STR_VAR_1} lleva ahora\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("{STR_VAR_1} ya lleva\n{STR_VAR_2}.\p¿Quieres intercambiar\nlos objetos?");
const u8 gText_SwitchedPkmnItem[] = _("{STR_VAR_1} no lleva\nnada.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Has recibido {STR_VAR_2}\nde {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("Has retirado la CARTA\ndel POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Has retirado {STR_VAR_2} y lo\nhas cambiado por {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("Lleva un objeto. No\npuede llevar CARTA.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove4[] = _("Se ha sacado la CARTA del\nBUZÓN.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("La MOCHILA está llena. No se\npuede retirar el objeto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("¡{STR_VAR_1} ha aprendido\n{STR_VAR_2}!");
const u8 gText_StopLearningMove2[] = _("¡{STR_VAR_1} ha aprendido\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} y {STR_VAR_2}\nno son compatibles.\p{STR_VAR_2} no se puede\naprender.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("{STR_VAR_1} quiere aprender\n{STR_VAR_2}.\pPero {STR_VAR_1} ya conoce\ncuatro movimientos.\p¿Quieres que olvide uno y lo\nsustituya por {STR_VAR_2}?");
const u8 gText_12PoofForgotMove[] = _("¿Dejar de enseñarle\n{STR_VAR_2}?");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} no ha aprendido\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("¿Qué movimiento debe olvidar?{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("1, {PAUSE 15}2 y{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}¡puf!\p{STR_VAR_1} ha olvidado\n{STR_VAR_2}.\pY…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} ya conoce\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} ha recuperado\n{STR_VAR_2} PS.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1} ya no está\nenvenenado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1} ya no está\nparalizado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} se ha despertado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("{STR_VAR_1} ya no está quemado.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} ya no tiene congelamiento.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} ya no está congelado.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("PP restaurados.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} ha recuperado salud.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} está sano.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("Los PP de {STR_VAR_1} han subido.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1} ha subido al\nnivel {STR_VAR_2}.");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("¡{STR_VAR_1} ha ganado\n{STR_VAR_2} puntos de experiencia!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("¡{STR_VAR_1} gana {STR_VAR_2} p. exp.\ny sube al nivel {STR_VAR_3}!");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_2} base de\n{STR_VAR_1} ha subido.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} es más amistoso.\n¡Ha bajado {STR_VAR_2} base!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("¡{STR_VAR_1} te adora!\n¡Ha bajado {STR_VAR_2} base!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} es más amistoso.\n¡{STR_VAR_2} base no puede bajar!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("{STR_VAR_1} ya no está\nconfuso.{PAUSE_UNTIL_PRESS}");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1} ya no está\nenamorado.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("¡{STR_VAR_1} se ha transformado!{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_ChoosePokemon[] = _("¿Tirar\n{STR_VAR_1}?");
const u8 gText_MoveToWhere[] = _("Has tirado\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon[] = _("¿A qué POKéMON?");
const u8 gText_UseOnWhichPokemon[] = _("Elige un POKéMON.");
const u8 gText_GiveToWhichPokemon[] = _("¿Adónde?");
const u8 gText_DoWhatWithPokemon[] = _("¿A qué POKéMON?");
const u8 gText_NothingToCut[] = _("¿En qué POKéMON?");
const u8 gText_CantSurfHere[] = _("¿A qué POKéMON?");
const u8 gText_AlreadySurfing[] = _("¿Qué hacer con {PKMN}?");
const u8 gText_CantUseHere[] = _("Nada que CORTAR.");
const u8 gText_RestoreWhichMove[] = _("No puedes surfear.");
const u8 gText_BoostPp[] = _("Ya haces SURF.");
const u8 gText_DoWhatWithItem[] = _("No se puede usar.");
const u8 gText_NoPokemonForBattle[] = _("¿Qué movimiento?");
const u8 gText_ChoosePokemon2[] = _("¿Subir PP de cuál?");
const u8 gText_NotEnoughHp[] = _("¿Qué hacer con él?");
const u8 gText_PokemonAreNeeded[] = _("¡Sin POKéMON aptos!");
const u8 gText_PokemonCantBeSame[] = _("Elige un POKéMON.");
const u8 gText_NoIdenticalHoldItems[] = _("Faltan PS…");
const u8 gText_CurrentIsTooFast[] = _("Se necesitan {STR_VAR_1} POKéMON.");
const u8 gText_DoWhatWithMail[] = _("No pueden ser iguales.");
const u8 gText_ChoosePokemonCancel[] = _("Objetos repetidos.");
const u8 gText_ChoosePokemonConfirm[] = _("¡La corriente es muy fuerte!");
const u8 gText_SendWhichMonToPC[] = _("¿Qué hacer con CARTA?");
const u8 gText_MoveItemWhere[] = _("Elige POKéMON o SALIR.");
const u8 gText_XsYAnd[] = _("Elige POKéMON y acepta.");
const u8 gText_XsYWereSwapped[] = _("¿Qué POKéMON envías al PC?");
const u8 gText_EnjoyCycling[] = _("¿Adónde lo mueves?");
const u8 gText_InUseAlready_PM[] = _("¡{STR_VAR_2} de {STR_VAR_1} y\n");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_2} de {STR_VAR_1} cambiados!{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichAppliance[] = _("¡A pedalear!");
const u8 gText_NoUse[] = _("Ya se está usando.");
const u8 gText_Able[] = _("{STR_VAR_1} ya lleva\n{STR_VAR_2}.");
const u8 gText_First_PM[] = _("¿Qué\naparato?");
const u8 gText_Second_PM[] = _("No sirve.");
const u8 gText_Third_PM[] = _("PUEDE");
const u8 gText_Able2[] = _("1.º");
const u8 gText_NotAble[] = _("2.º");
const u8 gText_Able3[] = _("3.º");
const u8 gText_NotAble2[] = _("PUEDE");
const u8 gText_Learned[] = _("NO PUEDE");
const u8 gText_Have[] = _("¡PUEDE!");
const u8 gText_DontHave[] = _("¡NO PUEDE!");
const u8 gText_Fourth[] = _("APRENDIDO");
const u8 gText_PkmnCantParticipate[] = _("TIENE");
const u8 gText_CancelParticipation[] = _("NO TIENE");
const u8 gText_CancelBattle[] = _("4.º");
const u8 gText_ReturnToWaitingRoom[] = _("Ese POKéMON no puede participar.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelChallenge[] = _("¿Cancelar la entrada?");
const u8 gText_EscapeFromHere[] = _("¿Dejar el combate?");
const u8 gText_ReturnToHealingSpot[] = _("¿Volver a la SALA DE ESPERA?");
const u8 gText_PauseUntilPress[] = _("¿Cancelar desafío?");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("¿Quieres escapar de aquí y volver\na {STR_VAR_1}?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("¿Quieres volver al último lugar\nde descanso de {STR_VAR_1}?");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Ese POKéMON no se puede\nintercambiar ahora.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Es tu único\nPOKéMON apto.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Ese POKéMON no se puede\nintercambiar ahora.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("Ese POKéMON no se puede intercambiar.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("No se puede intercambiar un HUEVO.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("El POKéMON del otro ENTRENADOR\nno se puede intercambiar ahora.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("El otro ENTRENADOR no puede\naceptar ese POKéMON ahora.");
const u8 gText_Register[] = _("Ahora no puedes cambiar\ncon ese ENTRENADOR.");
const u8 gText_Attack3[] = _("Ese no es el tipo de POKéMON\nque quiere el otro ENTRENADOR.");
const u8 gText_Defense3[] = _("No es un HUEVO.");
const u8 gText_SpAtk4[] = _("REGISTRAR");
const u8 gText_SpDef4[] = _("ATAQUE");
const u8 gText_Speed2[] = _("DEFENSA");
const u8 gText_SpAtk5[] = _("AT. ESP.");   // ficha: columna de 36 px
const u8 gText_SpDef5[] = _("DEF. ESP.");
const u8 gText_Speed3[] = _("VELOCIDAD");
const u8 gText_HP4[] = _("PS");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("EO/");
const u8 gText_RentalPkmn[] = _("ALQUILADO");
const u8 gText_TypeSlash[] = _("TIPO/");
const u8 gText_Power[] = _("POTENCIA");
const u8 gText_Accuracy2[] = _("PRECISIÓN");
const u8 gText_Appeal[] = _("ENCANTO");
const u8 gText_Jam[] = _("ESTORBO");
const u8 gText_Status[] = _("ESTADO");
const u8 gText_ExpPoints[] = _("PUNTOS EXP.");
const u8 gText_NextLv[] = _("SIG. NV.");
const u8 gText_RibbonsVar1[] = _("CINTAS: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTOS"); // Unused
const u8 gText_Switch[] = _("CAMBIAR");
const u8 gText_PkmnInfo[] = _("INFO POKéMON");
const u8 gText_PkmnSkills[] = _("HABILIDADES");
const u8 gText_BattleMoves[] = _("MOVIMIENTOS");
const u8 gText_ContestMoves[] = _("MOV. CONCURSO");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Parece que este HUEVO\nva a tardar mucho.");
const u8 gText_EggWillTakeSomeTime[] = _("¿Qué saldrá de aquí?\nAún tardará un poco.");
const u8 gText_EggWillHatchSoon[] = _("A veces se mueve.\nSe abrirá pronto.");
const u8 gText_EggAboutToHatch[] = _("Hace ruidos.\n¡Ya va a abrirse!");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("Listo para abrirse, ¡pero lo\nimpide el reto Nuzlocke!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Los MO no se\npueden olvidar.");
const u8 gText_XNatureMetAtYZ[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nVisto a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nEclosionó a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nObtenido en un intercambio.");
const u8 gText_XNatureFatefulEncounter[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nObtenido en un encuentro\nfatídico a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nVisto quizá a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}\nen {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}");
const u8 gText_XNatureMetSomewhereAt[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nVisto en algún lugar\na {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("Naturaleza {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7}.\nEclosionó en algún lugar\na {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Un HUEVO curioso que\nhalló la GUARDERÍA.");
const u8 gText_PeculiarEggNicePlace[] = _("Un HUEVO POKéMON peculiar\nobtenido en un lugar bonito.");
const u8 gText_PeculiarEggTrade[] = _("HUEVO peculiar de\nun intercambio.");
const u8 gText_EggFromHotSprings[] = _("HUEVO obtenido en\naguas termales.");
const u8 gText_OddEggFromDaycare[] = _("Un HUEVO curioso\nde la guardería.");
const u8 gText_EggFromTraveler[] = _("Un HUEVO curioso\nde un viajero.");
const u8 gText_ApostropheSBase[] = _(": BASE");
const u8 gText_OkayToDeleteFromRegistry[] = _("¿Borrar {STR_VAR_1}\ndel REGISTRO?");
const u8 gText_RegisteredDataDeleted[] = _("Se han borrado los datos registrados.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("No hay REGISTRO.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("BORRAR REG.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DECORAR");
const u8 gText_PutAway[] = _("GUARDAR");
const u8 gText_Toss2[] = _("TIRAR");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Coloca el objeto de decoración elegido.");
const u8 gText_StoreChosenDecorInPC[] = _("Guarda la decoración elegida en el PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Tira las decoraciones que no quieras.");
const u8 gText_NoDecorations[] = _("No hay decoraciones.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("MESA");
const u8 gText_Chair[] = _("SILLA");
const u8 gText_Plant[] = _("PLANTA");
const u8 gText_Ornament[] = _("ADORNO");
const u8 gText_Mat[] = _("ALFOMBRA");
const u8 gText_Poster[] = _("PÓSTER");
const u8 gText_Doll[] = _("MUÑECO");
const u8 gText_Cushion[] = _("COJÍN");
const u8 gText_Gold[] = _("ORO");
const u8 gText_Silver[] = _("PLATA");
const u8 gText_PlaceItHere[] = _("¿Aquí?");
const u8 gText_CantBePlacedHere[] = _("Aquí no se puede poner.");
const u8 gText_CancelDecorating[] = _("¿Dejar de decorar?");
const u8 gText_InUseAlready[] = _("Ya se está usando.");
const u8 gText_NoMoreDecorations[] = _("No se pueden poner más decoraciones.\nEl máximo es {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("No se pueden poner más decoraciones.\nEl máximo es {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("No se puede colocar aquí.\nDebe ir sobre un ESCRITORIO, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Esta decoración no se puede poner\nen tu habitación.");
const u8 gText_CantThrowAwayInUse[] = _("Esta decoración está en\nuso. No se puede tirar.");
const u8 gText_DecorationWillBeDiscarded[] = _("Se tirará {STR_VAR_1}.\n¿Seguro?");
const u8 gText_DecorationThrownAway[] = _("Has tirado la decoración.");
const u8 gText_StopPuttingAwayDecorations[] = _("¿Dejar de guardar decoraciones?");
const u8 gText_NoDecorationHere[] = _("Aquí no hay ninguna decoración.");
const u8 gText_ReturnDecorationToPC[] = _("¿Devolver esta decoración al PC?");
const u8 gText_DecorationReturnedToPC[] = _("La decoración ha vuelto al PC.");
const u8 gText_NoDecorationsInUse[] = _("No hay decoraciones en uso.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("No hay objetos.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Aquí no hay CARTAS.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("¿Qué quieres hacer con\nla CARTA de {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("Se perderá el mensaje.\n¿Seguro?");
const u8 gText_BagIsFull[] = _("La MOCHILA está llena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("La CARTA ha vuelto a la MOCHILA\ny se ha borrado el mensaje.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("PAPÁ");
const u8 gText_Mom[] = _("MAMÁ");
const u8 gText_MomHowMuchDeposit[] = _("¿Cuánto quieres dejarle\na tu MAMÁ?");
const u8 gText_MomHowMuchWithdraw[] = _("¿Cuánto quieres sacarle\na tu MAMÁ?");
const u8 gText_MomMatchCallDesc[] = _("AMABLE");
const u8 gText_MomMatchCallName[] = _("MAMÁ");
const u8 gText_MomMenuCheckSavings[] = _("VER AHORROS");
const u8 gText_MomMenuDeposit[] = _("INGRESAR");
const u8 gText_MomMenuWithdraw[] = _("SACAR");
const u8 gText_MomMenuToggleSaving[] = _("AHORRAR");
const u8 gText_MomMenuExit[] = _("SALIR");
const u8 gText_Info2[] = _("INFO");
const u8 gText_CoolnessContest[] = _("CONCURSO CARISMA");
const u8 gText_BeautyContest[] = _("CONCURSO BELLEZA");
const u8 gText_CutenessContest[] = _("CONCURSO DULZURA");
const u8 gText_SmartnessContest[] = _("CONCURSO INGENIO");
const u8 gText_ToughnessContest[] = _("CONCURSO DUREZA");
const u8 gText_Decoration2[] = _("DECORAR");
const u8 gText_PackUp[] = _("RECOGER");
const u8 gText_Registry[] = _("REGISTRO");
const u8 gText_Information[] = _("INFORMACIÓN");
const u8 gText_Yes[] = _("SÍ");
const u8 gText_No[] = _("NO");
const u8 gText_Lv50[] = _("NV. 50");
const u8 gText_OpenLevel[] = _("NV. LIBRE");
const u8 gText_RedShard[] = _("PARTE ROJA");
const u8 gText_YellowShard[] = _("PAR. AMARILLA");
const u8 gText_BlueShard[] = _("PARTE AZUL");
const u8 gText_GreenShard[] = _("PARTE VERDE");
const u8 gText_BattleFrontier[] = _("FRENTE BATALLA");
const u8 gText_Cool[] = _("CARISMA");
const u8 gText_Beauty[] = _("BELLEZA");
const u8 gText_Cute[] = _("DULZURA");
const u8 gText_Smart[] = _("INGENIO");
const u8 gText_Tough[] = _("DUREZA");
const u8 gText_Normal[] = _("NORMAL");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("HIPER");
const u8 gText_Master[] = _("MASTER");
const u8 gText_Cool2[] = _("CARISMA");
const u8 gText_Beauty2[] = _("BELLEZA");
const u8 gText_Cute2[] = _("DULZURA");
const u8 gText_Smart2[] = _("INGENIO");
const u8 gText_Tough2[] = _("DUREZA");
const u8 gText_Items[] = _("OBJETOS");
const u8 gText_Key_Items[] = _("OBJ. CLAVE");
const u8 gText_Poke_Balls[] = _("POKé BALLS");
const u8 gText_TMs_Hms[] = _("MT y MO");
const u8 gText_Berries2[] = _("BAYAS");
const u8 gText_Medicine[] = _("MEDICINAS");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("OBJ. COMBATE");
const u8 gText_Treasures[] = _("TESOROS");
#endif
const u8 gText_SomeonesPC[] = _("PC DE ALGUIEN");
const u8 gText_LanettesPC[] = _("PC DE AREN");
const u8 gText_BillsPc[] = _("PC DE BILL");
const u8 gText_PlayersPC[] = _("PC DE {PLAYER}");
const u8 gText_HallOfFame[] = _("HALL DE LA FAMA");
const u8 gText_LogOff[] = _("SALIR");
const u8 gText_Challenges[] = _("DESAFÍOS");
const u8 gText_Opponent[] = _("RIVAL");
const u8 gText_Tourney_Tree[] = _("VER LA TABLA");
const u8 gText_ReadyToStart[] = _("EMPEZAR");
const u8 gText_Single2[] = _("INDIVIDUAL");
const u8 gText_Double2[] = _("DOBLE");
const u8 gText_Multi[] = _("MÚLTIPLE");
const u8 gText_MultiLink[] = _("MULTIJ. CONEXIÓN");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("MOCHILA");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("POKéGEAR");
#else
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("GUARDAR");
const u8 gText_MenuOptionOption[] = _("OPCIONES");
const u8 gText_MenuOptionExit[] = _("SALIR");
const u8 gText_SouthernIsland[] = _("ISLA DEL SUR");
const u8 gText_BirthIsland[] = _("ISLA ORIGEN");
const u8 gText_FarawayIsland[] = _("ISLA SUPREMA");
const u8 gText_NavelRock[] = _("ROCA OMBLIGO");
const u8 gText_NormalTagMatch[] = _("ASCENSO NORMAL");
const u8 gText_VarietyTagMatch[] = _("ASCENSO VARIADO");
const u8 gText_UniqueTagMatch[] = _("ASCENSO ÚNICO");
const u8 gText_ExpertTagMatch[] = _("ASCENSO DIFÍCIL");
const u8 gText_TradeCenter[] = _("CENTRO de CAMBIO");
const u8 gText_Colosseum[] = _("COLISEO");
const u8 gText_RecordCorner[] = _("CENTRO de RÉCORDS");
const u8 gText_BerryCrush3[] = _("MACHACABAYAS");
const u8 gText_BattleRules[] = _("LO BÁSICO");
const u8 gText_JudgeMind[] = _("JUEZ: MENTE");
const u8 gText_JudgeSkill[] = _("HABILIDAD");
const u8 gText_JudgeBody[] = _("CUERPO");
const u8 gText_BasicRules[] = _("LO BÁSICO");
const u8 gText_SwapPartners[] = _("QUIÉN TRUECA");
const u8 gText_SwapNumber[] = _("QUÉ SE TRUECA");
const u8 gText_SwapNotes[] = _("EL TRUEQUE");
const u8 gText_BattleBasics[] = _("LO BÁSICO");
const u8 gText_PokemonNature[] = _("NATURALEZA");
const u8 gText_PokemonMoves[] = _("MOVIMIENTOS");
const u8 gText_Underpowered[] = _("SIN FUERZA");
const u8 gText_WhenInDanger[] = _("EN PELIGRO");
const u8 gText_BattlePokemon[] = _("POKéMON");
const u8 gText_BattleTrainers[] = _("ENTRENADORES");
const u8 gText_GoOn[] = _("SEGUIR");
const u8 gText_Record2[] = _("ANOTAR");
const u8 gText_Rest[] = _("DESCANSO");
const u8 gText_Retire[] = _("RETIRARSE");
const u8 gText_1F[] = _("P1");
const u8 gText_2F[] = _("P2");
const u8 gText_3F[] = _("P3");
const u8 gText_4F[] = _("P4");
const u8 gText_5F[] = _("P5");
const u8 gText_6F[] = _("P6");
const u8 gText_7F[] = _("P7");
const u8 gText_8F[] = _("P8");
const u8 gText_9F[] = _("P9");
const u8 gText_10F[] = _("P10");
const u8 gText_11F[] = _("P11");
const u8 gText_B1F[] = _("S1");
const u8 gText_B2F[] = _("S2");
const u8 gText_B3F[] = _("S3");
const u8 gText_B4F[] = _("S4");
const u8 gText_Rooftop[] = _("AZOTEA");
const u8 gText_ElevatorNowOn[] = _("Planta:");
const u8 gText_BP[] = _("PB");
const u8 gText_RankingHall[] = _("HALL CLASIFICAC.");
const u8 gText_ExchangeService[] = _("SERVICIO DE CANJE");
const u8 gText_LilycoveCity[] = _("CIUDAD CALAGUA");
const u8 gText_SlateportCity[] = _("CIUDAD PORTUAL");
const u8 gText_Exit[] = _("SALIR");
const u8 gText_YourPartysFull[] = _("¡Tu equipo está completo!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("EN EQUIPO");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combina cuatro palabras o frases");
const u8 gText_AndMakeYourProfile[] = _("y crea tu perfil.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combina seis palabras o frases");
const u8 gText_AndMakeAMessage[] = _("y crea un mensaje.");
const u8 gText_FindWordsThatDescribeYour[] = _("Busca palabras que describan");
const u8 gText_FeelingsRightNow[] = _("sentimientos en este momento.");
const u8 gText_WithFourPhrases[] = _("Con cuatro frases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combina nueve palabras o frases");
const u8 gText_AndMakeAMessage2[] = _("y crea un mensaje.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Cambia una sola palabra o frase");
const u8 gText_AndImproveTheBardsSong[] = _("y mejora la canción del BARDO.");
const u8 gText_YourProfile[] = _("Tu perfil");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Cómo te sientes al empezar");
const u8 gText_WhatYouSayIfYouWin[] = _("Lo que dices si ganas");
const u8 gText_WhatYouSayIfYouLose[] = _("Lo que dices si pierdes");
const u8 gText_TheAnswer[] = _("La respuesta");
const u8 gText_TheMailMessage[] = _("El mensaje de la CARTA");
const u8 gText_TheMailSalutation[] = _("El saludo del CORREO"); // Unused
const u8 gText_TheBardsSong2[] = _("La nueva canción");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combina dos palabras o frases");
const u8 gText_AndMakeATrendySaying[] = _("y crea una frase de moda.");
const u8 gText_TheTrendySaying[] = _("La frase de moda");
const u8 gText_IsAsShownOkay[] = _("es esto, ¿no?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combina dos palabras o frases");
const u8 gText_ToTeachHerAGoodSaying[] = _("para enseñarle una buena frase.");
const u8 gText_FindWordsWhichFit[] = _("Elige palabras que encajen");
const u8 gText_TheTrainersImage[] = _("con su imagen.");
const u8 gText_TheImage[] = _("La imagen:");
const u8 gText_OutOfTheListedChoices[] = _("De entre las opciones,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("¡elige la respuesta del test!");
const u8 gText_AndCreateAQuiz[] = _("¡y crea un test!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Elige un elemento y");
const u8 gText_SetTheQuizAnswer[] = _("escribe la respuesta.");
const u8 gText_TheAnswerColon[] = _("La respuesta");
const u8 gText_TheQuizColon[] = _("El cuestionario:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Frase del aprendiz:");
const u8 gText_QuitEditing[] = _("¿Dejas de escribir?");
const u8 gText_StopGivingPkmnMail[] = _("¿Dejar de darle CARTA?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("y rellena el cuestionario.");
const u8 gText_LetsReplyToTheInterview[] = _("¡Responde a la entrevista!");
const u8 gText_AllTextBeingEditedWill[] = _("Se borrará todo el texto");
const u8 gText_BeDeletedThatOkay[] = _("escrito. ¿Estás de acuerdo?");
const u8 gText_QuitEditing2[] = _("¿Dejas de escribir?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("El texto editado no se guardará."); // Unused
const u8 gText_IsThatOkay[] = _("¿Te parece bien?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Introduce una frase o palabra."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("No se puede borrar todo el texto.");
const u8 gText_OnlyOnePhrase[] = _("Solo se puede cambiar una frase.");
const u8 gText_OriginalSongWillBeUsed[] = _("Se usará la canción original.");
const u8 gText_ThatsTrendyAlready[] = _("¡Eso ya está de moda!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combina dos palabras o frases.");
const u8 gText_QuitGivingInfo[] = _("¿Dejar de dar información?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("¿Dejar de darle CARTA?"); // Unused
const u8 gText_CreateAQuiz2[] = _("¡Crea un test!"); // Unused
const u8 gText_SetTheAnswer[] = _("¡Establece la respuesta!"); // Unused
const u8 gText_CancelSelection[] = _("¿Cancelar la selección?"); // Unused
const u8 gText_Profile[] = _("PERFIL");
const u8 gText_AtTheBattlesStart[] = _("Al empezar a luchar");
const u8 gText_UponWinningABattle[] = _("Al ganar un combate:");
const u8 gText_UponLosingABattle[] = _("Al perder un combate");
const u8 gText_TheBardsSong[] = _("La canción del BARDO");
const u8 gText_WhatsHipAndHappening[] = _("¿Qué está de moda?");
const u8 gText_Interview[] = _("Entrevista");
const u8 gText_GoodSaying[] = _("Buena frase");
const u8 gText_FansQuestion[] = _("Pregunta de un admirador");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Frase del aprendiz");
const u8 gText_Questionnaire[] = _("CUESTIONARIO");
const u8 gText_YouCannotQuitHere[] = _("Aquí no puedes salir.");
const u8 gText_SectionMustBeCompleted[] = _("Hay que completar esta parte.");
const u8 gText_F700sQuiz[] = _("Test de {DYNAMIC 0}");
const u8 gText_Lady[] = _("Señora");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Cuando hayas leído la pregunta");
const u8 gText_QuestionPressTheAButton[] = _("del test, pulsa el Botón A.");
const u8 gText_TheQuizAnswerIs[] = _("¿Y la respuesta es?");
const u8 gText_LikeToQuitQuiz[] = _("¿Quieres abandonar este");
const u8 gText_ChallengeQuestionMark[] = _("desafío?");
const u8 gText_IsThisQuizOK[] = _("¿Está bien así?");
const u8 gText_CreateAQuiz[] = _("¡Crea un test!");
const u8 gText_SelectTheAnswer[] = _("¡Selecciona la respuesta!");
const u8 gText_LyricsCantBeDeleted[] = _("La letra no se puede borrar.");
const u8 gText_PokemonLeague[] = _("LIGA POKéMON");
const u8 gText_PokemonCenter[] = _("CENTRO POKéMON");
const u8 gText_Coolness[] = _("Carisma ");
const u8 gText_Beauty3[] = _("Belleza ");
const u8 gText_Cuteness[] = _("Dulzura ");
const u8 gText_Smartness[] = _("Ingenio ");
const u8 gText_Toughness[] = _("Dureza ");
const u8 gText_SaveFailedCheckingBackup[] = _("Error al guardar. Comprobando la\nmemoria de seguridad… Espera.\n{COLOR RED}“Tiempo necesario: 1 minuto”");
const u8 gText_BackupMemoryDamaged[] = _("La memoria de seguridad está dañada\no la pila interna se ha agotado.\nPuedes jugar, pero no guardar.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“No se puede continuar la partida.\nVolviendo a la pantalla de título…”");
const u8 gText_CheckCompleted[] = _("Comprobación terminada.\nIntentando volver a guardar.\nEspera unos instantes.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Partida guardada.\n{COLOR RED}“No se puede continuar la partida.\nVolviendo a la pantalla de título.”");
const u8 gText_SaveCompletePressA[] = _("Partida guardada.\n{COLOR RED}“Pulsa el Botón A.”");
const u8 gText_Ferry[] = _("FERRY");
const u8 gText_SecretBase[] = _("BASE SECRETA");
const u8 gText_Hideout[] = _("GUARIDA");
const u8 gText_ResetRTCConfirmCancel[] = _("¿Quieres ajustar la hora?\nA: sí, B: no");
const u8 gText_PresentTime[] = _("Hora actual en el juego");
const u8 gText_PreviousTime[] = _("Hora anterior en el juego");
const u8 gText_PleaseResetTime[] = _("Ajusta la hora.");
const u8 gText_ClockHasBeenReset[] = _("Se ha reiniciado el reloj.\nSe guardarán los datos. Espera.");
const u8 gText_SaveCompleted[] = _("Partida guardada.");
const u8 gText_SaveFailed[] = _("Error al guardar…");
const u8 gText_NoSaveFileCantSetTime[] = _("No hay partida guardada, así que\nno se puede ajustar la hora.");
const u8 gText_InGameClockUsable[] = _("Ya se puede usar el sistema\nde ajuste del reloj del juego.");
const u8 gText_Spicy2[] = _("picante");
const u8 gText_Dry2[] = _("seco");
const u8 gText_Sweet2[] = _("dulce");
const u8 gText_Bitter2[] = _("amargo");
const u8 gText_Sour2[] = _("ácido");
const u8 gText_Single[] = _("INDIVIDUAL");
const u8 gText_Double[] = _("DOBLE");
const u8 gText_Knockout[] = _("K.O.");
const u8 gText_Mixed[] = _("MIXTO");
const u8 gText_First[] = _("primero");
const u8 gText_Second[] = _("segundo");
const u8 gText_Third[] = _("tercero");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} se ha debilitado…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} ha sobrevivido al veneno.\n¡El veneno ha desaparecido!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1} ha sobrevivido al veneno.\n¡El veneno ha desaparecido!\p");
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NOMBRE: ");
const u8 gText_TrainerCardIDNo[] = _("N.º ID");
const u8 gText_TrainerCardMoney[] = _("DINERO");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" puntos"); // Unused
const u8 gText_TrainerCardTime[] = _("TIEMPO");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("FICHA DE ENTRENADOR DE {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("PRIMER HALL de la FAMA  ");
const u8 gText_LinkBattles[] = _("COMBATES M. CONEXIÓN");
const u8 gText_LinkCableBattles[] = _("COMBATES POR CABLE");
const u8 gText_WinsLosses[] = _("G:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  P:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("INTERCAMBIOS");
const u8 gText_UnionTradesAndBattles[] = _("INTERCAMB. Y COMB. UNIÓN");
const u8 gText_BerryCrush[] = _("MACHACABAYAS");
const u8 gText_WaitingTrainerFinishReading[] = _("Esperando a que el otro ENTRENADOR\ntermine de leer tu FICHA.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S HECHOS CON AMIGOS");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("CONCURSOS GANADOS CON AMIGOS");
const u8 gText_BattlePtsWon[] = _("PB GANADOS");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PB");
const u8 gText_BattleTower[] = _("TORRE BATALLA");
const u8 gText_WinsStraight[] = _("G/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  SEGUIDAS/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("TORRE BATALLA");
const u8 gText_BattleDome[] = _("CÚPULA BATALLA");
const u8 gText_BattlePalace[] = _("PALACIO BATALLA");
const u8 gText_BattleFactory[] = _("FÁBRICA BATALLA");
const u8 gText_BattleArena[] = _("DOJO BATALLA");
const u8 gText_BattlePike[] = _("SIERPE BATALLA");
const u8 gText_BattlePyramid[] = _("PIRÁMIDE BATALLA");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} INDIVIDUAL");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOBLE");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MÚLTIPLE");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} MULTIJ. CONEX.");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Dar");
const u8 gText_NoNeed[] = _("Nada");
const u8 gText_AnnouncingResults[] = _("¡Éstos son los resultados!");
const u8 gText_PreliminaryResults[] = _("¡Resultados de la 1.ª votación!");
const u8 gText_Round2Results[] = _("¡Resultados de la 2.ª votación!");
const u8 gText_ContestantsMonWon[] = _("¡Ha ganado {STR_VAR_2} de {STR_VAR_1}!");
const u8 gText_CommunicationStandby[] = _("Esperando conexión…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("MAYÚS.");
const u8 gText_Lower[] = _("minús");
const u8 gText_Others[] = _("OTRO");
const u8 gText_Symbols[] = _("símbolos");
const u8 gText_Register2[] = _("REGISTRAR");
const u8 gText_Exit2[] = _("SALIR");
const u8 gText_QuitChatting[] = _("¿Dejar el chat?");
const u8 gText_RegisterTextWhere[] = _("¿Dónde registras el texto?");
const u8 gText_RegisterTextHere[] = _("¿Lo registras aquí?");
const u8 gText_InputText[] = _("Escribir");
const u8 gText_F700JoinedChat[] = _("¡{DYNAMIC 0} se une al grupo!");
const u8 gText_F700LeftChat[] = _("¡{DYNAMIC 0} se ha desconectado!");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Saliendo del grupo…");
const u8 gText_LeaderLeftEndingChat[] = _("{DYNAMIC 0} se ha salido\ndel chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Se ha cambiado el texto registrado.\n¿Quieres guardar la partida?");
const u8 gText_AlreadySavedFile_Chat[] = _("Ya hay una partida guardada.\n¿Quieres sobrescribirla?");
const u8 gText_SavingDontTurnOff_Chat[] = _("GUARDANDO…\nNO APAGUES LA CONSOLA.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} guardó la partida.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Si el LÍDER se desconecta,\nse acabará el chat, ¿de acuerdo?");
const u8 gText_Hello[] = _("¡HOLA!");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("INTERCAMBIAR");
const u8 gText_Battle[] = _("COMBATE");
const u8 gText_Lets[] = _("¡VAMOS!");
const u8 gText_Ok[] = _("¡VALE!");
const u8 gText_Sorry[] = _("LO SIENTO");
const u8 gText_YaySmileEmoji[] = _("¡BIEN!{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("¡GRACIAS!");
const u8 gText_ByeBye[] = _("¡ADIÓS!");
const u8 gText_HatchedFromEgg[] = _("¡{STR_VAR_1} ha salido del HUEVO!");
const u8 gText_NicknameHatchPrompt[] = _("¿Quieres ponerle un mote al\n{STR_VAR_1} recién nacido?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("¿Listo para el MACHACABAYAS?\nElige una BAYA, por favor.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Espera a que todos los\nmiembros elijan una BAYA.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Has conseguido {STR_VAR_1}\ngramos de sedoso POLVO de BAYA.{RESUME_MUSIC}\pEn total, tienes {STR_VAR_2} gramos de\nPOLVO de BAYA.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Se están guardando los datos\nde tu partida.\lEspera un instante.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("¿Usas de nuevo el MACHACABAYAS?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("¡Pero si no tienes BAYAS!\nEntonces no puedes usarlo.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Alguien se ha desconectado.\nSe perderá la conexión.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("¡Tiempo!\pNo se ha podido hacer POLVO\nde BAYAS en condiciones…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Esperando conexión…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" vez/veces");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("BAYA {STR_VAR_1}");
ALIGNED(4) const u8 gText_TimeColon[] = _("Tiempo:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Vel. de presión:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Suavidad:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" segundos");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("veces/s");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("N.º usos");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Pulverización");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Pureza");
ALIGNED(4) const u8 gText_CoopRankings[] = _("En conjunto");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Potencia");
const u8 gText_BerryCrush2[] = _("MACHACABAYAS");
const u8 gText_PressingSpeedRankings[] = _("Vel. de presión:");
const u8 gText_Var1Players[] = _("{STR_VAR_1} JUGAD.");
const u8 gText_SymbolsEarned[] = _("Símbolos ganados");
const u8 gText_BattleRecord[] = _("Combate grabado");
const u8 gText_BattlePoints[] = _("Puntos de batalla");
const u8 gText_UnusedCancel[] = _("SALIR"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Ver el mapa del FRENTE de BATALLA.");
const u8 gText_CheckTrainerCard[] = _("Ver la FICHA de ENTRENADOR.");
const u8 gText_ViewRecordedBattle[] = _("Ver el combate grabado.");
const u8 gText_PutAwayFrontierPass[] = _("Guardar el PASE del FRENTE.");
const u8 gText_CurrentBattlePoints[] = _("Son los puntos de batalla que has ganado.");
const u8 gText_CollectedSymbols[] = _("Son los símbolos que has ganado.");
const u8 gText_BattleTowerAbilitySymbol[] = _("SÍMBOLO de la DESTREZA de TORRE BATALLA.");
const u8 gText_BattleDomeTacticsSymbol[] = _("SÍMBOLO de la TÁCTICA de CÚPULA BATALLA.");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("SÍMBOLO del ÁNIMO de PALACIO BATALLA.");
const u8 gText_BattleArenaGutsSymbol[] = _("SÍMBOLO del CORAJE de DOJO BATALLA.");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("SÍMBOLO del SABER de FÁBRICA BATALLA.");
const u8 gText_BattlePikeLuckSymbol[] = _("SÍMBOLO de la FORTUNA de SIERPE BATALLA.");
const u8 gText_BattlePyramidBraveSymbol[] = _("SÍMBOLO de la VALENTÍA de PIRÁMIDE BATALLA.");
const u8 gText_ThereIsNoBattleRecord[] = _("Sin combates grabados.");
const u8 gText_BattleTower3[] = _("TORRE BATALLA");
const u8 gText_BattleDome2[] = _("CÚPULA BATALLA");
const u8 gText_BattlePalace2[] = _("PALACIO BATALLA");
const u8 gText_BattleArena2[] = _("DOJO BATALLA");
const u8 gText_BattleFactory2[] = _("FÁBRICA BATALLA");
const u8 gText_BattlePike2[] = _("SIERPE BATALLA");
const u8 gText_BattlePyramid2[] = _("PIRÁMIDE BATALLA");
const u8 gText_BattleTowerDesc[] = _("¡Vence a tus rivales y llega hasta\nel final! ¡Pon a prueba tu destreza!");
const u8 gText_BattleDomeDesc[] = _("¡Ve superando los encuentros hasta\nla final! ¡Pon a prueba tu táctica!");
const u8 gText_BattlePalaceDesc[] = _("¡Mira cómo luchan tus POKéMON!\n¡Pon a prueba tu ánimo!");
const u8 gText_BattleArenaDesc[] = _("¡Elige bien a tus POKéMON para ganar!\n¡Pon a prueba tu coraje!");
const u8 gText_BattleFactoryDesc[] = _("¡Vence tomando prestados POKéMON!\n¡Pon a prueba tu saber!");
const u8 gText_BattlePikeDesc[] = _("¡Elige uno de los tres caminos para\ncombatir! ¡Pon a prueba tu fortuna!");
const u8 gText_BattlePyramidDesc[] = _("¡Explora y llega hasta la cima!\n¡Pon a prueba tu valentía!");
const u8 gText_Powder[] = _("POLVO");
const u8 gText_BerryPickingRecords[] = _("RÉCORDS DODRIO A POR BAYAS");
const u8 gText_BerriesPicked[] = _("BAYAS conseguidas:");
const u8 gText_BestScore[] = _("Puntuación máx.:");
const u8 gText_BerriesInRowFivePlayers[] = _("BAYAS conseguidas de una vez\npor 5 jugadores:");
const u8 gText_BerryPickingResults[] = _("¡Resultados de A POR BAYAS!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("¡Ésta es la clasificación!");
const u8 gText_AnnouncingPrizes[] = _("¡Éstos son los premios!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("¡El ganador del primer puesto\nse lleva {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("¡No puedes llevar más!");
const u8 gText_FilledStorageSpace[] = _("No te queda sitio.");
const u8 gText_WantToPlayAgain[] = _("¿Quieres jugar otra vez?");
const u8 gText_SomeoneDroppedOut[] = _("Alguien se ha desconectado.\nSe perderá la conexión.");
const u8 gText_SpacePoints[] = _(" puntos");
const u8 gText_CommunicationStandby3[] = _("Esperando conexión…");
const u8 gText_SpacePoints2[] = _(" puntos");
const u8 gText_SpaceTimes3[] = _(" vez/veces");
const u8 gText_PkmnJumpRecords[] = _("RÉCORDS SALTO POKéMON");
const u8 gText_JumpsInARow[] = _("Saltos seg.:");
const u8 gText_BestScore2[] = _("Puntuación máx.:");
const u8 gText_ExcellentsInARow[] = _("EXCELENTES seg.:");
const u8 gText_AwesomeWonF701F700[] = _("¡Genial! ¡Has\nganado {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("No te queda sitio.");
const u8 gText_CantHoldMore[] = _("¡No puedes llevar más!");
const u8 gText_WantToPlayAgain2[] = _("¿Quieres jugar otra vez?");
const u8 gText_SomeoneDroppedOut2[] = _("Alguien se ha desconectado.\nSe perderá la conexión.");
const u8 gText_CommunicationStandby4[] = _("Esperando conexión…");
const u8 gText_LinkContestResults[] = _("Concursos en conexión de {PLAYER}");
const u8 gText_1st[] = _("1.º");
const u8 gText_2nd[] = _("2.º");
const u8 gText_3rd[] = _("3.º");
const u8 gText_4th[] = _("4.º");
const u8 gText_Friend[] = _("Amigo");
const u8 gText_Pokemon3[] = _("POKéMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("Elige “Comunicación” del\nCARD E-READER{PLUS} y pulsa A."); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("No se puede comunicar con el\nCARD E-READER{PLUS}."); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}, sala batalla individual:");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}, sala batalla doble:");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}, sala batalla múltiple:");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}, sala batalla multij. con conexión:");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}, torneo de combates individuales:");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}, torneo de combates dobles:");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}, combate sin tutela individual:");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}, combate sin tutela doble:");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}, elección de combates:");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}, torneo con juez:");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}, combate con trueque individual:");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}, combate con trueque doble:");
const u8 gText_BattleQuestResults[] = _("{PLAYER}, expedición de combates:");
const u8 gText_Lv502[] = _("NV. 50");
const u8 gText_OpenLv[] = _("NV. LIBRE");
const u8 gText_WinStreak[] = _("Vic. seg.: {STR_VAR_1}");
const u8 gText_Current[] = _("ACTUAL");
const u8 gText_Record[] = _("ANOTAR");
const u8 gText_Prev[] = _("PREVIO");
const u8 gText_RentalSwap[] = _("Prést./trueq.");
const u8 gText_Total[] = _("Total");
const u8 gText_ClearStreak[] = _("Triunfos seg.: {STR_VAR_1}");
const u8 gText_Championships[] = _("Victorias: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Salas: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Superado:{CLEAR 0x05}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("K.O. seguidos: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Veces: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Niveles: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("NV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("NV. LIBRE");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Vic. seg.: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Triunfos seg.: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Salas: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("K.O. seguidos: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Niveles: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" y {STR_VAR_2} de las especies que\nhas capturado no pueden participar");
const u8 gText_FrontierFacilityIncluding[] = _(".\pEntre ellas están ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" no pueden participar");

const u8 gText_YesNo[] = _("SÍ\nNO");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("¡CUCÚ!");
const u8 gText_CommErrorCheckConnections[] = _("Error de conexión…\nRevisa todas las conexiones, apaga\nla consola y vuelve a encenderla.");
const u8 gText_CommErrorEllipsis[] = _("Error de conexión…");
const u8 gText_MoveCloserToLinkPartner[] = _("Procura que no haya distancia\nni obstáculos entre las consolas.");
const u8 gText_ABtnRegistrationCounter[] = _("Botón A: mostrador de inscripción");
const u8 gText_ABtnTitleScreen[] = _("Botón A: pantalla del título");
const u8 gText_NumPlayerLink[] = _("CONEXIÓN {STR_VAR_1}J");
const u8 gText_BronzeCard[] = _("BRONCE");
const u8 gText_CopperCard[] = _("COBRE");
const u8 gText_SilverCard[] = _("PLATA");
const u8 gText_GoldCard[] = _("ORO");
const u8 gText_Day[] = _("DÍA");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("ACEPTAR");
const u8 gText_Days[] = _("Días"); // Unused
const u8 gText_TimeColon2[] = _("Tiempo:"); // Unused
const u8 gText_GameTime[] = _("Hora del juego"); // Unused
const u8 gText_RTCTime[] = _("Hora RTC"); // Unused
const u8 gText_UpdatedTime[] = _("Hora actualizada"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("MOCHILA");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}GEAR");
#else
const u8 gText_MenuPokenav[] = _("POKéNAV");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("GUARDAR");
const u8 gText_MenuOption[] = _("OPCIONES");
const u8 gText_MenuExit[] = _("SALIR");
const u8 gText_MenuRetire[] = _("RETIRARSE");
const u8 gText_MenuRest[] = _("DESCANSO");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARI BALLS\nTienes {STR_VAR_1}.");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALLS  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("PIRÁMIDE\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Nivel 1");
const u8 gText_Floor2[] = _("Nivel 2");
const u8 gText_Floor3[] = _("Nivel 3");
const u8 gText_Floor4[] = _("Nivel 4");
const u8 gText_Floor5[] = _("Nivel 5");
const u8 gText_Floor6[] = _("Nivel 6");
const u8 gText_Floor7[] = _("Nivel 7");
const u8 gText_Peak[] = _("Cima");
const u8 gText_LinkStandby2[] = _("Esperando conexión…\n(…) Botón B: cancelar");
const u8 gText_PressAToLoadEvent[] = _("Pulsar Botón A para cargar evento.\n(…) Botón B: cancelar");
const u8 gText_LoadingEvent[] = _("Cargando evento…");
const u8 gText_DontRemoveCableTurnOff[] = _("No retires el cable Game Link.\nNo apagues la consola.");
const u8 gText_EventSafelyLoaded[] = _("El evento se ha cargado.");
const u8 gText_LoadErrorEndingSession[] = _("Error al cargar.\nFinalizando la sesión…");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NACIONAL");
const u8 gText_PokedexDiploma[] = _("Jugador: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nPOKéDEX {STR_VAR_1}\nEste documento certifica\nque has completado con\néxito tu POKéDEX.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_Johto[] = _("JOHTO");
const u8 gText_JohtoKanto[] = _("JOHTO Y KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} irá\na {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("¡Adiós, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} envió a {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("¡Cuida bien de {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("PS MÁX.");
const u8 gText_Attack[] = _("ATAQUE");
const u8 gText_Defense[] = _("DEFENSA");
const u8 gText_Speed[] = _("VELOCIDAD");
const u8 gText_SpAtk[] = _("AT. ESP.");
const u8 gText_SpDef[] = _("DEF. ESP.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Mezclando récords…");
const u8 gText_RecordMixingComplete[] = _("Mezcla de récords realizada.\nGracias por esperar.");
const u8 gText_RentalPkmn2[] = _("ALQUILADO");
const u8 gText_SelectFirstPkmn[] = _("Elige el primer POKéMON.");
const u8 gText_SelectSecondPkmn[] = _("Elige el segundo POKéMON.");
const u8 gText_SelectThirdPkmn[] = _("Elige el tercer POKéMON.");
const u8 gText_Rent[] = _("PRÉSTAMO");
const u8 gText_Summary[] = _("DATOS");
const u8 gText_Others2[] = _("OTRO");
const u8 gText_Deselect[] = _("DEJAR");
const u8 gText_TheseThreePkmnOkay[] = _("¿Eliges estos tres POKéMON?");
const u8 gText_Yes2[] = _("SÍ");
const u8 gText_No2[] = _("NO");
const u8 gText_CantSelectSamePkmn[] = _("No puedes repetir {PKMN}.");
const u8 gText_PkmnSwap[] = _("TRUEQUE");
const u8 gText_SelectPkmnToSwap[] = _("Elige el POKéMON que cambias.");
const u8 gText_SelectPkmnToAccept[] = _("Elige el POKéMON que quieres.");
const u8 gText_Swap[] = _("TRUEQUE");
const u8 gText_Summary2[] = _("DATOS");
const u8 gText_Rechoose[] = _("OTRO");
const u8 gText_QuitSwapping[] = _("¿Cancelas el trueque?");
const u8 gText_Yes3[] = _("SÍ");
const u8 gText_No3[] = _("NO");
const u8 gText_PkmnForSwap[] = _("{PKMN} DE TRUEQUE");
const u8 gText_Cancel3[] = _("SALIR");
const u8 gText_Swap2[] = _("TRUEQUE"); // Unused
const u8 gText_Accept[] = _("ACEPTAR"); // Unused
const u8 gText_AcceptThisPkmn[] = _("¿Aceptar POKéMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Tu equipo ya tiene ese {PKMN}.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("JUGADOR");
const u8 gText_SavingBadges[] = _("MEDALLAS");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("TIEMPO");
const u8 gText_WirelessCommStatus[] = _("Estado comunicación inalámbrica");
const u8 gText_PeopleTrading[] = _("Realizando intercambio:");
const u8 gText_PeopleBattling[] = _("Luchando:");
const u8 gText_PeopleInUnionRoom[] = _("En la SALA UNIÓN:");
const u8 gText_PeopleCommunicating[] = _("Conectados:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} JUGAD.");
const u8 gText_F701Players[] = _("{DYNAMIC 1} JUGAD.");
const u8 gText_F702Players[] = _("{DYNAMIC 2} JUGAD.");
const u8 gText_F703Players[] = _("{DYNAMIC 3} JUGAD.");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("TARJETAS MIST.");
ALIGNED(4) const u8 gText_WonderNews[] = _("NOTICIAS MIST.");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("COMUNICACIÓN INALÁMBRICA");
ALIGNED(4) const u8 gText_Friend2[] = _("AMIGO");
ALIGNED(4) const u8 gText_Exit3[] = _("SALIR");
ALIGNED(4) const u8 gText_Receive[] = _("RECIBIR");
ALIGNED(4) const u8 gText_Send[] = _("ENVIAR");
ALIGNED(4) const u8 gText_Toss[] = _("TIRAR");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Hay una serie de eventos disponibles\na través de comunicación inalámbrica.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Leer las TARJETAS MISTERIOSAS\nque tienes.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Leer las NOTICIAS que han llegado.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Volver a la pantalla del título.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Como no tienes TARJETA MISTERIOSA,\nse usará otra TARJETA.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Como no tienes NOTICIAS MISTERIOSAS,\nse usarán otras NOTICIAS.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("¿De dónde quieres tomar la TARJETA\nMISTERIOSA?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("¿De dónde quieres tomar las NOTICIAS\nMISTERIOSAS?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Comunicación en espera…\nBotón B: Cancelar"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Transmitiendo…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Conexión completada.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Error de transmisión…");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Se ha cancelado la conexión.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("¿Tiras la TARJETA MISTERIOSA\ny usas otra TARJETA?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Aún no has recibido el REGALO de la\nTARJETA. ¿Usas otra de todas formas?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("{STR_VAR_1} ha enviado una TARJETA\nMISTERIOSA.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("{STR_VAR_1} ha enviado NOTICIAS\nMISTERIOSAS.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Acaba de recibirse una TARJETA\nMISTERIOSA.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Acaban de recibirse NOTICIAS\nMISTERIOSAS.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Acaba de recibirse un SELLO.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("Acaba de unirse otro ENTRENADOR.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Ya tenías esa\nTARJETA MISTERIOSA.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Ya tenías esas\nNOTICIAS MISTERIOSAS.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Ya tenías ese\nSELLO.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("No queda sitio para\nmás SELLOS.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Se han cargado tus datos por\nCOMUNICACIÓN INALÁMBRICA.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("No puedes aceptar una TARJETA\nMISTERIOSA de este ENTRENADOR.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("No puedes aceptar NOTICIAS\nMISTERIOSAS de este ENTRENADOR.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("No se ha enviado nada…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("¿Qué quieres hacer con las\nTARJETAS MISTERIOSAS?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("¿Qué quieres hacer con las\nNOTICIAS MISTERIOSAS?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Enviando tu TARJETA MISTERIOSA…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Enviando tus NOTICIAS MISTERIOSAS…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Se ha enviado tu TARJETA\nMISTERIOSA a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Se han enviado tus NOTICIAS\nMISTERIOSAS a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("Se ha enviado un SELLO a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("Se ha enviado un REGALO a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("El otro ENTRENADOR ya tiene esa\nTARJETA MISTERIOSA.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("El otro ENTRENADOR ya tiene esas\nNOTICIAS MISTERIOSAS.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("El otro ENTRENADOR ya tiene ese\nSELLO.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("El otro ENTRENADOR ha cancelado\nla conexión.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("No puedes enviarle un REGALO\nMISTERIOSO a este ENTRENADOR.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Si tiras la TARJETA,\nno habrá evento. ¿Vale?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("¿Seguro que no quieres estas\nNOTICIAS?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("No has recibido el REGALO.\n¿Seguro que no lo quieres?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("GUARDANDO…\nEspera un instante.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Partida guardada.\nPulsa el Botón A.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("Se ha tirado la TARJETA MISTERIOSA.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("Has tirado las NOTICIAS MISTERIOSAS.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("REGALO MIST.");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}SEL. {A_BUTTON}VALE {B_BUTTON}SALIR");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}SEL. {A_BUTTON}VALE {B_BUTTON}SALIR");
const u8 gText_PlayersBattleResults[] = _("RESULTADOS COMBATES de {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("RÉCORDS V/{STR_VAR_1} D/{STR_VAR_2} E/{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}GAN.{CLEAR_TO 0x80}PERD.{CLEAR_TO 0xB0}EMP.");
const u8 gText_CommunicationStandby5[] = _("Esperando conexión…");
const u8 gDaycareText_GetAlongVeryWell[] = _("Diría que se llevan\nestupendamente.");
const u8 gDaycareText_GetAlong[] = _("Parece que se llevan bien.");
const u8 gDaycareText_DontLikeOther[] = _("Diría que no se quieren\ncon locura.");
const u8 gDaycareText_PlayOther[] = _("Pero más que juntos, prefieren\njugar con otros POKéMON.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("SALIR");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("PANEL DE TIEMPOS");
const u8 gText_TimeCleared[] = _("TIEMPO ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s");
const u8 gText_TrainerHill1F[] = _("P1");
const u8 gText_TrainerHill2F[] = _("P2");
const u8 gText_TrainerHill3F[] = _("P3");
const u8 gText_TrainerHill4F[] = _("P4");
const u8 gText_TeachWhichMoveToPkmn[] = _("¿Qué {STR_VAR_3} le\nenseñas a {STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("¿Le enseñas {STR_VAR_2}?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("¡{STR_VAR_1} ha aprendido\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} intenta\naprender {STR_VAR_2}.\pPero {STR_VAR_1} sólo puede\naprender cuatro movimientos.\p¿Quieres borrar un movimiento\npara hacer sitio a {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("¿Dejar de enseñarle\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}¡puf!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} ha olvidado {STR_VAR_3}.\pY…\p¡{STR_VAR_1} ha aprendido {STR_VAR_2}!");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} no ha aprendido el\nmovimiento {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("¿Dejas de enseñar un\nmovimiento nuevo a {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("¿Qué movimiento debería\nolvidar?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("MOVIMIENTOS");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("MOV. CONCURSO");
const u8 gText_MoveRelearnerType[] = _("TIPO/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("POTENCIA/");
const u8 gText_MoveRelearnerAccuracy[] = _("PRECISIÓN/");
const u8 gText_MoveRelearnerAppeal[] = _("ENCANTO");
const u8 gText_MoveRelearnerJam[] = _("ESTORBO");
const u8 gText_ClearAllSaveData[] = _("¿Borras los datos guardados?");
const u8 gText_ClearingData[] = _("Borrando los datos…\nEspera unos segundos.");
const u8 gText_IsThisTheCorrectTime[] = _("¿Ésta es la hora correcta?");
const u8 gText_Confirm3[] = _("ACEPTAR");
const u8 gText_Cancel4[] = _("SALIR");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Comunicación en espera…\nFalta elegir a un jugador.");
const u8 gText_BattleWasRefused[] = _("No se ha aceptado el combate.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Rechazó el combate.{PAUSE 60}");
const u8 gText_NoWeather[] = _("SIN CLIMA"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SOLEADO"); // Unused
const u8 gText_Sunny2[] = _("SOLEADO2"); // Unused
const u8 gText_Rain[] = _("LLUVIA"); // Unused
const u8 gText_Snow[] = _("NIEVE"); // Unused
const u8 gText_Lightning[] = _("RAYOS"); // Unused
const u8 gText_Fog[] = _("NIEBLA"); // Unused
const u8 gText_VolcanoAsh[] = _("CENIZA VOLCÁNICA"); // Unused
const u8 gText_Sandstorm[] = _("TORMENTA ARENA"); // Unused
const u8 gText_Fog2[] = _("NIEBLA2"); // Unused
const u8 gText_Seafloor[] = _("MAR"); // Unused
const u8 gText_Cloudy[] = _("NUBLADO"); // Unused
const u8 gText_Sunny3[] = _("SOLEADO3"); // Unused
const u8 gText_HeavyRain[] = _("LLUVIA FUERTE"); // Unused
const u8 gText_Seafloor2[] = _("FONDO MARINO2"); // Unused
const u8 gText_DelAll[] = _("BORRAR");
const u8 gText_Cancel5[] = _("SALIR");
const u8 gText_Ok2[] = _("VALE");
const u8 gText_Quiz[] = _("PREGUNTA");
const u8 gText_Answer[] = _("RESPUESTA");
const u8 gText_PokeBalls[] = _("POKé BALLS");
const u8 gText_Berry[] = _("BAYA");
const u8 gText_Berries[] = _("BAYAS");
const u8 gText_Obtained999RareCandies[] = _("¡Has obtenido 999\nCARAMELOS RAROS!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("Se ha activado el Repartir Exp.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Se ha desactivado el Repartir Exp.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("FANT.");
const u8 gText_Boulderbadge[] = _("MEDALLA ROCA");
const u8 gText_Cascadebadge[] = _("MEDALLA CASCADA");
const u8 gText_Thunderbadge[] = _("MEDALLA TRUENO");
const u8 gText_Rainbowbadge[] = _("MEDALLA ARCOÍRIS");
const u8 gText_Soulbadge[] = _("MEDALLA ALMA");
const u8 gText_Marshbadge[] = _("MEDALLA PANTANO");
const u8 gText_Volcanobadge[] = _("MEDALLA VOLCÁN");
const u8 gText_Earthbadge[] = _("MEDALLA TIERRA");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("OAK: Es importante que conozcas\nbien a tus POKéMON.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Esta es la lista de tus POKéMON,\n{PLAYER}.\pÁbrela para ver las características\ny movimientos de tus POKéMON.\pTambién eliges aquí un POKéMON si\nquieres usar un objeto con él.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("Se ha activado el GB Player.\nSuenan melodías del pasado.{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("Se ha desactivado el GB Player.\nLa nostalgia se desvanece.{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("DOMINGO");
const u8 gText_Monday[] = _("LUNES");
const u8 gText_Tuesday[] = _("MARTES");
const u8 gText_Wednesday[] = _("MIÉRCOLES");
const u8 gText_Thursday[] = _("JUEVES");
const u8 gText_Friday[] = _("VIERNES");
const u8 gText_Saturday[] = _("SÁBADO");
const u8 gText_LoveBall[] =     _("AMOR    / MELOC  / (HAD/PSI)");
const u8 gText_Lure[] =         _("CEBO    / SAFRE  / (AGU/DRA)");
const u8 gText_FriendBall[] =   _("AMIGO  / ZREZA  / (BIC/PLA)");
const u8 gText_Heavy[] =        _("PESO    / ARANJA / (ROC/TIE/ACE)");
const u8 gText_Moon[] =         _("LUNA    / ATANIA / (SIN/FAN/VEN)");
const u8 gText_Fast[] =         _("RAPID   / PERASI / (ELE/LUC/FUE)");
const u8 gText_LevelBall[] =    _("NIVEL  / CAQUIC / (NOR/VOL/HIE)");
const u8 gText_Vermilion[] = _("CIUDAD CARMÍN");
const u8 gText_Olivine[] = _("CIUDAD OLIVO");
const u8 gText_Floor0[] = _("Nivel 0");
const u8 gText_Pal[] = _("Colega");
const u8 gText_Underling[] = _("Subordinado");
const u8 gText_Strategy[] = _("Estrategia");
const u8 gText_Training[] = _("Entrenamiento");
const u8 gText_Cheating[] = _("Trampas");
const u8 gText_WeakPerson[] = _("Gente débil");
const u8 gText_ToughPerson[] = _("Gente dura");
const u8 gText_Anybody[] = _("Cualquiera");
const u8 gText_Love2[] = _("Amor");
const u8 gText_Violence[] = _("Violencia");
const u8 gText_Knowledge[] = _("Sabiduría");
const u8 gText_Tough3[] = _("Duro");
const u8 gText_Weak[] = _("Débil");
const u8 gText_Both[] = _("Ambos");
const u8 gText_GreenStone[] = _("PIEDRA VERDE");
const u8 gText_RedStone[] = _("PIEDRA ROJA");
const u8 gText_BlueStone[] = _("PIEDRA AZUL");
