VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "¿Has oído hablar del MAGNETOTRÉN?\p"
	.string "Es un tren que va hasta CIUDAD\n"
	.string "TRIGAL, en JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Quiero ir a CIUDAD AZAFRÁN para ver el\n"
	.string "MAGNETOTRÉN.$"
