FiveIsland_House1_Frlg_MapScripts::
	.byte 0

FiveIsland_House1_EventScript_Woman::
	msgbox FiveIsland_House1_Text_HusbandWentOffFishing, MSGBOX_NPC
	end

FiveIsland_House1_Text_HusbandWentOffFishing::
	.string "¡No te preocupes por comprar nada\n"
	.string "para la cena de esta noche!\p"
	.string "…Eso dijo mi marido cuando se fue\n"
	.string "a pescar hoy.\p"
	.string "No sé si puedo fiarme de que\n"
	.string "cumpla esa promesa.$"

