OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
	.string "¡Hace un día espléndido!\n"
	.string "¡El tiempo ideal para luchar!$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "¡La marea me arrastra!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "¡Por favor, no me salpiques la cara!\n"
	.string "Me vas a estropear el maquillaje.$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "Me estoy empezando a quemar...$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "¡Eres lo peor!$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "Me gusta esa gorra que llevas.\n"
	.string "Quizá debería ponerme una yo también…$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "Si lo miras desde aquí, parece\n"
	.string "que el MT. ASCUAS toca el cielo.$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "¡Ufff, eres fuerte!$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "El cielo se puede observar muy\n"
	.string "bien en esta zona.$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "¿Y he dejado de nadar para\n"
	.string "enfrentarme contigo?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "¡Oye, oye, realmente eres\n"
	.string "impresionante!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "Te recomiendo que nades de vez en\n"
	.string "cuando y que no uses tanto SURF.$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "¡Eh, un momento!\n"
	.string "¡Acaba de picar uno enorme!$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "¡Lo he vuelto a perder!$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "¡No sólo he perdido, también me he\n"
	.string "quedado sin el ejemplar de antes!$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "¿Me echas una mano con mi\n"
	.string "entrenamiento?$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "Eras un nivel por encima de mí.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "Está claro que eres hábil.\n"
	.string "¡Me caes bien!$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "No hay un solo día en el que no\n"
	.string "me entrene.$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "¡Qué tonto soy!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "¡A partir de ahora me entrenaré\n"
	.string "más!$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "Cada mañana, antes de desayunar,\n"
	.string "rodeo a nado la isla.$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "Agggg...\n"
	.string "Agggg...$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "He perdido porque esta mañana\n"
	.string "corrí mucho y estoy cansado.$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "¡Vístete adecuadamente para el\n"
	.string "combate! ¡Quítate ese atuendo frívolo!$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "¡¿Por qué?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "Hasta los profesionales de las\n"
	.string "artes marciales nos preocupamos\l"
	.string "de la moda últimamente.$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "Sabes, todo sabe genial cuando\n"
	.string "estás en plena naturaleza.$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "¡Vaya, me han derrotado!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "¿Sabías que el agua de las zonas\n"
	.string "volcánicas es muy buena?$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "La comida ha sido demasiado\n"
	.string "abundante. ¿Luchamos?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "Eso me ha hecho sudar.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "¿Qué hago?\n"
	.string "¡Otra vez tengo hambre!$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "PÍA: ¡Mi hermano mayor y yo\n"
	.string "hacemos un equipo increíble!$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "PÍA: ¡¿Eh?!\n"
	.string "¡No me lo puedo creer!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "PÍA: ¿Cómo puede haber alguien\n"
	.string "mejor que mi hermano?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "PÍA: Para luchar con nosotros,\n"
	.string "necesitas al menos dos POKéMON.$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "FER: ¡Junto a PÍA no tengo miedo\n"
	.string "de nada!$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "FER: ¡Buaaaah, eres demasiado!$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "FER: ¿Cómo ha podido fallar\n"
	.string "nuestro equipo?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "FER: ¿Quieres luchar con nosotros?\p"
	.string "Pues vuelve con dos POKéMON\n"
	.string "por lo menos.$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "Éste es el CAMINO CANDENTE.\p"
	.string "Conduce al MT. ASCUAS.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "BALNEARIO ASCUAS\n"
	.string "Enciende la llama que hay en ti.$"

